- appveyor.yml
- randovania/games/prime/claris_randomizer.py
- randovania/gui/background_task_mixin.py
- randovania/gui/main_window.py
- randovania/resolver/elevator_distributor.py
- randovania/resolver/generator.py
- test/conftest.py
- test/games/prime/test_claris_randomizer.py
- test/layout/test_layout_description.py
- test/resolver/test_elevator_distributor.py
- test/test_files/echo_tool.py
These tests should reproduce the errors in #105.
> Add tests for claris_randomizer._process_command

- randovania/resolver/filler/retcon.py
> Prevent extra starting item

- randovania/games/prime/patcher_file.py
- test/games/prime/test_patcher_file.py
> Implement patcher_file logic for PickupEntry conversion

- CHANGELOG.md
- randovania/game_description/resources/resource_database.py
- randovania/game_description/world_list.py
- randovania/games/prime/patcher_file.py
- randovania/games/prime/patcher_file_lib/sky_temple_key_hint.py
- randovania/interface_common/persisted_options.py
- randovania/layout/hint_configuration.py
- randovania/layout/layout_configuration.py
- requirements.txt
- setup.py
- test/conftest.py
- test/games/prime/test_patcher_file.py
- test/games/prime/test_sky_temple_key_hint.py
- test/interface_common/test_options.py
- test/layout/test_layout_configuration.py
- test/layout/test_permalink.py
- test/test_files/log_files/seed_a.json
> Sky temple key hints

- CHANGELOG.md
- randovania/gui/logic_settings_window.py
- randovania/gui/logic_settings_window.ui
> Add GUI options for disabling STK hints or lowering their precision

- randovania/games/prime/patcher_file_lib/item_hints.py
> Improve item hint messages

- randovania/gui/main_rules.py
- randovania/gui/main_rules.ui
- randovania/layout/layout_configuration.py
> Add preview of number of items in item pool

- randovania/games/prime/patcher_file.py
- test/games/prime/test_patcher_file.py
> Use the last conditional resource for expansions.

- CHANGELOG.md
- randovania/data/item_database/configuration/ammo.json
- randovania/data/item_database/configuration/major-items.json
- randovania/data/item_database/default_state/major-items.json
- randovania/data/json_data/prime2.json
- randovania/game_description/item/ammo.py
- randovania/generator/item_pool/major_items.py
- randovania/generator/item_pool/pickup_creator.py
- randovania/gui/main_rules.py
- randovania/gui/main_rules.ui
- randovania/interface_common/persisted_options.py
- randovania/layout/major_items_configuration.py
- test/interface_common/test_options.py
- test/layout/test_major_items_configuration.py
- test/layout/test_permalink.py
- test/resolver/item_pool/test_pickup_creator.py
- test/test_files/log_files/seed_a.json
> Add Progressive Grapple. Seekers don't convert missiles anymore.

- randovania/data/json_data/prime2.json
Fixes:
- #115
- #136
- #142
- #185
- #213
Also:
- Adds missing requirements in Hydrodynamo Station to Door to Hydrodynamo Shaft → Door to Save Station B (namely, the requirements to unlock all of the locks)
- Adds lots of requirements implied by other ones (mostly for Morph Ball, Charge Beam, and Scan Visor)
> Database additions

- CHANGELOG.md
- randovania/games/prime/patcher_file_lib/item_hints.py
- test/games/prime/patcher_file_lib/test_item_hints.py
This should make then slightly more obvious.
> Joke item and locations now have a `(?)` suffix.

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Fixes #232, and adds a bunch of other stuff.
> Sanctuary Entrance: add many fixes and additional connections

- CHANGELOG.md
- randovania/game_description/game_description.py
- randovania/game_description/requirements.py
- randovania/game_description/resources/damage_resource_info.py
- randovania/game_description/world_list.py
- randovania/generator/filler/retcon.py
- randovania/generator/generator_reach.py
- randovania/layout/layout_description.py
- randovania/resolver/bootstrap.py
- randovania/resolver/resolver.py
- randovania/resolver/resolver_reach.py
- randovania/resolver/state.py
- test/game_description/test_node.py
- test/game_description/test_requirements.py
- test/generator/test_generator_reach.py
- test/resolver/test_resolver_reach.py
- test/resolver/test_state.py
> Track energy in resolver

- CHANGELOG.md
- randovania/generator/item_pool/major_items.py
- randovania/generator/item_pool/pickup_creator.py
- randovania/generator/item_pool/pool_creator.py
- test/games/prime/test_patcher_file.py
- test/layout/test_game_patches_serializer.py
- test/resolver/item_pool/test_pickup_creator.py
> Make Seeker Launcher give temporary missiles

- randovania/generator/generator.py
> Fix generation failure exception being unhandled

- CHANGELOG.md
- randovania/data/json_data/prime2.json
- randovania/layout/trick_level.py
- test/layout/test_permalink.py
> Add trick for blind jumps

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Fixes #293.
Checks off Hive Dynamo Works in #103.
> More database adjustments

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Fixes #282.
Does this count as a major change?
> Invisible objects trick

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Fixes:
- #291 
- #292
- #294 
- #309
- #313 
- #314
Rooms to check off on #103:
- Hall of Honored Dead
- Phazon Site
- Watch Station Access
Thanks to gollop for adding some Morph Ball requirements as well! I imagine that some of those areas can also be checked off on #103.
> Even more database adjustments

- CHANGELOG.md
- randovania/resolver/bootstrap.py
> Minimal Checking now correctly handles progressive suit and grapple.

- randovania/generator/filler/retcon.py
- randovania/resolver/bootstrap.py
- randovania/resolver/state.py
- test/generator/test_generator_reach.py
- test/resolver/test_state.py
To get around `UncollectedState.resources` not working.
> Track collected resource nodes in State

- CHANGELOG.md
- randovania/data/json_data/prime2.json
- randovania/gui/logic_settings_window.py
> Database adjustments

- CHANGELOG.md
- randovania/games/prime/patcher_file_lib/item_hints.py
- test/games/prime/patcher_file_lib/test_item_hints.py
Fixes #403.
Unfortunately the "Metroids are not pets" joke hint is a little bit too long to fit in the text box. We could make the hint go over multiple pages, but I don't know if it's worth bothering to do for just that.
> Joke hint adjustments

- .idea/runConfigurations/Distribute.xml
- randovania/cli/commands/batch_distribute.py
- randovania/interface_common/sleep_inhibitor.py
- randovania/layout/layout_description.py
- test/cli/commands/test_batch_distribute.py
I'll move the SleepInhibitor to a separate python package later
> Batch Distribute improvements

- .idea/runConfigurations/Distribute.xml
- randovania/data/json_data/prime2.json
- randovania/game_description/data_reader.py
- randovania/game_description/data_writer.py
- randovania/game_description/game_description.py
- randovania/game_description/game_patches.py
- randovania/game_description/node.py
- randovania/game_description/world_list.py
- randovania/games/prime/binary_data.py
- randovania/games/prime/patcher_file.py
- randovania/generator/base_patches_factory.py
- randovania/generator/elevator_distributor.py
- randovania/resolver/debug.py
- test/games/prime/test_patcher_file.py
- test/generator/filler/test_runner.py
- test/generator/test_base_patches_factory.py
- test/generator/test_elevator_distributor.py
- test/generator/test_generator.py
- test/generator/test_generator_reach.py
- test/generator/test_retcon_filler_integration.py
- test/layout/test_game_patches_serializer.py
- test/test_files/log_files/seed_a.json
Backend support to more easily randomize Aerie and Sky Temple Gateway elevators.
> Add editable and keep_name_when_vanilla fields to TeleporterNode

- randovania/data/json_data/prime2.json
This reverts part of commit 871fab62913b952de2903861cf0fa5ab6bb06088.
> Revert regressions from "Simplify connections in Watch Station Access"

- CHANGELOG.md
This makes it easier to find out what are the new features of the update :)
> Group all database changes in the CHANGELOG

- CHANGELOG.md
- randovania/game_description/area.py
- randovania/generator/filler/runner.py
- test/generator/filler/test_runner.py
> Fixes for 0.29.1

- README.md
Added a comma after "releases page"  under the Installation heading.
> Grammar Correction

- pytest.ini
- test/conftest.py
- test/games/prime/test_claris_randomizer.py
- test/generator/test_generator.py
- test/generator/test_retcon_filler_integration.py
- test/gui/dialog/test_game_input_dialog.py
- test/gui/dialog/test_logic_settings_window.py
- test/gui/dialog/test_trick_details_popup.py
- test/gui/test_data_editor.py
- test/gui/test_main_window.py
- test/resolver/test_resolver.py
Use fixtures to skip tests based on CLI.
Fixes #408
> Dont use pytest config

- CHANGELOG.md
- randovania/generator/filler/filler_library.py
- randovania/generator/filler/retcon.py
- randovania/generator/filler/runner.py
> Hint Improvements

- CHANGELOG.md
- randovania/data/json_data/prime2.json
> Fixed: The Ing Cache in Dark Oasis now requires Power Bombs.

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Changes many of the wall boosts to a more appropriate difficulty, instead of Hard for every wall boost.
> Wall boost difficulty changes

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Trivial difficulty trick. Fixes https://github.com/randovania/randovania/issues/527.
> Hall of Honored Dead item with Power Bombs

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Fixes https://github.com/randovania/randovania/issues/474. Fixes https://github.com/randovania/randovania/issues/535. Fixes https://github.com/randovania/randovania/issues/645.
> Logic fixes, additions

- CHANGELOG.md
- randovania/data/json_data/prime2.json
Fixes https://github.com/randovania/randovania/issues/583. Fixes https://github.com/randovania/randovania/issues/666.
> More logic database changes

- CHANGELOG.md
- randovania/data/ClarisPrimeRandomizer/RandomizerData.json
- randovania/generator/base_patches_factory.py
- randovania/layout/translator_configuration.py
> Add support for unlocked Translator Gates

- randovania/game_description/requirements.py
- randovania/game_description/world_list.py
- randovania/generator/generator_reach.py
- test/game_description/test_requirements.py
Instead of And/Or having a class method called simplified, now each Requirement has their own method simplify.
This should also handle more interesting cases.
> Add Requirement.simplify

- CHANGELOG.md
- randovania/games/prime/claris_randomizer.py
- randovania/games/prime/dol_patcher.py
- randovania/gui/dialog/echoes_user_preferences_dialog.py
- randovania/gui/seed_details_window.py
- randovania/gui/ui_files/echoes_user_preferences_dialog.ui
- randovania/gui/ui_files/seed_details_window.ui
- randovania/interface_common/cosmetic_patches.py
- randovania/interface_common/echoes_user_preferences.py
- randovania/interface_common/options.py
- test/games/prime/test_claris_randomizer.py
- test/games/prime/test_dol_patcher.py
- test/gui/dialog/test_echoes_user_preferences_dialog.py
1. Customize the default in-game options
2. Replace hint system with a triggerable string alerts from memory writes. (for multiworld/crowd control
> Add additional Dol Patching

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
Added logic for Torvus Plaza without Boost Ball. Has two variants: one with just SA + SJ for Hard, and one with SJ + SA + Bombs + Spider for  Normal. Updated the E-Tank -> Door node to account for this change.
https://youtu.be/I81EA1e6zmg
> Logic Changes

- randovania/data/json_data/prime2.txt
For Shuffled Scan Visor. Fixes this issue: https://github.com/randovania/randovania/issues/769
> Added Scan Visor Requirement to Sand Processing Item

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
> More Bombless Bomb Slot Logic + Other Fixes/Updates

- randovania/data/json_data/prime2.txt
- randovania/game_description/data_writer.py
- test/game_description/test_data_writer.py
> Fix use of templates not being combined with resource requirements

- randovania/server/game_session.py
- test/server/test_game_session.py
> Dispatch session updated event when a pickup is collected.

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
Small updates for #103 and #333
> Minor Updates

- randovania/game_connection/connection_backend.py
- randovania/game_connection/dolphin_backend.py
- randovania/game_connection/game_connection.py
- randovania/gui/debug_backend_window.py
- randovania/gui/game_session_window.py
- randovania/gui/main_window.py
- randovania/gui/multiworld_client.py
- randovania/network_client/network_client.py
- randovania/server/game_session.py
- test/game_connection/test_dolphin_backend.py
- test/gui/test_debug_backend_window.py
- test/gui/test_game_session_window.py
- test/gui/test_main_window.py
- test/gui/test_multiworld_client.py
- test/server/test_game_session.py
> Persistent multiworld client

- CHANGELOG.md
- debug.log
- randovania/data/json_data/prime2.txt
- Sanctuary Fortress has now been fully updated with missing tricks
- Simplified a bunch of nodes
- Added damage requirements to a few rooms
- Minor adjustments throughout the database
- Issues Fixed
- Fixed #829 
- Fixed #910 
- Fixed #828 
- Fixed #907 
- Fixed #915 
- Fixed #442 
- Fixed #859
> Major Logic Updates: Part 4

- randovania/gui/game_session_window.py
- randovania/gui/lib/qt_network_client.py
- randovania/gui/online_game_list_window.py
- randovania/network_client/network_client.py
- randovania/server/database.py
- randovania/server/game_session.py
- randovania/server/server_app.py
- randovania/server/user_session.py
- test/gui/lib/test_qt_network_client.py
- test/gui/test_game_session_window.py
- test/gui/test_online_game_list_window.py
- test/server/test_server_app.py
- test/server/test_user_session.py
> Multiworld Fixes

- randovania/gui/game_session_window.py
- randovania/gui/generate_seed_tab.py
- randovania/gui/lib/window_manager.py
- randovania/gui/main_window.py
- randovania/gui/seed_details_window.py
- randovania/network_common/admin_actions.py
- randovania/server/game_session.py
- test/gui/test_game_session_window.py
- test/gui/test_main_window.py
- test/server/test_game_session.py
> Implement button for visualizing the spoiler in a game session.

- randovania/gui/game_session_window.py
- randovania/server/game_session.py
> Allow players to edit their own preset when teamcount=1

- .github/workflows/docker-image.yml
- Dockerfile.server
> Fix randovania version in server image

- randovania/generator/filler/retcon.py
- randovania/generator/filler/runner.py
- randovania/generator/generator.py
> Multi: don't select players with 0 actions left

- CHANGELOG.md
- randovania/gui/lib/theme.py
- randovania/gui/main_window.py
- randovania/gui/qt.py
- randovania/gui/ui_files/main_window.ui
- randovania/interface_common/options.py
- requirements.txt
- setup.py
> Added dark theme.

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- Meditation Vista Item with Extended Dash (Fixes #841)
- Removed Hall of Combat Mastery Item with Unmorphing Requirement
> Minor Database Updates

- randovania/gui/game_session_window.py
- randovania/gui/online_game_list_window.py
- randovania/network_common/admin_actions.py
- randovania/server/game_session.py
- test/gui/test_game_session_window.py
- test/server/test_game_session.py
> Implement passwords for sessions.

- randovania/gui/game_session_window.py
- randovania/gui/lib/qt_network_client.py
- randovania/gui/qt.py
- randovania/server/database.py
- randovania/server/user_session.py
- test/server/test_game_session.py
> Properly use UTC for datetimes.

- randovania/game_connection/dolphin_backend.py
- test/game_connection/test_dolphin_backend.py
> DolphinBackend: respect item's max capacity

- randovania/gui/game_session_window.py
* Refresh preset list when saving another player's preset
* Save locally your preset changes
Fixes #1032.
> Improve UX when dealing with presets in GameSessionWindow.

- CHANGELOG.md
- randovania/gui/main_window.py
- randovania/gui/ui_files/main_window.ui
- randovania/interface_common/update_checker.py
- test/interface_common/test_update_checker.py
Also update CHANGELOG for multi
> Add tab explaining Multiworld

- randovania/gui/generate_seed_tab.py
- test/gui/test_generate_seed_tab.py
> Fix customize preset in GenerateSeedTab.

- requirements.txt
Reverts randovania/randovania#1063
> Revert "Update markdown to 3.3"

- CHANGELOG.md
- randovania/game_description/hint.py
- randovania/game_description/node_search.py
- randovania/game_description/world_list.py
- randovania/games/prime/patcher_file.py
- randovania/games/prime/patcher_file_lib/item_hints.py
- randovania/generator/filler/retcon.py
- randovania/generator/filler/runner.py
- test/games/prime/patcher_file_lib/test_item_hints.py
- test/generator/filler/test_runner.py
- test/generator/test_generator_reach.py
> Implement generation of relative hints

- CHANGELOG.md
- randovania/gui/dialog/logic_settings_window.py
- randovania/gui/generate_seed_tab.py
- randovania/layout/trick_level.py
- test/gui/test_generate_seed_tab.py
> Improve layer issues for Trick Details/Customize Preset.

- randovania/data/item_database/configuration/major-items.json
- randovania/gui/game_session_window.py
- randovania/layout/layout_configuration.py
- randovania/layout/major_items_configuration.py
- randovania/layout/preset.py
- randovania/layout/trick_level.py
- test/gui/test_game_session_window.py
> Game Session: warn if any preset is dangerous

- randovania/gui/game_session_window.py
- randovania/gui/ui_files/game_session.ui
- randovania/layout/preset.py
- randovania/layout/preset_migration.py
- randovania/network_client/game_session.py
- randovania/server/database.py
- randovania/server/game_session.py
- test/gui/test_game_session_window.py
- test/server/test_game_session.py
> Support permalinks in Game Session

- randovania/gui/game_session_window.py
- randovania/server/game_session.py
- test/gui/test_game_session_window.py
- test/server/test_game_session.py
> Implement finishing sessions.

- CHANGELOG.md
- randovania/data/presets/fewest_changes.json
- randovania/data/presets/presets.json
- randovania/data/presets/starter_preset.json
- test/layout/test_preset_migration.py
- test/test_files/presets/fewest_changes_v1.rdvpreset
* Refresh included presets to latest version.
* Replace Beginner Friendly with Starter Preset.
* Make the default preset Starter Preset.
* Add extra tweaks to Darkszero's Deluxe.
Fixes #950.
> Improvements to the included presets.

- CHANGELOG.md
- randovania/data/item_database/configuration/ammo.json
- randovania/data/item_database/configuration/major-items.json
- randovania/game_description/hint.py
- randovania/game_description/item/ammo.py
- randovania/game_description/item/item_category.py
- randovania/game_description/item/major_item.py
- randovania/game_description/resources/pickup_entry.py
- randovania/games/prime/patcher_file_lib/item_hints.py
- randovania/generator/base_patches_factory.py
- randovania/generator/item_pool/pickup_creator.py
- randovania/gui/dialog/logic_settings_window.py
- randovania/gui/lib/trick_lib.py
- randovania/gui/main_rules.py
- randovania/gui/main_window.py
- randovania/network_common/pickup_serializer.py
- test/game_description/test_resources.py
- test/games/prime/patcher_file_lib/test_item_hints.py
- test/games/prime/test_patcher_file.py
- test/generator/filler/test_runner.py
- test/generator/test_base_patches_factory.py
- test/gui/test_debug_backend_window.py
- test/gui/test_multiworld_client.py
- test/layout/test_game_patches_serializer.py
- test/layout/test_major_item_state.py
- test/resolver/item_pool/test_ammo.py
- test/resolver/item_pool/test_pickup_creator.py
- test/resolver/test_state.py
- test/server/test_game_session.py
> Use broad item category hints for Keybearer hints

- CHANGELOG.md
- randovania/game_description/hint.py
- randovania/games/prime/patcher_file.py
- randovania/games/prime/patcher_file_lib/item_hints.py
- randovania/generator/base_patches_factory.py
- randovania/generator/filler/filler_library.py
- randovania/generator/filler/runner.py
- test/games/prime/patcher_file_lib/test_item_hints.py
- test/games/prime/test_patcher_file.py
- test/generator/test_base_patches_factory.py
- test/layout/test_game_patches_serializer.py
> Add a guaranteed hint for Temple Keys.

- randovania/generator/filler/runner.py
- test/generator/filler/test_runner.py
* Decrease the maximum distance
* Don't allow keys when not detailed.
> Improving relative hints

- randovania/server/game_session.py
- test/server/test_game_session.py
> Fix observers erroring for in-game sessions.

- PRIVACY_POLICY.md
- randovania/gui/dialog/login_prompt_dialog.py
- randovania/gui/game_patches_window.py
- randovania/gui/ui_files/login_prompt_dialog.ui
> Add PRIVACY_POLICY.md

- randovania/gui/game_session_window.py
- randovania/gui/seed_details_window.py
- randovania/interface_common/options.py
Fixes #1054, fixes #1055 and fixes #1105.
> Show alerts with good user information.

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- Fixed #381 
- Fixed #1123 
- Fixed #1124 
- Descriptions of tricks
- Minor fixes
> Cleanup of some issues/other fixes

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- Fixes from last PR
- Changelog updates
- New method in Industrial Site
> Minor Cleanup

- randovania/data/json_data/prime2.txt
- Added Advanced Method for Seekerless Locks
- Posioned Bog is now Advanced
> Seekerless Update

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- Balanced some Bombless Slot Tricks into Advanced
- Added some new requirements
- Simplified Seeker Lock Blast Shield requirements
- Fixed some missing Morph Ball requirements
- Other minor fixes
- Contributes to #860
> More Balancing and Minor Updates

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- New OoB trick added
- Fixes and updates in various room
- Some balancing
- Fixes #1167
> Fixes, Cleanup, and Balancing

- randovania/game_connection/connection_backend.py
- randovania/game_connection/connection_base.py
- randovania/game_connection/dolphin_backend.py
- randovania/game_connection/game_connection.py
- randovania/game_description/resources/resource_database.py
- randovania/games/prime/dol_patcher.py
- randovania/gui/auto_tracker_window.py
- randovania/gui/debug_backend_window.py
- randovania/gui/game_session_window.py
- randovania/gui/multiworld_client.py
- test/game_connection/test_connection_backend.py
- test/game_connection/test_dolphin_backend.py
- test/game_connection/test_game_connection.py
- test/gui/test_auto_tracker_window.py
- test/gui/test_debug_backend_window.py
- tools/game_console.py
There's absolutely no reason I'm doing this right now. 👀
> Refactor game connection

- CHANGELOG.md
- randovania/game_connection/backend_choice.py
- randovania/game_connection/connection_backend.py
- randovania/game_connection/connection_base.py
- randovania/game_connection/dolphin_backend.py
- randovania/game_connection/game_connection.py
- randovania/game_connection/nintendont_backend.py
- randovania/gui/auto_tracker_window.py
- randovania/gui/game_session_window.py
- randovania/gui/lib/game_connection_setup.py
- randovania/gui/main_window.py
- randovania/gui/qt.py
- randovania/gui/ui_files/auto_tracker_window.ui
- randovania/gui/ui_files/game_session.ui
- randovania/interface_common/options.py
- test/game_connection/test_dolphin_backend.py
- test/game_connection/test_game_connection.py
- test/game_connection/test_nintendont_backend.py
- test/gui/lib/test_game_connection_setup.py
- test/gui/test_auto_tracker_window.py
- test/gui/test_game_session_window.py
- test/interface_common/test_options.py
> Add UI for selecting the game backend

- randovania/game_description/item/item_category.py
- randovania/games/prime/patcher_file_lib/item_hints.py
- randovania/gui/main_window.py
- randovania/gui/ui_files/main_window.ui
* Mention Nintendont in the FAQ for multiworld. Fixes #1181.
* Add table of all item names for hints. Part of #1184.
> Improve help tab.

- randovania/gui/ui_files/main_window.ui
> Add description of how hints work.

- CHANGELOG.md
- randovania/gui/main_window.py
- randovania/gui/ui_files/main_window.ui
- test/gui/test_main_window.py
> Added easy way of opening location of game history.

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
> Fix incorrect pickup indices for Prime 3

- randovania/gui/game_session_window.py
- randovania/gui/multiworld_client.py
- test/gui/test_game_session_window.py
> Fix player status not being updated during setup.

- randovania/game_connection/nintendont_backend.py
- randovania/gui/main_window.py
- randovania/gui/tracker_window.py
- randovania/gui/ui_files/main_window.ui
- randovania/gui/ui_files/tracker_window.ui
- test/gui/test_main_window.py
* Organize elements in the Open menu
* Map tracker now prompts for which preset to use
* Updated credits
> UI improvements

- randovania/resolver/bootstrap.py
- test/resolver/test_bootstrap.py
* 1 for the Enable Vanilla X
* 1 or 0 for the Vanilla Great Temple Emerald Translator Gate
* 0 for everything else
* Also add all non-event/damage/item resources
> Ensure all misc resources are present.

- randovania/game_connection/connection_backend.py
- test/game_connection/test_connection_backend.py
> Fix setting suit model being broken

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
> Added Missing Connections for Prime

- randovania/server/app.py
- test/server/test_app.py
* Strictly equal
* Matching major/minor
* Don't care
> Add 3-tier version checking.

- randovania/cli/commands/distribute.py
- randovania/data/json_data/prime3.json
- randovania/generator/generator.py
- test/cli/commands/test_distribute_command.py
- test/generator/test_generator.py
- test/layout/test_game_patches_serializer.py
Also fix prime 3's victory condition.
> Command line distribute improvement

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
Added lots of basic tricks to logic across the whole game (except sunken frigate/deep tallon and Frigate Orpheon). Most of them will be very easy tricks. I performed every trick here myself to ascertain its difficulty and documented them appropriately.
> Added Basic Prime 1 Tricks to Logic

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
> Minor Updates to prime2.json and Changelog

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
- Added tricks in all rooms where applicable
- Added Spawn Points for all rooms
- Added missing events where necessary
- Fixed incorrect logic/connections
- Simplified/Updated some rooms
> Prime 3 Database Overhaul

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
- Minor Errors Fixed
- Readjusted some connections to suit the solver better
> Prime 3 Logic Fixes/Updates

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
- Room Updates
- Fixed Event Nodes
> Corruption Updates/Fixes

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
> More Event Nodes Fixed

- CHANGELOG.md
- randovania/gui/preset_settings/logic_settings_window.py
- test/gui/dialog/test_logic_settings_window.py
Only select these that are valid options
> Fix bulk selection of starting locations

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
- test/generator/test_generator_reach.py
- Damage updates
- Event updates
- Node updates
- Tricks added in more places
- Logic fixed
- Minor fixes/updates
> Corruption Fixes/Updates/Changes

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- Hive Entrance damage requirement leaving the pickup
- Meditation Vista trick update
> Prime 2 Minor Updates

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
This reverts commit 3c13dcff7ade0026529d811505a5d74a4e85a449.
Just so we can release 2.1.2
> Revert "Missing Damage and Minor Update (#1334)"

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
> Corruption Database Changes

- randovania/game_description/game_description.py
- randovania/games/game.py
- randovania/gui/generate_seed_tab.py
- randovania/gui/seed_details_window.py
This adds a long_name and short_name property to RandovaniaGame to get the correct title for a given game.
> Use correct game title when saving spoilers and iso files

- randovania/gui/seed_details_window.py
> Show correct state of show all button on spolier tab after switching players

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
- randovania/generator/item_pool/pickup_creator.py
Improves Impact Crater and adds more tricks to chozo ruins
> Prime 1: Chozo Ruins and Impact Crater Overhall

- randovania/gui/generate_seed_tab.py
- randovania/interface_common/echoes.py
> Fix generation not being abortable

- randovania/server/server_app.py
- test/server/test_server_app.py
This reverts commit 9716ae5c64246787aec37343ce08ad9e546318a8.
> Revert "Fixes for updated socket.io"

- CHANGELOG.md
- randovania/data/gui_assets/tracker/prime2.json
- randovania/data/json_data/prime2.txt
> Echoes Updates

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- New Roll Jump trick added to reach Dark Torvus Arena halfpipe pickup
- Removed Undertemple Access as a valid starting location until #800 is fixed
> Echoes Database Updates

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
Fixes and new tricks yet again ;)
> More Echoes Database Updates

- CHANGELOG.md
- randovania/games/prime/patcher_file_lib/item_hints.py
- test/games/prime/patcher_file_lib/test_item_hints.py
> Add more joke entries

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
- New Tricks added and adjustments made to logic
- Fixes #1504
- Fixes #1505
- Fixes #1523
- Fixes #1525
> v2.5 Fixes/Updates

- CHANGELOG.md
- randovania/bitpacking/json_dataclass.py
- randovania/games/prime/claris_randomizer.py
- randovania/games/prime/dol_patcher.py
- randovania/games/prime/echoes_dol_patches.py
- randovania/games/prime/echoes_dol_versions.py
- randovania/games/prime/patcher_file.py
- randovania/gui/dialog/echoes_user_preferences_dialog.py
- randovania/gui/ui_files/echoes_user_preferences_dialog.ui
- randovania/gui/ui_files/logic_settings_window.ui
- randovania/interface_common/cosmetic_patches.py
- randovania/interface_common/echoes_user_preferences.py
- randovania/interface_common/options.py
- randovania/server/game_session.py
- test/games/prime/test_claris_randomizer.py
- test/games/prime/test_dol_patcher.py
> Add option to disable elevator sound

- CHANGELOG.md
- randovania/layout/ammo_state.py
- test/layout/test_ammo_configuration.py
- test/layout/test_ammo_state.py
> Fix bitpacking for AmmoState and max ammo count

- setup.py
6.2.0 failed with the AsyncRetrying
> Require tenacity>=7.0.0

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
> Prime 1 updates to GTH and TFT

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
Added a new method for getting to Abandoned Worksite door from Translator gate
Added an NSJ method of crossing Grand Windchamber
Seeker Lock Difficulty Adjustments
> Various MP2 Changes

- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
> Defense Access

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
- Fixed Watery Hall Access bug
- Logic Updates/Cleanup
- New HotE event
> Half of Chozo Updates (Through Magma Pool)

- randovania/data/json_data/prime2.txt
> More Dark Agon Damage Updates

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
- New Bomb Jump trick added, Complex Bomb Jump, which includes HBJ, HPBJ, and UBJ
- Minor fixes/updates in other rooms
> Updated Bomb Jump Tricks for Prime

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
> Magmoor Heat Logic Part 2: Monitor Station

- .idea/runConfigurations/Validate_Prime_Vanilla.xml
- randovania/resolver/bootstrap.py
- randovania/resolver/debug.py
- test/test_files/log_files/prime1-vanilla.rdvgame
Though it'd likely too minimal
> Fix Prime 1 minimal logic

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
> Magmoor Heat Logic: Part 4

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
> Magmoor Heat Logic Finished

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
Added misc options for the QoL Logical listed in the app
> Prime: Quality of Life Logical Changes

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
IBJ listed as complex bomb jump level 2.
Added flaahgra event requirement to the sunchamber ghosts layer change
> Add requirements for Sunchamber ghosts from top of sun tower.

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
- adjusted GTH NSJ climb difficulty (expert -> hypermode)
- added more methods of climbing from hydro access tunnel to transport tunnel E
- added an R jump in observatory
- added vault without bombs
- adjusted suntower to have supers in logic
> logic adjustments

- randovania/gui/generate_seed_tab.py
Automatically forks the preset
> Allow customize on default preset

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
Thanks Retro/randomprime, ooops.
Fixes #1882.
> Remove trailing whitespace in West Tower name

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
Oops, meant sunchamber access, not lobby, in the commit message
> Block off sunchamber via sunchamber access between flaahgra and the chozo ghosts fight

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
For Torvus, only Poisoned Bog and Venomous Pond are left to do
> More Echoes Updates/Damage Updates

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
added invisible objects to the thermal visor option
> MQA update

- CHANGELOG.md
- randovania/gui/lib/hints_text.py
* Fix swapping games when sorted
* Add Artifact/Energy Cell
> Improve the Hint Item Names

- randovania/data/json_data/prime1.json
- randovania/data/json_data/prime1.txt
- randovania/data/json_data/prime2.txt
- randovania/data/json_data/prime3.json
- randovania/data/json_data/prime3.txt
> Various Updates

- randovania/game_description/requirements.py
- randovania/generator/filler/pickup_list.py
- test/game_description/test_requirements.py
- test/generator/filler/test_pickup_list.py
> Fixes RequirementList less than for sorting

- CHANGELOG.md
- randovania/data/json_data/prime2.txt
Added SJ to the logical NSA paths
> Mining Plaza/Watch Station

- CHANGELOG.md
- randovania/gui/lib/preset_describer.py
- randovania/gui/preset_settings/echoes_translators_tab.py
- randovania/gui/ui_files/preset_echoes_translators.ui
- randovania/layout/prime2/translator_configuration.py
> MP2: Random with unlocked button for translators

- CHANGELOG.md
- randovania/data/presets/prime2/darkszero_deluxe.rdvpreset
- randovania/layout/base/trick_level_configuration.py
> Sort tricks when saving to json

- randovania/data/json_data/prime1/Magmoor Caverns.txt
- randovania/data/json_data/prime1/header.json
- randovania/data/json_data/prime2/Temple Grounds.txt
- randovania/data/json_data/prime2/header.json
- randovania/data/json_data/prime2/header.txt
- randovania/data/json_data/prime3/header.json
Made trick descriptions more detailed and easier to read
> Rewrote trick descriptions

- CHANGELOG.md
- randovania/gui/ui_files/preset_prime_patches.ui
> Fixed Prime 1's Quality of Life page link

- CHANGELOG.md
- randovania/data/json_data/prime1/Chozo Ruins.json
- randovania/data/json_data/prime1/Chozo Ruins.txt
- randovania/data/json_data/prime1/Phendrana Drifts.json
- randovania/data/json_data/prime1/Phendrana Drifts.txt
These are all things brought up by the community in the discord server. I'll let the `.txt` diff speak for itself.
> Database - New Tricks and Fixes

- CHANGELOG.md
- randovania/data/json_data/prime1/Chozo Ruins.json
- randovania/data/json_data/prime1/Chozo Ruins.txt
> Fix Door to Plaza Access in Main Plaza.

- CHANGELOG.md
- randovania/data/json_data/prime1/Phendrana Drifts.json
- randovania/data/json_data/prime1/Phendrana Drifts.txt
- randovania/data/json_data/prime1/header.json
removed trick as discussed, patcher change will come later
> removed shorelines reposition trick

- CHANGELOG.md
- randovania/data/json_data/prime1/Phendrana Drifts.json
- randovania/data/json_data/prime1/Phendrana Drifts.txt
> Fix Database bugs in Research Lab Aether and Ice Ruins West

- CHANGELOG.md
- randovania/games/patchers/randomprime_patcher.py
- test/games/patchers/test_randomprime_patcher.py
for multiworld quality of life
> removed overly-conservative modal hudmemos

- randovania/game_description/item/item_category.py
- randovania/gui/lib/foldable.py
- randovania/gui/preset_settings/item_configuration_widget.py
- randovania/gui/preset_settings/item_pool_tab.py
- randovania/gui/ui_files/item_configuration_popup.ui
- test/gui/lib/test_foldable.py
Also contains a small fix for the "as_json" problem in ItemCategory
> Added a "Foldable" widget to make blocks that can be collapsed

- randovania/data/json_data/prime3/Phaaze.json
- randovania/data/json_data/prime3/Phaaze.txt
Allows for NSJ seeds to have Phaaze enabled and be completable.
> Phaaze NSJ Tricks

- CHANGELOG.md
- randovania/data/json_data/prime3/Bryyo - Ice.json
- randovania/data/json_data/prime3/Bryyo - Ice.txt
- randovania/data/json_data/prime3/Bryyo - Reptilicus.json
- randovania/data/json_data/prime3/Bryyo - Reptilicus.txt
- randovania/data/json_data/prime3/GFS Valhalla.json
- randovania/data/json_data/prime3/GFS Valhalla.txt
- randovania/data/json_data/prime3/Norion.json
- randovania/data/json_data/prime3/Norion.txt
- randovania/data/json_data/prime3/Pirate Homeworld - Command.json
- randovania/data/json_data/prime3/Pirate Homeworld - Command.txt
- randovania/data/json_data/prime3/Pirate Homeworld - Mines.json
- randovania/data/json_data/prime3/Pirate Homeworld - Mines.txt
- randovania/data/json_data/prime3/Pirate Homeworld - Research.json
- randovania/data/json_data/prime3/Pirate Homeworld - Research.txt
- randovania/data/json_data/prime3/SkyTown Elysia - Main.json
- randovania/data/json_data/prime3/SkyTown Elysia - Main.txt
- randovania/data/json_data/prime3/SkyTown Elysia - Pod.json
- randovania/data/json_data/prime3/SkyTown Elysia - Pod.txt
Added Energy Cells and Energy Tanks to Major items
> Prime 3 Major/Minor Updates

- CHANGELOG.md
- randovania/gui/preset_settings/trick_level_tab.py
- randovania/resolver/bootstrap.py
Added Prime 1 Minimal Logic. Like Prime 3, the UI still shows Echoes text. This should be all the relevant items to exclude.
> Prime 1 Minimal Logic

- CHANGELOG.md
Updates CHANGELOG.md for #2260 changes
> Update CHANGELOG.md for Magma Pool changes

- randovania/gui/lib/data_editor_canvas.py
- Draw arrow from selected node to nodes with connections
- Draw surrounding areas outside the boundaries of the current area.
> Data Visualizer improvements:

- randovania/patching/prime/asset_conversion.py
This is hacky, but it works.  This should really be created at build time of the asset file.
Padding seems to work in all cases at least.  So that's a plus.
You can fix my garbage code ;)
> Add Padding and Hack to add EVNT id to ANIM file

- CHANGELOG.md
- randovania/game_description/editor.py
- randovania/game_description/world/area.py
- randovania/game_description/world/world_list.py
- randovania/generator/filler/runner.py
- randovania/gui/data_editor.py
- randovania/gui/lib/area_list_helper.py
- randovania/gui/tracker_window.py
- randovania/gui/ui_files/data_editor.ui
- test/game_description/test_editor.py
- test/gui/test_data_editor.py
* Create module game_description.editor
> Implement Area renaming

- CHANGELOG.md
- randovania/game_description/editor.py
- randovania/gui/data_editor.py
- randovania/gui/lib/data_editor_canvas.py
> Add move nodes between areas

- randovania/layout/base/available_locations.py
```python
_ALL_INDICES = list(range(119))
```
Well, thanks for the warning, me in May. Me in January 2020 sure did like to hardcode things.
> AvailableLocationsConfiguration: get PickupIndex list from game

- .gitignore
- CHANGELOG.md
- randovania/games/prime1/patcher/randomprime_patcher.py
- requirements-small.txt
- requirements.txt
- setup.cfg
- test/test_files/randomprime_expected_data.json
> Prime Patcher - Nintendont Fix + Increase Expansion Capacity

- randovania/games/prime1/patcher/prime1_elevators.py
Great Tree hall and Mines elevators were swapped.
> Randovania GUI Elevator Name Mismatch

- randovania/games/cave_story/generator/pool_creator.py
- randovania/games/cave_story/json_data/Egg Corridor.json
- randovania/games/cave_story/json_data/Egg Corridor.txt
- randovania/games/cave_story/json_data/Grasstown.json
- randovania/games/cave_story/json_data/Grasstown.txt
- randovania/games/cave_story/json_data/Labyrinth.json
- randovania/games/cave_story/json_data/Labyrinth.txt
- randovania/games/cave_story/json_data/Mimiga Village.json
- randovania/games/cave_story/json_data/Mimiga Village.txt
- randovania/games/cave_story/json_data/Plantation.json
- randovania/games/cave_story/json_data/Plantation.txt
- randovania/games/cave_story/json_data/Ruined Egg Corridor.json
- randovania/games/cave_story/json_data/Ruined Egg Corridor.txt
- randovania/games/cave_story/json_data/Sand Zone.json
- randovania/games/cave_story/json_data/Sand Zone.txt
- randovania/games/cave_story/json_data/header.json
- randovania/games/cave_story/json_data/header.txt
- randovania/layout/base/trick_level.py
- test/generator/item_pool/test_pool_creator.py
- fixes error when enabling missiles/bubbler breaking blocks in start point seeds
- adds rudimentary logic for leveling machine gun to mitigate impossible seeds
> fix some cave story bugs

- randovania/games/dread/json_data/Elun.json
- randovania/games/dread/json_data/Elun.txt
- randovania/games/dread/json_data/header.json
> Metroid Dread: Elun Logic

- randovania/games/dread/item_database/item-database.json
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/header.json
Addressed most of darkszero's comments in the initial Cataris commit
> Cataris Logic - Added Kraid, Heat Placeholder, and EMMI Control Unit

- randovania/games/prime1/json_data/Tallon Overworld.json
- randovania/games/prime1/json_data/Tallon Overworld.txt
Added in videos in the description of tricks in the data visualizer, only tricks on Tallon for now.
All the videos I make are going to my public playlist on youtube for ease of access.
https://youtube.com/playlist?list=PLx2YFEoLb-KassQJobmYSfHSSv93e_b9W
> Just some videos for the data visualizer

- CHANGELOG.md
- randovania/games/prime1/json_data/Magmoor Caverns.json
- randovania/games/prime1/json_data/Magmoor Caverns.txt
Also re-structured Triclops Pit logic and added another SJ trick for the Triclops Pit Item.
> Added video comments for six more rooms in Magmoor.

- CHANGELOG.md
- randovania/games/prime1/json_data/Phazon Mines.json
- randovania/games/prime1/json_data/Phazon Mines.txt
Added video comments and changed/added trick logic for Main Quarry, Elite Research, Ore Processing and Elite Control.
> Early Phazon Mines videos and logic updates.

- CHANGELOG.md
- randovania/games/prime1/json_data/Phendrana Drifts.json
- randovania/games/prime1/json_data/Phendrana Drifts.txt
Added video comments for Phendrana Shorelines, Ice Ruins West and Ruined Courtyard. Changed and appended parts of the logic for Ice Ruins West.
> Video comments for early Phendrana and Ice Ruins West logic update.

- CHANGELOG.md
- randovania/games/prime1/json_data/Tallon Overworld.json
- randovania/games/prime1/json_data/Tallon Overworld.txt
Added some videos for Tallon, changed the frigate climb NSJ video with one that doesn't use boxes.
Added an SJ L-Jump Standable frigate climb to the logic.
Lowered the difficulty for frigate climb using Slope Space Jump and Standable, the Standable part is now (Beginner).
Added 2 entries to the changelog.
> Added more Tallon videos, and changed some logic in the database

- randovania/games/dread/item_database/item-database.json
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
- test/games/dread/patcher/test_open_dread_patcher.py
Implement initial logic for Ghavoran
Also added:
- Walljump Trick
- Template for destroying Enky
> Implement initial logic for Ghavoran

- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
Implement initial logic for Burenia. Also added Quiet Robe event to Ferenia.
> Implement initial logic for Burenia (rebased on the Ghavoran Branch)

- randovania/games/dread/item_database/item-database.json
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/header.json
Does not include power generator logic. Heat/Cold runs are placeholders.
> Dairon initial logic. 

- CHANGELOG.md
- randovania/games/prime1/json_data/header.json
- randovania/games/prime2/json_data/header.json
- randovania/gui/preset_settings/trick_level_tab.py
- randovania/gui/ui_files/preset_trick_level.ui
- Added descriptions for Prime 1 and 3.
- Cleaned up the Minimal Logic description to be more concise
- Closes #2351
> Min logic updates

- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
Fixes the underlying issue in #2610
> fixes a database error in burenia preventing generation/patching

- randovania/bitpacking/bitpacking.py
- randovania/cli/commands/distribute.py
- randovania/games/game.py
- randovania/generator/generator.py
- randovania/gui/game_session_window.py
- randovania/interface_common/preset_manager.py
- randovania/layout/generator_parameters.py
- randovania/layout/layout_description.py
- randovania/layout/permalink.py
- randovania/layout/preset.py
- randovania/server/discord/preset_lookup.py
- test/cli/commands/test_batch_distribute.py
- test/cli/commands/test_distribute_command.py
- test/generator/test_generator_reach.py
- test/gui/test_game_session_window.py
- test/layout/test_game_patches_serializer.py
- test/layout/test_generator_parameters.py
- test/layout/test_permalink.py
- test/server/test_database.py
Fixes #2598.
Adds best effort of discovering which games a permalink has even if it can't decode the presets.
> Improve GeneratorParameters encoding

- randovania/gui/dialog/game_input_dialog.py
> GameInputDialog: Save the selected output directory itself for directory output

- randovania/server/discord/bot.py
- randovania/server/discord/database_command.py
- randovania/server/discord/preset_lookup.py
- test/server/discord/test_database_command.py
- test/server/discord/test_preset_lookup.py
Show seed hash, git version, read from somewhat incompatible versions, interact with all guilds.
Fixes #2597.
> Bot: support new permalink features

- randovania/gui/data_editor.py
> Data Editor: Hide map viewer for prime games

- CHANGELOG.md
- randovania/gui/preset_settings/patcher_energy_tab.py
> Remove 1HP Mode UI for Non-Echoes Games

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/header.json
Everything in Intermediate for now.
> Add trick for Hell/Cold runs in Dread

- randovania/cli/commands/batch_distribute.py
> Fix batch_distribute

- randovania/games/dread/item_database/item-database.json
- randovania/games/dread/patcher/open_dread_patcher.py
- requirements-small.txt
- requirements.txt
- setup.cfg
> bump open-dread-rando and update alt models

- CHANGELOG.md
- randovania/gui/preset_settings/item_pool_tab.py
> Improve text for ammo in Item pool tab.

- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/header.json
Fixes the event in Freezer in Dairon and renames the event to be more readable
> Fix incorrect event in Dairon

- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
There is an EMMI valve blocking this pathway
> Fix connection in Green EMMI Introduction room

- CHANGELOG.md
- randovania/games/prime1/json_data/Magmoor Caverns.json
- randovania/games/prime1/json_data/Magmoor Caverns.txt
Lowered Monitor Station climb NSJ/No bombs difficulty. Expert is way too high for this trick
> Prime 1: Lower Monitor Station NSJ requirements

- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
You can shoot this wide beam block from below with wave beam
> Dairon transport access - Wide Beam Block with Wave

- .idea/runConfigurations/Validate.xml
- randovania/game_description/resources/logbook_asset.py
- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
This helps the generator/solver handle the ponr there.
> Make Missile Tank on path to Proto EMMI required

- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
Recombined Ghavoran Teleportal to Cataris with Golzuna Tower for better logic usage
> Minor Ghavoran Updates

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
Fixed dairon big hub item, cataris green emmi introduction logic, added tricks for artaria in thermal door tutorial for pseudo-wave of lower blob, for single wall jump to item / emmi door in Energy recharge station south, in burenia for crossbomb to fan item, for reaching the fan from the bottom by having lowered the water.
> Logic fixes and additions

- randovania/cli/commands/export_db_videos.py
- test/cli/commands/test_export_videos.py
- Minimum trick difficulty above each video
- Sort videos by difficulty on each connection (beginner first)
- Fix for multiple videos on one comment
- Skip duplicate videos (same video start time)
> Improved Database Video Export

- CHANGELOG.md
- randovania/gui/game_session_window.py
- randovania/network_common/admin_actions.py
- randovania/server/game_session.py
- test/gui/test_game_session_window.py
- test/server/test_game_session.py
- Rename session
- Duplicate session
> Game sesssion improvements

- CHANGELOG.md
- randovania/gui/game_session_window.py
- randovania/layout/description_migration.py
- randovania/layout/layout_description.py
- randovania/server/database.py
- test/layout/test_layout_description.py
- test/server/test_game_session.py
> Multiworld sessions can now be generated without spoilers.

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- test/game_description/test_integrity_check.py
- test/generator/test_generator_reach.py
Enforce test_database_collectable for all games.
Force test_find_database_errors for Dread.
Fix errors in Dread raised by these.
> Increase strictness with database checks.

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
Sorry to whoever reviews this on how much it is.
> Various logic fixes and additions

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
This reverts commit 3606712973037bf25a593bd7949079837f6b2623, reversing
changes made to aca2295cec49eac3bf7e52b928c8621b355db773.
> Revert "Merge pull request #2819 from XenoWars/main"

- randovania/games/dread/exporter/patch_data_factory.py
> add details to dread title screen

- CHANGELOG.md
- randovania/games/prime2/json_data/Temple Grounds.json
- randovania/games/prime2/json_data/Temple Grounds.txt
Currently only trickless means to obtain Sunburst requires Grapple Beam, adding SA as an alternative
> Revise Grand Windchamber logic

- CHANGELOG.md
- randovania/gui/game_session_window.py
- randovania/gui/lib/file_prompts.py
> Add `Import game/spoiler` button to GameSessionWindow

- CHANGELOG.md
- randovania/gui/game_details/game_details_window.py
- test/gui/test_game_details_window.py
> Game Details: show version that generated the game

- CHANGELOG.md
- randovania/games/prime1/exporter/patch_data_factory.py
> Use new combat visor model in cross-game multi

- README.md
> Update MaskedTAS twitter link.

- CHANGELOG.md
- randovania/games/prime1/gui/dialog/game_export_dialog.py
- randovania/games/prime2/gui/dialog/game_export_dialog.py
- randovania/gui/dialog/game_export_dialog.py
- randovania/patching/prime/asset_conversion.py
Organizes entries in changelog
Formatting code
> Fix potential error in EchoesGameExportDialog

- tools/prepare_virtual_env.bat
- tools/prepare_virtual_env.sh
> Install all packages in prepare_virtual_env

- randovania/game_description/resources/pickup_index.py
- randovania/game_description/world/node_identifier.py
- test/game_description/test_requirements.py
Solves these classes not properly having the ResourceInfo API
> Add short_name to PickupIndex and NodeIdentifier

- CHANGELOG.md
- randovania/games/prime2/exporter/game_exporter.py
- randovania/gui/game_details/game_details_window.py
- randovania/lib/json_lib.py
- randovania/patching/prime/asset_conversion.py
- test/gui/test_game_details_window.py
Code cleanup and slight speedup for Echoes.
> Asset conversion improvements

- CHANGELOG.md
- randovania/games/prime1/exporter/patch_data_factory.py
- randovania/games/prime1/json_data/Chozo Ruins.json
- randovania/games/prime1/json_data/Chozo Ruins.txt
- randovania/games/prime1/json_data/Frigate Orpheon.json
- randovania/games/prime1/json_data/Frigate Orpheon.txt
- randovania/games/prime1/json_data/Impact Crater.json
- randovania/games/prime1/json_data/Impact Crater.txt
- randovania/games/prime1/json_data/Magmoor Caverns.json
- randovania/games/prime1/json_data/Magmoor Caverns.txt
- randovania/games/prime1/json_data/Phazon Mines.json
- randovania/games/prime1/json_data/Phazon Mines.txt
- randovania/games/prime1/json_data/Phendrana Drifts.json
- randovania/games/prime1/json_data/Phendrana Drifts.txt
- randovania/games/prime1/json_data/Tallon Overworld.json
- randovania/games/prime1/json_data/Tallon Overworld.txt
- randovania/games/prime1/json_data/header.json
- randovania/games/prime1/layout/prime_configuration.py
- randovania/games/prime1/presets/april_fools_2022.rdvpreset
- randovania/gui/preset_settings/item_configuration_widget.py
- randovania/gui/ui_files/preset_prime_patches.ui
- requirements.txt
- setup.cfg
- test/test_files/randomprime_expected_data_crazy.json
- test/test_files/randomprime_expected_data_one_way_door.json
> Prime - Randovania Managed "Items in Every Room"

- randovania/games/dread/exporter/patch_data_factory.py
- randovania/games/dread/gui/dialog/dread_cosmetic_patches_dialog.py
- randovania/games/dread/gui/preset_settings/__init__.py
- randovania/games/dread/layout/dread_configuration.py
- randovania/games/dread/layout/dread_cosmetic_patches.py
- randovania/games/dread/layout/preset_describer.py
- randovania/games/dread/presets/starter_preset.rdvpreset
- randovania/gui/preset_settings/patcher_energy_tab.py
- randovania/gui/ui_files/dread_cosmetic_patches_dialog.ui
- randovania/gui/ui_files/preset_patcher_energy.ui
- randovania/layout/preset_migration.py
- requirements.txt
- setup.cfg
1) added cosmetic options 
2) exposed an option for immediate energy parts, enabled by default
3) added pulse radar to the starter preset as a starting item
> some small changes to dread

- randovania/games/dread/gui/dialog/game_export_dialog.py
- randovania/gui/ui_files/dread_game_export_dialog.ui
- test/games/dread/gui/test_dread_game_export_dialog.py
* Improve validation in FTP
* Improve tab ordering
* Save state of all tabs
> Improve Dread game export

- CHANGELOG.md
- randovania/gui/online_game_list_window.py
- randovania/gui/qt.py
- randovania/network_client/network_client.py
- randovania/server/game_session.py
- randovania/server/server_app.py
- test/server/test_game_session.py
> Only get latest 100 sessions by default.

- randovania/game_description/resources/resource_database.py
- randovania/games/dread/exporter/patch_data_factory.py
- randovania/games/dread/generator/base_patches_factory.py
- randovania/games/dread/generator/bootstrap.py
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
- randovania/games/dread/layout/dread_configuration.py
- randovania/layout/description_migration.py
- randovania/layout/game_patches_serializer.py
- requirements.txt
- setup.cfg
- test/layout/test_game_patches_serializer.py
- test/server/test_database.py
* Exports dock weakness customizing for open dread rando
> * Implements dock weakness serializing for GamePatches

- randovania/games/prime1/layout/preset_describer.py
Fixes #3128
This can probably go into stable
> Phazon suit hint in preset describer

- randovania/games/dread/exporter/patch_data_factory.py
- requirements.txt
- setup.cfg
> Update for open-dread-rando 0.17.0

- requirements.txt
Reverts randovania/randovania#3184
This version is missing wheels.
> Revert "Bump dulwich from 0.20.37 to 0.20.38"

- randovania/cli/cli_lib.py
- randovania/cli/commands/generate.py
- randovania/cli/commands/validate.py
- test/cli/commands/test_generate_cli.py
This is useful to run these multiple times to remove the variation.
> Add --repeat for validate/generate in CLI

- randovania/game_description/resources/item_resource_info.py
- randovania/game_description/resources/pickup_index.py
- randovania/game_description/resources/simple_resource_info.py
- randovania/game_description/resources/trick_resource_info.py
- randovania/game_description/world/area.py
- randovania/game_description/world/area_identifier.py
- randovania/game_description/world/configurable_node.py
- randovania/game_description/world/dock.py
- randovania/game_description/world/dock_lock_node.py
- randovania/game_description/world/dock_node.py
- randovania/game_description/world/event_node.py
- randovania/game_description/world/logbook_node.py
- randovania/game_description/world/node.py
- randovania/game_description/world/node_identifier.py
- randovania/game_description/world/pickup_node.py
- randovania/game_description/world/player_ship_node.py
- randovania/game_description/world/resource_node.py
- randovania/game_description/world/teleporter_node.py
- randovania/game_description/world/world.py
> Use slots=True in dataclasses

- CHANGELOG.md
- randovania/games/prime1/exporter/game_exporter.py
- randovania/patching/prime/asset_conversion.py
- requirements.txt
- setup.cfg
- test/games/prime1/exporter/test_prime_game_exporter.py
> Convert extra echoes models

- CHANGELOG.md
- randovania/games/prime1/item_database/item-database.json
- randovania/games/prime1/json_data/header.json
- randovania/generator/filler/pickup_list.py
- randovania/generator/filler/retcon.py
- randovania/generator/filler/runner.py
- randovania/generator/item_pool/pickup_creator.py
- test/games/prime1/exporter/test_prime_patcher_data_factory.py
- test/resolver/item_pool/test_pickup_creator.py
- test/test_files/randomprime_expected_data.json
- test/test_files/randomprime_expected_data_crazy.json
- test/test_files/randomprime_expected_data_one_way_door.json
I'm not happy with how locked resources work, but it works for now. If I don't make that change for Prime 1 then generator will place expansions first compared to mains and that's just boring.
> Expansions for multi pickup

- randovania/games/dread/gui/preset_settings/__init__.py
- randovania/games/dread/gui/preset_settings/dread_item_pool_tab.py
- randovania/games/dread/json_data/header.json
> Dread: Add GUI for customizing Energy Parts in pool

- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
> Dread: Fix Thermal Door not being defined

- randovania/game_description/requirements.py
With an incredible sample size of 1, it sped up a dock rando seed gen by 10%.
> Minor optimizations in Requirements

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/header.json
- Added methods to reach Pickup (Missile Tank) 1 in Melee Tutorial using Ice Missiles
- Added IBJ methods to reach the door and Tile Group (BOMB) in Proto EMMI Introduction from the bottom
- Added new trick: Stand on Frozen Enemies, used where the player must freeze an enemy in order to stand on it to get somewhere
> Dread: Revise Proto EMMI Intro and Melee Tutorial

- randovania/game_description/world/node_identifier.py
New time: 157.346s
Old time: 167.641s
Speedup of 6.5%.
> Cache NodeIdentifier hash

- randovania/game_description/requirements/resource_requirement.py
- randovania/game_description/world/event_node.py
- randovania/game_description/world/logbook_node.py
- randovania/game_description/world/pickup_node.py
- randovania/game_description/world/player_ship_node.py
- randovania/games/dread/generator/base_patches_factory.py
- randovania/games/prime1/generator/bootstrap.py
- randovania/games/prime2/generator/base_patches_factory.py
- randovania/generator/dock_weakness_distributor.py
- randovania/generator/filler/pickup_list.py
- randovania/generator/old_generator_reach.py
- randovania/gui/dialog/connections_editor.py
- randovania/gui/lib/connections_visualizer.py
- randovania/gui/tracker_window.py
- randovania/resolver/event_pickup.py
- test/game_description/test_pretty_print.py
- test/game_description/test_requirements.py
- test/game_description/world/test_world_list.py
- test/games/prime2/patcher/test_patch_data_generator.py
- test/generator/filler/test_pickup_list.py
- test/generator/test_base_patches_factory.py
- test/generator/test_generator_reach.py
- test/layout/test_game_patches_serializer.py
Old time: 157.346s
New time:  140.695s
Speedup: 11.8%
> Specialize ResourceRequirement into different classes for optimization

- randovania/game_description/editor.py
- randovania/game_description/world/dock_node.py
- randovania/game_description/world/node_identifier.py
- randovania/gui/dialog/node_details_popup.py
- randovania/resolver/event_pickup.py
- requirements.txt
- setup.cfg
> Change NodeIdentifier to use attrs instead of dataclasses.

- randovania/game_description/editor.py
> Fix being unable to rename DockNodes that have valid locks.

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- requirements.txt
- Added possibility of using Bombs to destroy some blobs in case you may not have a beam
- Added beam requirement to the pseudos in Melee Tutorial and Early Cloak
- Lowered Cold Introduction damage run to Beginner
- Added Speed requirement to climbing Phantom Cloak Tutorial
- Changed the Access Closed in Charge Beam Access to a Missile Door
> Dread: Small revisions to a few rooms in Artaria

- randovania/game_description/data_reader.py
- randovania/game_description/editor.py
- randovania/game_description/game_patches.py
- randovania/game_description/world/dock_lock_node.py
- randovania/game_description/world/logbook_node.py
- randovania/game_description/world/node.py
- randovania/game_description/world/world_list.py
- randovania/generator/old_generator_reach.py
- randovania/gui/data_editor.py
- randovania/gui/dialog/node_details_popup.py
- randovania/resolver/event_pickup.py
- randovania/resolver/resolver_reach.py
- test/game_description/test_editor.py
- test/game_description/world/test_world_list.py
- test/games/prime/patcher_file_lib/test_item_hints.py
- test/games/prime/patcher_file_lib/test_pickup_exporter.py
- test/generator/test_generator_reach.py
- test/gui/preset_settings/test_location_pool_row_widget.py
- test/resolver/test_resolver_reach.py
> Nodes: Have NodeIndex be defined on constructor

- randovania/game_description/data_reader.py
- randovania/game_description/resources/item_resource_info.py
- randovania/game_description/resources/node_resource_info.py
- randovania/game_description/resources/resource_database.py
- randovania/game_description/resources/resource_info.py
- randovania/game_description/resources/simple_resource_info.py
- randovania/game_description/resources/trick_resource_info.py
- randovania/games/blank/json_data/header.json
- test/cli/commands/test_database_cli.py
- test/game_description/test_pickup_entry.py
- test/game_description/test_requirements.py
- test/game_description/world/test_world_list.py
- test/games/prime/patcher_file_lib/test_pickup_exporter.py
- test/games/prime2/patcher/test_patch_data_generator.py
- test/gui/dialog/test_trick_details_popup.py
- test/network_client/test_network_client.py
Closes #3296.
For `DaTmoSINQL63aukNRpBXJajbBiAka4MQVCsh` (seed hash `42QSEDKA`), the times are:
Old: 134.482 seconds
New: 127.007 seconds
Speedup: 5.8%
> Add a resource_index to Resources, use array in ResourceCollection

- randovania/game_description/game_description.py
- randovania/game_description/requirements/requirement_list.py
- randovania/game_description/resources/resource_info.py
- test/game_description/test_game_description.py
> Add bitmask to requirements

- CHANGELOG.md
- randovania/server/discord/database_command.py
- test/server/discord/test_database_command.py
> Ignore lock nodes in the discord bot

- randovania/generator/dock_weakness_distributor.py
This saves us from wasting time with a generation result that'd fail the solver later on.
> Run the resolver before starting the weakness rando

- CHANGELOG.md
- requirements.txt
- setup.cfg
> Randomprime v1.7

- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- Added Speed Booster method in Left Entrance to reach the EMMI Zone
- Corrected the Right Entrance <-> Spider Magnet Elevator and the Super Missile Room -> Super Missile Room Access dock types
- Added Speed Booster method to reach Tunnel to Super Missile Room Access in Dairon Transport Access
- Added various methods of climbing Blue EMMI Introduction
- Added wall jump methods of climbing Super Missile Room Access
> Dread: Revise logic for the Super Missile loop

- requirements.txt
- setup.cfg
- Fixes #3433
- Fixes #3432
- Fixes #3431
- Fixes #3428
- Fixes #3380
- Fixes #3412 
- Fixes #3422 
- Fixes music triggers near boss battles
- Probably helps with recent crashes described in #3421
> Randomprime v1.8.1

- randovania/patching/patchers/gamecube/iso_packager.py
- test/games/patchers/gamecube/test_iso_packager.py
> Fix exporting Echoes iso

- requirements.txt
- setup.cfg
- Fixes #3439
- Fixes #3448 
- Patcher implementation for #2051
> Randomprime v1.9.0

- randovania/games/dread/json_data/header.json
> Added trick descriptions for Dread

- requirements.txt
- setup.cfg
Fixes some of the more pressing issues described in #3312
> Randomprime v1.9.3

- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
- Change the Advanced requirement to Beginner
> Dread: Change PBs opening Charge Doors to Beginner Knowledge

- randovania/bitpacking/bitpacking.py
- test/bitpacking/test_bitpacking.py
This allows us to have values in configuration classes that can be None.
> Support optional values in bitpacking

- randovania/__init__.py
- randovania/gui/lib/clickable_label.py
- randovania/gui/lib/flow_layout.py
- randovania/gui/main_window.py
- randovania/gui/ui_files/main_window.ui
- randovania/gui/widgets/about_widget.py
- test/gui/test_main_window.py
> adjustments for the game intro tab

- randovania/server/discord/bot.py
- randovania/server/discord/database_command.py
- randovania/server/discord/faq_command.py
- randovania/server/discord/preset_lookup.py
- randovania/server/discord/randovania_cog.py
- requirements.txt
- setup.cfg
- test/server/discord/test_bot.py
- test/server/discord/test_database_command.py
- test/server/discord/test_faq_command.py
- test/server/discord/test_preset_lookup.py
The former is no longer developed, the later changed it's api entirely, so we'd have to rewrite everything anyway.
> Use py-cord instead of discord.py and discord-py-interactions

- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
Before:
After:
Using the method presented in this video https://youtu.be/KX6N59HDpNM?t=115
> Dread: Add connection to get Main Hub Tower Top Energy Tank

- randovania/gui/ui_files/games_tab_blank_widget.ui
- randovania/gui/ui_files/games_tab_cavestory_widget.ui
- randovania/gui/ui_files/games_tab_corruption_widget.ui
- randovania/gui/ui_files/games_tab_dread_widget.ui
- randovania/gui/ui_files/games_tab_echoes_widget.ui
- randovania/gui/ui_files/games_tab_prime_widget.ui
- randovania/gui/ui_files/games_tab_supermetroid_widget.ui
- randovania/gui/widgets/base_game_tab_widget.py
> display cover art in intro tab

- CHANGELOG.md
- randovania/generator/filler/filler_logging.py
- randovania/generator/filler/player_state.py
- randovania/generator/filler/retcon.py
- randovania/generator/hint_distributor.py
- randovania/resolver/state.py
Ooops regression from some refactor
> Fix hints not being placed during generation

- .github/workflows/tests.yml
The certificate is not available so it fails
> Don't build installer on prs

- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- test/test_files/dread_expected_data.json
> Make all pickup indices for Dread a single sequence

- randovania/gui/main_window.py
- randovania/gui/ui_files/main_window.ui
- randovania/gui/ui_files/randovania_help_widget.ui
> improve formatting of multiworld help, and mention it in the multi tab

- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
- Add two new tricks, Cross Bomb Skip and Climb Sloped Tunnels.
- Remove the HBJ trick
> Dread: Adjust the trick database a bit

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/Itorash.json
- randovania/games/dread/json_data/Itorash.txt
- randovania/games/dread/json_data/header.json
- Add Heat/Cold Runs trick to all instances of lava damage that did not already have it
- Added energy requirements for all 7 main bosses
> Dread: Adjust lava damage and boss energy requirements

- randovania/gui/widgets/about_widget.py
Fixes issue https://github.com/randovania/randovania/issues/3590
> Set QtWidget to open links externally

- CHANGELOG.md
- randovania/gui/ui_files/games_tab_blank_widget.ui
- randovania/gui/ui_files/games_tab_cavestory_widget.ui
- randovania/gui/ui_files/games_tab_corruption_widget.ui
- randovania/gui/ui_files/games_tab_dread_widget.ui
- randovania/gui/ui_files/games_tab_echoes_widget.ui
- randovania/gui/ui_files/games_tab_prime_widget.ui
- randovania/gui/ui_files/games_tab_supermetroid_widget.ui
- Justify the introduction
- Replace horizontal widget with just a layout, improving size propagation and reducing borders
> Adjustments to the game introduction

- randovania/games/dread/gui/preset_settings/dread_goal_tab.py
- randovania/gui/ui_files/preset_dread_goal.ui
it's broken and is not a priority to fix for the moment
> prevent shuffling DNA in the world

- randovania/games/dread/json_data/Hanubia.json
- randovania/games/dread/json_data/Hanubia.txt
- randovania/games/dread/json_data/Itorash.json
- randovania/games/dread/json_data/Itorash.txt
raven beak isn't technically complete, but any remaining details are *very* minor imo and are not a priority
fixes a logic issue in hanubia regarding breaking screw attack blocks below a morph tunnel
> some hanubia + itorash logic

- randovania/games/dread/exporter/patch_data_factory.py
- test/test_files/dread_expected_data.json
- test/test_files/log_files/dread_1.rdvgame
Workaround for https://github.com/randovania/open-dread-rando/issues/141
> Do not use progressive models for pickups in Hanubia.

- randovania/gui/ui_files/games_tab_dread_widget.ui
- randovania/gui/widgets/base_game_tab_widget.py
> Add a list of known crashes to Dread.

- .github/workflows/tests.yml
- tools/Randovania Installer.aip
- Install to application folder
- Change application folder to default to where we were installing before
- Use FolderDlg instead of ConfigureDlg, so we don't pointlessly offer feature selection
> Installer fixes:

- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/header.json
- Added event for the upper speed blocks in case the player somehow enters through the top door first
- Added two new nodes to make navigating the left side easier, "Left Blob Alcove" and "Room Top"
> Dread: Revise the Freezer to make it less dangerous

- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/header.json
Final review of Ferenia
- Looked over logic and searched for mistakes. 
- Changed all Event and Door names which still contained db names.
> Dread: Final Ferenia revision

- randovania/games/dread/json_data/Itorash.json
- randovania/games/dread/json_data/Itorash.txt
- randovania/games/dread/json_data/header.json
> Dread: Final Itorash revision

- randovania/games/dread/json_data/Hanubia.json
- randovania/games/dread/json_data/Hanubia.txt
- randovania/games/dread/json_data/header.json
Looked over the logic
- Changed event names accordingly
- Added Red Chozo requirements
- Added Gold Chozo event and requirements
> Dread: Final Hanubia revision

- randovania/games/dread/json_data/Elun.json
- randovania/games/dread/json_data/Elun.txt
- randovania/games/dread/json_data/header.json
Checked for logic errors and additional tricks
- Renamed Grapple event in Vertical Bomb Maze
> Dread: Final Elun revision

- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/header.json
Final review of Dairon
- renamed events
- added Grapple Beam movement (intermediate) to "Transport to Artaria" Area
- renamed "full samus controll" node to "Start Point"
> Dread: Final Dairon revision

- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
5 events in Cataris and 2 in Ghavoran were all that remained. Renamed the rest of the docks in Cataris as well and the two in Spin Boost Tower.
> Dread: Rename the remaining events in Cataris and Ghavoran

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/Elun.json
- randovania/games/dread/json_data/Elun.txt
- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
- Changed "Lay Cross Comb" to "Lay Cross Bomb"
- Changed Simple IBJ to include Beginner IBJ for Cross Bombs and Intermediate IBJ for Bombs
- Added two new events for the trigger and fight of the Chozo-X in Ghavoran
> Dread: Fix Lay Cross Bomb typo and add Ghavoran Chozo-X

- randovania/games/dread/game_data.py
> Added debug input 

- CHANGELOG.md
- randovania/games/dread/game_data.py
> Dread: Add FAQ entry for Wide Beam door in Dairon

- CHANGELOG.md
- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
Adds Gravity Suit as a requirement for the Space Jump and walljump methods rather than being optional.
> Dread: Fix Purple EMMI Arena logic to climb the tower.

- CHANGELOG.md
- randovania/games/blank/generator/pool_creator.py
- randovania/games/blank/json_data/Intro.json
- randovania/games/blank/json_data/Intro.txt
- randovania/games/blank/json_data/header.json
- randovania/resolver/resolver.py
- test/generator/filler/test_player_state.py
- test/resolver/test_resolver.py
- test/test_files/log_files/blank/issue-3717.rdvgame
> Resolver: don't use node identifier resources for additional requirements

- CHANGELOG.md
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- Added Advanced Cross Bomb Skip methods
- Added Power Bombs method for the Speedbooster Conservation
> Dread: Add logic to getting Cross Bomb Puzzle Room item

- CHANGELOG.md
- randovania/gui/game_details/game_details_window.py
- randovania/gui/ui_files/game_validator_widget.ui
- randovania/gui/widgets/game_validator_widget.py
- test/gui/test_game_details_window.py
- test/gui/widgets/test_game_validator_widget.py
> Add GUI tooling for running the validator

- CHANGELOG.md
- randovania/gui/dialog/preset_history_dialog.py
- randovania/gui/lib/file_prompts.py
- randovania/gui/ui_files/preset_history_dialog.ui
- randovania/gui/widgets/generate_game_widget.py
- randovania/interface_common/preset_manager.py
- randovania/layout/preset.py
- randovania/layout/versioned_preset.py
- test/gui/dialog/test_preset_history_dialog.py
- test/gui/widgets/test_generate_game_widget.py
- test/interface_common/test_preset_manager.py
> Add dialog for viewing past versions of a preset

- CHANGELOG.md
- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
> a couple quick dread db changes

- requirements-lint.txt
- requirements.txt
- tools/update_requirements.py
Add --upgrade argument to update_requirements.py
> Update all dependencies

- CHANGELOG.md
- randovania/games/dread/layout/dread_configuration.py
- randovania/gui/lib/async_dialog.py
- randovania/gui/widgets/generate_game_widget.py
- randovania/layout/base/base_configuration.py
- randovania/layout/preset_describer.py
- test/games/dread/layout/test_dread_configuration.py
- test/gui/lib/test_async_dialog.py
- test/gui/widgets/test_generate_game_widget.py
> Add to preset description when it uses unsupported feature

- CHANGELOG.md
- randovania/games/prime2/json_data/Temple Grounds.json
- randovania/games/prime2/json_data/Temple Grounds.txt
Re-added a Slope Jump, and added a new Boost Ball way to access the item in Communication Area.
> Communication Area additions

- requirements.txt
- setup.cfg
> Randomprime v10.1.4

- randovania/games/prime3/json_data/SkyTown Elysia - Main.json
- randovania/games/prime3/json_data/SkyTown Elysia - Main.txt
- Changes the connection from Door to Transit Hub to Door to Barracks Lift to go to Door to Aurora Lift
- Changes the connection from Door to Barracks Lift to Door to Transit Hub to go from Door to Aurora Lift
> Prime 3: Fix connections in Zipline Station Bravo

- randovania/games/samus_returns/json_data/Area 1.json
- randovania/games/samus_returns/json_data/Area 1.txt
- randovania/games/samus_returns/json_data/Area 2 - Exterior.json
- randovania/games/samus_returns/json_data/Area 2 - Exterior.txt
- randovania/games/samus_returns/json_data/Area 3 - Exterior.json
- randovania/games/samus_returns/json_data/Area 3 - Exterior.txt
- randovania/games/samus_returns/json_data/Area 3 - Interior East.json
- randovania/games/samus_returns/json_data/Area 3 - Interior East.txt
- randovania/games/samus_returns/json_data/Area 3 - Interior West.json
- randovania/games/samus_returns/json_data/Area 3 - Interior West.txt
- randovania/games/samus_returns/json_data/Area 4 - East.json
- randovania/games/samus_returns/json_data/Area 4 - East.txt
- randovania/games/samus_returns/json_data/Area 4 - West.json
- randovania/games/samus_returns/json_data/Area 4 - West.txt
- randovania/games/samus_returns/json_data/Area 5 - Entrance.json
- randovania/games/samus_returns/json_data/Area 5 - Entrance.txt
- randovania/games/samus_returns/json_data/Area 6.json
- randovania/games/samus_returns/json_data/Area 6.txt
- randovania/games/samus_returns/json_data/Area 8.json
- randovania/games/samus_returns/json_data/Area 8.txt
- randovania/games/samus_returns/json_data/Surface - East.json
- randovania/games/samus_returns/json_data/Surface - East.txt
- randovania/games/samus_returns/json_data/header.json
- randovania/games/samus_returns/json_data/header.txt
- Add Nothing item
- Remove unused templates
- Remove more Chozo Seal requirements
- Cleanup unnecessary requirements
> Samus Returns Database Updates

- CHANGELOG.md
- randovania/games/prime2/json_data/Agon Wastes.json
- randovania/games/prime2/json_data/Agon Wastes.txt
- randovania/games/prime2/json_data/Sanctuary Fortress.json
- randovania/games/prime2/json_data/Sanctuary Fortress.txt
- Lowered difficulty of Sand Processing glass clip and added video
- Cleaned up Main Gyro and fix requirements
> Echoes - Minor Updates

- CHANGELOG.md
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
This Water Bomb Jump appears to be impossible.
> Dread: Remove WBJ from Ghavoran Map Station Access Secret

- CHANGELOG.md
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
Fix Readme for Prime 2 as well
> Dread - Climbing Z-57 Room with Ice and Spin

- randovania/games/prime3/json_data/Bryyo - Reptilicus.json
- randovania/games/prime3/json_data/Bryyo - Reptilicus.txt
- randovania/games/prime3/json_data/GFS Valhalla.json
- randovania/games/prime3/json_data/GFS Valhalla.txt
- randovania/games/prime3/json_data/Pirate Homeworld - Research.json
- randovania/games/prime3/json_data/Pirate Homeworld - Research.txt
- randovania/games/prime3/json_data/SkyTown Elysia - Main.json
- randovania/games/prime3/json_data/SkyTown Elysia - Main.txt
- Added a few more videos
- Adjusted some trick levels
- Added a few more tricks
> Corruption Updates

- randovania/__init__.py
- randovania/interface_common/update_checker.py
- randovania/monitoring/__init__.py
- setup.py
- Dirty repositories do not report
- Indicate if you're frozen or not as data
> Better handle frozen and dirty reports to Sentry

- randovania/data/gui_assets/tracker/prime3-game.json
> Fix Corruption tracker making reference to missing asset

- CHANGELOG.md
- randovania/games/dread/gui/preset_settings/__init__.py
- randovania/games/dread/layout/dread_configuration.py
- randovania/games/prime2/gui/preset_settings/echoes_patches_tab.py
- randovania/games/prime2/layout/echoes_configuration.py
- randovania/gui/preset_settings/starting_area_tab.py
- randovania/gui/ui_files/preset_echoes_patches.ui
- randovania/gui/ui_files/preset_generation.ui
- randovania/gui/widgets/generate_game_widget.py
- randovania/server/app.py
- Inverted Aether is now Unsupported
- Unsupported features are labeled as such in-app and requires a dev build
> Minor revamp for experimental/unsupported features

- randovania.spec
Put this in the root for now, so we don't have to fuss with the flatpak yml more. TODO: Make this Linux-only!
> Add xdg_assets to spec

- CHANGELOG.md
- randovania/gui/ui_files/.gitignore
- requirements.txt
- setup.cfg
> Randomprime v1.12.0

- CHANGELOG.md
- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/header.json
Removed all remaining Tile Nodes from the database in Artaria, Dairon, and Ghavoran
> Dread - Remove all remaining Tile Nodes

- CHANGELOG.md
- randovania/gui/online_game_list_window.py
Closes issue #3071
- Fixed: Searching for Multiworld sessions by name is no longer case sensitive.
> Multiworld Search Case Sensitivity

- randovania/cli/commands/patcher_data.py
- randovania/games/prime1/exporter/patch_data_factory.py
- test/test_files/randomprime_expected_data.json
Ensure `rooms` key exist in randomprime output
> Fix prime 1 export, patch-data cli

- CHANGELOG.md
- randovania/generator/item_pool/pool_creator.py
- randovania/gui/preset_settings/item_pool_tab.py
> Add major/minor count to tab

- randovania/games/cave_story/gui/dialog/cs_cosmetic_patches_dialog.py
- randovania/games/cave_story/gui/preset_settings/cs_goal_tab.py
- randovania/games/dread/gui/dialog/dread_cosmetic_patches_dialog.py
- randovania/games/prime1/gui/dialog/prime_cosmetic_patches_dialog.py
- randovania/games/prime1/gui/preset_settings/prime_hints_tab.py
- randovania/games/prime1/gui/preset_settings/prime_patches_chaos.py
- randovania/games/prime1/gui/preset_settings/prime_patches_qol.py
- randovania/games/prime2/gui/dialog/echoes_cosmetic_patches_dialog.py
- randovania/games/prime2/gui/preset_settings/echoes_beam_configuration_tab.py
- randovania/games/prime2/gui/preset_settings/echoes_goal_tab.py
- randovania/games/prime2/gui/preset_settings/echoes_hints_tab.py
- randovania/games/prime2/gui/preset_settings/echoes_translators_tab.py
- randovania/games/prime3/gui/dialog/corruption_cosmetic_patches_dialog.py
- randovania/gui/data_editor.py
- randovania/gui/dialog/connections_editor.py
- randovania/gui/dialog/node_details_popup.py
- randovania/gui/docks/connection_layer_widget.py
- randovania/gui/lib/common_qt_lib.py
- randovania/gui/lib/signal_handling.py
- randovania/gui/preset_settings/dock_rando_tab.py
- randovania/gui/preset_settings/elevators_tab.py
- randovania/gui/preset_settings/generation_tab.py
- randovania/gui/preset_settings/item_configuration_widget.py
- randovania/gui/preset_settings/item_pool_tab.py
- randovania/gui/preset_settings/pickup_style_widget.py
- randovania/gui/tracker_window.py
- test/games/dread/gui/test_dread_cosmetic_patches_dialog.py
- test/gui/dialog/test_corruption_cosmetic_patches_dialog.py
- test/gui/dialog/test_item_configuration_popup.py
- test/gui/preset_settings/test_item_pool_tab.py
Also fix DreadCosmeticPatchesDialog tests showing UI elements during tests
> Use signal_handling.set_combo_with_value whenever possible

- CHANGELOG.md
- randovania/games/prime2/json_data/Sanctuary Fortress.json
- randovania/games/prime2/json_data/Sanctuary Fortress.txt
Eventually will replace the clips with proper videos
> Echoes: Two Sanctuary Additions

- randovania/game_description/pickup/ammo_pickup.py
- randovania/games/dread/pickup_database/pickup-database.json
- randovania/gui/preset_settings/item_pool_tab.py
Rename "warning" to "description" in ammo_pickup to match standard_pickup
> Fix ammo_pickup field name

- pytest.ini
- randovania/game_connection/connector/prime_remote_connector.py
- randovania/lib/infinite_timer.py
- test/game_connection/builder/test_prime_connector_builder.py
- test/game_connection/connector/test_prime1_remote_connector.py
- test/game_description/test_integrity_check.py
- test/games/dread/gui/test_ftp_uploader.py
- test/lib/test_infinite_timer.py
- Fail tests if any test raises a warning
- Fail tests if there's any xpassed
- Default all games to expecting integrity checks to pass
> Improving test quality.

- CHANGELOG.md
- randovania/games/dread/layout/preset_describer.py
- randovania/games/prime1/layout/preset_describer.py
- randovania/games/prime2/layout/preset_describer.py
- randovania/games/prime3/layout/preset_describer.py
- randovania/games/samus_returns/layout/preset_describer.py
- randovania/layout/base/available_locations.py
- randovania/layout/base/logical_resource_action.py
- randovania/layout/preset_describer.py
- test/games/dread/layout/test_dread_describer.py
- test/games/prime1/layout/test_preset_describer.py
- test/games/prime2/layout/test_echoes_preset_describer.py
Left is before, right is after
> Improve the base Preset describer

- CHANGELOG.md
- randovania/gui/data_editor.py
- randovania/gui/dialog/node_details_popup.py
- randovania/gui/docks/resource_database_editor.py
- randovania/gui/lib/connections_visualizer.py
- randovania/gui/ui_files/data_editor.ui
- randovania/gui/ui_files/resource_database_editor.ui
> Use QTreeWidget for requirements

- randovania/generator/pickup_pool/pool_creator.py
- randovania/gui/preset_settings/item_pool_tab.py
- randovania/layout/preset_describer.py
- test/games/prime2/layout/test_echoes_preset_describer.py
- test/generator/item_pool/test_pool_creator.py
- test/gui/preset_settings/test_item_pool_tab.py
> Change calculate_pool_pickup_count to return the count per category

- randovania/bitpacking/json_dataclass.py
- test/bitpacking/test_json_dataclass.py
- Lists of anything supported
- Dicts of anything supported
- UUIDs
> Support for more types in JsonDataclass

- randovania/game_description/resources/location_category.py
- randovania/game_description/world/dock.py
- randovania/game_description/world/hint_node.py
- randovania/games/cave_story/layout/cs_configuration.py
- randovania/games/dread/layout/dread_configuration.py
- randovania/games/dread/layout/dread_cosmetic_patches.py
- randovania/games/prime2/layout/translator_configuration.py
- randovania/layout/base/damage_strictness.py
- randovania/layout/base/logical_resource_action.py
- randovania/layout/base/pickup_model.py
- randovania/layout/base/trick_level.py
- randovania/layout/lib/teleporters.py
- randovania/lib/enum_lib.py
- test/lib/test_enum_lib.py
This adds an easy to use way of adding a long_name to enum values
> Add enum_lib.add_long_name

- CHANGELOG.md
- randovania/games/prime2/exporter/patch_data_factory.py
- randovania/games/prime2/gui/dialog/echoes_cosmetic_patches_dialog.py
- randovania/games/prime2/layout/echoes_cosmetic_patches.py
- randovania/gui/preset_settings/elevators_tab.py
- randovania/gui/ui_files/echoes_cosmetic_patches_dialog.ui
- randovania/gui/ui_files/preset_elevators.ui
- randovania/interface_common/persisted_options.py
- randovania/layout/lib/teleporters.py
- test/games/prime2/exporter/test_echoes_patch_data_factory.py
Also dynamically generate the tab description.
> Echoes: automatically decide noise removal

- CHANGELOG.md
- randovania/games/blank/presets/starter_preset.rdvpreset
- randovania/games/cave_story/presets/classic.rdvpreset
- randovania/games/cave_story/presets/starter_preset.rdvpreset
- randovania/games/dread/exporter/patch_data_factory.py
- randovania/games/dread/generator/bootstrap.py
- randovania/games/dread/presets/april_fools_2023.rdvpreset
- randovania/games/dread/presets/starter_preset.rdvpreset
- randovania/games/prime1/generator/base_patches_factory.py
- randovania/games/prime1/generator/bootstrap.py
- randovania/games/prime1/presets/april_fools_2022.rdvpreset
- randovania/games/prime1/presets/moderate_challenge.rdvpreset
- randovania/games/prime1/presets/starter_preset.rdvpreset
- randovania/games/prime2/presets/darkszero_deluxe.rdvpreset
- randovania/games/prime2/presets/fewest_changes.rdvpreset
- randovania/games/prime2/presets/starter_preset.rdvpreset
- randovania/games/prime3/presets/starter_preset.rdvpreset
- randovania/games/samus_returns/presets/starter_preset.rdvpreset
- randovania/games/super_metroid/presets/starter_preset.rdvpreset
- randovania/generator/dock_weakness_distributor.py
- randovania/generator/generator.py
- randovania/gui/preset_settings/dock_rando_tab.py
- randovania/gui/ui_files/preset_dock_rando.ui
- randovania/layout/base/dock_rando_configuration.py
- randovania/layout/preset_describer.py
- randovania/layout/preset_migration.py
- test/generator/test_dock_weakness_distributor.py
- test/layout/test_dock_rando_configuration.py
This swaps an entire weakness at once with another one, allowing this generation to be fast and compatible with multiworld.
> Add Door Lock: Weaknesses

- .github/workflows/build-test-publish.yml
- CHANGELOG.md
- randovania/game_description/game_patches.py
- randovania/gui/game_details/game_details_window.py
- randovania/layout/layout_description.py
- randovania/lib/.gitignore
- randovania/lib/obfuscator.py
- test/conftest.py
- test/layout/test_layout_description.py
- test/lib/test_obfuscator.py
- tools/create_release.py
- Only available in builds provided by CI
- Spoiler is obfuscated with symetric encryption
- Attempts to hide the key for encryption
This does not need to be fool-proof, just annoying.
> Support creating spoiler-less LayoutDescription from files

- randovania/gui/lib/scroll_message_box.py
- randovania/gui/ui_files/trick_usage_popup.ui
I wanted to select the errors from DB validation and paste them somewhere else where I can look at them more comfortably, this seemed like the best solution to me.
Also makes the trick text in trick usage popup selectable, as I remembered that a user wished for it.
> Make the text in ScrollMessageBox and Trick Usage Popup selectable

- CHANGELOG.md
- randovania/server/user_session.py
- test/server/test_user_session.py
> Properly handle the new discord usernames

- randovania/bitpacking/construct_dataclass.py
- randovania/bitpacking/json_dataclass.py
- test/bitpacking/test_construct_dataclasss.py
- test/bitpacking/test_json_dataclass.py
At some point this should really become it's own library
> New JsonDataclass features

- CHANGELOG.md
- randovania/cli/database.py
- test/cli/commands/test_database_cli.py
Would be nice to publish these on the website somehow
> Fix render-region-graph and improve output

- CHANGELOG.md
- randovania/games/prime2/json_data/Agon Wastes.json
- randovania/games/prime2/json_data/Agon Wastes.txt
- randovania/games/prime2/json_data/Great Temple.json
- randovania/games/prime2/json_data/Great Temple.txt
- randovania/games/prime2/json_data/Sanctuary Fortress.json
- randovania/games/prime2/json_data/Sanctuary Fortress.txt
- randovania/games/prime2/json_data/Temple Grounds.json
- randovania/games/prime2/json_data/Temple Grounds.txt
- randovania/games/prime2/json_data/Torvus Bog.json
- randovania/games/prime2/json_data/Torvus Bog.txt
142 video links for Echoes tricks.
> Echoes database videos

- randovania/bitpacking/construct_dataclass.py
- test/bitpacking/test_construct_dataclasss.py
- Fix Enum encoding
- UUIDs are fixed length
> Construct Dataclass improvements

- randovania/games/am2r/generator/bootstrap.py
- randovania/games/am2r/gui/preset_settings/__init__.py
- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/pickup_database/pickup-database.json
- randovania/games/am2r/presets/starter_preset.rdvpreset
- randovania/gui/preset_settings/patcher_energy_tab.py
- randovania/gui/ui_files/preset_am2r_patches.ui
See title.
Also renames Missiles/Supers for consistency
> Implement basic exporting options for AM2R

- randovania/bitpacking/construct_dataclass.py
- randovania/cli/commands/patcher_data.py
- randovania/game_connection/connector/debug_remote_connector.py
- randovania/game_connection/connector/prime_remote_connector.py
- randovania/game_connection/connector/remote_connector.py
- randovania/game_connection/game_connection.py
- randovania/games/blank/game_data.py
- randovania/games/dread/exporter/patch_data_factory.py
- randovania/gui/lib/preset_tree_widget.py
- randovania/gui/ui_files/generate_game_widget.ui
- randovania/gui/widgets/generate_game_widget.py
- randovania/lib/construct_lib.py
- randovania/network_client/network_client.py
- randovania/network_common/error.py
- test/bitpacking/test_construct_dataclasss.py
- test/game_connection/connector/test_prime1_remote_connector.py
- test/game_connection/test_game_connection.py
- test/gui/test_auto_tracker_window.py
- test/server/conftest.py
- test/server/test_database.py
- test/server/test_game_session.py
- test/test_files/patcher_data/dread/crazy_settings.json
- test/test_files/patcher_data/dread/custom_start.json
- test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json
- test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json
many different things I've changed while working on multiworld server
> Multiple Improvements

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
Renames some AM2R room names for consistency and fixes some wrong names
> Rename AM2R room names

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
Fixes generator getting stuck in BG3
> AM2R: Fix BG3 softlock

- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
Apparently i'm bad with directions, and interchanged east and west originally
> AM2R: Fix BG1 names

- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
AM2R does not use these, so i've removed them.
> AM2R: remove back only doors from DB

- randovania/gui/multiworld_client.py
- test/gui/test_multiworld_client.py
> Fix MultiworldClient not loading any data on start

- randovania/gui/multiworld_client.py
Performing a `ServerWorldSync` with non-Disconnected state joins the room for that world, meaning you'll now be notified of new pickup events.
This forces the client to send such a request immediately after connecting, otherwise we'd wait until some even from the game.
> Try to sync to server again after a reconnect

- randovania/network_client/network_client.py
- test/network_client/test_network_client.py
Likely the root cause of #4545, and the inconsistent issues @ThanatosGit mentioned.
Easy to reproduce locally as whenever you change and save a file, the debug server restarts.
> Rejoins the session room when reconnecting

- randovania/gui/dialog/select_preset_dialog.py
- randovania/gui/ui_files/select_preset_dialog.ui
- randovania/gui/widgets/multiplayer_session_users_widget.py
- test/gui/dialog/test_select_preset_dialog.py
> Add game selector to SelectPresetDialog

- randovania/gui/multiplayer_session_window.py
> Swap to session tab when exporting, so progress bar is visible

- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
This PR adds new teleporters to the DB that the patcher now always places for a better endgame.
> AM2R: Add teleporter pipes for better endgame

- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Fix misc things in the logic DB.
Need to go over the changes with @DruidVorse later.
> AM2R: fix misc things in the DB

- randovania/games/am2r/presets/starter_preset.rdvpreset
> AM2R: Make door lock generation not fail

- randovania/game_description/db/node.py
- randovania/game_description/resources/node_resource_info.py
- test/interface_common/test_simplified_patcher.py
Also adds a test to catch the way it broke.
> Fix generation after #4589

- randovania/game_connection/connector_builder_choice.py
- randovania/gui/auto_tracker_window.py
- randovania/gui/debug_backend_window.py
- randovania/gui/ui_files/auto_tracker_window.ui
- randovania/gui/ui_files/debug_connector_window.ui
- randovania/gui/widgets/item_tracker_widget.py
- randovania/interface_common/options.py
- test/gui/test_auto_tracker_window.py
- Option to which game to use when you've never been connected to a game
- Don't lose connected game and inventory when game disconnects
Fixes #4595
> Improve Auto Tracker and no connected games

- randovania/patching/prime/asset_conversion.py
> fix asset conversion

- randovania/games/prime2/json_data/Sanctuary Fortress.json
- randovania/games/prime2/json_data/Sanctuary Fortress.txt
- randovania/games/prime2/json_data/Torvus Bog.json
- randovania/games/prime2/json_data/Torvus Bog.txt
no seekers in main research
CATW excluded completely
sacrificial chamber <-> sacrificial chamber excluded completely
fixes #4567
hopefully fixes crashes in main research/CATW
> more echoes door lock exclusions

- randovania/gui/preset_settings/dock_rando_tab.py
> Hide the Door Types section for Vanilla randomization type

- randovania/gui/lib/foldable.py
Dunno if increasing the height is really the right fix for it, but it does work.
Fixes #4617
> Fix foldable being cut off

- CHANGELOG.md
- randovania/generator/generator.py
- randovania/gui/lib/generation_failure_handling.py
- randovania/gui/main_window.py
- randovania/gui/multiplayer_session_window.py
- randovania/gui/qt.py
- randovania/gui/ui_files/multiplayer_session.ui
- test/gui/test_multiplayer_session_window.py
> Improve the MultiplayerSessionWindow UX, add changelog

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/header.json
Need to review these with @DruidVorse later
> AM2R: add fusion mode requirements

- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
Was talking about this with @Jesright73 and we decided it's better to remove this.
> AM2R: do not remove super crystal if coming from right

- randovania/layout/layout_description.py
- randovania/layout/versioned_preset.py
- test/gui/lib/test_multiplayer_session_api.py
> Improve error messages when decoding invalid presets

- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/header.json
Already reviewed by @DruidVorse
> AM2R: make grave grotto change in DB

- CHANGELOG.md
- randovania/gui/lib/background_task_mixin.py
- randovania/gui/multiplayer_session_window.py
- randovania/network_common/__init__.py
I managed to reproduce it _once_ by spamming the button. It's very likely a weird race condition.
Also, I forgot some changelog.
> Handle background task being busy for multiworld

- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Need to go over the changes with @DruidVorse later.
> AM2R: Fix up traversing logic for larva rooms

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
See title, need to review this with @DruidVorse later
> AM2R: Fix traversal logic for Gravity Area Shaft

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
Already reviewed by @DruidVorse
> AM2R: Add damage boosting values

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Already reviewed by @DruidVorse
> AM2R: Fix Boss requirements

- randovania/gui/multiworld_client.py
- randovania/gui/ui_files/game_connection_window.ui
- randovania/gui/ui_files/multiplayer_session.ui
- randovania/gui/widgets/game_connection_window.py
- randovania/interface_common/world_database.py
- test/gui/widgets/test_game_connection_window.py
> Improved connected game visibility in GameConnectorWindow

- randovania/game_connection/connector/prime_remote_connector.py
> Detect when Dolphin quickly swaps games, without breaking hooks

- randovania/server/user_session.py
- test/server/test_user_session.py
- Revising for pure browser auth, after a client auth
- Closing the client and then finishing the browser flow
> Fix the login page breaking in a few cases

- randovania/gui/dialog/online_game_list_dialog.py
- randovania/gui/lib/qt_network_client.py
> Fix no visible error when server reject client due to version.

- randovania/gui/ui_files/randovania_help_widget.ui
> Revise Multiworld help text for new Multiworld Server

- CHANGELOG.md
- randovania/gui/game_details/game_details_window.py
- randovania/gui/lib/window_manager.py
- randovania/gui/main_window.py
- randovania/gui/multiplayer_session_window.py
> show world names in multiworld spoiler log

- randovania/gui/ui_files/randovania_help_widget.ui
- randovania/gui/widgets/about_widget.py
> Some small UX improvements to help and about page

- randovania/server/multiplayer/session_api.py
> Avoid more queries

- CHANGELOG.md
- randovania/network_common/pickup_serializer.py
- test/server/multiplayer/test_world_api.py
> bitpack negative resources

- CHANGELOG.md
- randovania/gui/dialog/text_prompt_dialog.py
- randovania/gui/multiplayer_session_window.py
- randovania/gui/widgets/multiplayer_session_users_widget.py
- randovania/server/multiplayer/session_admin.py
- test/gui/test_multiplayer_session_window.py
- test/server/multiplayer/test_session_admin.py
> Various MultiplayerSession improvements

- randovania/games/am2r/generator/bootstrap.py
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
Still needs to be reviewed by @DruidVorse
> AM2R: Add option for bomb block before A3

- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Adds boss doors to Door weaknes rando
some future PRs needs to clean up the door names to be more understandable as well as fix some keys (blergh) for some events while this is still in experimental pre-beta testing stage
> AM2R: Add new doors to door lock rando

- randovania/games/am2r/generator/bootstrap.py
- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
See title. apparently i had the option inverted earlier for some reason.
> AM2R: Fix grave grotto blocks option

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
> AM2R: revise database for softlock prevention blocks

- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
- randovania/gui/ui_files/preset_am2r_patches.ui
Makes all the new options accessible from the UI
> AM2R: Fix UI for new options

- randovania/games/am2r/generator/bootstrap.py
- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
- randovania/gui/ui_files/preset_am2r_patches.ui
Still needs to be reviewed by @DruidVorse
> AM2R: Add option for screw attack pipe blocks

- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
> AM2R: add emp doors to change from door lock rando

- randovania/games/dread/gui/dialog/dread_connector_prompt_dialog.py
- randovania/gui/widgets/game_connection_window.py
- test/gui/widgets/test_game_connection_window.py
> Improve UX of Dread's connector builder prompt

- randovania/game_connection/connector/echoes_remote_connector.py
- test/game_connection/connector/test_echoes_remote_connector.py
> fixes echoes remote connector on nintendont

- randovania/games/am2r/presets/starter_preset.rdvpreset
- test/games/am2r/generator/test_am2r_pool_creator.py
Makes launchers required (whoo!), reduces dna and better misc  options
> AM2R Starter preset improvements

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Want some confirmation first that door names are understandable before i put this out of draft
> AM2R: Rename Doors to be clearer

- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Burenia.json
- randovania/games/dread/json_data/Burenia.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Dairon.json
- randovania/games/dread/json_data/Dairon.txt
- randovania/games/dread/json_data/Elun.json
- randovania/games/dread/json_data/Elun.txt
- randovania/games/dread/json_data/Ferenia.json
- randovania/games/dread/json_data/Ferenia.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
- randovania/games/dread/json_data/Hanubia.json
- randovania/games/dread/json_data/Hanubia.txt
- randovania/games/dread/json_data/Itorash.json
- randovania/games/dread/json_data/Itorash.txt
- randovania/games/dread/json_data/header.json
- randovania/games/dread/json_data/header.txt
- test/game_description/test_integrity_check.py
This PR now only includes Dread.
> [Dread] Fix integrity checks

- CHANGELOG.md
- randovania/games/cave_story/generator/hint_distributor.py
- randovania/games/dread/generator/base_patches_factory.py
- randovania/games/dread/generator/hint_distributor.py
- randovania/games/prime2/generator/hint_distributor.py
- randovania/generator/hint_distributor.py
> Dread: Place a joke hint in the hint node used by DNA hints.

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Reorganizes event long and short names to be clearer and consistent
> AM2R reorganize events

- CHANGELOG.md
- randovania/gui/multiplayer_session_window.py
- randovania/gui/ui_files/multiplayer_session.ui
- test/gui/test_multiplayer_session_window.py
> Support filtering the history tab in MultiplayerSessionWindow

- CHANGELOG.md
- randovania/gui/game_details/game_details_window.py
- randovania/gui/game_details/generation_order_widget.py
- test/gui/game_details/test_generation_order_widget.py
> Add widget for filtering the GenerationOrder

- randovania/games/dread/pickup_database/pickup-database.json
- randovania/games/prime1/pickup_database/pickup-database.json
- randovania/games/prime2/pickup_database/pickup-database.json
Apart from what title says, also adds dread's charge beam to echoes charge beam as I noticed it was missing
> Adds AM2R offworld models to primes/dread

- randovania/game_connection/connector/debug_remote_connector.py
- randovania/gui/debug_backend_window.py
- randovania/gui/ui_files/debug_connector_window.ui
- Keep track of an inventory
- Have a list of messages
- Have UI for changing the inventory
- Send inventory to the server
> Improvements for DebugRemoteConnector and DebugConnectorWindow

- randovania/network_client/network_client.py
Reliable way of reproducing:
- Start local dev server with debug enabled
- Start client, connect to server and open a multiplayer session
- Update SERVER_API_VERSION to a bigger value, which causes the server to reload disconnecting user and no longer allow connection
- Do something in a connected game which causes a world_sync to happen
- World sync -> server_call -> connect_to_server. It connects, but then is rejected due to version. Sync fails.
- Another World sync -> server_call -> connect_to_server. This logs "sio is already connected" in _internal_connect_to_server, and then the server_call does not succeed and times out.
> Properly disconnect from server if rejected on session restore

- randovania/games/am2r/generator/bootstrap.py
- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
- randovania/gui/ui_files/preset_am2r_patches.ui
This option is depcrecated, as it was split up into further options.
> AM2R: Get rid of "dynamically change level design" option

- randovania/gui/ui_files/preset_am2r_patches.ui
Fixes typos and hopefully makes settings clearer
> AM2R: Change some wording on patches page

- CHANGELOG.md
- randovania/games/prime1/gui/preset_settings/prime_patches_qol.py
- randovania/games/prime1/layout/preset_describer.py
- randovania/games/prime1/layout/prime_configuration.py
- randovania/gui/ui_files/preset_prime_qol.ui
- requirements.txt
- setup.cfg
Hidden unless you turn on experimental
Update Randomprime to v1.14.1
> Add `Skippable` Cutscene Mode

- randovania/gui/dialog/multiplayer_session_browser_dialog.py
- randovania/gui/main_online_interaction.py
- randovania/gui/ui_files/multiplayer_session_browser_dialog.ui
- randovania/network_common/__init__.py
- randovania/network_common/multiplayer_session.py
- randovania/server/database.py
- randovania/server/multiplayer/session_api.py
- test/gui/lib/test_qt_network_client.py
- test/gui/test_main_online_interaction.py
- test/gui/test_multiplayer_session_browser_dialog.py
- test/server/multiplayer/test_session_api.py
Filtering for already joined sessions.
> Adds a "Joined Session?" filter and column for multiworld browse list

- randovania/games/am2r/pickup_database/pickup-database.json
Did a quick run with this before, apparently just works:tm:
> AM2R: Allow negative ammo expansions

- randovania/games/am2r/generator/bootstrap.py
> AM2R: Make dna be random again, instead of choosing first x ones

- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Found by @JeffGainsNGames , commited by me
> AM2R: Fix IBJ condition in hijump tunnel climb template

- randovania/game_connection/connector/corruption_remote_connector.py
- randovania/game_connection/connector/debug_remote_connector.py
- randovania/game_connection/connector/prime_remote_connector.py
- randovania/game_connection/connector/remote_connector.py
- randovania/gui/debug_backend_window.py
- randovania/gui/lib/model_lib.py
- randovania/gui/widgets/game_connection_window.py
- test/conftest.py
- test/game_connection/connector/test_echoes_remote_connector.py
- test/game_connection/connector/test_prime1_remote_connector.py
- test/gui/game_details/test_generation_order_widget.py
- test/gui/game_details/test_pickup_details_tab.py
- test/gui/test_debug_backend_window.py
- test/gui/test_multiplayer_session_window.py
- test/gui/widgets/test_game_connection_window.py
Skipped implementing it for Dread as it turned out to be more complicated than I expected.
> Add RemoteConnector.display_arbitrary_message

- randovania/cli/server.py
- randovania/server/app.py
- randovania/server/multiplayer/__init__.py
- randovania/server/multiplayer/session_admin.py
- randovania/server/multiplayer/session_api.py
- randovania/server/multiplayer/session_common.py
- randovania/server/multiplayer/web_api.py
- randovania/server/multiplayer/world_api.py
- randovania/server/server_app.py
- randovania/server/user_session.py
- test/network_client/test_network_client.py
- test/server/multiplayer/test_multiplayer_init.py
- test/server/multiplayer/test_session_admin.py
- test/server/multiplayer/test_session_api.py
- test/server/multiplayer/test_session_common.py
- test/server/multiplayer/test_world_api.py
- test/server/test_app.py
- test/server/test_server_app.py
- test/server/test_user_session.py
sio should mean SocketIO, so that was very wrong
> Rename all variables for ServerApp to sa

- .github/workflows/build-test-publish.yml
- .github/workflows/daily-generate.yml
- tools/post_discord_webhook.py
- Exclude certain jobs from running on merge queue
- Don't upload artifacts for PR/merge queue
- Don't build wheel everywhere
And also don't post link for the wheels in discord, no one cares
> Slight optimizations for CI:

- CHANGELOG.md
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
Thanks Logarhythmic for the videos
> Blue Emmi Intro: Add video of ballspark, remove trivial ballspark

- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
A1 - Golden Temple
- Fixed: Armory - reworked PB requirement to need 2 PBs with spider
- ~~Added: Inner Temple East Hall - locked door by EMP event unless Door Rando~~
- Fixed: Parkour Course - removed redundant walljump
- ~~Added: Spider Ball Chamber - added requirement for the tunnel climb heading down~~
- Added: Inner Temple West Hall - spider ball requirement for escape from bottom
> AM2R Database Updates

- randovania/gui/ui_files/games_tab_am2r_widget.ui
> AM2R: Add introduction description

- randovania/games/am2r/gui/dialog/cosmetic_patches_dialog.py
- randovania/games/am2r/layout/am2r_cosmetic_patches.py
- randovania/gui/ui_files/am2r_cosmetic_patches_dialog.ui
- test/games/am2r/gui/test_am2r_cosmetic_patches_dialog.py
Adds a few cosmetic options for am2r. Wondering whether the color rotation function should maybe be somewhere in some color lib.
> AM2R: Implement cosmetic options

- CHANGELOG.md
- randovania/games/prime1/json_data/Phendrana Drifts.json
- randovania/games/prime1/json_data/Phendrana Drifts.txt
Phendrana Drifts:
- Added: Quarantine Cave NSJ Scan Dash to Q-Mon Tunnel
> Added Quarantine Cave Scan Dash to Q-Mon Tunnel

- CHANGELOG.md
- randovania/gui/dialog/multiplayer_select_preset_dialog.py
- randovania/gui/lib/multiplayer_session_api.py
- randovania/gui/multiplayer_session_window.py
- randovania/gui/ui_files/multiplayer_session.ui
- randovania/gui/widgets/multiplayer_session_users_widget.py
- randovania/network_common/__init__.py
- randovania/network_common/admin_actions.py
- randovania/network_common/multiplayer_session.py
- randovania/server/database.py
- randovania/server/multiplayer/session_admin.py
- test/gui/lib/test_multiplayer_session_api.py
- test/gui/test_multiplayer_session_window.py
- test/server/multiplayer/test_session_admin.py
- test/server/multiplayer/test_session_api.py
- test/server/multiplayer/test_session_common.py
- test/server/test_database.py
> Allow Everyone to Claim + UI improvements

- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- Fixed: Breeding Grounds Fly Stadium - now correctly has an AND for the IBJ requirements
- Added: Breeding Grounds Gamma Nest Top - Escape back to Alpha Nest
- Added: Breeding Grounds Gamma Nest West - Added connection and requirements to Outer Caverns Crossroads
- Added: Exterior Gamma Nest - Added Ledge Climb to enter and morph requirement to leave
- Fixed: Exterior Gamma Nest Access - Leaving Gamma Nest now correctly has Wall Jump instead of Short Charge
- Added: Industrial Complex Exterior - Added connection from Exterior Maze (top) to allow logical escape
- Added: Lower Factory Tunnel - Added Morph requirement
- Added: Outer Caverns Crossroads - Added connection and requirements from Outer Caverns Crossroads to Bottom of Pit
- Added: Upper Factory Alpha Nest Access - Added bombs …
> AM2R: Industrial Complex Database Updates

- randovania/games/dread/game_data.py
- randovania/games/prime1/game_data.py
i couldve fixed this with two spaces, but felt two newlines is more visible to see.
> Fix newlines in prime1/dread faq

- randovania/games/am2r/game_data.py
> AM2R: Add FAQ

- CHANGELOG.md
- randovania/gui/lib/common_qt_lib.py
- randovania/gui/main_window.py
- randovania/gui/ui_files/select_preset_widget.ui
- randovania/gui/widgets/select_preset_widget.py
- randovania/interface_common/preset_manager.py
- randovania/layout/description_migration.py
- randovania/layout/preset_migration.py
- randovania/lib/migration_lib.py
- test/lib/test_migration_lib.py
- Disable menu actions that need a preset if it's invalid
- Add a clickable link that opens the preset dir when there's an error
- Show full error stack for unknown errors
> Better handle invalid presets

- randovania/games/am2r/exporter/patch_data_factory.py
- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
- randovania/gui/ui_files/preset_am2r_patches.ui
- test/games/am2r/exporter/test_am2r_patch_data_factory.py
- test/test_files/log_files/am2r/door_lock.rdvgame
- test/test_files/log_files/am2r/starter_preset.rdvgame
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
It should be a cosmetic setting now, not a preset setting
> Remove unexplored map from preset settings

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Needs review from other people
> AM2R: Add new trick for missile less metroid fights

- CHANGELOG.md
- randovania/__init__.py
- randovania/game_connection/connector_builder_choice.py
- randovania/gui/lib/window_manager.py
- randovania/gui/main_window.py
- randovania/gui/multiplayer_session_window.py
- randovania/gui/ui_files/game_connection_window.ui
- randovania/gui/ui_files/multiplayer_session.ui
- randovania/gui/widgets/game_connection_window.py
> Better UX for connectors

- randovania/games/am2r/json_data/header.json
Adds description for zip, CBJ, missile less metroid fights, and some misc improvements to knowledge and shinespark
> Add mising am2r trick descriptions

- randovania/games/prime1/json_data/Chozo Ruins.json
- randovania/games/prime1/json_data/Chozo Ruins.txt
This is already in the changelog
> Remove Door Lock exclusions from HoTE Statue Door

- CHANGELOG.md
- randovania/games/prime1/json_data/Chozo Ruins.json
- randovania/games/prime1/json_data/Chozo Ruins.txt
- randovania/games/prime1/json_data/Magmoor Caverns.json
- randovania/games/prime1/json_data/Magmoor Caverns.txt
- randovania/games/prime1/json_data/Phazon Mines.json
- randovania/games/prime1/json_data/Phazon Mines.txt
- randovania/games/prime1/json_data/Phendrana Drifts.json
- randovania/games/prime1/json_data/Phendrana Drifts.txt
- randovania/games/prime1/json_data/Tallon Overworld.json
- randovania/games/prime1/json_data/Tallon Overworld.txt
52 vids added from the Prime Database Video Tracking Sheet doc (https://docs.google.com/spreadsheets/d/11v0YjiuxwJUB1DmJ9990DlF_uLqaYsPxYh5Bl6IXp7g/edit?usp=sharing)
> Prime1: Bulk Database Video Upload

- requirements.txt
- setup.cfg
Fix a crash in sunchamber (hopefully)
> Randomprime v1.17.1

- randovania/games/am2r/game_data.py
Question not needed anymore, fixed by https://github.com/randovania/YAMS/commit/c1c6eb168c017bc4e662d99476e04f50fb6735dc
> AM2R: remove fixed faq question

- requirements.txt
- setup.cfg
> Randomprime v1.17.2

- CHANGELOG.md
- randovania/games/prime2/json_data/Temple Grounds.json
- randovania/games/prime2/json_data/Temple Grounds.txt
> Echoes: Add Videos to Database

- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Thanks hyperbola for bringing these up
> AM2R: fix some small logic issues

- randovania/games/am2r/exporter/patch_data_factory.py
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
Will eventually be needed for multiworld
> AM2R: add uuid of game to exported json

- randovania/games/super_metroid/gui/dialog/super_cosmetic_patches_dialog.py
- randovania/games/super_metroid/layout/super_metroid_cosmetic_patches.py
- randovania/gui/ui_files/super_cosmetic_patches_dialog.ui
- test/test_files/sdm_expected_result.json
> Super Metroid: Add enable moonwalk by default + redo cosmetic window

- CHANGELOG.md
- randovania/gui/dialog/racetime_browser_dialog.py
- Added: Dread now in list of supported games for racetime search
closes #4960
> Add Dread to Racetime Search

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Tower.json
Makes some stuff easier for MW
> AM2R: Add internal numbers as extra data for areas

- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- Crystal Corridor West
- Fixed: OR corrected to AND
- Laboratory Pipe
- Changed: climb into pipe now uses correct templates
- Waterfall Passage Top
- Added: Morph requirements for pipe
- Waterfall Ravine North West
- Changed: climb now uses correct template
- Elevator Shaft
- Removed: not entrance rando requirement for descent
- Added: requirements for climb
> AM2R: Logic updates for Genetics Lab and GFS Thoth

- randovania/games/am2r/exporter/game_exporter.py
- requirements.txt
- setup.cfg
- test/games/am2r/exporter/test_am2r_game_exporter.py
Attempt number 2!
Tested this on Linux, Jeff has been running 0.0.1 for a bit on Windows, I have absolutely no idea how this behaves on Mac.
> AM2R: Add Patcher

- randovania/gui/ui_files/am2r_game_export_dialog.ui
> AM2R: Clarify where to find 1.5.5

- randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py
- randovania/games/am2r/layout/am2r_configuration.py
- randovania/games/am2r/presets/starter_preset.rdvpreset
- randovania/gui/ui_files/preset_am2r_patches.ui
- test/test_files/log_files/am2r/door_lock.rdvgame
- test/test_files/log_files/am2r/starter_preset.rdvgame
> AM2R: Add option to skip item cutscenes

- CHANGELOG.md
- randovania/layout/lib/teleporters.py
Fixes https://discord.com/channels/914291389293027329/1137871765671006298/1137871765671006298
EDIT: I hope this is the right Node. Pls check!
> Fix mixing AreaIdentifier and NodeIdentifier

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
Needed for transporter rando later down the line
> AM2R: Include extra data for teleporter pipes

- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- test/test_files/log_files/am2r/door_lock.rdvgame
- test/test_files/log_files/am2r/starter_preset.rdvgame
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
Torture room -> Guardian Storage
A3 Storage Cavern -> Sentry Cavern Vault
> AM2R: Change names of torture room + a3 emp reward

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
> AM2R: more extra data for pipes

- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/layout/am2r_configuration.py
Apparently they weren't on a layer before. whoops.
> AM2R: Actually put new pipes on proper layer.

- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- Depths Curved Bubble Pillar
- Added: Morph requirement fpr top pillar -> bomb blocks
- Depths Shinespark Cave
- Removed: Removed combat requirement from shinespark
- Added: WJ to HJ climb for Cave West (Top) -> Hub
- Depths Shinespark Cave East
- Added: Morph requirement for pipe
- ~~Glowfly Maze~~
- ~~Changed: mid-air moph requirement changed to Tunnel Climb template as there is a 2-tile high tunnel~~
- Hideout Hub Access East
- Added: Morph requirement for pipe
- Hideout Omega Nest
-  Changed: rewrote left -> right, no logical change
-  Added: right -> left requirements
> AM2R: Logic updates for the Nest

- randovania/generator/dock_weakness_distributor.py
- randovania/resolver/debug.py
- randovania/resolver/logic.py
- randovania/resolver/resolver.py
- randovania/resolver/resolver_reach.py
Does not fix the issue with `check_if_beatable_after_base_patches`
> Move all actual code from debug to Logic

- randovania/game_connection/connector/corruption_remote_connector.py
- randovania/game_connection/connector/debug_remote_connector.py
- randovania/game_connection/connector/dread_remote_connector.py
- randovania/game_connection/connector/echoes_remote_connector.py
- randovania/game_connection/connector/prime1_remote_connector.py
- randovania/game_connection/connector/prime_remote_connector.py
- randovania/game_connection/connector/remote_connector.py
- randovania/game_connection/game_connection.py
- randovania/game_description/resources/inventory.py
- randovania/game_description/resources/item_resource_info.py
- randovania/game_description/resources/resource_info.py
- randovania/gui/auto_tracker_window.py
- randovania/gui/debug_backend_window.py
- randovania/gui/multiplayer_session_window.py
- randovania/gui/widgets/item_tracker_popup_window.py
- randovania/gui/widgets/item_tracker_widget.py
- randovania/network_common/remote_inventory.py
- randovania/server/multiplayer/world_api.py
- test/game_connection/connector/test_dread_remote_connector.py
- test/game_connection/connector/test_echoes_remote_connector.py
- test/game_connection/connector/test_prime1_remote_connector.py
- test/game_connection/test_game_connection.py
- test/gui/test_multiworld_client.py
- test/gui/widgets/test_item_tracker_popup_window.py
- test/gui/widgets/test_item_tracker_widget.py
- test/network_client/test_network_client.py
- test/server/multiplayer/test_world_api.py
Avoids an error that PySide 6.5 does not like non-string keys for dicts in signals
> Use a proper class for Inventory

- CHANGELOG.md
- randovania.spec
- randovania/data/.gitignore
- randovania/gui/main_window.py
- randovania/gui/ui_files/main_window.ui
- randovania/interface_common/installation_check.py
- test/interface_common/test_installation_check.py
https://github.com/randovania/randovania/assets/884928/aaaa70cc-7ee1-4fb1-9438-33c471e0643a
> Add tool for verifying your installation

- randovania/game_description/data_reader.py
- randovania/game_description/db/dock_lock_node.py
- randovania/game_description/db/node_provider.py
- randovania/game_description/editor.py
- randovania/game_description/resources/node_resource_info.py
- randovania/generator/old_generator_reach.py
- randovania/generator/reach_lib.py
- randovania/resolver/state.py
- test/game_description/db/test_region_list.py
Very scientific benchmark:
Before
```
$ python -m randovania layout generate-from-permalink --permalink Da3N_L4qMzyCzJ0KWIRiEuMOO6C_f_zV --no-validate seed3.rdvgame
Took 23.496 seconds. Hash: ZX6L4KRT
```
After
```
$ python -m randovania layout generate-from-permalink --permalink Da3N_L4qMzyCzJ0KWIRiEuMOO6C_f_zV --no-validate seed3.rdvgame
Took 21.289 seconds. Hash: ZX6L4KRT
```
> Micro optimizations for generation

- CHANGELOG.md
- randovania/generator/old_generator_reach.py
Test permalinks:
DREAD: Da3N_L4qMzyCzJ0KWIRiEuMOO6C_f_zV
ECHOES: DZQlfQMM47o8ilgMOM9towp4jKE0R9owABzg
PRIME: Deo9W6GlEro8ilgMjaHcfjh85lO6Q9O4AAPW
DREAD: 23.653s
ECHOES: 5.216s
PRIME: 4.796s
DREAD: 12.953s (82% faster)
ECHOES: 3.467s (50% faster)
PRIME: 2.021s (137% faster)
> _potential_nodes_from: invert `as_set` and `patch_requirements`

- randovania/games/samus_returns/game_data.py
> MSR: Fix progressives being shown properly

- randovania/games/am2r/exporter/patch_data_factory.py
- randovania/games/am2r/gui/dialog/cosmetic_patches_dialog.py
- randovania/games/am2r/layout/am2r_cosmetic_patches.py
- randovania/gui/ui_files/am2r_cosmetic_patches_dialog.ui
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
> AM2R: Add option for room names on hud

- randovania/games/dread/pickup_database/pickup-database.json
> Dread: Add more original start locations for existing items

- randovania/games/am2r/exporter/game_exporter.py
- randovania/games/prime2/patcher/claris_randomizer.py
- randovania/gui/lib/error_message_box.py
- randovania/gui/lib/game_exporter.py
- randovania/patching/patchers/exceptions.py
- test/games/am2r/exporter/test_am2r_game_exporter.py
- test/games/patchers/test_claris_randomizer.py
Hyperlink isnt shown in blue but eh. You can still select it and copy paste it.
> AM2R: Check if dotnet is in path before trying to export

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Nest.json
- randovania/games/am2r/json_data/The Nest.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
Need this later for a feature to display room names in-game on map
> AM2R: Add minimap data for all relevant rooms

- randovania/games/am2r/game_data.py
- randovania/games/am2r/layout/__init__.py
- randovania/games/am2r/layout/preset_describer.py
- test/games/am2r/layout/test_am2r_describer.py
Looks fine here
But this may need some splitting up:
> AM2R: Add preset describer

- randovania/gui/ui_files/preset_patcher_super_patches.ui
> SM: Expose no_ln_chozo_inventory_check in GUI

- randovania/games/common/prime_family/gui/prime_trilogy_teleporter_details_tab.py
- randovania/games/dread/game_data.py
- randovania/games/dread/gui/__init__.py
- randovania/games/dread/gui/dread_teleporter_details_tab.py
- randovania/games/prime1/game_data.py
- randovania/games/prime2/game_data.py
- randovania/gui/game_details/teleporter_details_tab.py
Also fixed wrong elevators for echoes iff portal rando is selected
Fixes #5097
> Add transporters spoiler tab for dread

- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
199 health means 298.5 for the default 1.5x multiplier
Dividing that by 2 (for one suit) gives you 149.25
> Bump gamma health req + fix omega super

- randovania/games/am2r/exporter/patch_data_factory.py
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
Now that i think of it, this probably should've been in the other PR.
> AM2R: Pass minimap data in patch data factory

- randovania/games/am2r/exporter/game_exporter.py
This can make troubleshooting easier.
> AM2R: Don't redirect stdout/-err for dotnet check

- randovania/gui/multiplayer_session_window.py
> Fixes for update_multiworld_client_status in made states.

- randovania/games/prime1/exporter/game_exporter.py
> Prime 1: Abort if py_randomprime.symbols_for_file is None

- requirements.txt
Dont wanna wait on dedpendabot any longer, should reduce noise in sentry.
> Bump am2r-yams to 0.0.21

- randovania/gui/widgets/select_preset_widget.py
> Properly handle import a preset file that isn't a json

- CHANGELOG.md
- randovania/layout/layout_description.py
> Layout: Extract secret before migrating versions

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/header.json
- randovania/games/am2r/json_data/header.txt
- Added: Defeat Dual Gamma template
- Changed: Dual Gamma's now use `Defeat Dual Gamma` template
> AM2R: Dual Gamma Logic Update

- randovania/cli/commands/batch_distribute.py
- tools/bulk_generate_for_discord.sh
This reverts commit 5a9d56f4420d3fb12106d9c2efcb18858e6fd31b, reversing changes made to f0f627da08b45f98726d060e39cfb8bb6ac7049f.
> Revert "Merge pull request #4950 from randovania/feature/bulk-report"

- randovania/games/super_metroid/json_data/Brinstar.json
- randovania/games/super_metroid/json_data/Brinstar.txt
- randovania/games/super_metroid/json_data/Crateria.json
- randovania/games/super_metroid/json_data/Crateria.txt
- randovania/games/super_metroid/json_data/Wrecked Ship.txt
- randovania/games/super_metroid/json_data/header.json
- randovania/games/super_metroid/json_data/header.txt
Fixes PR #3814 by rebasing it on top of main mostly.
Note, that I am not a regular SM runner, I only have some basic knowledge about the game.
However, things I noticed and will try to do:
- Templates should be rephrased to be more clear. 
- Add disabled entrance rando and disabled door lock rando and limit some tricks by them
- Potentially more.
Will mark as draft until i fix those at least.
Obsoletes #3814
> Super Metroid: Fix up PR #3814

- randovania/games/am2r/pickup_database/item_data.json
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
> AM2R: Fix locked PB clipping in 4:3

- CHANGELOG.md
- randovania/games/prime2/patcher/csharp_subprocess.py
- test/games/patchers/test_csharp_subprocess.py
> Add common Mono Mac paths for echoes exporting

- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- test/test_files/patcher_data/am2r/door_lock.json
- test/test_files/patcher_data/am2r/starter_preset.json
> AM2R: Fix crystal corridors east/west mixup

- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- Mines Alpha Nest Access
- Added: Shinespark method
- Mines Gamma Nest Access
- Added: Shinespark method
- Mines Intersection
- Added: Shinespark up tunnel
- Mines O-Shape Shaft
- Added: Shinespark to climb with Septogg
- Surface Gunzoo Room
- Removed: Requirements for shinespark to Spider Ball Challenge
- Changed: Template for entering tunnel to Spider Ball Challenge
- Surface Spider Challenge
- Changed: Template used for escape to Surface Gunzoo Room
- Changed: Bumped difficulty to Advanced for Shinespark from other room
- The Pit
- Added: Shinespark to climb methods
- Western Cave Entrance
- Added: Morph requirement for Missile Tank
- Changed: Bumped WJ and Mid-air Morph to Intermediate to Missile Tank
> AM2R: Main Caves Logic

- CHANGELOG.md
- randovania/games/prime1/gui/preset_settings/prime_patches_qol.py
- randovania/games/prime1/layout/preset_describer.py
- randovania/games/prime1/presets/starter_preset.rdvpreset
- randovania/gui/ui_files/preset_prime_qol.ui
- randovania/layout/preset_migration.py
- requirements.txt
- setup.cfg
- test/games/prime1/layout/test_preset_describer.py
- test/test_files/randomprime_expected_data.json
- test/test_files/randomprime_expected_data_crazy.json
> Randomprime 1.18.1 + Cutscene Migration

- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
Added 3-tile docks and corrected a missing 4-tile dock between pincherfly parlor and EMP sentry cavern
> AM2R: A3 horizontal docks update

- randovania/games/am2r/presets/starter_preset.rdvpreset
> AM2R: Update starter preset description

- randovania/games/am2r/json_data/Distribution Center.json
- randovania/games/am2r/json_data/Distribution Center.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
- randovania/games/am2r/json_data/Golden Temple.json
- randovania/games/am2r/json_data/Golden Temple.txt
- randovania/games/am2r/json_data/Hydro Station.json
- randovania/games/am2r/json_data/Hydro Station.txt
- randovania/games/am2r/json_data/Industrial Complex.json
- randovania/games/am2r/json_data/Industrial Complex.txt
- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
- randovania/games/am2r/json_data/The Depths.json
- randovania/games/am2r/json_data/The Depths.txt
- randovania/games/am2r/json_data/The Tower.json
- randovania/games/am2r/json_data/The Tower.txt
Boy do I love unreviewable PRs
> AM2R: Add extra data to area transitions

- randovania/games/am2r/json_data/GFS Thoth.json
- randovania/games/am2r/json_data/GFS Thoth.txt
- randovania/games/am2r/json_data/Genetics Laboratory.json
- randovania/games/am2r/json_data/Genetics Laboratory.txt
Combined A7 & A8 as Thoth only has one applicable dock.
> AM2R: A7 and A8 horizontal docks update

- randovania/games/am2r/json_data/Main Caves.json
- randovania/games/am2r/json_data/Main Caves.txt
> AM2R: Fix logic bug going from a5 -> tower

- CHANGELOG.md
- randovania/games/dread/json_data/Artaria.json
- randovania/games/dread/json_data/Artaria.txt
- randovania/games/dread/json_data/Cataris.json
- randovania/games/dread/json_data/Cataris.txt
- randovania/games/dread/json_data/Ghavoran.json
- randovania/games/dread/json_data/Ghavoran.txt
> Videos added to Dread logic database.

- CHANGELOG.md
- randovania/gui/ui_files/main_window.ui
> Restore menu button for opening the Dependencies widget

- CHANGELOG.md
- pytest.ini
- randovania/games/prime2/patcher/csharp_subprocess.py
- test/games/patchers/test_csharp_subprocess.py
> detect mono not found
