randovania/randovania

CHANGELOG.md, randovania/games/prime/patcher_file.py, randovania/games/prime/patcher_file_lib/hint_name_creator.py, randovania/games/prime/patcher_file_lib/item_hints.py, randovania/games/prime/patcher_file_lib/sky_temple_key_hint.py, test/games/prime/test_patcher_file.py, test/games/prime/test_sky_temple_key_hint.py
Implements #46 
Not implemented: GUI to disable and control how precise.
Extra future features:
- Randomly include "joke hints".
- Multiple hints for certain things.
- Including hints for only a portion of the items
- Option for how precise
- Option to disable
- Use Luminoth Warrior's body scan for what is included in the matching Ing Cache.
- Include Pirate Lore scans in the pool, but make then more likely for joke hints.
- Different tiers of precise hints: "Screw Attack"/"movement system"/"major item".
=> Lore hints for items

randovania/gui/data_editor.py
a7282de3a45fd1b6795176365ece662b7d2f55f2 made the data editor create instances of `Node` instead of `GenericNode`, which broke the data writer. This undoes that commit's changes to `data_editor.py`.
=> Use GenericNode in data editor code

randovania/data/json_data/prime2.json
This fixes Trivial showing up as an option for roll jumps and underwater dashes in the trick difficulty sliders.
=> Correct some roll jump and underwater dash requirements

randovania/generator/filler/retcon.py
This allows generation to be retried.
=> Use UnableToGenerate exception when too many starting items are placed

CHANGELOG.md, randovania/data/item_database/configuration/major-items.json, randovania/game_description/item/item_category.py, randovania/games/prime/patcher_file_lib/item_hints.py, test/games/prime/patcher_file_lib/test_item_hints.py
Changes made:
- "Major item" → "Major upgrade" (to hopefully this prevents confusion when using major/minor randomization)
- "Temple Key" → "red Temple Key" (to clarify that Sky Temple Keys are excluded)
- "beam combo" → "Charge Combo" (to match what they're called in-game)
- "key" → "Dark Temple Key" (to match what they're called in-game)
=> Improved item category names

CHANGELOG.md, randovania/games/prime/patcher_file_lib/sky_temple_key_hint.py, requirements.txt, setup.py, test/games/prime/patcher_file_lib/test_sky_temple_key_hint.py
Cardinals are used everywhere else, so this makes the STK names 100% consistent.
In addition, the `num2words` dependency is no longer needed.
=> Use cardinal numbers in STK hints

CHANGELOG.md, randovania/data/json_data/prime2.json
Fixes #315. The affected rooms are:
- War Ritual Grounds
- GFMC Compound
- Sacred Path
- Warrior's Walk
- Security Station B
- Polluted Mire
- Fortress Transport Access (Torvus)
- Temple Transport Access (Sanctuary)
- Sanctuary Entrance
- Transit Station (Sanctuary)
=> Add missing default node indices

CHANGELOG.md, randovania/data/item_database/configuration/major-items.json, randovania/game_description/area.py, randovania/game_description/world.py, randovania/generator/filler/retcon.py
Here are my goals for these:
1. Make seeds shorter
2. Increase the number of seeds with unusual item orders/placements
3. Spread items out between the worlds more evenly
For goal 2, the thing I'd like most is for Power Bombs to not appear as early as they almost always do, even in Missile Launcher-first seeds, since they trivialize a lot of early game routing and bosses. Maybe they should get a negative probability offset? Or perhaps `_calculate_weight_for` could look like this:
```python
def _calculate_weights_for(potential_reach: GeneratorReach,
current_uncollected: UncollectedState,
name: str
) -> float:
potential_uncollected = UncollectedState.from_reach(potential_reach) - current_uncollected
return sum((
_RESOURCES_WEIGHT_MULTIPLIER * int(bool(potential_uncollected.resources)), …
```
=> Generator tweaks

randovania/data/json_data/prime2.json
Changes:
- Added missing Scan Visor requirements
- Added additional Space Jump/Screw Attack requirements (No Tricks; most for skipping Scan Visor requirements between E-Tank/Storage C/Ventilation Area B.
- Added method of reaching Storage C from Security Station A with Space Jump and Screw Attack (easy difficulty). The general method can be seen at https://www.youtube.com/watch?v=Ki7qox6t9lA . But, since it goes to Storage C instead, there's no obstacles in the way and Scan Visor isn't required, 
- Added roll jump method of reaching Storage C (Normal difficulty).
- Added method of reaching Ventilation Area B using Screw Attack without Space Jump (Normal difficulty).
=> Fix Bioenergy Production connections, add new connections

randovania/data/json_data/prime2.json
Adds missing morph ball requirements to crossing Sandcanyon. Also adds the "boost boost" trick to get the Sandcanyon item without Screw Attack.
=> Rework Sandcanyon requirements

CHANGELOG.md, randovania/data/json_data/prime2.txt
Logic changes for:
- Torvus Grove climb without Boost Ball
- Seeker Locks with Screw Attack
- Bombless Bomb Slots (some haven't been added yet)
- Lower Torvus Escape without Gravity Boost
- Transport Center Climb with Space Jump + simplifying nodes (Closes https://github.com/randovania/randovania/issues/804) (Contributes to https://github.com/randovania/randovania/issues/103)
- Doomed Entry climb with Space Jump and Screw Attack + simplifying nodes (Closes https://github.com/randovania/randovania/issues/796) (Contributes to https://github.com/randovania/randovania/issues/103)
- Quadraxis with PBs
- Hive Temple escape without Spider Ball (New nodes and updated damage requirements accordingly) (Contributes to https://github.com/randovania/randovania/issues/333) (Contributes to …
=> Many Logic Changes

randovania/gui/game_session_window.py, randovania/network_client/game_session.py, randovania/server/database.py, randovania/server/game_session.py, test/gui/test_game_session_window.py, test/server/test_game_session.py
GameSessionMembership: Remove is_observer field and make row nullable. Add UNIQUE(session_id, row) constraint.
GameSessionPreset: Add primary key using (session_id, row)
Fixes #1078.
=> Database improvements for consistency

CHANGELOG.md, randovania/gui/dialog/logic_settings_window.py, randovania/gui/dialog/trick_details_popup.py, randovania/gui/main_window.py, randovania/gui/ui_files/main_window.ui, randovania/gui/ui_files/trick_details_popup.ui, test/gui/dialog/test_trick_details_popup.py
Also removes all flows to TrickDetailsPopup without a trick, since it's no longer needed.
Implements part of #381.
=> Add trick description to TrickDetailsPopup.

CHANGELOG.md, randovania/data/json_data/prime2.txt
- Fixed logic bugs in Phazon Pit, Central Mining Station, and Sand Processing
- New requirements added
- Room adjustments/Simplification
- Slope Jumps and Bomb Space Jumps are slightly more balanced (Beginner has some of both)
- Balanced/Updated some tricks in a few places
- Added wiki link to Boost Jump trick
- Contributes to #860
=> Trick Balancing: Slope Jumps and Bomb Space Jumps

randovania/data/json_data/prime1.json, randovania/data/json_data/prime1.txt
For Metroid Prime 1's Internal Database:
-Added a basic set of tricks
-Added damage types with appropriate suit resistances
-Added Phendrana Drifts logic
-Added Magmoor Caverns logic
-Added Frigate Orpheon logic
-Added Phazon Mines logic
-Added the ability for Flaahgra to be defeated with 4 powerbombs as a beginner trick
-Added the ability for Flaahgra to be defeated with wavebuster & 230 missiles as a hypermode trick
NOTE: I've done some basic vetting (Checking all the doors, pickups, save stations, elevators, making sure every node leads to at least one other node) but this logic is still basically untested; treat this as highly experimental.
NOTE: Trick integration is very minimal, and only includes some trivial difficulty tricks in logic for portions which I worked on.
Also I'm bad at …
=> Completed Basic Metroid Prime 1 Randomizer Logic

CHANGELOG.md, randovania/gui/dialog/logic_settings_window.py, randovania/layout/starting_location.py, test/gui/dialog/test_logic_settings_window.py
On starting locations tab, replaced the world group titles with tristate checkboxes. Clicking this checkbox will select or unselect all areas in that world. Selecting only some of the areas in that world will set the world checkbox to partially selected.
=> Feature: Starting area quick fill by world checkbox

CHANGELOG.md, randovania/gui/game_session_window.py
Implements #959.  
Auto-scrolls to bottom of session history until user scrolls up. Auto-scrolling will resume once user has scrolled back to bottom.
=> Multiworld: Autoscroll game session history

randovania/data/json_data/prime3.json, randovania/data/json_data/prime3.txt
Generator avoids actions which softlock you, so the "Energy Cell Room" and the Power Outage having "Before" was an issue.
Now the flow goes Central Hallways -> Power Outage -> Energy Cell -> Seeker -> Central Hallways.
These nodes being accessible again afterwards isn't a big issue.
=> Simplify Xenoresearch B

randovania/data/json_data/prime2.txt
- Removed Intermediate path for reaching item from Security Station B door without Screw Attack since it was broken and impossible.
- Renamed "Before Pickup" to "Next to Pickup" for more clarity
=> Main Reactor Logic Bug Fix

.gitignore, randovania/data/ClarisEchoesMenu/EchoesMenu.exe.config, randovania/data/ClarisPrimeRandomizer/Randomizer.exe.config, randovania/games/prime/claris_randomizer.py
This PR contains two minor commits to fix a couple issues with Linux support, mostly on Ubuntu Focal but also for any Debian derivatives and distros that ship Python 3.8, and fixes #1248 . Namely:
* `e368f47` - On Debian derivatives, `liblzo2.so.2` is not actually mapped to `lzo2.dll` in the system-wide Mono configs by default, and since `/usr/lib/x86_64-linux-gnu` isn't in Mono's library search path, it was wholly unable to find the library. This caused the randomizer and the menu mod patcher to die on startup. By adding .config files for those two applications, we add those library mappings ourselves, fixing the issue. This will require that the user have `liblzo2-2` installed system-wide, but this is a common dependency of most desktop environments and should not be a serious issue.
* …
=> Update Linux Support for Focal (fixes #1248)

randovania/gui/lib/preset_describer.py, randovania/layout/preset_migration.py, randovania/layout/prime_configuration.py
Adds dangerous tank to PrimeConfiguration. Fixes a bug that prevents user from editing Prime 1 presets.
=> Add dangerous tank to PrimeConfiguration

randovania/gui/main_window.py, test/gui/test_main_window.py
Clicking on "Previous Game History" in "Open" menu opens the folder in Finder on macOS or the default file manager for Linux based systems. Falls back to showing the textbox with the path if this fails.
=> Open folder for previous game history on non-Windows plaforms

randovania/data/json_data/prime3.json, randovania/data/json_data/prime3.txt, randovania/game_description/world_list.py, randovania/resolver/event_pickup.py
Fixes #1485
There was a path from Door -> Event -> Pickup, not caring about Command Visor/Ship Node.
Leaving only the path Ship Node -> Pickup means that only if "the ship is there" will the pickup node be reachable.
These areas also break in-game if they're the starting location, and logic gets stuck because it can't leave a ship node that's not unlocked anyway.
=> Fix Corruption landing sites with ship upgrades

CHANGELOG.md, randovania/data/json_data/prime2.txt
Ensures that logic paths that use NSJ Screw Attacks are ignored if Space Jump is on the logical path prior to it.
Example: Having Space Jump but attempting to leave Sanctuary Temple Access in reverse, which can be done on Beginner Z-Axis, but impossible with Space Jump. Logic assumes it is possible to cross regardless.
=> Potential NSJ SA Fix

CHANGELOG.md, randovania/layout/game_patches_serializer.py, randovania/layout/layout_description.py
=> Multiworld spoiler logs now use 1-indexed player names for locations.

randovania/gui/dialog/game_input_dialog.py, randovania/gui/game_session_window.py, randovania/gui/seed_details_window.py, test/gui/dialog/test_game_input_dialog.py
Show the correct game name in the description label above the input file entry.
Don't show the text about randovania saving a copy of the game if the patcher uses input file directly.  
Minor grammar fix changing "a ISO" to "an ISO"
=> Show correct game name in description label of GameInputDialog

randovania/data/json_data/prime1.json, randovania/data/json_data/prime1.txt
- fixed ruined shrine, missed a morph ball requirement
- OP isn't finished yet, but made it so that players using tricks are not required to have all beams for omega pirate
=> ruined shrine fix and op modification

randovania/data/json_data/prime1.json, randovania/data/json_data/prime1.txt
Require that you can actually reach the item after using the spinner.
This seed is impossible because of the lack of this check: [Prime Randomizer - Radion Transport Warrior.txt](https://github.com/randovania/randovania/files/6606945/Prime.Randomizer.-.Radion.Transport.Warrior.txt)
I wasn't really sure where to put the bomb jump difficulty. I put it at advanced since it needs to be laddered, but it's not very hard
=> Life Grove Fix

randovania/data/json_data/prime1.json, randovania/data/json_data/prime1.txt
Currently, the database has no way of getting to Great Tree Hall from HAT. This was causing "Validate Prime Vanilla" to fail. This adds a path from Connection Elevator to Deck Beta to Great Tree Hall and lets the prime 1 vanilla validation pass
=> Allow moving through Hydro Access Tunnel from left to right

randovania/data/json_data/prime1.json, randovania/data/json_data/prime1.txt
Randomprime pre-activates these elevators if scan visor is shuffled.
=> Remove scan visor requirement from major elevators

randovania/games/patchers/claris_patcher.py, randovania/games/patchers/randomprime_patcher.py, randovania/gui/dialog/game_input_dialog.py, randovania/gui/ui_files/game_input_dialog.ui, randovania/interface_common/options.py, randovania/interface_common/persisted_options.py, test/gui/dialog/test_game_input_dialog.py, test/interface_common/test_options.py
Since dol patching is handled by randomprime now, randovania should be able to save .ciso and .gcz for prime 1 now with no issue.  
If a patcher has multiple output formats supported, a set of radio buttons will appear to let the user select which format they want.  
Output format preference is saved per-game via the Options class. As a note, I had to bump the options file version to 15.
=> Support multiple output formats for supported patchers

CHANGELOG.md, randovania/gui/dialog/racetime_browser_dialog.py, randovania/gui/ui_files/racetime_browser_dialog.ui
Implements #2046  
Adds support for Prime 1 in the racetime.gg browser. A checkbox filter for each supported game allows users to filter out unwanted games.
This also fixes #1434 and updates _TEST_RESPONSE to include this edge case.
=> Prime 1 racetime.gg integration

CHANGELOG.md, randovania/games/prime/patcher_file_lib/hints.py
adds "The Scan Visor is useful for gathering information." to joke hints
wouldn't normally be my kinda thing, but I figure this poor issue has been open for multiple years and deserves closure :P
=> fixes #473 - adds a joke hint requested in an issue from 2019

CHANGELOG.md, randovania/data/json_data/prime1/Phendrana Drifts.json, randovania/data/json_data/prime1/Phendrana Drifts.txt
If I'm understanding this right, this is preventing tourney seeds from logical access to ice ruins west from shorelines. This is a bug from the PR from 1 week ago.
=> fixed trivial logic walking in upper phendrana shorelines

CHANGELOG.md, randovania/games/patchers/claris_patcher.py, randovania/games/patchers/claris_patcher_file.py, randovania/games/patchers/gamecube/banner_patcher.py
echoes uses a different game ID (GM2E1R) when saving ISOs with menu mod enabled, so that different save file formats aren't shared
=> fixes #392 - use different game ID with menu mod

CHANGELOG.md, randovania/data/json_data/prime1/Chozo Ruins.json, randovania/data/json_data/prime1/Chozo Ruins.txt, randovania/data/json_data/prime1/Magmoor Caverns.json, randovania/data/json_data/prime1/Magmoor Caverns.txt, randovania/data/json_data/prime1/Tallon Overworld.json, randovania/data/json_data/prime1/Tallon Overworld.txt
- Changed: Picking up Sunchamber Ghosts item NSJ is now L-Jump (Beginner) instead of Intermediate.   
- Changed: Crossing TFT to TF with Gravity+SJ now requires Movement (Beginner)
- Changed: FCS Item Scan Dash method is now Intermediate without SJ.
- Added: FCS Grapple strat - Movement (Beginner)
- Missing Patcher Changelog Entries
=> Database - Difficulty Adjustments

CHANGELOG.md, randovania/data/json_data/prime2/Temple Grounds.json, randovania/data/json_data/prime2/Temple Grounds.txt
Walk up to this spot on the halfpipe, screw attack across, then screw attack across to the top. Very easy, and quite lenient with the positioning
=> adds additional method of climbing meeting grounds to db

CHANGELOG.md, randovania/data/json_data/prime1/Impact Crater.json, randovania/data/json_data/prime1/Impact Crater.txt, randovania/data/json_data/prime1/Magmoor Caverns.json, randovania/data/json_data/prime1/Magmoor Caverns.txt, randovania/data/json_data/prime1/Phazon Mines.json, randovania/data/json_data/prime1/Phazon Mines.txt
Changes:
* Adds a Movement (Beginner) trick to Fiery Shores and Transport Tunnel B for forced lava damage
* Adds a Movement (Beginner) trick to Crater Tunnel B for forced red Phazon damage
Fixes:
* Fixes the Movement (Beginner) trick in Phazon Mining Tunnel to be with Morph Ball Bomb instead of Boost Ball and adds Phazon requirements for moving without Boost Ball
* Adds Phazon requirements to Processing Center Access and Phazon Processing Center from that door
=> Adding tricks for forced damage

.github/workflows/tests.yml, tools/create_release.py
pyintaller calls lipo/codesign on macOS and frequently timeout in github actions
=> Hack a longer timeout in PyInstaller

randovania/games/prime1/patcher/prime1_elevators.py, randovania/gui/preset_settings/elevators_tab.py
Renamed Ext. Docking Hangar and untick Frigate/Essence teleporters when boxes are grayed out
=> Prime - Elevators Tab Fixes

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt
Water blob logic was broken (had wrong event in checks), and early cloak blob was overly confusing.
=> Fix & simplify blob events logic in Early Cloak room

CHANGELOG.md, randovania/games/prime1/json_data/Chozo Ruins.json, randovania/games/prime1/json_data/Chozo Ruins.txt
Amending the Sun Tower database entry to enforce Medium Knowledge with or without spider ball, and adding comments to explain/video link the trick (especially important since the trick falls outside Knowledge's current explanation).
=> Sun Tower Early Wild logic update

CHANGELOG.md
- Prime 1 no longer checks for Plasma Beam
- Prime 2 no longer checks for Light Suit or Agon Keys
=> Minimal Logic Changelog Update (No new changes)

randovania/server/discord/database_command.py, test/server/discord/test_database_command.py
Use one embed per node (max of 4096 characters), limit to 10 nodes selected (maximum embeds in a message). When over
the size limit, instead of skipping replace message with a "skipped" text.
Fixes #2621.
=> Bot: Improve handling of message limit

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/header.json
I've deleted a bunch of unused Start Point nodes, added a few missing connections and changed some missile/super doors to be matching on both sides.
There's a special case in the blast shield logic that if both sides of a door are the same shield, then it handles opening from the back. Pretty much a kludge until I can get the correct way working, though I think I'll just patch the game to be that way.
=> Fix Dread db to be strongly connected

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Elun.json, randovania/games/dread/json_data/Elun.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
Rename pickups to be more readable.
Logically allow charge beam doors to be opened by PBs.
Minor logic fixes.
=> Minor logic fixes and renaming after darkszero's fun test stream

randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt
Heat damage change is somewhat arbitrary, but the missing connections are fixes.
=> Dread: Fix missing connections in transport area

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/header.json
- Added Event - Unlock David Jaffe Room to Navigation Station North so that going through is not a dangerous action
- Start Point in David Jaffe Room requires the event to go to Door to Navigation Station North
=> Added Event to Unlock David Jaffe Room

randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
- Added "Dock to Golzuna Arena" in "Above Golzuna" for the SSC
- Added "Dock from Above Golzuna" in "Golzuna Arena" for the SSC
- Removed "Tile (WEIGHT)" connection to "Door to Cross Bomb Tutorial"
=> Ensure Hanubia is reachable only by Golzuna or SSC

randovania/patching/prime/asset_conversion.py
When converting assets to Prime 1, use the echoes missile expansion model instead of the launcher. The echoes launcher model causes the Prime to crash.
=> Use echoes missile expansion for unlimited missiles

randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt
- Removes the node for Tile Group (SPEEDBOOST) as it is unnecessary
- Adds Gravity Suit to the ballspark requirement to get the PB Tank
=> Correct logic for the PB Tank in Grav Suit Room

randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt
- Changes the event in the connection of "Breakable Floor" to "Door to Navigation Station South" from destroying the third blob to pulling the grapple block
=> Dread: Fix Gravity Suit Tower logic bug

randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
- Added the event for destroying the enky to the ballspark requirement to get the missile tank and through the tunnel in Golzuna Tower
- Added expert movement trick for getting through the tunnel with just both bomb types
- Adjusted some logic for reaching the missile tank from the other side
- Added the event for destroying the enky to the speed booster requirement to reach Teleport to Burenia in Energy Recharge Station
=> Adjust logic involving the Pulse Radar Enky

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt
- Removed Spider Magnet going from left to right
- Added other methods to get to the item from "Door to Hot Room Hub"
- Added Spider Magnet to reach the item from "Door to Transport to Cataris"
=> Dread: Fix logic for Hot Cataris Shortcut

randovania/exporter/hints/credits_spoiler.py, randovania/exporter/hints/guaranteed_item_hint.py, randovania/exporter/hints/hint_exporter.py, randovania/exporter/hints/hint_formatters.py, randovania/game_description/game_description.py, randovania/game_description/game_patches.py, randovania/game_description/integrity_check.py, randovania/generator/base_patches_factory.py, randovania/generator/old_generator_reach.py, randovania/layout/base/base_configuration.py, randovania/layout/game_patches_serializer.py, test/conftest.py, test/game_description/test_integrity_check.py, test/games/prime/patcher_file_lib/test_item_hints.py, test/games/prime/patcher_file_lib/test_sky_temple_key_hint.py, test/games/prime2/patcher/test_patch_data_generator.py, test/generator/filler/test_pickup_list.py, test/generator/filler/test_player_state.py, test/generator/filler/test_runner.py, test/generator/item_pool/test_pool_creator.py, test/generator/test_base_patches_factory.py, test/generator/test_generator.py, test/generator/test_generator_reach.py, test/gui/test_game_details_window.py, test/gui/test_tracker_window.py, test/interface_common/test_preset_editor.py, test/layout/test_echoes_configuration.py, test/layout/test_game_patches_serializer.py, test/layout/test_preset_describer.py, test/resolver/test_bootstrap.py
This is in preparation to prefer getting the GameDescription from a BaseConfiguration, instead of RandovaniaGame.
It also comes with plenty of refactoring for how GamePatches are created in tests.
=> Change GamePatches to hold a BaseConfiguration

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
Changes necessary Access Closed docks to Access Locked so that logic can properly account for them. Changes doors in every area except Elun, Hanubia, and Itorash.
Fixes Issue #2837 List of Access Closed Docks
=> Dread: Properly account for Access Closed doors

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
- Added extra methods of climbing to the Ammo Recharge station from "Above Breakable"
- Added templates for "Perform Water Bomb Jump" and "Perform Water Cross Jump"
=> Dread: redo logic for Artaria - First Tutorial

randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/header.json
The grapple blocks in Ghavoran were sharing events in pairs, causing some seeds to be incompletable due to triggering the other one in the pair first.
- Adds two new events: Burenia Transport Grapple Box and Ferenia Transport Grapple Box
- The former is in Right Entrance and the latter is in Total Recharge Station North, with both a front and a back to allow for pseudoing it
- Spin Boost Tower and Dairon Transport Access are unchanged
=> Dread: Fix grapple events for Ghavoran

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt
Changes a few things and adds a Speed option to going from EMMI Zone Entrance Hallway to Early Cloak Room. Unchanged for the most part.
=> Dread: Redo logic for Melee Tutorial Room

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt
- Changes up some logic for Artaria - Proto EMMI Introduction, including the Ice Missile method for reaching the item
- Adds a comment to "East of Blob" > "Pickup (Missile) 2" in Melee Tutorial Room explaining why the pickup is required
- Adds speed option to go from "Door to Charge Tutorial" > "Door to Navigation Station South" in Melee Tutorial West
=> Dread: Redo logic for Proto EMMI Introduction

randovania/games/dread/layout/preset_describer.py
As I mentioned [here](https://discord.com/channels/914291389293027329/914294231877713940/972019943375781898), Dread doesn't display that `hanubia_easier_path_to_itorash` is enabled in the preset description. I opted to just fix the bug myself.
=> add preset describer config for hanubia_easier_path_to_itorash in dread

randovania/games/dread/json_data/Elun.json, randovania/games/dread/json_data/Elun.txt, randovania/games/dread/json_data/header.json
- Removes the Speed Booster Tile Group node in Fan Room
- Reimplements logic around it
=> Dread: Remove Speed Block in Elun

randovania/gui/lib/qt_network_client.py, randovania/gui/lib/wait_dialog.py, randovania/gui/main_online_interaction.py, randovania/gui/online_game_list_window.py, randovania/network_common/__init__.py, randovania/network_common/error.py, randovania/server/app.py, randovania/server/client_check.py, randovania/server/game_session.py, randovania/server/server_app.py, test/gui/test_main_online_interaction.py, test/server/test_app.py, test/server/test_client_check.py, test/server/test_server_app.py
This allows the use of old dev builds.
=> Only check client headers when using online features.

CHANGELOG.md, randovania/game_description/data_reader.py, randovania/game_description/game_migration.py, randovania/game_description/world/dock_lock_node.py, randovania/game_description/world/dock_node.py, randovania/game_description/world/node_identifier.py, randovania/game_description/world/world_list.py, randovania/generator/old_generator_reach.py, randovania/lib/migration_lib.py, randovania/resolver/event_pickup.py, randovania/resolver/resolver.py, randovania/resolver/resolver_reach.py, test/resolver/test_resolver_reach.py
If you're curious, the biggest gains were from:
* `randovania/resolver/resolver_reach.py`
* `randovania/generator/old_generator_reach.py`
Using indices of a list as keys instead of dicts is fast.
=> Optimize generation + validation combined by 48%

randovania/game_description/data_reader.py, randovania/game_description/game_description.py, randovania/game_description/world/dock.py, randovania/game_description/world/dock_node.py, randovania/game_description/world/node_provider.py, randovania/game_description/world/world_list.py, test/game_description/world/test_world_list.py
Closes #3298.
For `DaTmoSINQL63aukNRpBXJajbBiAka4MQVCsh` (seed hash `42QSEDKA`), the times are:
Old: 128.270 seconds
New: 94.390 seconds
Speedup: 35,89%
=> Improve patch requirements and optimize it

CHANGELOG.md, randovania/games/prime1/json_data/Magmoor Caverns.json, randovania/games/prime1/json_data/Magmoor Caverns.txt, randovania/games/prime1/json_data/Phazon Mines.json, randovania/games/prime1/json_data/Phazon Mines.txt, randovania/games/prime1/json_data/Phendrana Drifts.json, randovania/games/prime1/json_data/Phendrana Drifts.txt, randovania/games/prime1/json_data/header.json, randovania/games/prime1/json_data/header.txt
This logic is very useful for door rando seeds in particular, where you may find yourself in rooms with enemies without the means to properly defend yourself.
- Added: Advancing through rooms containing Trooper Pirates now requires either the proper beam(s), basic defensive capabilities (varies slightly by room), or Combat (Intermediate), except where noted. Rooms affected:
- Elite Control
- Elite Research
- Ore Processing - Climbing the room vanilla now requires Power Beam. Ore Processing climb without Power Beam now requires Combat (Advanced).
- Central Dynamo
- Omega Research
- Mine Security Station
- Metroid Quarantine B - The Standable Terrain method of traversing the room now requires Combat (Advanced) without Plasma Beam.
- Phazon Processing Center - This room is only affected …
=> Added logic for traversing rooms with Trooper Pirates and Scatter Bombus

randovania/games/prime1/json_data/Phazon Mines.json, randovania/games/prime1/json_data/Phazon Mines.txt
Hopefully will fix some issues the resolver seemed to be running into with Door Rando. Even if these numbers weren't the cause, I forgot to account for damage strictness multipliers when I initially wrote the numbers, so these needed to be changed anyway.
=> Lowered Trooper Pirate damage requirements.

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
Revised the logic for rooms in east Artaria:
- Added event in Thermal Device for opening the door to the item without Morph Ball
- Accounted for the Charge doors along the way when using Speed Booster as an option in the area
- Added Damage Boost trick to the Morph Ball method of taking Lower Path to Cataris
- Added Speed Booster method of reaching the upper parts of Energy Recharge Station South
- Added Wave Beam option for the Charge Beam Access blob
- Added Bomb option for destroying exposed blobs in these rooms
- Other various methods of reaching nodes
=> Dread: East Artaria Revision

randovania/patching/patchers/gamecube/iso_packager.py, requirements.txt, setup.cfg, test/games/patchers/gamecube/test_iso_packager.py
This simplifies the code for using nod, as well as improve GUI responsiveness when exporting Prime 1 and when converting assets.
=> Expect a released GIL from native packages

randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
- Added some speedbooster methods for climbing to various points in the room
- Added a speedbooster method of getting the power bomb tank
- Properly accounted for the ability to get the energy part item at the grapple block
- Removed the "Energy Part Platform" node as I thought it was pretty redundant
- Added advanced HBJ for Left Entrance item
=> Dread: Revise logic for Spin Boost Tower

randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
- A few more changes to Spin Boost Tower
- Total Recharge Station North removed the crumble block nodes as they are redundant
- Made it impossible to reach the Screw Attack nodes in the above room and Teleport to Burenia if coming from above since you cannot use Screw Attack while in morph ball
- Added a connection to the Screw Attack node in Total Recharge Station North as there was not one previously
- Added various tricks to connections in Energy Recharge Station
- Added Flash Shift and Spin Boost methods for crossing the crumble blocks in Cross Bomb Tutorial and Teleport to Burenia
- Changed Ballspark to go from Orange to Golzuna Tower proper to beginner movement
- Changed Movement to Stand on Frozen Enemy now that this trick exists for climbing Golzuna Tower with Ice Missiles
- …
=> Dread: Finalize Ghavoran logic revision

randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
Reverts the changes I made to Pulse Radar Room and adds the Power Switch 2 event to access the western doors in Dairon's Freezer.
=> Dread: Fix Pulse Radar and Dairon Freezer

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/header.json
This adds various method of getting around the rooms on the right half of the Artaria EMMI Zone. This includes:
- EMMI Zone Entrance Hallway
- EMMI Zone First Entrance
- White EMMI Introduction
- EMMI Zone Spinner
- White EMMI Arena
- Central Unit Access
- Central Unit
- EMMI Zone Ballspark Hallway
- Teleport to Dairon
- EMMI Zone First Chase End
- EMMI Zone Exit North
fixes #3548
=> Dread: Revise logic for the right half of Artaria EMMI Zone

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/header.json
This adds the misc resource for door lock randomizer, and adds it being disabled as a requirement for all multi-room speedboosts that use doors and in rooms that have already been revised.
=> Dread: Add Misc. Resource for Door Lock Rando

CHANGELOG.md, randovania/games/dread/item_database/item-database.json, randovania/gui/preset_settings/item_configuration_widget.py, randovania/gui/preset_settings/item_pool_tab.py, randovania/gui/preset_settings/progressive_item_widget.py, randovania/gui/ui_files/item_configuration_popup.ui, randovania/layout/base/major_item_state.py
- Only create warning label for items that has it
- Handle warning label for items that must be starting
- Use custom shuffled count for simplified cases for progressive items
- Fix excluding all pickups of a progressive/non-progressive set
- Remove mention of multi-pickup for expansions
=> Improve Item Pool tab

randovania/exporter/item_names.py, randovania/game_description/game_patches.py, randovania/games/blank/generator/pool_creator.py, randovania/games/cave_story/generator/pool_creator.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/generator/pool_creator.py, randovania/games/game.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/generator/item_pool/pool_creator.py, randovania/games/prime2/exporter/patch_data_factory.py, randovania/games/prime2/generator/item_pool/pool_creator.py, randovania/games/prime2/generator/item_pool/sky_temple_keys.py, randovania/games/prime3/generator/item_pool/pool_creator.py, randovania/games/super_metroid/generator/item_pool/pool_creator.py, randovania/generator/filler/filler_logging.py, randovania/generator/filler/player_state.py, randovania/generator/filler/retcon.py, randovania/generator/generator.py, randovania/generator/item_pool/__init__.py, randovania/generator/item_pool/pool_creator.py, randovania/gui/game_details/pickup_details_tab.py, randovania/layout/game_patches_serializer.py, test/games/dread/generator/test_dread_pool_creator.py, test/games/prime/patcher_file_lib/test_pickup_exporter.py, test/games/prime/patcher_file_lib/test_sky_temple_key_hint.py, test/games/prime2/patcher/test_patch_data_generator.py, test/generator/item_pool/test_pool_creator.py, test/generator/test_generator_reach.py, test/layout/test_game_patches_serializer.py, test/resolver/item_pool/test_sky_temple_key.py
In addition, GamePatches.assign_new_pickups now checks that the indices are known.
=> Use node identifier instead of raw indices in Dread Pool Creator

randovania/gui/widgets/base_game_tab_widget.py, randovania/gui/widgets/generate_game_widget.py
since quick generate uses the most recent preset (or the default, if none were used yet) it's helpful to display the name of the preset it'll use
=> display the name of the preset on the quick generate button

randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/header.json
This PR begins the process of revising the logic for Burenia. This covers the upper portion of Burenia stretching from the Ghavoran Transport to the Ferenia Teleport.
- Added event for Drogyga to account for some logic in Underneath Drogyga
- Corrected the logic for fighting Drogyga
- Renamed various event nodes to make them easier to understand
- Removed some redundant WEIGHT tile nodes
Added various methods of traversing the following rooms:
- Transport to Ghavoran
- Teleport to Ferenia
- Drogyga Eyedoor
=> Dread: Begin Burenia Logic Revision

randovania/exporter/pickup_exporter.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime2/exporter/patch_data_factory.py, randovania/games/super_metroid/exporter/patch_data_factory.py, test/games/prime/patcher_file_lib/test_pickup_exporter.py, test/games/prime1/exporter/test_prime_patcher_data_factory.py, test/games/prime2/patcher/test_patch_data_generator.py, test/test_files/randomprime_expected_data.json, test/test_files/randomprime_expected_data_crazy.json, test/test_files/randomprime_expected_data_one_way_door.json
Split scan_text into name and description. Rename `hud_text` into `collection_text`.
=> ExportedPickupDetails: less prime-specific

requirements.txt, setup.cfg
I fixed 4 actors being scaled that shouldn't of been scaled due to them having the same instance ID as another actor in another PAK (Ex: Two of the pistons in Research Entrance were being randomized instead of some Elite Pirate Actors in the tubes) I also released the GIL.
I was wanting to wait on this pull request until I got the callback thing done, but I ended up getting sick so its quite unlikely that I'll get that done before next month rolls around.
Idk why the 8 commits from my last pull request are showing up but since they don't change anything, I suppose it doesn't matter.
Also this won't make any previous test of this null or anything, cause if my changes broke anything, it would cause an exception.
=> Fixed incorrect actors being randomized, released GIL

randovania/games/dread/json_data/Itorash.json, randovania/games/dread/json_data/Itorash.txt
This has been confirmed to only be possible if you have space jump for the extra walljump height.
=> Remove impossible Walljump from Itorash

randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/header.json
- Always allow navigation on the right side of the freezer when unpowered
- The left side of the freezer (pickups, both doors) are blocked by the misc resource
- Rename a few resources and events
=> Add misc resource for navigating unpowered freezer

randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/header.json
This should finish off the logic revision for Burenia. Fixed a few things from the previous PR as well.
- Added various methods of traversing "Main Hub Tower Bottom"
- Added various methods of traversing "Gravity Suit Tower"
- Corrected some logic in "Gravity Suit Tower"
- Corrected some logic in "Gravity Suit Room"
- Corrected some logic in "Transport to Artaria"
- Fixed the connection between the bomb blocks in "Energy Recharge South"
- Accounted for the magnet wall event when choosing to grapple it to reach the item in "Main Hub Tower Middle"
- Added event for the Twin Robot Fight
- Added event for a speedboost in "Main Hub Tower Bottom"
- Corrected minor typo in the event long name for the Ferenia Twin Robot Fight
- Renamed "Allow Disabled Freezer" to "Highly Dangerous Logic", …
=> Dread: Final Burenia Revision

randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/header.json
Looking over the Cataris logic and adding anything I see that is missing from trickless and changing things to be tricks if needed. I am also renaming all the events and nodes as I go through. This affects the following rooms on the west side of Cataris:
- Path to Kraid Entryway
- Above Kraid
- Heated U-Turn
- Kraid Eyedoor Room
- Diffusion Beam Room
- Teleport to Dairon
- Green EMMI Introduction
- Long Mouth Statue Room
- Teleport to Artaria (Red)
- Teleport to Ghavoran
- Ghavoran Teleport Access
=> Dread: Cataris Revision, West Side

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/header.json
- Removed the event for opening the upper door
- Added a direct connection to the door if Door Rando is disabled
=> Dread: Fix up the logic around getting the Thermal Device item without Morph

randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/header.json
This revision goes over the entire EMMI Zone and up to the Artaria Transport, renaming events and other nodes, and adding other methods to trickless connection and some tricks. Pretty much every room is affected within the EMMI Zone and between Green EMMI Introduction Access and Transport to Artaria.
=> Dread: Cataris Revision Part 2

CHANGELOG.md, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/header.json
Finishes the primarily trickless-focused revision for Cataris. A few rooms in the EMMI Zone were affected, and most rooms ranging from Underlava Puzzle Room 2 all the way to Teleport to Artaria (Blue), and all the way to the upper edge of the EMMI Zone from there.
- Added event in Underlava Puzzle Room 2 for breaking the speed blocks so that going between the two parts can be accounted for
- Added event for the trigger that reopens the door to Central Unit Access, allowing it logical to go back through
- Separated the First Tunnel Blob event into two to account for Diffusion/Wave not needing to be in the tunnel
- Deleted some unnecessary tile nodes
- Accounted for whether the player could have Varia or not when trudging through lava
- Accounted for the upper parts of Thermal Device Room …
=> Dread: Final Trickless Cataris Revision

randovania/gui/ui_files/preset_prime_enemy_stat_randomizer.ui
when pressing tab in the 'enemy attribute randomizer' tab, it would be completely out of order, so now that's fixed.
=> fixed tab order in ui for enemy attribute rando

randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
This adds Short Boost to the list of tricks. No implementation included, only adds it to the header. Trick description is as follows:
> Flash Shift can be manipulated to allow you to charge Speed Booster in a smaller area than intended.
Also adds template for Short Boost, requiring Flash Shift and Speed Booster.
=> Add trick for Short Boost

randovania/games/dread/json_data/header.json
Adds a trick for Aim Down Clip. Description is as follows:
> A type of shine sink clip that allows you to clip through 2 tile thick floors.
Also adjusts the description for Shinesink Clip. It is now as follows:
> Shinesparking and firing the grapple beam in certain locations allows you to clip through 1 tile thick floors.
Includes no implementation of the new trick. This will be handled in future PRs.
=> Add trick for ADC and adjust SSC trick description

CHANGELOG.md, randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
- Add the new Diffusion Abuse trick
- Apply it to pushing Wide Beam Blocks while next to them as intermediate
- Added the trick to activating the Cataris lava buttons from outside as beginner
- Added hypermode trick for the Artaria Wide Beam Block
=> Dread: Add Diffusion Abuse trick

CHANGELOG.md, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
This prevents the generator from getting stuck by rotating it before either enabling the freezer or pulling the grapple block.
=> Ghovran: Add entrance grapple block requirement to the spinner

randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt
- Added the two remaining implementations of Diffusion Abuse for Wide Beam Blocks in Big Hub and Purple EMMI Arena
=> Dread: Add the remaining Wide Block Diffusion Abuse tricks

CHANGELOG.md, randovania/games/blank/presets/starter_preset.rdvpreset, randovania/games/cave_story/presets/classic.rdvpreset, randovania/games/cave_story/presets/starter_preset.rdvpreset, randovania/games/dread/generator/bootstrap.py, randovania/games/dread/gui/preset_settings/__init__.py, randovania/games/dread/gui/preset_settings/dread_generation_tab.py, randovania/games/dread/json_data/header.json, randovania/games/dread/layout/dread_configuration.py, randovania/games/dread/layout/preset_describer.py, randovania/games/dread/presets/starter_preset.rdvpreset, randovania/games/prime1/presets/april_fools_2022.rdvpreset, randovania/games/prime1/presets/moderate_challenge.rdvpreset, randovania/games/prime1/presets/starter_preset.rdvpreset, randovania/games/prime2/presets/darkszero_deluxe.rdvpreset, randovania/games/prime2/presets/fewest_changes.rdvpreset, randovania/games/prime2/presets/starter_preset.rdvpreset, randovania/games/prime3/presets/starter_preset.rdvpreset, randovania/games/super_metroid/presets/starter_preset.rdvpreset, randovania/gui/preset_settings/generation_tab.py, randovania/layout/preset_migration.py, test/games/dread/gui/preset_settings/test_dread_generation_tab.py, test/gui/preset_settings/test_generation_tab.py
- Adds a setting in the Generation tab for the Highly Dangerous Logic misc resource
- Updates the presets with the new setting defaulted to off
- Setting appears under Logic Settings on the preset summary
- Supplied a link to view the rooms affected by the setting
=> Dread: Add new setting for Highly Dangerous Logic

randovania/games/prime3/json_data/SkyTown Elysia - Main.json, randovania/games/prime3/json_data/SkyTown Elysia - Main.txt, randovania/games/prime3/json_data/SkyTown Elysia - Pod.json, randovania/games/prime3/json_data/SkyTown Elysia - Pod.txt, randovania/games/prime3/json_data/header.json
- Fixes Gearworks by adding an event for collecting Ship Grapple
- Fixes Steambot Barracks by requiring the Gate event so you can reload the room to go back up
- Fixes Transit Hub by requiring Defense Drone to be defeated before using the kinetic orb cannon
- Adds the possibility of beginner Knowledge to enter the AU Chamber
=> Prime3: Minor logic fixes for Elysia

CHANGELOG.md, randovania/games/prime2/json_data/Agon Wastes.json, randovania/games/prime2/json_data/Agon Wastes.txt
The standable terrain is massive. There is little to no risk of breaking the standable terrain. There is little to no risk of taking damage or softlocking from using the standable terrain. The Screw Attack itself is very lenient and is not difficult to perform. The majority of players should be able to perform the trick successfully 90%+ of the time. This all suggests the trick belongs in Beginner and not Intermediate.
I did not run the tests to see if they broke.
=> Lower difficulty of Central Mining Station Standable Terrain

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/Hanubia.json, randovania/games/dread/json_data/Hanubia.txt, randovania/games/dread/json_data/header.json
- Adds exclusions to all doors that need it
- Removes the Hanubia Tank Room event as it is unneeded
- Readds the Burenia Early Gravity Pickup 1 event to ensure the door next to it does not need excluded
- Adds and removes "Disabled Door Lock Randomizer" in a few places where necessary
=> Dread: Add door exclusions to Door Lock Rando

CHANGELOG.md, randovania/games/dread/gui/preset_settings/__init__.py, randovania/games/dread/layout/dread_configuration.py
Existing presets with it enabled will still work, but will have the unsupported feature warning.
=> Dread: Hide door lock rando for stable

CHANGELOG.md, randovania/resolver/resolver.py
This change makes the issue posted in https://discord.com/channels/914291389293027329/1045827510534930602 look less like looping and more like just not finding the correct path, because the rollbacks line up better.
=> Rersolver: Debug rollback also for results that had action

randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
- Excludes all save stations' doors that are the only door into the room
- Excludes the door under Burenia Cyan since Samus can get stuck above a blast shield without morph or the weapon for the shield
- Removes "Disabled Door Lock Randomizer" for going from "Dock to Map Station Access (Upper)" to "Dock to EMMI Zone Exit West" in Ghavoran's EMMI Zone Exit Southeast since the map station door is now excluded.
=> Dread: Exclude one-way save station doors

randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
I excluded Wide Beam Doors in door rando for Eye-doors because you can not pass them if they have wide beam cover.
Corpius, Kraid, Drogyga, Escue and Golzuna doors.
https://user-images.githubusercontent.com/117127188/206510843-7389e8c8-4994-4be9-88dc-8f6018e4bc05.mp4
=> Exclude Wide Beam for Eye-Doors

randovania/games/dread/json_data/Elun.json, randovania/games/dread/json_data/Elun.txt
Missed the eye door in elun to exclude the wide beam in door lock rando.
=> Missing exclude for eye door in elun

CHANGELOG.md, randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Elun.json, randovania/games/dread/json_data/Elun.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
Adds 20 Major Item Locations to the pool
- Energy Tanks are now Major Locations
- Energy Parts are now Minor Locations
- Drogyga is now a Major Location
- Missile+ Tanks are now Major Locations
- Fixes #3867
=> Dread - Major/Minor Item Location Updates

CHANGELOG.md, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt
Use the "Lay Power Bomb" template when Power Bombs are used by logic. This includes both the Main Power Bomb and the Morph Ball as part of the template. The "Power Bombs" value is only referenced directly when the logic asks asks for more that one unit of ammo.
=> Dread: Add missing Main Power Bomb requirement

CHANGELOG.md, randovania/game_description/integrity_check.py, randovania/games/prime1/presets/starter_preset.rdvpreset, randovania/lib/random_lib.py
This PR fixes typos where `its` should have been used instead of `it's`. The first one I noticed was in the Prime Starter Preset description:
> This preset is ideal for those new to playing Metroid Prime or *it's* Randomizer.
Then I did a find-and-replace for all the other instances I could find where `it's` was used when it should have been `it's`.
=> Fix typos where `it's` was used when it should have been `its`

CHANGELOG.md, randovania/games/dread/json_data/Hanubia.json, randovania/games/dread/json_data/Hanubia.txt, randovania/games/dread/json_data/Itorash.json, randovania/games/dread/json_data/Itorash.txt, randovania/games/dread/json_data/header.json
- Added: Spin Boost Movement (Intermediate) and Speedbooster Conservation (Beginner) for getting up Hanubia - Central Unit without Space Jump or Infinite Bomb Jump.
- Added: Spin Boost method to climb Hanubia - Escape Room 3.
- Added: Morph Ball Single-Wall Walljumps to get to the Nav Station in Itorash - Transport to Hanubia.
- Changed: Increased difficulty of Flash Shift Walljump to reach the Raven Beak elevator from Intermediate to Advanced.
- Removed all block nodes in Hanubia and the one in Itorash
- Started initial preparation for logic accounting for the ADC and clips for finishing without Hyper Beam
=> Dread: Add some tricks and remove Hanubia block nodes

CHANGELOG.md, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
- Added: New trick "Flash Shift Skip" to account for skipping Flash Shift gates.
- Added: Flash Shift Skip (Intermediate) with Bombs to skip the Flash Shift gate in Teleport to Ferenia.
- Added: Shine Sink Clips (Intermediate/Advanced) to go to and from Storm Missile Gate Room without Morph Ball.
- Added: Shine Sink Clip (Intermediate) and Speedbooster Conservation (Advanced) to reach the bottom of Teleport to Ghavoran from the top level.
- Added: Shine Sink Clip (Advanced) to reach the blobs in Gravity Suit Tower from the top level.
- Changed: Shine Sink Clip in Main Hub Tower Middle to Main Hub Tower Bottom is now Intermediate (from Expert).
- Fixed: Collecting the Power Bomb Tank in Gravity Suit Room now properly requires Speed Booster and Gravity Suit.
- Removed all block nodes from …
=> Dread - Burenia Updates (Tricks, Block Nodes)

CHANGELOG.md, randovania/game_description/requirements/resource_requirement.py, randovania/generator/filler/pickup_list.py, randovania/generator/old_generator_reach.py, test/generator/filler/test_pickup_list.py
Fixes #4057.
Fixes Echoes placing 13 missiles expansions for Quad, despite having Light Beam.
=> Simplify requirements during generator to improve multi-pickup

CHANGELOG.md, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
- Removes all block nodes in Ferenia
- Adds a connection from Transport to Ghavoran to Pitfall Puzzle Room (Upper)
- Adds Flash Shift Skip in Purple EMMI Introduction
- Removes Simple IBJ from reaching the end of the cold run to Purple EMMI; you cannot break SA blocks after doing an IBJ.
- Adds new dock connection between Purple EMMI Introduction and Quiet Robe Room to account for the QR event warping you.
- Added "Shoot Missile" to template "Activate Storm Missile Locks"
=> Dread: Remove Ferenia block nodes

tools/flatpak/io.github.randovania.Randovania.yml
Otherwise the builder might complain that the file doesn't exist... even though we're clearly trying to create it ಠ_ಠ
=> Use `install` to create the flatpak shell wrapper

tools/flatpak/io.github.randovania.Randovania.metainfo.xml, tools/flatpak/io.github.randovania.Randovania.yml
This adds the final _required_ piece of the puzzle for RDV on Flathub. Notably absent is screenshots, which can be added to the flathub repo after it's accepted.
With this file, in addition to the application working, there's now also information that app stores can use when browsing:
As a bonus, I found a less horrifying way to do the wrapper script, so that's in here too.
=> flatpak: Add metainfo XML, needed for submission

randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/gui/dialog/dread_cosmetic_patches_dialog.py, randovania/games/dread/layout/dread_cosmetic_patches.py, randovania/gui/ui_files/dread_cosmetic_patches_dialog.ui, test/test_files/dread_expected_data.json
This adds the cosmetic option for randovania/open-dread-rando#186.
When enabled:
=> Add Death Counter cosmetic option

randovania/gui/lib/node_list_helper.py, randovania/gui/preset_settings/elevators_tab.py, randovania/gui/preset_settings/starting_area_tab.py, randovania/layout/lib/location_list.py, randovania/layout/lib/teleporters.py, test/gui/preset_settings/test_preset_elevator.py, test/gui/preset_settings/test_starting_area.py, test/layout/test_teleporters.py
Fix for the regression from discord channel.
Summary:
Elevators can be shuffled to use any starting location. There is one corner case: You can activate a warp to the credits for MP1 and MP2. These areas in MP1 and MP2 have a `default_node` which is not a `valid_starting_location`. This means the logic doesn't find this node when builidng the internal nodes list and crashes when try to mark them as selected.
Setting `valid_starting_location` to true for these nodes is wrong because it will appear selectable in `Starting area` tab.
In the call to `nodes_by_areas_by_world_from_locations` the area is not present for `Starting area`.
In the call to `nodes_by_areas_by_world_from_locations` the area is present for `Elevators`.
I just added the check for the special case. I don't like the fact …
=> Fix error when selecting / deselecting Credits in Elevator tab

randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt
Burenia - Main Hub Tower Top and Main Hub Tower Bottom were the only ones missing it. Checked it with a temporary integrity check.
=> Dread: Add missing collision_camera in DB for Burenia

CHANGELOG.md, randovania/games/prime2/json_data/Agon Wastes.json, randovania/games/prime2/json_data/Agon Wastes.txt, randovania/games/prime2/json_data/header.json, randovania/games/prime2/json_data/header.txt
Closes #4120  
- Added: Shoot Super Missile template
- Change: Removed SJ and Bomb Jump (beginner) requirements from Amorbis fight
- Change: Add combat requirements to Amorbis fight
- Change: Amorbis to Dark Suit now trivial
=> Fix dark agon temple logic

randovania/game_description/game_patches.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/patcher/prime1_elevators.py, test/test_files/randomprime_expected_data.json, test/test_files/randomprime_expected_data_crazy.json, test/test_files/randomprime_expected_data_one_way_door.json
This has the side effect of re-randomizing chaos setting seeds generated on older versions. That was never guaranteed to begin with, however.
Also, the prime patch data factory now deletes empty fields, as randomprime guarantees that empty fields and non-populated fields are the same behavior.
=> Fix room+door rando incompatibility

CHANGELOG.md, randovania/games/dread/gui/preset_settings/__init__.py, randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt, randovania/games/dread/json_data/Burenia.json, randovania/games/dread/json_data/Burenia.txt, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/Dairon.json, randovania/games/dread/json_data/Dairon.txt, randovania/games/dread/json_data/Elun.json, randovania/games/dread/json_data/Elun.txt, randovania/games/dread/json_data/Ferenia.json, randovania/games/dread/json_data/Ferenia.txt, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/Hanubia.json, randovania/games/dread/json_data/Hanubia.txt, randovania/games/dread/json_data/Itorash.json, randovania/games/dread/json_data/Itorash.txt, randovania/games/dread/layout/dread_configuration.py, randovania/gui/preset_settings/starting_area_tab.py, test/games/dread/layout/test_dread_configuration.py, test/gui/preset_settings/test_starting_area.py, test/test_files/log_files/dread_1.rdvgame, test/test_files/log_files/dread_2.rdvgame
Starting Locations
- Removes all existing starting locations except Intro Room
- Adds every Save Station or save-like room as an option to start in, except Elun
-- Exception is Itorash where it is instead the Transport to Hanubia
- Moves the option out of Unsupported status
Logic
- Added Grapple Movement (Beginner) for going up the left side of Burenia - Main Hub Tower Middle.
- Added Movement (Intermediate) and Water Bomb Jump (Intermediate) for getting out of the water at the same spot.
- Removed Walljump from Flash Shift for reaching the left Dock to Main Hub Tower Top in Main Hub Tower Middle; it is now trickless.
- Added Grapple Movement (Beginner) for the Grapple only method of reaching the Missile Tank in Main Hub Tower Top.
=> Dread: Add Random Starting Locations

CHANGELOG.md, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/prime1/json_data/Tallon Overworld.json, randovania/games/prime1/json_data/Tallon Overworld.txt, randovania/games/prime2/item_database/item-database.json
- Fixed: The Artifact of Truth pickup is now a major location for Major/Minor split.
- Fixed: Energy Tanks are now considered major items in Echoes' Major/Minor split.
- Fixed: Experiment Z-57's pickup is now a major item location in Major/Minor split.
=> Database Updates for Major/Minor

randovania/games/prime3/patcher/corruption_dol_versions.py
Allows to use automatic item tracker for both of those versions
=> Added Corrruption PAL and JP standalone versions

randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, test/games/dread/exporter/test_dread_patch_data_factory.py, test/test_files/patcher_data/dread/crazy_settings.json, test/test_files/patcher_data/dread/custom_start.json, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json, test/test_files/patcher_data/dread/starter_preset.json
Fixes #4316
Fixed the following room names:
Ghavoran:
- "Total Recharge Station North" by changing from collision_camera_025b to collision_camera_025
Elun:
- "Bottom Morph Launcher" by applying a static fix for renaming the key for "collision_camera_MBL_B" (which is the name according to dread-editor) to "collision_camera_MBL" (which is used according to the screenshots)
Ferenia:
- "Central Unit Access" by applying a static fix for renaming the key for "collision_camera_038_A" (which is the name according to dread-editor) to "collision_camera_038" (which is used according to the screenshots)
Burenia:
- "Gravity Suit Room" by applying a static fix for renaming the key for "collision_camera_023_B" (which is the name according to dread-editor) to "collision_camera_023" (which is used …
=> Fix some room names

randovania/games/prime3/json_data/GFS Valhalla.json, randovania/games/prime3/json_data/GFS Valhalla.txt
Someone accidentally made two morph ball doors instead of one door and one morph ball door
=> Fix Corruption valhalla having wrong door type

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/GFS Thoth.json, randovania/games/am2r/json_data/GFS Thoth.txt, randovania/games/am2r/json_data/Genetics Laboratory.json, randovania/games/am2r/json_data/Genetics Laboratory.txt, randovania/games/am2r/json_data/Golden Temple.json, randovania/games/am2r/json_data/Golden Temple.txt, randovania/games/am2r/json_data/Hydro Station.json, randovania/games/am2r/json_data/Hydro Station.txt, randovania/games/am2r/json_data/Industrial Complex.json, randovania/games/am2r/json_data/Industrial Complex.txt, randovania/games/am2r/json_data/Main Caves.json, randovania/games/am2r/json_data/Main Caves.txt, randovania/games/am2r/json_data/The Tower.json, randovania/games/am2r/json_data/The Tower.txt
This adds extra fields to doors for future use in the door lock rando and fixes some slight logic errors.
The logic errors have been gone through with @DruidVorse
Specifically what they fix are:
**Golden Temple**
- Add a missing PB check for a potential way to get up torture room
**Hydro Station**
- Add a missing "after emp activated" event in order to reach the a2 emp event in breeding grounds entrance
- Add a missing "defeat alpha" template in order to reach the alpha node in breeding grounds alpha nest west
- Remove Super Missile requirement in Speedboosting challenge
**Distribution Center**
- Going in upper factory save station from the save to the sand now requires all requirements instead of any
**Tower**
- Going from the dock node in Inner Zeta nest to the zeta event, now requires …
=> AM2R: add fields to doors + slight logic errors

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/Golden Temple.json, randovania/games/am2r/json_data/Golden Temple.txt
Some rooms were named `Breeding Ground` instead of `Breeding Ground*s*`. 
Also the `Beam Bot Prison` is now named `Robomine Prison`, because that's the actual name of the enemies.
=> AM2R: Fix some room name typos

randovania/gui/ui_files/preset_dread_goal.ui
Makes UI not resize awkwardly now when switching to the goal tab
=> Enable word wrap for dread goal ui

randovania/games/am2r/json_data/Main Caves.json, randovania/games/am2r/json_data/Main Caves.txt
In vanilla AM2R, when you go down from the Thoth elevator, you need to reset the game, as you're blocked by the power bombs.
Since the patcher will clear the event if you come from above, I adjusted the DB accordingly.
=> AM2R: When going down from thoth, have access to the lift event

randovania/gui/preset_settings/dock_rando_tab.py
I was going to add it the params so it's per type, but I have a server bug to fix
=> Dock Lock Rando Weakness: disallow shuffling the unlocked type

randovania/games/am2r/json_data/Hydro Station.json, randovania/games/am2r/json_data/Hydro Station.txt, randovania/games/am2r/json_data/Industrial Complex.json, randovania/games/am2r/json_data/Industrial Complex.txt
Fixes an accidental OR in A2, and missing EMP+Super conditions for A3.
Noticed during a testing session.
=> AM2R: Fix A2/A3 EMP logic errors

randovania/server/discord/database_command.py, test/server/discord/test_database_command.py
There's a bug in the bot currently that it seems to randomly fail to work. I can reproduce it easily by:
1. Starting the bot
2. Run `/database-inspect` with a game
3. Select one section of regions
4. Press back
5. Repeat 3 and 4 until it fails
The error messages comes as if we're sending too much data, but adding prints to the libraries tells we don't. But since that request is a PATCH one, I'm wondering if we're hiting a _lifetime_ total message or something?
This PR dodges the issue by just never editing the message anymore.
=> Remove the Back button, always reply with new message

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
See title. Instance_id was wrong.
Also remove Locked Door from change_from, as they never appear in vanilla under normal circumstances
=> AM2R: fix extra data of 2 doors

randovania/gui/ui_files/tracker_window.ui
This stops the tracker from forcibly increasing in size if the current location has a very long name
=> Enable word wrap for map tracker current location

randovania/games/prime2/json_data/Great Temple.json, randovania/games/prime2/json_data/Great Temple.txt, randovania/games/prime2/json_data/Torvus Bog.json, randovania/games/prime2/json_data/Torvus Bog.txt
- Removes Screw Attack weakness from all underwater doors
- Removes Bomb and Boost Ball weaknesses from Sky Temple doors
Fixes #4585
=> Echoes Door Lock Rando Exclusions

randovania/games/am2r/json_data/Main Caves.json, randovania/games/am2r/json_data/Main Caves.txt, randovania/games/am2r/json_data/The Nest.json, randovania/games/am2r/json_data/The Nest.txt, randovania/games/am2r/json_data/The Tower.json, randovania/games/am2r/json_data/The Tower.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
Adds doors for all available beams (charge, wave, spazer, plasma, ice)
The plasma beam chamber door was accidentally assigned the wrong type
And the tester arena logic has been revised to better reflect what actually happens in-game. (need to review this with @DruidVorse)
=> AM2R: add new beam doors and make tower doors shuffable

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
- Excludes underwater doors from screw+spider
- fixes requirements for bombs+spider
- marks some doors as incompatible with DLR, specifically serris arena, and some in the gravity area
=> AM2R: exclude underwater doors from screw+spider, fix bomb+spider door reqs

randovania/gui/preset_settings/item_pool_tab.py, randovania/gui/ui_files/preset_item_pool.ui
I removed this from the tooltip and made it into a proper label to be more discoverable.
Also made it not hardcode to echoes' ETM+119 pickups
Fixes #387
And a full view for context:
=> Clarify that leftover items will be nothings in GUI

randovania/game_connection/game_connection.py, randovania/gui/dialog/online_game_list_dialog.py, randovania/gui/lib/multiplayer_session_api.py, randovania/gui/lib/qt_network_client.py, randovania/gui/lib/window_manager.py, randovania/gui/main_online_interaction.py, randovania/gui/main_window.py, randovania/gui/multiplayer_session_window.py, randovania/gui/qt.py, randovania/gui/widgets/game_connection_window.py, randovania/interface_common/world_database.py, randovania/network_client/network_client.py, randovania/network_common/multiplayer_session.py, randovania/server/database.py, randovania/server/multiplayer/session_api.py, randovania/server/multiplayer/world_api.py, randovania/server/user_session.py, test/game_connection/test_game_connection.py, test/gui/lib/test_qt_network_client.py, test/gui/test_main_online_interaction.py, test/gui/test_main_window.py, test/gui/test_multiplayer_session_window.py, test/gui/test_multiworld_client.py, test/gui/test_online_game_list_window.py, test/gui/widgets/test_game_connection_window.py, test/network_client/test_network_client.py, test/network_common/test_world_sync.py, test/server/multiplayer/test_session_api.py, test/server/multiplayer/test_world_api.py
1. Adds "Open Session Window" action to game connection window
2. Allow joining without password if user already belongs to the session
Got somehow distracted by 2. because that made the refactor for 1. a little bit easier.
Not really happy with some parts: Moving the whole "which game session windows are open" part to `WindowManager` introduced some cyclic dependencies. Atm I fixed that by importing when used in the functions.
Let's see what codecov says.
=> Add "Open Session Window" action / Allow joining without password 

randovania/gui/multiplayer_session_window.py, randovania/gui/qt.py, test/gui/test_multiplayer_session_window.py
Without the session cli command, there should be no reason anymore to do this `WindowManager | PresetManager` shenanigans.
=> Remove CLI command to directly open a session window

randovania/__init__.py, randovania/gui/lib/qt_network_client.py, randovania/network_client/network_client.py, randovania/server/server_app.py
Since we have a reverse proxy in front of the server, the socket itself is not broken when the server itself restarts.
This means `_internal_connect_to_server` is not called every time, so rejoining rooms there is not a good location.
Move the code to where the exact same thing was done before, ooops!
=> Rejoin rooms when restoring a session, not when raw connecting

randovania/server/multiplayer/session_admin.py, test/server/multiplayer/test_session_admin.py
This prevent issues if someone had exported the game, started playing, collected locations, then we change the session layout before starting.
=> Reset world UUIDs when clearing a game

randovania/gui/ui_files/main_window.ui
I think this now raises the minimum height of the main RDV window, but I don't think shortening this text would be a good idea to for UX.
preview:
=> Revise MW description in Main window

randovania/monitoring/__init__.py
Filters out `/home/username/` and `/User/username` style home directories from monitoring
=> Monitoring: Filter out home folder on macOS and Linux

randovania/games/dread/assets/lua/bootstrap_part_3.lua, randovania/games/dread/exporter/patch_data_factory.py, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json
- skip everything besides game state updates if rando identifier is wrong
- use unknown map icon for pickups with an item for other games
- change map text to include the world name for the item iff it belongs to another world
=> Dread multiworld improvements

test/gui/test_multiworld_client.py
Causes full test runs to sometimes fail.
=> Don't leak a task in test_start_server_sync_task

randovania/game_connection/connector/dread_remote_connector.py, randovania/games/dread/exporter/patch_data_factory.py, test/games/dread/exporter/test_dread_patch_data_factory.py
- refactored `get_resources_for_details` to take only the parts needed...
- such that multiworld can use the same function...
- which fixes non-required mains e.g. like flash shift upgrade
=> Fix multiworld with non-required mains

CHANGELOG.md, randovania/gui/multiplayer_session_window.py, randovania/gui/ui_files/multiplayer_session.ui, randovania/gui/widgets/multiplayer_session_users_widget.py
- Added: An "Export Game" button has been added to "Session and Connectivity" tab as a shortcut to export any of your worlds.
- Fixed: Any buttons for changing presets or deleting worlds are properly disabled when a game is being generated.
=> UI improvements for multiplayer session

randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/am2r/presets/starter_preset.rdvpreset
Noticed that this should be `Hi-Jump Boots`, not `Hi-Jump`
=> AM2R: Fixes Hi-Jump name

randovania/monitoring/__init__.py
Prevents the "packet queue is empty, aborting" message from reaching sentry
=> Ignore engineio.client logger

randovania/exporter/pickup_exporter.py, test/test_files/patcher_data/dread/crazy_settings.json, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json, test/test_files/patcher_data/dread/starter_preset.json
I have the feeling that I'm using it wrong.
Logically, it's now an `offgame_model` and not an `offworld_model`
=> Fix models of dread-dread multiworld

CHANGELOG.md, randovania/gui/game_details/pickup_details_tab.py, randovania/gui/lib/foldable.py, randovania/gui/preset_settings/dock_rando_tab.py, randovania/gui/preset_settings/item_pool_tab.py, randovania/gui/preset_settings/location_pool_tab.py, randovania/gui/ui_files/game_details_window.ui, randovania/gui/ui_files/pickup_details_tab.ui, test/gui/game_details/test_pickup_details_tab.py, test/gui/lib/test_foldable.py
Does not show up for solo games:
Defaults to hidden in multis:
Shows where pickups for the currently selected world are:
=> Add pickup search to PickupDetailsTab

randovania/games/am2r/pickup_database/pickup-database.json
Adds offworld models to AM2R
While this is probably a good enough base, some thoughts i had earlier were:
- AM2R's power grip could potentially be represented primes/dreads grapple beam
- AM2R's spring ball could potentially be represented by morph ball models
- AM2R's space jump could potentially be represented in echoes by gravity booster. Currently it's space jump boots for consistency
Adding am2r as offworld models to other games will follow in a different PR
=> AM2R: add offworld models

randovania/game_connection/game_connection.py, randovania/gui/multiplayer_session_window.py, randovania/gui/multiworld_client.py, randovania/gui/ui_files/multiplayer_session.ui
MultiplayerSessionWindow:
- 60s after losing connection and not regaining it, display an error message for it
- In the connectivity tab, for each world list if you have a connected game for it and what state
MultiworldClient:
- Consider a disconnection as reason to request a new sync, to make sure we're connected and receiving remote pickups
=> Improve feedback with connection errors.

randovania/game_description/integrity_check.py
Integrity check for non dock nodes only fails if it also has `to` or `from` in the name
Would fix question 3 of https://github.com/randovania/randovania/pull/4800
=> Integrity check for non dock nodes using dock type name

CHANGELOG.md, randovania/generator/filler/filler_logging.py, randovania/generator/filler/player_state.py, randovania/generator/filler/retcon.py, randovania/generator/filler/weighted_locations.py, test/generator/filler/test_player_state.py
Current code ensures that your major pickups are always placed in major locations, even in other worlds. But other people's major pickups can be placed in your minors.
=> Fix Major/Minor interacting badly with full randomization in multiworld

randovania/games/am2r/json_data/Hydro Station.json, randovania/games/am2r/json_data/Hydro Station.txt, randovania/games/am2r/json_data/Industrial Complex.json, randovania/games/am2r/json_data/Industrial Complex.txt
BG2 blocks change to speedbooster blocks in vanilla if you come from the left and dont have screw
BG3 just had completely screwed up logic
Already reviewed by @DruidVorse
=> AM2R: fix logic in BG2 and BG3

randovania/games/am2r/presets/starter_preset.rdvpreset
For some reason it was false before
=> AM2R: change screw block option to be true for starter preset

CHANGELOG.md, randovania/games/prime1/json_data/Chozo Ruins.json, randovania/games/prime1/json_data/Chozo Ruins.txt
The door from ToL acces -> ruined shrine is a normal door.
=> Prime: Fix tower of light access -> ruined shrine door

randovania/games/am2r/json_data/Genetics Laboratory.json, randovania/games/am2r/json_data/Genetics Laboratory.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
On the process of adding Queen doors, this also does the following:
- Adds a queen defeated event (no clue why this wasnt done before)
- Changes queen arena for top door to go to event first, instead of the hatchling door.
Primary use for plando and room rando
=> AM2R: Add queen doors

randovania/gui/ui_files/node_details_popup.ui
Should hopefully clear confusion over people thinking its for something else
=> Make slightly clearer that incompatible weaknesses is for DLR

randovania/games/am2r/exporter/patch_data_factory.py, randovania/generator/pickup_pool/pickup_creator.py, test/games/am2r/exporter/test_am2r_patch_data_factory.py
Defaults to `Nothing` for backwards compatibility. Games (like AM2R) who have a different model name for Nothing can specify it now there without needing to create the whole pickup from scratch.
=> Add optional model parameter to create_nothing_pickup

CHANGELOG.md, randovania/gui/dialog/preset_history_dialog.py, randovania/gui/widgets/select_preset_widget.py, test/gui/dialog/test_preset_history_dialog.py, test/gui/widgets/test_select_preset_widget.py
- Customizing a preset no longer loses it's position in the tree
- Delete/View History for a preset can be used for invalid presets (Fixes #4922)
- View History no longer errors if the current version is broken
=> Multiple fixes for the SelectPresetWidget

CHANGELOG.md, randovania/gui/ui_files/games_tab_prime_widget.ui
=> Add Phazon Suit Hint location to Hints page

randovania/games/super_metroid/json_data/Brinstar.json, randovania/games/super_metroid/json_data/Brinstar.txt, randovania/games/super_metroid/json_data/Ceres Station.json, randovania/games/super_metroid/json_data/Ceres Station.txt, randovania/games/super_metroid/json_data/Crateria.json, randovania/games/super_metroid/json_data/Crateria.txt, randovania/games/super_metroid/json_data/Maridia.json, randovania/games/super_metroid/json_data/Maridia.txt, randovania/games/super_metroid/json_data/Norfair.json, randovania/games/super_metroid/json_data/Norfair.txt, randovania/games/super_metroid/json_data/Tourian.json, randovania/games/super_metroid/json_data/Tourian.txt
Fixes the teleporters to adhere to new naming scheme, and to not go to previous default nodes.
Would be appreciated if someone can double check the elevator to lower norfair <-> main hall connection in norfair, because based on the names, not sure if it sounds correct.
=> Super Metroid: Fix Elevators after teleporter refactor

randovania/games/super_metroid/pickup_database/pickup-database.json
Missile launcher, super launcher and PB launcher don't have one assigned. *technically* the first vanilla locations could be assigned but as these are actually expansions and not launchers i feel like it'd be weird to do that.
=> Super Metroid: Add vanilla locations

randovania/gui/ui_files/preset_patcher_super_patches.ui
Adds a few word wraps, makes pre spazer and pre hijump consistent in naming, clarifies skip intro better to indicate that its not ceres.
=> Slightly improve SM patcher page

randovania/games/super_metroid/game_data.py, randovania/games/super_metroid/generator/bootstrap.py, randovania/games/super_metroid/json_data/header.json, randovania/games/super_metroid/json_data/header.txt, randovania/games/super_metroid/layout/super_metroid_configuration.py, randovania/games/super_metroid/layout/super_metroid_patch_configuration.py, randovania/games/super_metroid/presets/starter_preset.rdvpreset, test/test_files/presets/super_test_preset.rdvpreset, test/test_files/sdm_expected_result.json, test/test_files/sdm_test_game.rdvgame
- Adds DB options for `Dachora Pit Tweaks`, `Early Supers Bridge Tweaks`, `Pre Hi-Jump Tweaks`, `Moat Tweaks`, `Pre Spazer Tweaks`, `Red Tower Tweaks`, `Nova Boost Tweaks`, `Can't Use Supers On Red Doors` and `Mother Brain Rainbow Beam Nerf`
- Also adds `No Lower Norfair Space Jump Check` as a patch, but doesn't expose it in the GUI yet
- Fix logic condition for missile doors to account for `Can't Use Supers On Red Doors`
- Add damage reduction with suits
=> Super Metroid: Add DB options for (map) tweaks

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
Can't get rid of the BEFORE's sadly, but should make serris logic a bit easier to follow.
=> AM2R: Get rid of serris entrance doors

randovania/games/am2r/json_data/The Tower.json, randovania/games/am2r/json_data/The Tower.txt
- Dark Maze
- Added: Escape from Left Bottom now has High Jump option
- Ext. Zeta Nest East
- Added: Speedboost method from access to enter the arena
- Changed: Speedboost escape from knowledge to shinespark trick??????
- Ext. Zeta Nest East Access
- Changed: HJ method from mid-air morph to morph glide
- Inner Zeta Nest Access
- Removed: Moved tunnel climbing requirements to Inner Zeta Nest
- Inner Zeta Nest
- Added: Tunnel climbing requirements
- Power Plant Entrance
- Changed: Now uses tunnel climb or lower difficulty mid-air morph
- Tower Ext. N
- Added: Dark Maze (left) escape requirements
- Changed: Reworked requirements to reach top missile
- Added: Requirements from exterior lower sides to top climb
- Tower Ext. W
- Fixed: Missing morph requirement for morph glides
=> AM2R: Tower (A4) Database Updates

README.md
See title.
orange indicates new stuff in the *autotracker* section.
=> Add AM2R credits in readme

randovania/games/am2r/game_data.py
Since hints moved locations, and I feel like putting names just straight up into an faq is a bad choice, it will now just mention that the in-game map shows the locations.
=> AM2R: revise hint faq question.

requirements.txt
Opening this instead of letting dependabot do it, just so I can announce the relation between current open am2r PRs.  
These PRs rely on the new version:
- #5066 
- #5065
- #5059
---
- #5039 has no effect on this.  
- #5037 can be merged, and has functionality here, but will have some slight bugs on both the RDV side, and game side
- #5025 is not implemented at all here.
=> Bump am2r-yams to 0.0.13

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt
- Energy Distribution Activation
- Changed: Moved connections between doors instead of through event
- Energy Distribution Activation Access
- Added: Shinespark trick to climb room
- EMP Ball Introduction
- Changed: Moved connection between EMP puzzle to the bottom door, this allows entrance rando to not have to climb to the top
- Energy Distribution Robot Home
- Changed: Moved connections between doors instead of through event
- Energy Distibution Tower East
- Added: Node for bottom of room, allows traversal without EMP puzzle
- Energy Distribution Zeta Nest
- Changed: Requirements for bypassing Zeta are updated
- Pipe Hub
- Changed: Moved tower pipe connection to door in line with others
- Meat Boy Room 
-Removed: Redundant requirements for morph ball as using bombs already covers this
=> AM2R: Energy Distribution Logic

randovania/games/am2r/exporter/game_exporter.py
For some reason unknownst to me, `dotnet --help` on windows sometimes returns the error code `-2147450751` which is described as `One of the specified arguments for the operation is invalid.`
For even more stranger reasons, that error code does not appear when calling `--info`. So we'll try to call that now instead.
=> Check for dotnet --info instead of --help

randovania/games/am2r/json_data/Golden Temple.json, randovania/games/am2r/json_data/Golden Temple.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
This is part one of many, which refactors the docks in AM2R's DB.
Currently, **all** of AM2R's docks are classified as "Open Access Docks". This is fine for the current feature set, but for future features (mainly Room Rando and "Replace docks with doors") it will be required to know how high/wide docks are.
This PR adds Horizontal docks, and goes through all of them in Golden Temple.
Doing the Vertical docks will come in later PRs, as this feature is not too important right now, and i'd like to split this as much as possible for reviewability
It's worth noting, that the "dock order" is currently intentional like this, as they're approximately sorted by how often they're used.
=> AM2R: start refactoring docks in DB for GT

CHANGELOG.md, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
- Added: All Chozo-X encounters now have energy requirements.
- Changed: Added Wide Beam to missile farming during Kraid's fight.
- Changed: Fighting Kraid in Phase 2 without going up is moved from Beginner Combat to Intermediate.
- Changed: Dodging in all Chozo-X fights now have Flash Shift as trivial, Spin Boost with Beginner Combat, and nothing with Intermediate.
Energy-less tricks for Chozo-X increases in difficulty due to each tier of Chozo-X dealing more damage and being harder to fight.
=> Dread: Stricter Kraid and Chozo-X requirements

CHANGELOG.md, randovania/exporter/pickup_exporter.py, randovania/game_description/default_database.py, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime2/exporter/patch_data_factory.py, randovania/games/prime2/pickup_database/memo_data.json, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/super_metroid/exporter/patch_data_factory.py, randovania/generator/pickup_pool/pickup_creator.py, test/game_description/test_game_patches.py, test/games/am2r/exporter/test_am2r_patch_data_factory.py, test/games/prime/patcher_file_lib/test_pickup_exporter.py
This changes the `create_visual_etm` function to accept optional model_name, game and pickup_name parameters.
While I'd usually put pickup_name as the first param, AFAIK that'd mean that if one only wants to change the model name (which is much more likely), that one always has to provide `Unknown item` as the first argument.
One step forwards to seperating ETM from nothing I suppose.
Fixes #5146
=> Fix am2r and prime getting invalid ETM model

CHANGELOG.md, randovania/games/dread/json_data/Cataris.json, randovania/games/dread/json_data/Cataris.txt
Fixed: In Cataris - Kraid Area, when using Wave Beam to fight Kraid from behind, you now also need the rest of the rest of the requirements to fight Kraid.
=> Dread: Fix conditions for fighting Kraid from behind

randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py, randovania/games/am2r/layout/am2r_configuration.py, randovania/games/am2r/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_am2r_patches.ui, test/test_files/log_files/am2r/door_lock.rdvgame, test/test_files/log_files/am2r/no_ammo.rdvgame, test/test_files/log_files/am2r/starter_preset.rdvgame, test/test_files/patcher_data/am2r/door_lock.json, test/test_files/patcher_data/am2r/starter_preset.json
Community wished for it to be a seperate option instead of being encompassed by skip gameplay cutscenes
=> AM2R: Add seperate option to skip save cutscenes

CHANGELOG.md, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt
- Changed: The connection of EMMI Zone Exit Southeast and EMMI Zone Exit West is now a proper door. This enables it to now be shuffled in door lock rando.
=> Dread: Fix a Dock Type in Ghavoran

randovania/games/super_metroid/json_data/Crateria.json, randovania/games/super_metroid/json_data/Crateria.txt, randovania/games/super_metroid/json_data/Norfair.json, randovania/games/super_metroid/json_data/Norfair.txt, randovania/games/super_metroid/json_data/header.json, test/generator/test_generator_reach.py
This is nicer than listing every single pickup.
Noticed this while investigating why tests failed for #5264
=> SM: exclude beginner shinespark instead of specific items.

randovania/games/samus_returns/json_data/Area 4 - West.json, randovania/games/samus_returns/json_data/Area 4 - West.txt, randovania/games/samus_returns/json_data/Area 5 - Entrance.json, randovania/games/samus_returns/json_data/Area 6.json, randovania/games/samus_returns/json_data/Area 6.txt, randovania/games/samus_returns/json_data/Area 7.json, randovania/games/samus_returns/json_data/header.json
Some of the events were using the old room names, so I updated those. There are probably more that I missed (and likely more will exist once most of the rooms get renamed, if we even bother making them match), but these are most important right now.
I also added a separate event for the other grapple block leaving Area 6 because of the soon-to-be-supported option that removes grapple blocks, which needs to properly check for an event to remove. Not splitting the events would mean that the smaller block is also being removed which is not the case.
=> MSR: Update grapple block names in header + add new grapple event in area 6

CHANGELOG.md, randovania/generator/filler/pickup_list.py
I only tested this with ~2k seeds with am2r
Should *probably* be tested for other games, can imagine that echoes could not like this much.
=> Generator: Fix not wanting to place etanks, when damage req would be just high enough to kill player

.pre-commit-config.yaml
Ruff can generate code that black would then be not happy with.
=> Run black after ruff, use mirror for faster black

randovania/games/am2r/json_data/Golden Temple.json, randovania/games/am2r/json_data/Golden Temple.txt, randovania/games/am2r/json_data/Industrial Complex.json, randovania/games/am2r/json_data/Industrial Complex.txt, randovania/games/am2r/json_data/Main Caves.json, randovania/games/am2r/json_data/Main Caves.txt, randovania/games/am2r/json_data/The Tower.json, randovania/games/am2r/json_data/The Tower.txt
- 3-Orb Hallway Missile -> Minor
- Gamma in BG3 -> Minor
- Vanilla Supers -> Major
- Fat Crocomire Room Missile -> Minor
- Vanilla PBs -> Major
=> AM2R: Fix incorrect major/minor locations

CHANGELOG.md, randovania/games/dread/json_data/Ghavoran.json, randovania/games/dread/json_data/Ghavoran.txt, randovania/games/dread/json_data/header.json
- Changed: Going backwards through the Eyedoor now requires having first destroyed it, Flash Shift and Intermediate Movement, or being able to tank the damage.
This one is the only relevant Eyedoor these changes can apply to. The other ones would require starting in Corpius Arena, Escue Arena, and that alcove above Drogyga. The Kraid one can be bypassed completely just by going above. which you would be guaranteed to be able to do if you can get to it from reverse.
=> Dread: Ghavoran Eyedoor changes

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/GFS Thoth.json, randovania/games/am2r/json_data/GFS Thoth.txt, randovania/games/am2r/json_data/Golden Temple.json, randovania/games/am2r/json_data/Golden Temple.txt, randovania/games/am2r/json_data/Hydro Station.json, randovania/games/am2r/json_data/Hydro Station.txt, randovania/games/am2r/json_data/Industrial Complex.json, randovania/games/am2r/json_data/Industrial Complex.txt, randovania/games/am2r/json_data/Main Caves.json, randovania/games/am2r/json_data/Main Caves.txt, randovania/games/am2r/json_data/The Tower.json, randovania/games/am2r/json_data/The Tower.txt, test/test_files/patcher_data/am2r/door_lock.json, test/test_files/patcher_data/am2r/starter_preset.json
Event nodes are visible by end users in the data visualizer, and thus should be more readable instead of just throwing something together to have one word.
=> AM2R: Rename event nodes

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt
Neither resolver nor generator stacks ammo, which makes them think that you can go through the passage with only 1 Bomb. Which is not possible
=> AM2R: Workaround for a5 zeta

randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/gui/preset_settings/msr_patches_tab.py, randovania/games/samus_returns/json_data/Area 1.json, randovania/games/samus_returns/json_data/Area 1.txt, randovania/games/samus_returns/json_data/Surface - East.json, randovania/games/samus_returns/json_data/Surface - East.txt, randovania/games/samus_returns/json_data/header.json, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_patches.ui, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/patcher_data/samus_returns/starter_preset.json
- Adds new misc resources for removing certain crumble blocks as per the patcher
- Updates `starter_preset.json` and all relevant test files accordingly
- Updates logic to account for the misc resources
- Cleaned up patches tab to be more descriptive/fix bad names
=> Samus Returns - Support Crumble Block Removal Misc Resources

randovania/games/am2r/json_data/The Depths.json, randovania/games/am2r/json_data/The Depths.txt
Previously, only the way *back* was behind a trick. which lead to logic going there, and then being stuck.
Also adds some hypermode morph stuff too ig.
=> AM2R: Make *both* ways for first omega behind a trick for traversal

randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
Not quite sure whether Omegas have the best approach
Both zetas and omegas are harder with supers only than guardian (which is combat beginner)
but omegas specifically can be killed quicker if you only do backshots. I currently bumped this to advanced.
Combat in general needs to be bumped up and redone completely, likely.
=> AM2R: Make super Omegas/zetas not trickless

randovania/games/am2r/exporter/patch_data_factory.py
Community Updates uses "Monster" instead of "Metroid".
=> AM2R: Fix metroid fanfare not being shuffled.

CHANGELOG.md, randovania/games/dread/game_data.py
This PR intends to address the confusion reported in #5248.
It introduces a new entry in the Dread FAQ addressing this issue and advising to switch the language to English when playing randomized Dread.
This PR was tested by running a new GUI instance from source and assessing the changes were present.
A next but much more complex task would be ensuring the vanilla text is replaced regardless of console language
=> Dread: Add warning about custom text in FAQ

randovania/games/super_metroid/json_data/Crateria.json, randovania/games/super_metroid/json_data/Crateria.txt, randovania/games/super_metroid/json_data/header.json
Added: CWJ as its own trick.
Fixed: CWJ over The Moat
Removed: Blue Suit from Old Mother Brain item
Added: Shinespark to Terminator from Landing Site
=> SM: Make CWJ its own Trick + Minor Logic Updage

randovania/gui/preset_settings/item_pool_tab.py
This makes it possible to have ammo in the game without relying on other non-ammo items to give the same item.
Having that functionality is currently required for AM2R for items such as the flashlight/speedbooster upgrade/health drops.
This *could* be worked around, by making it an item similar to how flash shift does it:
But having them in the ammo format works more nicely.
Thinking of other games/use cases:
- Games where there's ammo with a launcher not being possible to implement and where creating one on RDVs side could lead to more confusion
- "Ammo"-Style items which would be very weird with main item. For example, Ori 2's/Hollow Knight/Paper Mario shard/charm slot upgrades, Ori 2's Life/Energy Cells, Psycron's Jump upgrades and probably more I can't think of right now.
=> Workaround for when ammo does not have other items

randovania/games/samus_returns/gui/preset_settings/__init__.py, randovania/games/samus_returns/json_data/Area 2 - Entrance.json, randovania/games/samus_returns/json_data/Area 2 - Entrance.txt, randovania/games/samus_returns/json_data/Area 2 - Exterior.json, randovania/games/samus_returns/json_data/Area 2 - Exterior.txt, randovania/games/samus_returns/json_data/Area 3 - Interior West.json, randovania/games/samus_returns/json_data/Area 3 - Interior West.txt, randovania/games/samus_returns/json_data/Area 4 - West.json, randovania/games/samus_returns/json_data/Area 4 - West.txt, randovania/games/samus_returns/json_data/Area 5 - Entrance.json, randovania/games/samus_returns/json_data/Area 5 - Entrance.txt, randovania/games/samus_returns/json_data/Area 5 - Exterior.json, randovania/games/samus_returns/json_data/Area 5 - Exterior.txt, randovania/games/samus_returns/json_data/Area 5 - Interior.json, randovania/games/samus_returns/json_data/Area 5 - Interior.txt, randovania/games/samus_returns/json_data/Area 7.json, randovania/games/samus_returns/json_data/Area 7.txt, test/test_files/log_files/samus_returns/starter_preset.rdvgame
- Adds Generation tab
- Fixes A2 Entrance Metroid not being correctly labelled as a plus variant
- Changes all plus variant Metroids to be Major locations
- Changes the two standard Omegas in A7 to be minor locations
=> Samus Returns - Major/Minor Updates

randovania/games/am2r/generator/bootstrap.py, randovania/games/am2r/presets/starter_preset.rdvpreset, test/games/am2r/layout/test_am2r_describer.py
- Super Launcher now correctly gives 2 instead of 5
- A3 blocks are enabled
- Include DoorLockRando in bootstrap
=> AM2R: Update starter preset with correct super count and a3 blocks enabled

CHANGELOG.md, randovania/gui/tracker_window.py, test/gui/test_tracker_window.py
Missing changelog and test.
Did this because of bug report in Discord.
I'm very unsure about the `raise ValueError("Preset without a starting location.")`. Do we have a better way to deal with it without spamming sentry in this case?
Should it actually be completly ignored and be fixed in the future by simply forbid to save a preset without a starting location?
=> Fix map tracker with a single non-default starting location

randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/preset_settings/msr_aeion_tab.py, randovania/games/samus_returns/json_data/header.json, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_aeion.ui, test/games/samus_returns/gui/test_msr_aeion_tab.py, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/patcher_data/samus_returns/starter_preset.json
Little bit wild:
Patcher does everything from Lua but has parent classes and assumes that the first item is the important main item.
Non required mains works in randovania by just adding the main item to each ammo/tank item.
=> Had to prepend the main item to the ammo in that case.
I introduced an `item_export_id` because we need different items in starting inventory and in the pickups. E.g. we need to use `ITEM_WEAPON_POWER_BOMB_MAX` in starting inventory but `ITEM_POWER_BOMB_TANK` in pickups.
The game has implicit main item, which means as soon as you have a `ITEM_WEAPON_POWER_BOMB_MAX` you have the main item => patcher locks them by using  `ITEM_POWER_BOMB_TANK` in pickups.
Please never add an option to start with ammo without the main item :)
=> Sync export with MSR patcher

CHANGELOG.md, randovania/games/dread/json_data/Artaria.json, randovania/games/dread/json_data/Artaria.txt
- Changed: The item above Proto EMMI now requires Speed Booster Conservation set to Beginner when reaching it with Speed from the top.
=> Dread: Proto EMMI Item Shinespark

.github/dependabot.yml
With merge queue this should be bearable.
=> Allow up to 5 dependabot PRs

randovania/gui/preset_settings/item_pool_tab.py
AM2R "needs" (as in, I dont want to provide worse UX) ammo currently in their own category, so here's this little hack.
Hopefully very very temporary, as dunc is working on refactoring hint category from the UI category. Dunno how far away that is tho, and wanted this in the the meantime
This PR fixes the crash that would happen when having a UI category with only ammo:
=> Allow ammo to be standalone in their category

.github/workflows/build-test-publish.yml, randovania.spec, randovania/__main__.py, randovania/data/dotnet_runtime/.gitignore, tools/create_release.py
This PR adds dotnet to portable releases. This was mostly done to stop AM2R from crashing on exporting, but will be useful for planets later down the line as well.
Shale tested this on Windows where it worked, I tested this on Linux where it also worked. So far, no one has tested this on macOS yet. I also need to test whether this works in flatpak later.
=> Add dotnet to portable installations

randovania/__main__.py
when running from source, the directory does exist, but i dont want developers to properly populate it; it should just use the system provided one
=> Fix dotnet_root for source builds

randovania/resolver/resolver.py
If there's a list of damage requirements and all of them are satisfied individually, but the list as a whole is unsatisfied, we need want to add them to the additional requirements.
=> Resolver: Fix adding additional requirement on list of damage requirements

randovania/__main__.py
After more rigorous testing, seems like this env var fixes stuff if you have multiple dotnet runtimes installed. those being over dotnet6 may or may not have some factor there.
=> Fix edge case with multiple dotnet runtimes

CHANGELOG.md, randovania/generator/generator.py, test/generator/test_generator.py
Fixes #5545.
I could've sworn this check existed. Looked into doing a GUI lock, but though how annoying it'd be to need to change the values in the correct order, so would need improved UX which is... lot of work. So not doing anything!
=> Detect when minimum starting pickups is more than maximum

CHANGELOG.md, randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt
- Changed: Using Speed Booster to reach the pickup in EMMI Zone First Entrance now requires either the EMMI defeated or Speed Booster Conservation set to Beginner.
=> Dread: Artaria EMMI Zone First Entrance logic change

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt
Spider ball room:
- Video for clipping out of bounds and getting both items with out of bounds movement.
- Video of clipping back out of bounds and single wall jumping back up to the top of the room and back in bounds.
Central Shaft:
- Change the trick requires for right side climb without spider/bombs.
- add left side climb with video for SWJ and UE.
Shaft East:
- Add video for SWJ.
=>  Area 1 logic updates and videos

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt
Spazer beam door inner room, updated to not have Simple IBJ be possibly required due to the crumble blocks at the bottom
=> Area 1 logic update

randovania/games/samus_returns/logic_database/Area 2 - Entrance.json, randovania/games/samus_returns/logic_database/Area 2 - Entrance.txt, randovania/games/samus_returns/logic_database/Area 2 - Exterior.json, randovania/games/samus_returns/logic_database/Area 2 - Exterior.txt, randovania/games/samus_returns/logic_database/Area 2 - Interior.json, randovania/games/samus_returns/logic_database/Area 2 - Interior.txt
Area 2 - entrance:
- Add logic for getting from lightning armor room to top with movement and taking damage.
Area 2 - Exterior:
- Update a check to be checking for ability to use spider ball instead of just having spider ball.
- Add trick with video to grapple gap.
Area 2 - Interior:
- Update main hub? requirements for getting to the top door to not be a bunch of and's stuck together when it should be OR.
=> Area 2 logic updates

randovania/games/samus_returns/logic_database/Area 3 - Exterior.json, randovania/games/samus_returns/logic_database/Area 3 - Exterior.txt, randovania/games/samus_returns/logic_database/Area 3 - Interior East.json, randovania/games/samus_returns/logic_database/Area 3 - Interior East.txt, randovania/games/samus_returns/logic_database/Area 3 - Interior West.json, randovania/games/samus_returns/logic_database/Area 3 - Interior West.txt
Area 3 - Exterior:
- Transport to Area 2 Entrance, seal -> Entrance hub door make trivial
- Transport to Area 3 interior west (upper), Ammo Recarge -> Outer hub access add logic for getting past / destroying the turret.
- Outer Hub, Change spider sparks to be beginner tricks, add spider ball for trickless of climbing further.
Area 3 - Interior (east):
- Gamma awakening access, change movement req to spiderball trick. Add HJ for the unmorph extend to getting to supermissile door.
- Fiery Path, change climb vertical no high jump to be Simple IBJ or Spiderspark.
Area 3 - interior (west):
- Transport to Area 3 exterior (upper), update logic for spiderspark trick and raise underwater bomb jump out of gravity suit check layer.
Miscellaneous changes for can spiderspark to being an AND of can …
=>  Area 3 logic updates

CHANGELOG.md, randovania/games/dread/logic_database/Ghavoran.json, randovania/games/dread/logic_database/Ghavoran.txt
- Changed: Golzuna logic has been overhauled to include Storm Missiles, Bombs, or Cross Bombs to fight it and forcing Flash Shift, Spin Boost, or Space Jump to dodge its attacks.
=> Dread: Golzuna logic update

CHANGELOG.md, randovania/games/dread/layout/preset_describer.py, test/games/dread/layout/test_dread_describer.py
- Added: Power Bomb Limitations now shows up on the Preset Summary when enabled.
=> Dread: Add Power Bomb Limitations to Preset Summary

CHANGELOG.md
I forgot to update the changelog in #5580, whoops. As this is a change to a stable game, this is probably required.
=> Prime: Update CHANGELOG.md of previous broad-category missile launcher PR

randovania/gui/ui_files/preset_patcher_energy.ui
Makes sure that the marked text labels are wrapping now.
=> Use wordwrap for prime/echoes energy labels

randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/generator/pool_creator.py, randovania/games/samus_returns/gui/preset_settings/msr_goal_tab.py, randovania/gui/ui_files/preset_msr_goal.ui, test/games/samus_returns/generator/test_msr_bootstrap.py, test/games/samus_returns/gui/preset_settings/test_msr_goal_tab.py
I added the Diggernaut Chase Sequence reward (vanilla Space Jump) as a boss location to add more value to the boss goal. It fits since Diggernaut is a boss, so the chase, although removed, could be considered a "boss" or something equivalent in importance. A neat side effect of this is now every even area has a boss check (2, 4, 6, 8). This is also more relevant now since the area has be relocked by Charge, so it's less "free" to access.
=> MSR - Add Diggernaut Chase Sequence reward as boss location

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Area 2 - Entrance.json, randovania/games/samus_returns/logic_database/Area 2 - Entrance.txt, randovania/games/samus_returns/logic_database/Area 2 - Exterior.json, randovania/games/samus_returns/logic_database/Area 2 - Exterior.txt, randovania/games/samus_returns/logic_database/Area 2 - Interior.json, randovania/games/samus_returns/logic_database/Area 2 - Interior.txt, randovania/games/samus_returns/logic_database/Area 3 - Exterior.json, randovania/games/samus_returns/logic_database/Area 3 - Exterior.txt, randovania/games/samus_returns/logic_database/Area 3 - Interior East.json, randovania/games/samus_returns/logic_database/Area 3 - Interior East.txt, randovania/games/samus_returns/logic_database/Area 3 - Interior West.json, randovania/games/samus_returns/logic_database/Area 3 - Interior West.txt, randovania/games/samus_returns/logic_database/Area 4 - East.json, randovania/games/samus_returns/logic_database/Area 4 - East.txt, randovania/games/samus_returns/logic_database/Area 4 - West.json, randovania/games/samus_returns/logic_database/Area 4 - West.txt
Fixes the connections to the teleporters in Areas 1-4 to not require the event of unlocking them to access the node itself
=> MSR - Teleporter updates A1-A4

CHANGELOG.md, randovania/games/dread/logic_database/Burenia.json, randovania/games/dread/logic_database/Burenia.txt
The "Flash-only" trick to get the item in the Burenia fan requires the player to Flash Shift quickly twice to the left. The logic didn't have a Flash Shift Upgrade in the requirements, so a seed could end up being unsolvable if the player was not given enough upgrades.
=> Fix Burenia fan item logic

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Area 4 - East.json, randovania/games/samus_returns/logic_database/Area 4 - East.txt, randovania/games/samus_returns/logic_database/Surface - West.json, randovania/games/samus_returns/logic_database/Surface - West.txt
- Adds a Space Jump method and an Ice Beam method to collect the Transport to Area 8 Missile Tank in Surface - West.
- For the same item as above, IBJ now requires Spider Ball to collect the item since the Baby will not destroy the blocks otherwise.
- In Area 1's Central Shaft, adds two different High Jump methods to climb to the top, and one with only Phase Drift.
- Adds Power Bombs as an alternative to Wave for Area 4 - East's Main Shaft bottom Super Missile Tank.
=> Surface, Area 1, and Area 4 logic additions

randovania/data/gui_assets/tracker/prime1-pixel-tournament.json, randovania/data/gui_assets/tracker/prime2-pixel-tournament.json, randovania/data/gui_assets/tracker/trackers.json, randovania/gui/widgets/item_tracker_widget.py
Gives the key/artifact labels big numbers to make them easier to see on tournament restreams.
This is achieved by allowing tracker layouts to define stylesheets for labels.
=> Add tournament layouts to the auto-tracker for Prime and Echoes

CHANGELOG.md, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt
- Added: In Treadmill Room: Going from right to left is now possible via a beginner Shinespark or an intermediate Morph Glide.
- Fixed: In Shirk Prisons: Going from right to left, now requires Morph Ball, or 4 (Super) Missiles.
- Fixed: In Treadmill Room: Going from right to left via Movement is now impossible.
=> AM2R: slight logic adjustments for 2 a3 rooms

CHANGELOG.md, randovania/games/am2r/generator/base_patches_factory.py, randovania/games/am2r/gui/preset_settings/am2r_patches_tab.py, randovania/games/am2r/layout/am2r_configuration.py, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, randovania/gui/ui_files/preset_am2r_patches.ui, randovania/layout/preset_migration.py, test/games/am2r/generator/test_am2r_base_patches.py
Planning to later also do another configuration change for am2r (exclude certain doors in labs from being shuffled), not sure how i should handle preset migrations there. Should I just stuff the next thing also into v70? or should i make a v71 for it?
=> AM2R: Add Unlocked save station option.

randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
#5776 forgot to change the change_from/change_to fields.
This fixes it. No changelog entry needed, as it's already there.
=> AM2R: fix research site not being shuffleable

randovania/games/am2r/exporter/patch_data_factory.py
Makes the starting text wrap in AM2R. No changelog entry needed, as the starting memo feature was introduced in dev builds after the last stable release.
Before:
After:
=> AM2R: Wrap starting memo text

CHANGELOG.md, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt
Activating the EMP Slot incorrectly checked for Missile Launchers instead of Missiles
=> AM2R - Fix A2 EMP Slot Requirements

randovania/exporter/hints/credits_spoiler.py, randovania/games/am2r/exporter/hint_namer.py, randovania/games/am2r/exporter/patch_data_factory.py
~~Wanted to at least open this PR. Depending on how much effort it is to change generic_credits (should hopefully:tm: just be a signature change?), I might do that later.~~
Hacky way gotten rid of.
Some games (i.e. AM2R) do not support color. In order to avoid writing a whole new credits function, I just added a param to let it not use color.
Needed as part of AM2R MW.
=> AM2R: Add option for generic credits to not have players in colors

randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/dread/generator/pool_creator.py, randovania/games/dread/pickup_database/pickup-database.json, randovania/games/prime1/pickup_database/pickup-database.json, randovania/games/prime2/pickup_database/pickup-database.json
I know that Dread DNA cant be placed offworld right now. But thanatos has expressed interest in a feature for that, so I'm just planning ahead for when such a feature will eventually be implemented.
=> Add more am2r offworld models

CHANGELOG.md, randovania/gui/game_details/pickup_details_tab.py
Before:
After:
Shouldn't cause any performance loss hopefully, as i'm pretty sure that setFixedString was also using a regex in the background.
=> Fix pickup filtering for items that start the same

CHANGELOG.md, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt
- Fixed: In Surface Hi-Jump Challenge: Now correctly uses normal damage vs lava damage for damage boost.
- Fixed: In Drivel Drive: Intended Ballspark now requires Gravity.
- Changed: In Drivel Drive: Bumped mockball method to Expert.
=> AM2R: Main Caves logic updates

randovania/gui/lib/qt_network_client.py, test/gui/lib/test_qt_network_client.py
Hopefully fixes #5843 
But this didn't get any public testing yet. It didn't regress for me locally at least, so there's that.
Dunno if we should get testing now and don't merge on issues, or merge first then get testing and then revert if we have any.
=> Use qdesktopservices instead of webbrowser

randovania/games/am2r/pickup_database/text_data.json, test/test_files/patcher_data/am2r/progressive_items.json, test/test_files/patcher_data/am2r/starting_items.json
IDK if it's actually clearer now. Sure hope so tho.
Could look weird with negatives, aka `Missiles refilled by -10`.
Fixes https://github.com/randovania/YAMS/issues/138
=> Make drop descriptions clearer

randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt
These seem to cause some issues with the resolver.
The `After Area 5 - Distribution Center Item at Ice location Collected` can be safely removed, because that's already implied by *going* to this node.
The `Before Boss - Serris Defeated` can be safely removed, because if serris is defated, it would by default just choose the other paths. It also doesnt really matter whether we visit this event multiple times or not.
=> AM2R: Clean up path requirements to go to Serris

CHANGELOG.md, randovania/gui/lib/tracker_item_image.py
Looks like normally the tooltips in general usually use their native theming. Hyperbola forced the foreground color to black to have better contrast/accessibility, but for systems where the default tooltip background is dark, this made things much worse.
I couldve either made an OS check and only styled the foreground color on windows, or i just force a custom tooltip everywhere. Opted for the latter.
Before:
After:
=> Fix auto tracker tooltip for non Windows

CHANGELOG.md, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/generator/pickup_pool/artifacts.py, randovania/games/prime1/generator/pickup_pool/pool_creator.py, randovania/games/prime1/gui/preset_settings/prime_goal_tab.py, randovania/games/prime1/layout/prime_configuration.py, randovania/gui/ui_files/preset_prime_goal.ui, randovania/layout/preset_migration.py, test/games/prime1/layout/test_prime_configuration.py, test/test_files/patcher_data/prime1/all_game_multi/world_2.json, test/test_files/patcher_data/prime1/all_game_multi/world_6.json, test/test_files/randomprime_expected_data.json, test/test_files/randomprime_expected_data_crazy.json, test/test_files/randomprime_expected_data_one_way_door.json
This seperates the total amount of artifacts and required artifacts, so the player is able to choose for which artifacts they route for. 
For example, you can have 7 total artifacts, but 3 required. You are able to get hints for all 7 artifacts, but only 3 are needed to reach Impact crater. 
Logic assumes that have you to collect all 7 artifacts tho, in order to ensure that all 7 artifacts are reachable and the player is thus *always* able to choose which artifacts they go for, and not *forced* to go for specific ones.
Fix #3323
=> Prime 1: Introduce a seperate required amount of artifacts

requirements.txt
No changelog entry needed, as it's still MW fixes.
Apparently i somehow reverted an important commit in the patcher right before the 1.2.3 release. whoops.
=> Bump am2r yams to 1.2.4

randovania/gui/docks/resource_database_editor.py
I thought about display a warning popup with `Entry already exists!`, but then i'd need to figure how to properly await that function without making the setData function async.
Thus i lowered my expectations until they were fully met.
Also apparently the whole DB editor just doesnt have any tests at all????
Fixes #4506
=> Don't try to add duplicate entries to DB editor

CHANGELOG.md, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/gui/dialog/dread_cosmetic_patches_dialog.py, randovania/games/dread/layout/dread_cosmetic_patches.py, randovania/gui/ui_files/dread_cosmetic_patches_dialog.ui, randovania/interface_common/persisted_options.py, test/games/dread/gui/test_dread_cosmetic_patches_dialog.py, test/test_files/patcher_data/dread/all_game_multi/world_4.json, test/test_files/patcher_data/dread/all_game_multi/world_8.json, test/test_files/patcher_data/dread/crazy_settings.json, test/test_files/patcher_data/dread/custom_start.json, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json, test/test_files/patcher_data/dread/elevator_rando.json, test/test_files/patcher_data/dread/starter_preset.json
Adds volume sliders to the cosmetic options for music (`fMusicVolume`) , SFX (`fSfxVolume`) and background ambience (`fEnvironmentStreamsVolume`)
Fixes #5247
=> Dread: Implement cosmetic option for volume sliders

CHANGELOG.md, randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt, randovania/games/dread/logic_database/Cataris.json, randovania/games/dread/logic_database/Cataris.txt, randovania/games/dread/logic_database/Dairon.json, randovania/games/dread/logic_database/Dairon.txt, randovania/games/dread/logic_database/header.json, randovania/games/dread/logic_database/header.txt
We have learned that pushing Wide Beam Blocks with Plasma or Wave, without Wide is possible, and at the time we thought it made sense to do so with Wave, from an angle. However, based on our current understanding, this should be considered a bug in the implementation of split beams.
=> Dread: Remove pushing Wide Beam Blocks with Wave and no Wide

CHANGELOG.md, randovania/gui/preset_settings/location_pool_tab.py
CS was the only thing that used this.
Addresses part of #5926
=> Fix locations with nested brackets not showing correctly.

randovania/games/prime3/logic_database/Bryyo - Fire.json, randovania/games/prime3/logic_database/Bryyo - Fire.txt, randovania/games/prime3/logic_database/header.json
Collecting the Pickup in the Fuel Gel will cause the elevator to become active again. The elevator will instantly kill Rundas when he makes contact. RE: https://discord.com/channels/458432177223368704/758832290838216704/1201387901674590332
Bumped combat logic for Screw-Only method from intermediate to advanced.
=> MP3: Add Rundas Quick-Kill + Other Fight Logic

randovania/games/samus_returns/logic_database/Area 5 - Tower Exterior.json, randovania/games/samus_returns/logic_database/Area 5 - Tower Exterior.txt
Fixes a database error where there was no connection from `Dangerous Hallway` to the right side of the Tower, which forced logic to always enter the Tower from the right elevator and prevented it from going backwards.
=> MSR - Fix one-way logic loop in Area 5 Tower

randovania/game_connection/connector/am2r_remote_connector.py
`itemroom` is a room where you get teleported to, during an item acquisition cutscene. Since this is still in-game, the connector shouldn't think that the player went to the title screen for the 1-2seconds.
=> AM2R: In MW, dont set item room to title screen

randovania/generator/filler/runner.py
It's already hidden in the UI, but too many people like looking at the file and being confused.
No change log entry being for me the rdvgame format is an internal detail.
=> Remove the generator log internally if it should be hidden

randovania/games/samus_returns/logic_database/Area 6.json, randovania/games/samus_returns/logic_database/Area 6.txt
Wrong event was being used to leave the elevator node in A6 to A7
=> MSR - Fix A6 Elevator Logic

randovania/game_connection/executor/am2r_executor.py, randovania/game_connection/executor/common_socket_holder.py, randovania/game_connection/executor/cs_executor.py, randovania/game_connection/executor/dread_executor.py, randovania/game_connection/executor/nintendont_executor.py, test/game_connection/executor/test_cs_executor.py
Fixes #5887 
Apparently almost every executor was affected, not just dread and am2r.
=> MW: refactor executors to use a common socket holder

CHANGELOG.md, randovania/generator/base_patches_factory.py, test/generator/filler/test_pickup_list.py, test/generator/test_base_patches_factory.py, test/generator/test_generator_reach.py
Fixes #5861 
Not sure if the base patches factory is the right place for it tbh. I just searched where the error message for starting locations was, and put it there.
=> Show warning before genning, if item pool is more than max items.

randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.json, randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.txt
Requiring anything other than grapple to leave out the top tunnel is pointless as you need grapple to even go that way
=> MSR - Remove unnecessary reqs from A3 MC Ascending Alleyway

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Surface - East.json, randovania/games/samus_returns/logic_database/Surface - East.txt, test/test_files/log_files/samus_returns/start_inventory.rdvgame, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/log_files/samus_returns/vanilla_game.rdvgame
- fix tank being named expansion
- fix aeion tank being named missile tank
- adds a test rdvgame with vanilla locations. does have progressives turned on tho.
=> MSR: fix name of pickups, add vanilla test

CHANGELOG.md, pyproject.toml, randovania/gui/lib/qt_network_client.py, randovania/gui/lib/wait_dialog.py, randovania/network_client/network_client.py, test/network_client/test_network_client.py
Fixes connection error being considered a critical error when triggered from world sync. Prevents these errors from being sent to Sentry.
=> Improve handling of errors when connecting to server

randovania/games/samus_returns/logic_database/Area 5 - Tower Exterior.json, randovania/games/samus_returns/logic_database/Area 5 - Tower Exterior.txt, randovania/gui/ui_files/games_tab_samusreturns_widget.ui, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
- Updated Differences tab to mentioned Scan Pulse don't use Aeion + rearranging other entries
- Updated Hints tab to mention the Hatchling Room DNA Seal is disabled until after the Queen
- Fixed wrong cc being used in A5 Tower Exterior Gamma Arena
=> MSR - Bug Fix and UI Updates

CHANGELOG.md, randovania/gui/preset_settings/item_pool_tab.py, randovania/gui/preset_settings/standard_pickup_widget.py, test/gui/dialog/test_item_configuration_popup.py
For example, Power Bombs in Echoes and Life Capsules for Cave Story.
=> Fix StandardPickupWidget for entries where shuffle count don't match progressive count.

randovania/cli/commands/new_game.py, randovania/game_description/pickup/migrations.py, randovania/game_description/pickup/standard_pickup.py, randovania/games/am2r/layout/preset_describer.py, randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/blank/pickup_database/pickup-database.json, randovania/games/cave_story/layout/preset_describer.py, randovania/games/cave_story/pickup_database/pickup-database.json, randovania/games/dread/layout/preset_describer.py, randovania/games/dread/pickup_database/pickup-database.json, randovania/games/prime1/pickup_database/pickup-database.json, randovania/games/prime2/layout/preset_describer.py, randovania/games/prime2/pickup_database/pickup-database.json, randovania/games/prime3/layout/preset_describer.py, randovania/games/prime3/pickup_database/pickup-database.json, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/pickup_database/pickup-database.json, randovania/games/super_metroid/pickup_database/pickup-database.json, randovania/gui/preset_settings/standard_pickup_widget.py, randovania/layout/base/standard_pickup_state.py, randovania/layout/preset_describer.py, test/games/dread/layout/test_dread_describer.py, test/games/prime2/layout/test_echoes_preset_describer.py, test/games/samus_returns/layout/test_msr_describer.py, test/generator/pickup_pool/test_pickup_creator.py, test/gui/dialog/test_item_configuration_popup.py, test/layout/test_standard_pickup_state.py
Fixes setting a pickup as starting effectively setting it as excluded.
I think the way this works now finally makes sense.
=> Improve how custom shuffled/starting count works

randovania/games/samus_returns/exporter/patch_data_factory.py, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
The custom seal in Surface - West now functions properly, so adding it into the DNA mix. This brings the total hint seals to 20: 10 Item, 10 DNA.
I made it hint 1 DNA since it can be accessed early on with the Baby. So now the DNA amounts are the following:
Surface (East/West): 1
Area 1: 4
Area 2: 5
Area 3: 6
Area 4: 4
Area 5: 5 (from 6)
Area 6: 3, 3
Area 7: 3
Area 8: 5
Alternatively, I can remove one from Area 4 and put it back on Area 5.
Merge after OSRR is updated.
=> MSR - Rebalance hints to accommodate new seal

randovania/game_description/db/node_provider.py, randovania/game_description/db/region_list.py, randovania/game_description/db/teleporter_network_node.py
One MSR seed went from 13.889s generation time to 8.492s.
No changelog because no stable games use network nodes.
=> Cache the list of TeleporterNetworkNode in a network

randovania/games/fusion/generator/bootstrap.py, randovania/games/fusion/generator/pool_creator.py, randovania/games/fusion/gui/preset_settings/__init__.py, randovania/games/fusion/gui/preset_settings/fusion_goal_tab.py, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt, randovania/games/fusion/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_fusion_goal.ui, test/conftest.py, test/games/fusion/conftest.py, test/games/fusion/generator/test_fusion_bootstrap.py, test/games/fusion/generator/test_fusion_pool_creator.py, test/games/fusion/gui/preset_settings/test_preset_fusion_goal.py, test/games/fusion/test_fusion.py
Adds the goal of collecting infant/baby metroids. Configurable on bosses or anywhere. Add associated tests.
Also adds basic testing for DB.
=> Add Metroid Goal to Fusion

randovania/cli/commands/benchmark.py, test/cli/commands/test_benchmark.py
```
Difference | Fixes | Failures |     Mean |    Stdev |   Median
Blank Development Game |     0 |       16 |   -0.003 |    0.006 |   -0.001
Metroid Prime |     0 |      100 |    0.000 |    0.000 |    0.000
Metroid Prime 2: Echoes |     0 |       97 |    0.000 |    0.000 |    0.000
Metroid Prime 3: Corruption |     0 |       98 |    0.000 |    0.000 |    0.000
Super Metroid |     0 |       97 |    0.000 |    0.000 |    0.000
Metroid Dread |     0 |      100 |    0.000 |    0.000 |    0.000
Metroid: Samus Returns |     0 |      100 |    0.000 |    0.000 |    0.000
Cave Story |     0 |      100 |    0.000 |    0.000 |    0.000
Another Metroid 2 Remake |     0 |      100 |    0.000 |    0.000 |    0.000
Metroid Fusion |     0 |       92 |    0.000 |    0.000 |    0.000
```
instead of a …
=> Improve readability of benchmark reports

randovania/games/fusion/game_data.py, randovania/games/fusion/gui/dialog/cosmetic_patches_dialog.py, randovania/games/fusion/layout/fusion_cosmetic_patches.py, randovania/gui/ui_files/fusion_cosmetic_patches_dialog.ui, test/games/fusion/gui/test_fusion_cosmetic_patches_dialog.py
Adds basic palette randomizer options to cosmetics.
Room for future growth with hue_min, hue_max, symmetric options but is beyond the scope of this PR.
=> Fusion: Add palette randomizer

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
Per request in fusion-dev channel https://discord.com/channels/914291389293027329/1215675687936196608/1216805632905052310
Route all two-way recharge rooms through the recharge node to ensure it is used for energy requirements
=> Fusion: All areas: route recharge rooms through the recharge pad node

randovania/games/fusion/gui/dialog/cosmetic_patches_dialog.py, randovania/games/fusion/layout/fusion_cosmetic_patches.py, randovania/gui/ui_files/fusion_cosmetic_patches_dialog.ui, test/games/fusion/gui/test_fusion_cosmetic_patches_dialog.py
Adds the following audio options:
=> Fusion: add audio options to cosmetics

randovania/games/fusion/generator/pool_creator.py, randovania/games/fusion/gui/preset_settings/fusion_goal_tab.py, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_fusion_goal.ui, test/games/fusion/generator/test_fusion_bootstrap.py, test/games/fusion/generator/test_fusion_pool_creator.py, test/games/fusion/gui/preset_settings/test_preset_fusion_goal.py, test/games/fusion/layout/test_fusion_configuration.py
Add option to control number of required metroids vs placed.
UI updates so required can never be higher than placed.
=> Fusion: Add required and placed metroids to goal

CHANGELOG.md, requirements.txt
Fixed: Hitting Zetas with Charge Beam works again.
=> bump yams to 1.2.15

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt
Added a SWJ & Jump Extend method for Pyrochamber Access
Added SWJ for Level 1 Security Room
Added beginner wall jump requirement for getting back up to the door in Zazabi Speedway, as well as a beginner shinespark trick
Added SWJ template to Zazabi arena -> zazabi speedway
added shinespark tricks to level 1 Security Room to reach the door, and zazabi arena to cross without hi jump
Removed the TODO in Main Boiler as the room is not heated
=> FUSION: clear some todo's in TRO and PYR

randovania/games/fusion/generator/bootstrap.py, randovania/games/fusion/gui/preset_settings/__init__.py, randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
add DLR tab
add locked hatches
fix missing/incorrect room ids
remove many unnecessary `not DLR` checks and add some hatch requirements where it is necessary
fix some minor template usage in zebesians waters and security shaft west in s5
=> Fusion: DLR gui and db updates

randovania/games/dread/logic_database/Ferenia.json, randovania/games/dread/logic_database/Ferenia.txt, randovania/games/dread/logic_database/Hanubia.json, randovania/games/dread/logic_database/Hanubia.txt
This is intended to be used for plandos only, as targets for either starting location or transport destination. Affects the following rooms:
- Ferenia - Central Unit Access (using `SP_Checkpoint_CentralUnit`)
- Hanubia - Escape Room 1
- Hanubia - Escape Room 2
- Hanubia - Escape Room 3
- Hanubia - Raven Beak X Arena (using `SP_Checkpoint_Escape`)
- Hanubia - Ship Room (using `SP_Checkpoint_Endgame`)
Note: On initial spawn, the Ship Room spawn point will disable pressing Start/Select until reloading to checkpoint, and leaving the room will cause the screen to go black until an area transition. This is a vanilla bug with this room and unavoidable to my knowledge.
=> Dread: Add spawn point nodes to rooms without any

CHANGELOG.md, randovania/games/dread/generator/bootstrap.py
Fix for https://discord.com/channels/914291389293027329/1220476257557545011
Bug TL;DR: E.g.: Use 11 DNA, set Phantom Cloak to vanilla. bootstrapping can decide to also place DNA on Corpius. Game cannot be generated because you can not leave Corpius. Add Door lock to it such that Sensor lock doors gets removed => Can be generated  + exported and played. but importing the rdvgame leads to an error.
(If this is OK, I add the same fix to other games).
=> Remove pre-placed indices from DNA locations

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/header.json
Per request in fusion-dev: https://discord.com/channels/914291389293027329/1215675687936196608/1216880163917271111
The bomb block in Data Hub is permanently gone once destroyed, so this should be reflected in logic as an event.
=> Fusion: S2: Data Hub: Create event for bomb block

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/header.json
Short names changed to avoid future confusion:
S1MissileBlock -> S1Charge
S1ShotBlock -> S1SaveShotBlock
S2BombBlock -> S2DHubBombBlock
=> Fusion: safety rename of destructible block events

CHANGELOG.md, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt
If the Water Turbine is shuffled to any of these doors, there will be water when getting to the door from the front, thus rendering it impossible to enter them. 
The water will lower when entering them from behind, but logic doesn't guarantee this.
=> AM2R: Fix door lock rando bug with a2 exterior

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt
Rationale behind this one, is that if something causes enemies to not be freezable here, that we can more easily disable it.
This doesn't have any logical consequences for now.
=> Fusion: explicitly use freezing template as well for screw shaft

CHANGELOG.md, randovania/resolver/resolver.py, randovania/resolver/resolver_reach.py
Fix issue where required items are skipped because they aren't interesting yet, and never gotten back to because we don't have a good way to indicate that we should go back for it.
=> Resolver: Remove filter on interesting resources

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/logic_database/header.json
- Added a cold damage category in the resource database
- NOC: Nocturnal Playground - Clogged Cavern -> Nocturnal Shaft now has added requirements since you will have to dodge blue X
- PYR: Removed todo message in Deserted Runway that was already finished
- TRO: Added Jaggers trick videos for the Security Room shinesparks
- AQA: Moved the nodes in Pump Control Unit for better readability, this room will get a overhaul in the future to account for the shinespark.
=> MF: clear todos

pyproject.toml, randovania/exporter/patch_data_factory.py, randovania/game_description/game_patches.py, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/blank/exporter/patch_data_factory.py, randovania/games/cave_story/exporter/patch_data_factory.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime2/exporter/patch_data_factory.py, randovania/games/prime3/exporter/patch_data_factory.py, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/super_metroid/exporter/patch_data_factory.py, randovania/layout/game_patches_serializer.py, requirements.txt, test/games/test_log_file_export.py, test/test_files/log_files/dread/custom_patcher_data.rdvgame, test/test_files/patcher_data/dread/dread/custom_patcher_data/world_1.json
- Game specific PDFs now override `create_game_specific_data`, which is then invoked by the common PDF
- Adds a `custom_patcher_data` field to GamePatches
- Adds a package requirement for `json-delta`
Conflicts with #6250. Unsure if PDF changes conflict with others.
=> Add field in rdvgames that overrides Patch Data Factory output

randovania/games/samus_returns/exporter/joke_hints.py
Currently this causes the text to be two hints. THis PR fixes it to be one hint.
=> MSR: fix spider boost hint

randovania/gui/ui_files/msr_game_export_dialog.ui
tooltip is completely unnecessary and slightly confusing.
=> MSR: remove export tooltip

CHANGELOG.md, randovania/gui/tracker_window.py
IDK why there supposed to be hidden in the first place. This now makes the `Map` view much more user friendly
=> Map Tracker: always show accessible nodes

randovania/gui/ui_files/trick_details_popup.ui
Allows the Trick Details window to be resized freely instead of being height limited.
Fixes https://discord.com/channels/914291389293027329/914294217256362024/1214968506714685530
=> Update trick_details_popup.ui to allow Trick Details window to be resized freely

test/games/prime/patcher_file_lib/test_item_hints.py
Done by simply not monkeypatching the echoes database and use it as-is.
=> Don't make echoes hint tests fail when run in reverse

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
tanking a hit from the kago is now gated behind `Damage Boosts (Beginner)`
also tweaked the movements requirements for jumping over the kago without getting hit
=> Kago Room rework

.github/workflows/build-test-publish.yml, randovania/exporter/game_exporter.py, randovania/interface_common/generator_frontend.py, randovania/monitoring/__init__.py, tools/create_release.py
This means sentry is only initialized in builds provided via our CI, and the official server
---
I'm not worried about these values being secret, but I do want to stop reports from people who make their own executables.
=> Get sentry url from configuration

randovania/games/cave_story/logic_database/Grasstown.json, randovania/games/cave_story/logic_database/Grasstown.txt, randovania/games/cave_story/logic_database/Last Cave.json, randovania/games/cave_story/logic_database/Last Cave.txt, randovania/games/cave_story/logic_database/Plantation.json, randovania/games/cave_story/logic_database/Plantation.txt, randovania/games/cave_story/logic_database/Ruined Egg Corridor.json, randovania/games/cave_story/logic_database/Ruined Egg Corridor.txt, randovania/games/cave_story/logic_database/Sand Zone.json, randovania/games/cave_story/logic_database/Sand Zone.txt, randovania/games/cave_story/logic_database/header.json
This increases documentation from 55% to 87%, if I've done my math correctly. Of the remaining undocumented tricks, one is a very easy damage boost, a handful are gravity hops (which I'll want vids with input display for), and the rest are pacifist strats that need videos showing a successful attempt
=> Improve Cave Story documentation

CHANGELOG.md, randovania/games/dread/exporter/game_exporter.py, randovania/games/dread/exporter/options.py, randovania/games/dread/gui/dialog/game_export_dialog.py, randovania/gui/ui_files/dread_game_export_dialog.ui, randovania/interface_common/persisted_options.py, test/games/dread/gui/test_dread_game_export_dialog.py
Flatpak (default):
Native:
I have not tested this on anything other than Linux
Fixes #5293
=> Dread: Add ryujinx export to linux and macos

CHANGELOG.md, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt
Fixes #4806 
The connection in Mining Station B to Transit Station with just Bombs was missing Boost Ball as well as Standable Terrain. It's was probably forgotten about when the path was added.
Also shortens the video links on that one connection. I could have fixed the others but the whole DB needs fixing, so I left it.
=> Echoes - Add missing requirements to MSB connection

randovania/monitoring/__init__.py
This should hopefully fix usernames leaking into sentry sometimes.
I have no idea if this needs a changelog entry.
Event in action: https://randovania.sentry.io/issues/5294468965/events/e6144169a00f4b8c945e7e508a567996/
=> Scrub breadcrumbs from home username

randovania/gui/ui_files/fusion_game_export_dialog.ui
The accept buttons starts exporting which errors due to not implemented.
So we just remove the accept button.
=> Fusion: remove export accept button

randovania/games/cave_story/exporter/game_exporter.py, randovania/games/dread/exporter/game_exporter.py, randovania/games/prime1/exporter/game_exporter.py, randovania/games/samus_returns/exporter/game_exporter.py, randovania/gui/main_window.py, randovania/interface_common/generator_frontend.py, randovania/monitoring/__init__.py
I don't think this needs a changelog entry
tldr: 
- track how long it takes to open a game page
- track noteworthy settings for exporters
- track the CPU arch. 
- track a few more generation settings
=> Sentry: add more tags

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 4 Central Caves.json, randovania/games/samus_returns/logic_database/Area 4 Central Caves.txt
Dunno if this goes to `Logic database` section in the changelog.
Logically it is fine to start anywhere but at the same time it's just wrong to start in a door and it fails during patch time not generaton time.
=> Remove Door as start location

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
- Adds TODO's and FIXME's to things that are worth remembering to change/revise later
- Adds more comments
- Adds a lot of trick videos
- Adds events for the operations deck missile shield, and maintenance shaft gerons
- Adds a lot of shinespark tricks
As well as a lot of other Main Deck clean up.
Note, that for open transitions, or hatches, I removed `Disabled Door Lock Rando`, because no doors can be placed there. In a future PR, I plan to add "shuffle open hatches" misc resource, so that shinesparks aren't always completely out of logic when Door Lock Rando is enabled.
=> Main deck: comment and trick (video) pass

CHANGELOG.md, pyproject.toml, randovania/games/samus_returns/exporter/hint_namer.py, randovania/games/samus_returns/logic_database/Area 3 Factory Exterior.json, randovania/games/samus_returns/logic_database/Area 3 Factory Exterior.txt, randovania/games/samus_returns/logic_database/Area 4 Crystal Mines.json, randovania/games/samus_returns/logic_database/Area 4 Crystal Mines.txt, requirements.txt, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
- DNA hints now just say "DNA" instead of "Metroid DNA".
- Starting at Area 3 Factory Exterior - Beam Burst Chamber & Tsumuri Station no longer spawns Samus out of bounds.
- Bumps OSRR
=> MSR - Softlocks and bug fixes

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 3 Metroid Caverns.json, randovania/games/samus_returns/logic_database/Area 3 Metroid Caverns.txt
Adds proper logic with HJ in Caverns Teleporter East to reach the pickup
=> MSR - A3 Metroid Caverns Logic Fix

randovania/games/samus_returns/logic_database/Area 3 Metroid Caverns.json, randovania/games/samus_returns/logic_database/Area 3 Metroid Caverns.txt
Doesnt need changelog entry, as its part of the DLR change.
=> MSR: exclude a3 mc door from being wave

CHANGELOG.md, randovania/generator/teleporter_distributor.py
Fixes a typo and changes the check in L88-89.
From my understanding this wants to check if the teleporters are connected or reachable from the other.
a) The two teleporters `cteleporter2` and `cteleporter1` are in the same region => reachable
or
b) `cteleporter2`'s area has the same name as `cteleporter1`'s destination area.
b) was intended to express `Is cteleporter2 and cteleporter1 connected` but as MSR uses the same area names multiple times e.g. `Transport to Area 7` it breaks. Therefore I added the check of the destination region name.
(Waits for new release? => then needs a changelog entry)
=> Fix elevator two-way shuffle (for MSR)

randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
No changelog entry, as it is part of long beam
=> AM2R: adjust missile-less metroid requirements without long beam

CHANGELOG.md, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, requirements.txt
No changelog entry, because all 2.5.0 did was change 2 sprites, which already have their changelog entry.
=> Bump am2r_yams to 2.5.0

CHANGELOG.md
Removed "inbounds" to avoid confusion since it requires `Single Room Out of Bounds`.
=> Update Root Cave NSJ climb in Changelog

randovania/games/fusion/gui/ui_files/fusion_cosmetic_patches_dialog.ui, randovania/gui/ui_files/preset_patcher_energy.ui
fixes `randovania\games\fusion\gui\ui_files\fusion_cosmetic_patches_dialog.ui: Warning: The name 'verticalSpacer' (QSpacerItem) is already in use, defaulting to 'verticalSpacer1'.`
this doesn't noticeably change anything but here's a screenshot for completeness
=> GUI: fix 2 warnings for ui where multiple objects have the same name

randovania/generator/pickup_pool/ammo_pickup.py, test/generator/pickup_pool/test_ammo.py
The test was working by magic before, because apparently `range(MagicMock())` is `range(0, 1)`??
=> Slightly optimize add_ammo_pickups

CHANGELOG.md, randovania/gui/lib/common_qt_lib.py, randovania/gui/multiplayer_session_window.py, test/gui/test_multiplayer_session_window.py
This adds a button (hidden behind "Show Experimental Settings") to the Multiworld Session window to export the preset of every world in the session to a folder. This is extremely helpful for troubleshooting large multis that are having generation problems, or to verify that all users are using settings that abide by whatever session rules were established by the host.
I'm not sure if "Show Experimental Settings" is necessarily the correct choice for toggling the visibility, but I didn't think it made sense for it to show up for all users by default.
=> Add "Export All Presets" feature for multiworld sessions

randovania/gui/dialog/multiplayer_session_browser_dialog.py
Was causing crashes on macOS, but I don't think it's the reason tests are flaky.
=> Extra safety in broswer dialog

randovania/games/samus_returns/logic_database/Area 2 Dam Entryway.json, randovania/games/samus_returns/logic_database/Area 2 Dam Entryway.txt, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json
Fixes the door not appearing after the Alpha is dead
=> MSR - Add A2 Entryway custom door to PostAlpha group

CHANGELOG.md, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt
On top of everything already in the database you can also reach bubble lair hub from shinespark cave west with just a glide and some expert walljumps as demonstrated here:
https://youtu.be/Gq5wq0yHvCY
(link I attached to the database)
=> Reach top of bubble lair shinespark cave from shinespark cave west with only a morph glide and walljumps

.github/workflows/build-test-publish.yml
(Hopefully) Fixes #6603 
Should hopefully, be fine, at least documentation has put `target/release/my*` as an example for the glob, so I'm assuming this works too.
=> Only upload binaries to GH release

CHANGELOG.md, randovania/games/prime1/pickup_database/pickup-database.json, randovania/games/prime2/pickup_database/pickup-database.json, randovania/games/samus_returns/pickup_database/pickup-database.json, test/test_files/patcher_data/dread/dread_prime1_multiworld/world_1.json, test/test_files/patcher_data/samus_returns/multi-am2r+cs+dread+prime1+prime2+msr/world_1.json
- Fixed Dread using Morph Ball for MSR Bomb
- Fixes Dread using Missile Launcher for Prime 1 Missile Launcher
- Beam Ammo in Prime 2 now shows up as Aeion Tank in MSR
- Boost Ball for Prime 1/2 now shows up as Speed Booster in MSR
- Cannon Ball for Prime 2 now shows up as Speed Booster in MSR
- Phantom Cloak and Flash Shift now show up as Lightning Armor and Phase Drift respectively in MSR
- Gravity Boost for Prime 2 now shows up as Gravity Suit in MSR
- Updated Missile Reserve Tank description
=> Pickup Database/Offworld Model Changes

CHANGELOG.md, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt
- remove redundant connection causing logically incompleteable seeds
- minor changelog fixes
=> Prime: remove redundant Hive Totem connection

CHANGELOG.md, randovania/games/samus_returns/layout/msr_cosmetic_patches.py, randovania/interface_common/persisted_options.py, test/test_files/patcher_data/samus_returns/multi-am2r+cs+dread+prime1+prime2+msr/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
I believe this change is necessary because DNA hints are a thing. Plus, it doesn't block the map much so being defaulted to on is fine.
=> MSR - Enable room names on HUD by default

CHANGELOG.md, randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/samus_returns/pickup_database/pickup-database.json
I thought these were added when they got added for dread and echoes. apparently not.
=> Make vanilla progressives for am2r and MSR too

randovania/resolver/resolver.py
These resources are meant to be be the resources gained by collecting the node that's being rolled back. Given that the resource can depends on the current inventory, it must use the state from before collecting the node.
Particularly in the case of progressive items, it matters that we pass the context from before collecting the node into this function.
These resources are used to detect the point at which we roll back collecting a dangerous resource that where we see the requirement that makes it dangerous. If any games would have a chain of progressive items where any of the items in the chain were dangerous, then this fix would likely be important.
=> Resolver: Fix using the wrong state when finding the resources gained

CHANGELOG.md, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
multiple missing morph ball requirements, tricks listed as mid-air morph rather than glide, and added a new method for crossing Zeta East Access
=> AM2R: Fix several tower connecting rooms 

CHANGELOG.md, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt
technically still a logic issue due to version differences in collision, but this improves things by documentation at the least.
as a reminder, this is the branch that is missing.
=> Prime: Document non-ntsc ruined shrine NSJ

randovania/games/prime3/logic_database/Bryyo - Reptilicus.json, randovania/games/prime3/logic_database/Bryyo - Reptilicus.txt
Logic assumed it was possible to fly to the Cliffside from Jungle Bryyo after getting the battery, which is impossible. Now the Energy Cell in Hidden Court also checks for both sides of Machineworks Bridge to be opened in order to access the Energy Cell location.
=> MP3 - Fix Hidden Court Edge Case with the battery

CHANGELOG.md, randovania/games/am2r/gui/preset_settings/am2r_teleporters_tab.py, randovania/games/dread/gui/preset_settings/dread_teleporters_tab.py, randovania/games/samus_returns/gui/preset_settings/msr_teleporters_tab.py, randovania/gui/preset_settings/dock_rando_tab.py
=> Don't show unnecessary lines in DLR and Teleporter tabs

randovania/monitoring/__init__.py
Should cover the `Incompatible client version '8.2', expected '8.3'` entries, but also the `An existing connection was forcibly closed by the remote host` and `The specified network name is no longer available` ones.
=> Ignore ConnectionError when sending exceptions to Sentry

randovania/lib/infinite_timer.py
Dunc had the correct idea when hii made the CS connector use a non-strict timer: if `target` runs for longer than `interval`, then `_current_task` will be not-None in `_on_timeout`. Since we use this timer to make network calls, it's perfectly reasonable for them to take forever.
For an infinitely repeatable timer, we don't really mind skipping a few triggers so defaulting strict to false.
No changelog because I'm not even sure this error shows up visibly for users. And the message would be something like "Fixed: An invisible error that could happen in rare cases with is now fixed."
=> Default InfiniteTimer to not strict

randovania/monitoring/__init__.py
Fifth time's the charm right? I'm guessing it's only the fifth time I lost track already.
When sentry reports the stack it includes all local variables, which sometimes is an imported module which is converted to a string. Doing so on Windows gets something like `<module 'open_dread_rando' from 'C:\\Users\\henri\\programming\\randovania\\venv-3.12\\Lib\\site-packages\\open_dread_rando\\__init__.py'>`, including the double slashes. (nice python bug by the way)
=> Sentry Filtering: Account for multiple forward-and-backward slashes in a row

CHANGELOG.md, requirements.txt
> Add toggle for tanks fully refilling ammo
and
> Support shuffling block types
are not listed, because RDV doesnt have toggles for them yet.
The performance improvements by Henrique also have not been listed cause I wasn't sure if I should put it in.
=> Bump OSRR to 2.4.0

CHANGELOG.md, randovania/monitoring/__init__.py
Plus changelog entry for #6976 that I forgot to commit.
=> Sentry: Fallback to non-empty string in cpu.processor

CHANGELOG.md, randovania/games/dread/logic_database/Burenia.json, randovania/games/dread/logic_database/Burenia.txt
Makes the Early Gravity puzzle require Speed Booster Conservation instead of being trickless, as was intended back when the trick was added to this section.
=> Dread: Early Gravity logic fix

CHANGELOG.md, randovania/games/prime1/logic_database/Frigate Orpheon.json, randovania/games/prime1/logic_database/Frigate Orpheon.txt, randovania/games/prime1/logic_database/header.json, randovania/games/prime1/logic_database/header.txt
Yay for last minute major bug findings
The generator can go through a node, when it is able to fullfill its "open" and "lock" requirements. Thus, if a Teleporter leads to frigate, the generator is able to leave instantly again, even though in-game you would be expected to go through the whole frigate to kill Parasite Queen.
Thus we change the open requirements on the ship teleporter to require the queen to be killed and for scan visor, as you'll need to scan the ship in order to activate the teleportation.
=> Fix frigate orpheon ship being immedately usable

randovania/lib/infinite_timer.py, test/lib/test_infinite_timer.py
I always hated using Qt for the Game Connector. If we also stop using signals we can have a non-qt build of Randovania that can do multiworld things.
Plus if we're calling the timeout via the event loop, hopefully https://randovania.sentry.io/issues/3920644751/ won't happen anymore.
Leaving for next release because I want a full month of testing for this.
=> Pure asyncio timers for InfiniteTimer

.github/workflows/build-test-publish.yml
The binaries are in `Randovania *` subdirectories, so a single glob doesn't work to get them.
=> Fix CI not uploading binaries to release

.github/workflows/build-test-publish.yml
Hopefully fixes #7030 
What i've additionally done outside of this PR:
- Create a PAT on my account, with the orga as an owner. The PAT can be viewed here: https://github.com/organizations/randovania/settings/personal-access-tokens/active
- The PAT has read and write access to the website only
- Added the token as an [orga secret](https://github.com/organizations/randovania/settings/secrets/actions/WEBSITE_VERSION_UPDATER_PAT)
=> Use a PAT when pushing to website

randovania/games/samus_returns/gui/ui_files/preset_msr_aeion.ui, randovania/games/samus_returns/gui/ui_files/preset_msr_energy.ui, randovania/games/samus_returns/gui/ui_files/preset_msr_goal.ui, randovania/games/samus_returns/gui/ui_files/preset_msr_hints.ui, randovania/games/samus_returns/gui/ui_files/preset_msr_patches.ui, randovania/games/samus_returns/gui/ui_files/preset_msr_reserves.ui, randovania/games/samus_returns/gui/ui_files/preset_teleporters_msr.ui
This is really hard to visualize, idk if the screenshot help. But this was applied to a bunch of MSR ui files in order to have consistent padding/margins.
=> MSR: make GUI stuff more consistent

CHANGELOG.md, randovania/gui/widgets/multiplayer_session_users_widget.py
=> Align "last activity" on MW session window

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 3 Metroid Caverns.json, randovania/games/samus_returns/logic_database/Area 3 Metroid Caverns.txt
Adds a missing connection to remove the Grapple block between Leetum Shrine and Gravitt Garden, since the block is only one tile wide and can be destroyed from both sides.
=> MSR - Area 3 MC Gravitt Garden Fix

randovania/games/planets_zebeth/exporter/hint_namer.py, randovania/games/planets_zebeth/exporter/patch_data_factory.py, randovania/games/planets_zebeth/logic_database/Kraid.json, randovania/games/planets_zebeth/logic_database/Kraid.txt, randovania/games/planets_zebeth/pickup_database/item_data.json, test/games/test_log_file_export.py, test/test_files/log_files/planets_zebeth/starter_preset.rdvgame, test/test_files/log_files/planets_zebeth/starter_preset_shuffle_keys.rdvgame, test/test_files/patcher_data/planets_zebeth/planets_zebeth/starter_preset/world_1.json, test/test_files/patcher_data/planets_zebeth/planets_zebeth/starter_preset_shuffle_keys/world_1.json
[Planets (Zebeth) DB: Added missing starting area](https://github.com/UltiNaruto/randovania/commit/b7f8062f98808db253f1a30255be71c366e02339)
Added some missing starting areas which are elevator rooms.
[Planets (Zebeth): Implemented patch data factory](https://github.com/UltiNaruto/randovania/commit/6d64dc8410e6e00789f56193e9bb8c3050ced114)
Exporting to dict the game datas that will be used by the patcher to export the game.
=> Planets (Zebeth): Implemented patch data factory

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Documents several tricks in Sector 2:
* Nettori Access
* Accessing the upper half of the room with frozen enemies 
* Oasis
* Retrieving the item in the room in multiple ways
* Navigating to Oasis Storage with only frozen enemies
* Overgrown Entrance
* Using Frozen Ki Hunters as platforms
=> fusion: Document tricks and logic in Sector 2

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/header.json
Reactor core now has a platform to allow non-dangerous-nettori traversal. Image in the DB is getting replaced soon:tm:
Added a new misc resource for when open transition hatches are not shuffled in DLR (currently thats not implemented, and while the plan is to implement them at one point, no clue when that will be)
Rest should be self explanantory.
=> Fusion: a few main deck changes

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
- West Reservoir: added a new node to isolate the speedboost block connection
- Serris Escape: added logic for destorying the bomb block chain, removed connection for going back up
- Aquarium Hub: added logic for speedboosting the kago from the right
- Drain Pipe: pulled out the PB method for killing the geron so that it no longer needs grav
- Sciser Sanctuary: added checks for grav and UWJ for leaving the room
- Aquarium Tank: removed walljump trick for climbing back out
- added l0 checks for various speedboosts
- Powamp Shaft: removed space jump from gravityless climbing method connection
=> start clearing AQA notes

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
For when you dont want to dodge it.
=> Main deck: Add missing damage boost to a pirate

randovania/games/planets_zebeth/exporter/patch_data_factory.py, randovania/games/planets_zebeth/logic_database/Ridley.json, randovania/games/planets_zebeth/logic_database/Ridley.txt, randovania/games/planets_zebeth/pickup_database/item_data.json, test/test_files/patcher_data/planets_zebeth/planets_zebeth/starter_preset/world_1.json, test/test_files/patcher_data/planets_zebeth/planets_zebeth/starter_preset_shuffle_keys/world_1.json
The internal id was set to 10085 instead of 100085.
The pickup type was set to `Tourian Key #` instead of `Tourian Key`.
It would say `Tourian Key acquired` instead of `Tourian Key # acquired`
=> Few fixes for Planets

README.md
it is really unintuitive that we do not mention this anywhere, and even when it fails we only have a vague 
```
if len(self.randovania_version) != 4:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```
message.
Theoretically, we could add a mention on how to add upstream and use its tags should one have forgotten to uncheck it, but if one notices it that early they can just delete the fork and refork.
=> Readme: Mention to uncheck "copy main branch only" on fork

randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, test/test_files/patcher_data/am2r/am2r/chaos_options/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock_open/world_1.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2+msr/world_6.json
- in every case where the instance id was referring to a door, its been renamed to `door_instance_id`
- mostly adds the oGoToObjects instance_ids (+ facing) for GT and Thoth, with a few other random docks sprinkled in.
=> AM2R: add ER extra data to a few areas

randovania/games/fusion/generator/bootstrap.py, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/logic_database/header.json
This PR avoids 3 very bad pitfalls for the generator right now: water pump, a5 nightmare nook, a6 shell access/zozoro wine cellar
Water pump is now a safe action for the generator
Nightmare nook and lower left a6 we stop the generator from going there unless it can get out, as the generator there is unable to see what it needs to get out and spends ~10 actions just frantically placing arbitrary items
A6 is still a bit of an issue, but now it takes way less actions to get out if it gets stuck there. 
Also adds a trickless path to exit a4 with PBs+SJ
=> Fusion: hack very dangerous ponrs

randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/header.json
This will make the selections in the logic editor consistent with the room name for less confusion.
=> fusion: rename internal long names for atmospheric stabilizers

CHANGELOG.md, pyproject.toml, randovania/data/gui_assets/tracker/samus-returns-game-progressive.json, randovania/data/gui_assets/tracker/samus-returns-game.json, randovania/games/samus_returns/assets/lua/bootstrap_part_1.lua, randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/gui/preset_settings/msr_goal_tab.py, randovania/games/samus_returns/logic_database/Area 6.json, randovania/games/samus_returns/logic_database/Area 6.txt, randovania/games/samus_returns/logic_database/header.json, requirements.txt, test/test_files/patcher_data/samus_returns/samus_returns/custom_final_boss_free_placement_dna/world_1.json
- Accessing the item behind Diggernaut is now possible if Diggernaut is the final boss
- This also includes backdooring Diggernaut to start the fight from the left side
- The item tracker now shows the collected DNA out of the required DNA instead of being DNA you start with out of 39
`0 collected / 39 required`
`0 collected / 4 required`
Fixes https://github.com/randovania/open-samus-returns-rando/issues/468
=> Bump OSRR to 2.6.0

randovania/games/prime3/logic_database/Bryyo - Fire.json, randovania/games/prime3/logic_database/Bryyo - Fire.txt, randovania/games/prime3/logic_database/Bryyo - Reptilicus.json, randovania/games/prime3/logic_database/Bryyo - Reptilicus.txt, randovania/games/prime3/logic_database/GFS Valhalla.json, randovania/games/prime3/logic_database/GFS Valhalla.txt, randovania/games/prime3/logic_database/header.json
While this PR is mostly about adding new strat vids or replacing the existing ones with (hopefully) more catered towards rando strats, I've also taken the liberty of modifying some existing logic which I will list below : 
- Front of Lasso Walls -> Pickup (Missile Expansion) : 
Added a new trick to reach the item pickup with a standable ; Beginner Standable Terrain and Movement, with video
- G.F.S Theseus Lower Ledge -> G.F.S Theseus Upper Ledge - Beginner Slope Jump and Terminal Fall Abuse : 
Replaced the existing video with a fully dedicated strat vid
- Door to Gateway -> Bridge - Intermediate Slope Jump : 
Added strat vid
- Room Center -> Event - Leviathan Shield : 
Added either beginner knowledge or After South Jungle Court Turret to existing conditions;
I don't think it's fair to …
=> Extra video documentation for the Corruption DB, as well as a few suggestions

randovania/games/fusion/pickup_database/pickup-database.json
Causes etanks to be spread out more and not dumped all at the end when the generator realized it needs access to dna/bosses.
=> Fusion: tweak etank weight

randovania/games/prime1/logic_database/Tallon Overworld.txt, randovania/games/prime1/logic_database/header.json
Entrance rando is the usual RDV terminology.
=> Prime 1: rename long name of "room rando" to "entrance rando"

randovania/game_description/pickup/ammo_pickup.py, randovania/generator/pickup_pool/pickup_creator.py
Fusion (and other games maybe too?) would benefit from changing missile tank weights.
I don't know if this needs a migration
=> Allow tweaking multipliers for ammo

randovania/games/am2r/gui/ui_files/preset_am2r_chaos.ui, randovania/games/dread/gui/ui_files/dread_cosmetic_patches_dialog.ui, randovania/games/dread/gui/ui_files/preset_dread_goal.ui, randovania/games/fusion/gui/ui_files/preset_fusion_goal.ui, randovania/games/planets_zebeth/gui/ui_files/preset_planets_zebeth_goal.ui, randovania/games/prime1/gui/ui_files/preset_prime_chaos.ui, randovania/games/prime1/gui/ui_files/preset_prime_goal.ui, randovania/games/prime1/gui/ui_files/prime_cosmetic_patches_dialog.ui, randovania/games/prime2/gui/ui_files/echoes_cosmetic_patches_dialog.ui, randovania/games/prime2/gui/ui_files/preset_echoes_goal.ui, randovania/games/samus_returns/gui/ui_files/msr_cosmetic_patches_dialog.ui
Fixed custom scroll protected slider "QSlider" import in UI files from the previous PR.  I don't know enough to say what it broke to have the wrong uncapitalized class extended, or why it functions anyway, but this fixes it :)
=> Fixed "QSlider" capitalization in UI custom widget definition

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
=> Fusion: add missing room ID for operations maintenance shaft

pyproject.toml
We don't want these typed either.
=> Mypy: override typing for generic generated gui module

CHANGELOG.md, randovania/games/samus_returns/logic_database/Surface East.json, randovania/games/samus_returns/logic_database/Surface East.txt
Fixes #7334
If I'm not mistaken, this node should be part of the "final-boss-not-ridley" layer because the other side only exists if the final boss is not ridley to teleport back to surface east after ridley was beaten.
=> Move Dock from Surface West to "final-boss-not-ridley" layer

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 6 NOC.json
Adds them as discussed previously. Changes them now, as they do affect generation and I want to see that in advance.
S1 -> L1
S2 -> L1
S3 -> L2
S4 -> L2
S5 -> L3
S6 -> L3
Main Deck Top -> free
Main Deck Middle -> L2
Main Deck Bottom -> L4
=> Fusion: add proper hint requirements

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Reasoning for making HJless behind a trick:
The game doesn't teach you anywhere to bait reos into swooping down and freezing them in mid air. The game does teach you on freezing and standing on kagos though, hence why HJ is trickless.
=> Fusion: Readjust kago freezing

randovania/gui/dialog/node_details_popup.py
Makes it not annoying anymore to change descriptions of door nodes that have overrides.
=> Visualizer: Save door overrides when editing node

randovania/games/prime1/logic_database/header.json
The auto tracker was switching between being in-game and on the title screen because of incorrect settings for specific item IDs (in this case "Unknown Item 2" and "Power Suit"). Adjusted their max_capacity in the database and now it should work fine again.
=> Fixed connection for auto tracker

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/header.json
```
[P: Missile Launcher Data] - 1.75
[P: Morph Ball] - 1.75
[P: Level 2 Locks] - 0.0
[P: Level 4 Locks] - 0.0
```
=> Fusion: Fix 1st action giving items to unlock hints only

CHANGELOG.md, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
Moves all dark world damage requirements out of the door connection and into the dock override.
Updated videos for Seeker skips
Also truncated some links here and there.
fixes #6608
=> Fix Seeker Door Overrides

randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/generator/bootstrap.py, randovania/games/prime1/gui/preset_settings/prime_patches_qol.py, randovania/games/prime1/gui/ui_files/preset_prime_qol.ui, randovania/games/prime1/layout/prime_configuration.py, randovania/games/prime1/logic_database/Tallon Overworld.json, randovania/games/prime1/logic_database/Tallon Overworld.txt, randovania/games/prime1/logic_database/header.json, randovania/layout/preset_migration.py, test/test_files/log_files/prime1_refills.rdvgame, test/test_files/patcher_data/prime1/prime1_refills/world_1.json
Discussion from the Community: The idea behind removing bars was to open up mines from the front without needing to go through frigate in beginner logic. There was also an argument that it gives ice more utility since reverse frigate can be a thing before wave beam.
This feature will be disabled by default
Details of Changes
- Added a boolean to the prime configuration
- Added a checkbox to the UI that toggles that configuration value
- Wrote a preset migration to write the default value for older presets migrating
- Edited the patch data factory to tell the patcher to remove specific objects in Great Tree Hall.
- Added Misc Resource to the Logic DB for this new feature
- Edited the correct node in Great Tree Hall to be able to use the Misc Resource
- Edited the bootstrap for the feature …
=> Implemented the Remove Bars Feature

randovania/games/dread/gui/dialog/game_export_dialog.py, randovania/games/factorio/game_data.py, randovania/games/factorio/gui/dialog/game_export_dialog.py, randovania/games/factorio/gui/preset_settings/__init__.py, randovania/games/factorio/gui/ui_files/factorio_game_export_dialog.ui, randovania/games/factorio/layout/__init__.py, randovania/games/factorio/layout/factorio_preset_describer.py, randovania/games/factorio/pickup_database/pickup-database.json, randovania/games/factorio/presets/starter_preset.rdvpreset, randovania/games/samus_returns/gui/dialog/game_export_dialog.py, randovania/gui/data_editor.py, randovania/gui/dialog/game_export_dialog.py, randovania/gui/tracker_window.py, randovania/lib/windows_lib.py, tools/factorio/create_resources.py
The actual mod downloading will be handled in https://github.com/randovania/factorio-randovania-mod/.
=> Polish Factorio UX

CHANGELOG.md, randovania/games/prime1/generator/bootstrap.py, randovania/games/prime1/logic_database/header.json, randovania/games/prime1/logic_database/header.txt
This makes it possible to understand for users how heat reduction is handled without needing to know that its a thing that can be patched at runtime by bootstrap.
Alternatively we could also say, legacy mode isn't logical and remove the branch entirely :upside_down_face:
=> Prime 1: use misc resource for vanilla heat reduction

CHANGELOG.md, randovania/game_description/pickup/ammo_pickup.py, randovania/game_description/pickup/pickup_entry.py, randovania/game_description/pickup/standard_pickup.py, randovania/generator/filler/player_state.py, randovania/generator/filler/retcon.py, randovania/generator/pickup_pool/pickup_creator.py, test/generator/pickup_pool/test_pickup_creator.py
Recontinuation of #6607 
Pickups have an impact in the age when they're assigned. The weight of an index depends on it's age, where younger age = more likely
This PR does introduce an option, but it is currently off for all games.
In future PRs, I want to do a bit more analysis on nicer values (especially for Prime)
Fixes https://github.com/randovania/randovania/issues/4496
=> Properly introduce PickupIndex age v2

pyproject.toml, randovania/bitpacking/construct_pack.py, randovania/cli/commands/export_game.py, randovania/interface_common/options.py, randovania/interface_common/update_checker.py, randovania/server/client_check.py, requirements.txt, test/interface_common/test_update_checker.py, test/server/test_client_check.py
Reverts randovania/randovania#7563
For some reason, this breaks stable for new users. They are not able to use the application at all, and instead just get an error message and the application immediately closing afterwards.
I don't want to try to find the proper solution for now, so full on revert it is (it's not like we're testing python 3.13 right now anyway)
=> Revert "Fixes needed for running with Python 3.13"

randovania/game_connection/connector/mercury_remote_connector.py, test/game_connection/connector/test_msr_remote_connector.py
Fixes #6961
That should do the trick if I understand correctly.
Afaik this was catched in the source and only shown in the console. Was there anything else which the user experienced that it would be worth a changelog entry?
=> Ensure that inventory only contains ints and no floats

randovania/game_connection/connector/am2r_remote_connector.py, randovania/game_connection/connector/corruption_remote_connector.py, randovania/game_connection/connector/cs_remote_connector.py, randovania/game_connection/connector/debug_remote_connector.py, randovania/game_connection/connector/dread_remote_connector.py, randovania/game_connection/connector/mercury_remote_connector.py, randovania/game_connection/connector/msr_remote_connector.py, randovania/game_connection/connector/prime_remote_connector.py, randovania/game_connection/connector/remote_connector.py, randovania/network_client/network_client.py, randovania/network_common/__init__.py, randovania/network_common/multiplayer_session.py, randovania/network_common/remote_pickup.py, randovania/server/multiplayer/world_api.py, test/game_connection/connector/test_am2r_remote_connector.py, test/game_connection/connector/test_cs_remote_connector.py, test/game_connection/connector/test_dread_remote_connector.py, test/game_connection/connector/test_echoes_remote_connector.py, test/game_connection/connector/test_msr_remote_connector.py, test/game_connection/connector/test_prime1_remote_connector.py, test/network_client/test_network_client.py, test/server/multiplayer/test_world_api.py
Need this to fix MSR DNA counter in coop.
Provider UUID to compare to remote connector UUID. If it's the same, it's a coop item.
Pickup index to find the region of the pickup for the coop world.
=> Add pickup index and provider uuid to remote pickups

randovania/resolver/bootstrap.py
Fixes #7667
Another way to fix it would be to provide a ResourceCollection to `create_damage_state` which each implementation then uses to calculate the proper starting energy. 
But this feels cleaner to me.
=> Fix: Generator now has proper starting energy based on items that increase it.

randovania/gui/multiplayer_session_window.py
=> Co op: make clearer why check is disabled during/after gen

CHANGELOG.md, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt
Added spider method along the ceiling to both horizontal docks in mining facility alpha nest access making sure you can reach the ceiling as a ball first
Intermediate mid-air morph since the short height means you have to do the jump > morph > aim inputs in fairly quick succession
A single bomb jump inside the doorways lets you reach the ceiling
Plus disabled entrance rando since you can roll in from the adjacent rooms
I was unsure about adding CBJ, I think it might be redundant since the CBJ template also has "can use bombs"
=> Spider method of crossing mining facility alpha nest access

CHANGELOG.md, randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt
I noticed a small typo in Dread's logic database yesterday involving this event:
It didn't seem intentional (as literally everywhere else, it's written as "speedboost"), so I fixed it. I have two questions about this change:
- Do I need to do a migration for this? I saw that there was `dairon_typo` migration data for Dread, but that seems to be because those strings are used for `dock_weakness`. I see no such thing for this event, which makes me think a migration is unnecessary.
- Do I need to update the changelog for this? The [contributing guide](https://github.com/randovania/randovania/blob/6012fa9dc176789bd38709182ea3febbb50cb428/CONTRIBUTING.md#example-of-changes-that-should-have-changelog) says it should be updated for "any database change for a stable game," which is what this fix …
=> Fix typo in Dread logic database

CHANGELOG.md, randovania/game_description/game_patches.py, randovania/generator/generator.py, randovania/gui/preset_settings/generation_tab.py
Closes #7096 
There's a funky ownership model where the connection cache lives in the GamePatches object that is shared with later stages of generation, while the underlying connection data is not.
=> Fix option to check if base patches is beatable with all pickups

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt
A few things to hopefully explain the thought process a little better:
- i removed the space jump requirement to fight ridley, since its barely useful for casual play anyway
- wide+plasma only has been bumped to intermediate combat because due to the lack of dps it can be fairly easy to get a ton of damage accumulated by ridley
- space jump cheese strat is currently charge only. Supposedly possible with missiles too, but since I haven't heard of anyone actually doing this yet, so will probably be added later when we have a video
- to my knowledge the only way to do it hitless is with vanilla+ beams. may be possible with lower beams (or missiles only) but for me it seemed too unpredictable for now.
- i ran 1k seeds on this, ridley now had progression of ~6% (where "progression" means …
=> Fusion: Ridley revision

randovania/generator/generator.py
Games with pre placed key items such as Dread need these items to be accessible in order to beat the game. Considering that these are placed without checking if the locations are accessible, it stands to reason that the check_if_beatable logic should run after these are placed, to reject base patches that make these key items inaccessible even when having everything else in the item pool.
=> Generator: Move check if beatable check to after assigning pool results

CHANGELOG.md, pyproject.toml, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/gui/preset_settings/__init__.py, randovania/games/dread/gui/preset_settings/dread_lights_tab.py, randovania/games/dread/gui/ui_files/preset_dread_lights.ui, randovania/games/dread/layout/dread_configuration.py, randovania/layout/preset_migration.py, requirements.txt, test/test_files/log_files/dread/all_settings.rdvgame, test/test_files/patcher_data/dread/dread/all_settings/world_1.json, test/test_files/patcher_data/dread/dread/crazy_settings/world_1.json, test/test_files/patcher_data/dread/dread/custom_patcher_data/world_1.json, test/test_files/patcher_data/dread/dread/custom_start/world_1.json, test/test_files/patcher_data/dread/dread/dread_dread_multiworld/world_1.json, test/test_files/patcher_data/dread/dread/dread_dread_multiworld/world_2.json, test/test_files/patcher_data/dread/dread/elevator_rando/world_1.json, test/test_files/patcher_data/dread/dread/hide_all_with_nothing/world_1.json, test/test_files/patcher_data/dread/dread/starter_preset/world_1.json, test/test_files/patcher_data/dread/dread_prime1_multiworld/world_1.json, test/test_files/patcher_data/dread/multi-am2r+cs+dread+prime1+prime2+msr/world_4.json, test/test_files/patcher_data/dread/multi-am2r+cs+dread+prime1+prime2/world_4.json, test/test_files/patcher_data/dread/multi-cs+dread+prime1+prime2/world_4.json, test/test_files/patcher_data/dread/multi-cs+dread+prime1+prime2/world_8.json, test/test_files/patcher_data/dread/multi_coop_am2r+bdg+cs+dread+prime1+echoes+msr/world_4.json
As titled, when this option is enabled all light actors within a scenario will be deleted. This is a preset option rather than a cosmetic option, as it provides a substantially different gameplay experience. Enabling it makes many elements of the game very difficult to see, primarily items.
This also includes an open-dread-rando bump from 2.15.0 -> 2.16.0.
=> Dread: Add preset option to remove all light sources in a region

CHANGELOG.md, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
Adds a bunch of new tricks with their respective videos and changes the logic for Temple Security Access to remove an incorrect requirement.
Shamelessly copied from the changelog:
- Added: Mining Station B: Hypermode method to open the portal without Space Jump Boots or Morph Ball Bombs.
- Added: Torvus Grove: Two expert difficulty methods to cross the upper part of this room without Space Jump Boots.
- Added: Worker's Path: Advanced bomb jumps to get to the cannon platforms NSJ.
- Added: Grand Abyss: Expert extended dashes and standables to cross from the Vault side to the Watch Station side.
- Added: Hive Dynamo Works: Advanced/Expert NSJ Extended Dashes to go across the gap with the grapple point.
- Added: Hive Entrance: Expert inbounds method to get to the item without Light Suit.
- …
=> Echoes: Many logic changes

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
Turns out that this works just fine as is. Not sure if we did something else that changed it, or if I was just previously tripped up by the values because arachnus is weighted differently on whether he has dna or not.
=> Rework Arachnus logic to remove Generator Workarounds

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Reason for WJ intermediate on most is due to you being on a time frame until enemy unfreezes
Reason for freezing intermediate on most is that you more or less have one attempt at freezing the first kihunter in the correct position and if that fails you need to reload the room because its then too low. Since its initial descent happens relatively quickly, if you're not prepared for it it will catch you off-guard.
Due to the room change most if not all of the old videos are now outdated. I'd need to search which ones still apply and which ones don't.
=> Fusion: Rework sector 2 eastern shaft

CHANGELOG.md, randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt
Put Highly Dangerous Logic on most before-conditions. Assume flipping the spinner from the left is safe.
=> Dread: Make events in Screw Attack Room non dangerous

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Great Temple.json, randovania/games/prime2/logic_database/Great Temple.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
Added "keybearer corpse" and "morph ball tunnel" hint features to applicable areas with pickup nodes.
=> Echoes: Add area features

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Added videos for:
* Eastern Shaft
* From Door to "Nettori Save Room" to KiHunter Hallway (multiple)
* From Door to "Collapsed Shaft" to Door to "Nettori Save Room"
* Puyo Palace
* Nettori Save Room to Collapsed Shaft via shinespark trick
* Ripper Tower
* Freeze the enemies with Diffusion Only
Adjusted Logic in Puyo Palace due to redundant requirements.
Door to Central Shaft -> Door to Collapsed Shaft has single wall jump trick or space jump requirements and is already trivial from Nettori Save Room door. No need to go back up to Nettori Save Room to try the shinespark trick again.
Adjusted Logic in Eastern Shaft.
Doors to Collapsed Shaft and Door to Overgrown checkpoint had requirements which could not be satisfied.
Moving Left to Right was asking to maneuver without wall jumps …
=> fusion: sector 2 video documentation and logic update

randovania/generator/hint_distributor.py
this is important because the hint namers make the distinction, so the information is being provided to the player
=> REGION_ONLY now distinguishes between light and dark world for precision

randovania/games/cave_story/generator/hint_distributor.py, randovania/generator/hint_distributor.py
cave story hints don't include the region name, so a hint pointing to "Grasstown" was much more ambiguous than intended
=> allow games to disable the universal precisions in their hint features

randovania/games/prime2/generator/hint_distributor.py, randovania/generator/hint_distributor.py, test/generator/filler/test_runner.py
standard deviation has been halved for both types of hint feature. this keeps the average precision the same, but makes extremely low precisions *much* rarer and high precisions somewhat rarer
also, region-only precision has been removed from echoes hints. the changes to precision calculation made them significantly more common than intended, and they're pretty much antithetical to the new direction for hint design
=> adjust echoes hint distribution params

randovania/game_description/hint_features.py, randovania/games/binary_data.py, randovania/games/prime2/logic_database/header.json, randovania/gui/dialog/trick_details_popup.py, randovania/gui/dialog/trick_usage_popup.py, randovania/gui/docks/hint_feature_database_editor.py, randovania/gui/lib/data_editor_links.py, randovania/gui/widgets/base_game_tab_widget.py, randovania/gui/widgets/hint_feature_tab.py, randovania/network_common/pickup_serializer.py, test/gui/dialog/test_trick_details_popup.py, test/gui/dialog/test_trick_usage_dialog.py, test/gui/lib/test_data_editor_links.py, test/network_client/test_network_client.py, test/server/multiplayer/test_world_api.py
Location features now use database links, and omit the pickup name if all pickups in the area have the feature.
Also, features can define a description which gets displayed at the top of their foldable in the feature tab.
=> Improve the appearance of the hint feature tabs

tools/shell.nix
These will only be of use to people running nixos (or running not-nixos but with a nix-centric development environment) who want to use and/or hack on RDV, but since that includes me and I've done the work anyways, I might as well publish.
It might be possible to upstream `randovania.nix` into nixpkgs so that people can install it via the package manager, but it's not ready for that yet -- at minimum it needs additional metadata marking it not cross-compileable and whatnot.
=> Add nix/nixos support files.

CHANGELOG.md, randovania/games/dread/logic_database/Cataris.json, randovania/games/dread/logic_database/Cataris.txt
This PR basically bundles two unrelated Cataris logic changes into one; the only thing they have in common is that they coincidentally involve heated rooms.
- One change involves the Energy Part pickup in Thermal Device Room North. For those unfamiliar, this pickup is placed in a room that is normally heated, but you can turn the heat off by activating the "Cataris - Lower Lava Button" event in Lava Button West. The problem was that the connection between "Tunnel to Lava Button West" and "Pickup (Energy Part)" (and vice versa) expected you to have the Varia Suit in order to avoid taking heat damage, even though it was possible to avoid it via the event as well. I added the event to the logic for these connections; this will potentially affect item placement (for example, I think it was …
=> Fix some logic involving heated rooms in Cataris

CHANGELOG.md, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/dialog/cosmetic_patches_dialog.py, randovania/games/samus_returns/gui/ui_files/msr_cosmetic_patches_dialog.ui, randovania/games/samus_returns/layout/msr_cosmetic_patches.py, randovania/interface_common/persisted_options.py, test/games/samus_returns/gui/dialog/test_msr_cosmetic_patches_dialog.py, test/test_files/patcher_data/samus_returns/samus_returns/arachnus_boss_start_inventory/cosmetic_1.json, test/test_files/patcher_data/samus_returns/samus_returns/arachnus_boss_start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/diggernaut_boss_free_placement_dna/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/progressive_beams_and_suits/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/queen_boss_custom_required_dna/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
As was discussed in [the server](https://discord.com/channels/914291389293027329/1236719072318718084/1340834768714993716), there is no reason to have `enable_remote_lua` be optional when exporting. Now, it will always be enabled.
Removed from `Cosmetic Options` as shown below:
=> MSR - Force enable `enable_remote_lua` when exporting

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 5 Tower Interior.json, randovania/games/samus_returns/logic_database/Area 5 Tower Interior.txt, randovania/games/samus_returns/logic_database/header.json
An path to the item with a Melee Clip expected passing through the top Grapple Block without moving it on the return trip.
=> MSR - Fix A5 Grapple Shuffler Logic

CHANGELOG.md, randovania/games/samus_returns/assets/migration_data.json, randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/generator/pool_creator.py, randovania/games/samus_returns/gui/preset_settings/msr_goal_tab.py, randovania/games/samus_returns/gui/ui_files/preset_msr_goal.ui, randovania/games/samus_returns/logic_database/Area 4 Crystal Mines.json, randovania/games/samus_returns/logic_database/Area 4 Crystal Mines.txt, randovania/games/samus_returns/logic_database/header.json, randovania/layout/description_migration.py, test/games/samus_returns/generator/test_msr_bootstrap.py, test/games/samus_returns/generator/test_msr_pool_creator.py, test/games/samus_returns/gui/preset_settings/test_msr_goal_tab.py, test/test_files/patcher_data/samus_returns/multi-am2r+cs+dread+prime1+prime2+msr/world_1.json, test/test_files/patcher_data/samus_returns/multi_coop_am2r+bdg+cs+dread+prime1+echoes+msr/world_7.json, test/test_files/patcher_data/samus_returns/samus_returns/arachnus_boss_start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/diggernaut_boss_free_placement_dna/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/progressive_beams_and_suits/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/queen_boss_custom_required_dna/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
As mentioned in the issue, the room was misnamed and thus the logic/event is also wrong. This PR fixes that.
Fixes #7884
=> MSR - Rename/Fix Gamma Arena in Area 4 Crystal Mines

randovania/games/prime2/game_data.py
should make translators significantly more common in echoes, which helps make up for hints being less powerful overall
=> echoes: increase hint action weight

randovania/games/prime2/game_data.py
Reverts randovania/randovania#7987
The changes in #7986 actually turned out to make the hint weight way more important than it previously was, so this change was overkill
=> Revert "echoes: increase hint action weight"

tools/bulk-generation/.gitignore
For bulk-generation it's useful to have an ignored output folder in the repo folder.
=> Gitignore bulk generation folder

randovania/game_connection/connector/prime_remote_connector.py, test/game_connection/connector/test_echoes_remote_connector.py, test/game_connection/connector/test_prime1_remote_connector.py
This removes the chance of it being lost by the following execute_remote_patches failing.
=> Change PickupIndexCollected to be emitted as soon as possible.

randovania/generator/hint_distributor.py
this prevents completely non-logical hints from taking potential logical targets from other hints
=> place hints with no valid targets at the end instead of the start

CHANGELOG.md, randovania/games/am2r/generator/hint_distributor.py, randovania/games/dread/generator/hint_distributor.py, randovania/games/prime1/hint_distributor.py, randovania/games/prime2/generator/hint_distributor.py, randovania/games/samus_returns/generator/hint_distributor.py, randovania/generator/hint_distributor.py, test/games/prime2/generator/test_echoes_hint_distributor.py, test/generator/filler/test_runner.py
fixes #723 (save for some extremely unlikely edge cases)
you can still get hints for an item *required* to get a translator, but that's not as immediately offensive to players as a violet hint telling you where to find violet translator
=> prevent translators from hinting themselves in echoes

CHANGELOG.md, randovania/games/prime2/logic_database/header.json, randovania/generator/dock_weakness_distributor.py
on my preset, most doors are solved in under 300 attempts, and all are solved in under 500 attempts. the 600 is just a little bit of leeway in case of weird presets. critically, this means the doors in Sky Temple can actually be non-blue, which is an important part of my intended design for echoes DLR and hasn't been working for a while
=> increase DLR attempts for echoes

CHANGELOG.md, randovania/generator/dock_weakness_distributor.py
this should affect all games with DLR in some fashion, but it most noticeably improves the performance of DLR generation in prime 1, where anything in uncrashed frigate now gets skipped (unless those elevators are shuffled ofc) rather than very slowly calculated in failure. I would suggest looking into increasing the max attempts and/or to_shuffle proprtions in prime 1 now that there aren't so many slow impossible doors to consider
=> skip resolving in DLR for impossible to reach doors

randovania/generator/filler/filler_library.py
fixes recent regression in the echoes batch generation from #8021
before:
```
[P: Light Beam] - 0.0
[P: Morph Ball Bomb] - 0.0
[P: Space Jump Boots] - 0.0
[P: Power Bomb] - 0.5
[P: Missile Launcher] - 0.375
[P: Violet Translator] - 0.0
[P: Emerald Translator] - 0.75
```
after:
```
[P: Light Beam] - 0.0
[P: Morph Ball Bomb] - 0.0
[P: Space Jump Boots] - 0.0
[P: Power Bomb] - 0.5
[P: Missile Launcher] - 0.375
[P: Violet Translator] - 0.0
[P: Emerald Translator] - 0.0
```
=> only include collectable resource nodes in UncollectedState unsafe

randovania/game_description/pickup/pickup_entry.py, randovania/gui/ui_files/game_validator_widget.ui, randovania/gui/widgets/game_validator_widget.py, randovania/resolver/logic.py, randovania/resolver/resolver.py, randovania/resolver/resolver_reach.py, test/gui/widgets/test_game_validator_widget.py
at this point I think I actually find the playthrough tab *more* readable than the generation order tab, which is a massive success imo
- adds region name
- splits major and minor pickups and allows them to be filtered separately
- filters rollbacks based on the type of action being rolled back
the big remaining issue is that EventPickup names are soooo long but idk what can be done about that lmao
=> Further improvements to playthrough tab

randovania/gui/widgets/game_validator_widget.py
the trailing space left by `logic.action_string()` was breaking the end-of-string check in the rollback regex
=> fix exception on certain rollback logs

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Community feedback suggests that long underwater walljump tricks should be hypermode/ludicrous.
Additionally, I think they should be hypermode/ludicrous so we do not give players who chose expert repetitive strain injury.
Changed:
Sector 4
* Security Access
* Door to Security -> Beside Hole
* Beside Hole -> Door to Cheddar Bay
=> fusion: update underwater walljump logic in sector 4

randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
Fixes a missing room name in sector 6 after you defeat Varia Core boss.
=> fusion(sector6): Add alternate room id for Clogged Cavern

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Made and added new video that was requested from trick spreadsheet
I increased the initial movement trick with no upgrades from intermediate to advanced
Reasons:
- If you fail any of the below you are punished heavily esp in alternate start
- Hanging, jumping, holding L, aiming down, shooting and then holding right was pretty tough to do quickly
- If you pressed "b" or did the sequence too late, you shoot the block below ruining your chances of getting out with no upgrades (which that movement trick is set to advanced. IMO this trick should match that trick since it ties to and impacts the ability to do that advanced trick at all)
In addition I also found and added in some easier methods
- You can shoot the blocks with Wave Beam or Diffusion from above making the movement much easier to …
=> Fusion Puyo Palace Trick and Video Updates

CHANGELOG.md, randovania/games/am2r/generator/base_patches_factory.py, randovania/games/dread/generator/base_patches_factory.py, randovania/games/fusion/generator/base_patches_factory.py, randovania/games/prime1/generator/base_patches_factory.py, randovania/games/prime2/generator/base_patches_factory.py, randovania/generator/base_patches_factory.py, randovania/gui/tracker_window.py, test/games/prime2/generator/test_echoes_base_patches_factory.py, test/test_files/prime2_small.json
This allows the tracker to have information that would be available to the player based on the game's configuration without "cheating" by knowing the results of the randomization.
=> Separate static base game patches from non-static.

CHANGELOG.md, randovania/game_description/requirements/base.py, randovania/game_description/requirements/node_requirement.py, randovania/game_description/requirements/requirement_and.py, randovania/game_description/requirements/requirement_or.py, randovania/game_description/requirements/requirement_template.py, randovania/game_description/requirements/resource_requirement.py, randovania/resolver/resolver_reach.py
When a chain of requirements is unsatisfied, use all requirements between heal nodes to form additional requirements, in order to capture the accumulated damage requirements.
=> Resolver: Fix unmet damage requirement chain disregarded as additional

randovania/games/fusion/gui/ui_files/fusion_game_export_dialog.ui
Jeff pointed out in the discord to have this fixed
I did not see an open issue for this, but here is the PR
Here is screenshot of how it looks with the export is unsupported text removed:
=> Fusion Remove the export is unsupported text

tools/post_discord_webhook.py
sometimes we post stuff from the stable branch, which could then get confused for a dev build even though it doesnt use the staging environment
=> clarify branch name in discord post

randovania/games/fusion/pickup_database/pickup-database.json
Fixes https://github.com/randovania/randovania/issues/8049
Moved the Keycards in the pickup databasae JSON in the categories section
Tested the gui still worked and changed a few of the items and exported to make sure stuff was still working
=> Fusion Change Keycards Order in GUI

randovania/games/fusion/exporter/joke_hints.py
Most Important PR, added in some joke hints. If some didnt land, I can remove them
- "WARNING: No hint without authorization"
- "If you do not know where you are going, you are playing Metroid conFUSION"
- "Someone who looked just like you already claimed this hint"
- "The electrified water is quite shocking"
- "Did Gary touch the thermostat again?"
=> Fusion More Joke Hints

randovania/game_connection/connector/cs_remote_connector.py, randovania/game_description/pickup/pickup_entry.py, randovania/games/cave_story/exporter/patch_data_factory.py, randovania/generator/pickup_pool/pickup_creator.py, test/conftest.py
this makes it a lot more convenient to access in the PDF and in connectors, where this is the most relevant. especially helpful for generated pickups, where the old pattern of getting a pickup definition by name wasn't possible
=> add extra to pickupentry

randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt
Added
- The trick video for the beginner logic frozen enemies and wall jump
Changed
- Adjusted comments on other tricks to match and be consistent with what I was seeing in the rest of the db
- Adjusted the existing Frozen Enemies No Wall Jump video comment to the intermediate trick it was meant for (this should also fix the trick report)
I understand the tricks are close, but had a seed where only beginner logic was required and thought the intermedate was the beginner. Made a new video and adjustments in hopes this clears it all up
=> Fusion Traning Grounds Video and Clean Up Comments

randovania/game_description/pickup/pickup_definition/ammo_pickup.py, randovania/games/fusion/pickup_database/pickup-database.json, randovania/games/prime1/pickup_database/pickup-database.json, randovania/gui/preset_settings/item_pool_tab.py
Fixes https://github.com/randovania/randovania/issues/7959
Felt this implementation was the best middle ground. There is no nice way to add in a check for hiding the required mains in the item pool gui for ammo. In fact, there is a "fix me" for prime 1 that just hard checks if the game is prime 1 and then hides required mains.
Trying to add anything into the definitions/properties for ammo_pickups blew everything sky high. Changing ammo being not temporary (so item pool gui doesnt even do required mains) blew up logic and other stuff.
In the end, I decided to add in a value to extra for the ammo in the pickup database instead. Then added a check in the item pool gui for this value. This also safely didnt hurt other games.
I could probably fix the prime 1 hardcode as well by adding this …
=> Fusion Hide Required Main Fixes

randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt
Adds morph ball checks where "can break single bomb block" template is used for morph tunnels and the missing morph ball check from the Power Bomb tank pickup.
=> fusion(sector3): Add morph-ball checks in Alcove

CHANGELOG.md, randovania/gui/dialog/async_race_proof_popup.py
=> Async Race: Make clearer that proof url is not required when submission notes were given

CHANGELOG.md, randovania/generator/filler/retcon.py, randovania/generator/old_generator_reach.py, randovania/generator/reach_lib.py
When evaluating an action that gives a dangerous action, use reach.act_on, because this function accounts for the new dangerous resource in terms of removing nodes as safe in the reach.
=> Generator: Fix not accounting for dangerous resource when evaluating

randovania/games/fusion/pickup_database/pickup-database.json
game breaks if we start with a required metroid so don't do that
=> Fusion: force infants as non-starting

CHANGELOG.md, randovania/games/dread/pickup_database/pickup-database.json, test/test_files/patcher_data/dread/dread/all_settings/world_1.json, test/test_files/patcher_data/dread/dread/crazy_settings/world_1.json, test/test_files/patcher_data/dread/multi-am2r+cs+dread+prime1+prime2/world_4.json
SBUs are now excluded from the credits (and thus the hinted item pool). The description was also changed to take randovania/open-dread-rando#398 into account, and to be less precise about the times since the minimum charge time is no longer exactly a multiple of 0.25 seconds.
=> Fix Speed Booster Upgrades being included as hintable items

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
The logic for this connection was impossible. It allowed to reach upper ladder gravless and no jump upgrade which ran by multiple people and the community, seems to be undoable by only Frozen Enemies advanced. I did enounter this in testing a seed and it was noncontinuable. 
- Fixed logic with what is possible
- Adjusted the difficulty level to reflect the tricks better
- Added in the videos
=> Fusion: Fixes to Powamp Shaft Logic

CHANGELOG.md, randovania/resolver/resolver.py
In fast branch of the resolver, fix using the wrong node when determining which dangerous resources the node gives. This is used to remove these resources from the additional requirements we set on the node.
=> Resolver: Fix resources from wrong node when rolling back dangerous items

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Thanks to Raddley Vance for pointing this out and the video
Aquarium Speedway to Kago Storage
- Gravless impossible wihout freezing the Yard to get enough height to start the UWJ
- Added Raddley's Video
- Updated the Kago Storage room to reflect the changes
Made the stand on enemies intermediate to follow the same standard that was the stand on frozen enemy in this same room. Not sure why it was intermiedate or if it should all get changed to beginner, but left at intermediate to make it consistent with what was there currently.
Testing from Raddley: 
> Yeah, just high without grav puts you about half a hitbox short of having to get a frame perfect walljump. Ice is required.
In a quick verification, I also could not reach enough high with HJ and No Grav
=> Fusion: DB Fix Aquairum Speedway and Kago Storage Requirements 

CHANGELOG.md, randovania/generator/hint_distributor.py
this fixes an issue where hint targets for specific hint locations were not being freed
sample seed shows a pickup being hinted on a specific location hint
supersedes #8313
=> Hints: if specific locations are off, fill with joke hints

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
Hotdogged the "and" in the logic for the damage run on subzero containment.
=> Fusion: Fix Sub Zero Damage Run Logic

randovania/games/fusion/presets/open_sector_hub.rdvpreset, randovania/games/fusion/presets/vanilla_start.rdvpreset, test/games/fusion/layout/test_fusion_describer.py
As requested by Jeff and Duncathan this will adjust OSH to the vanilla amount of PBs to where everything is vanilla total numbers and there is 1 nothing instead of many
I also added PBs in the vanilla start item pool until it was full as well to try and keep things consistent.
Updated the preset description as well to match the numbers for test validation
=> Fusion: Update Preset Item Pool Numbers

pyproject.toml, randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/fusion/pickup_database/pickup-database.json, test/test_files/log_files/fusion/starting_items.rdvgame, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/fusion/starting_items/world_1.json, uv.lock
Issues reported:
- Launchers did not give ammo with multiple copies shuffled
- Starting with ammo tanks was not considered
With the new changes on the patcher/asm side for how launcher is handled, adjusted the RDV side to match and address the two issues above.
- Updated mars to patcher 0.5.0 in the reqs
- Initialized missiles and pbs to `0` since that is now possible/intended depending on settings
- Adjusted the cases to now consider launcher amount and ammos together as intented for starting
- Added MissileData and PowerBombData to match new patcher/asm changes
- Updated test files to reflect new chaanges
Tested (includes other stuff in the patcher/asm update)
- A bunch of starting ammo/launcher configs
- With starting ammo, checked it out in the status screen, worked good
- Increments …
=> Fusion: Launcher Adjustments

randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/fusion/logic_database/header.json, test/games/fusion/exporter/test_fusion_game_exporter.py, test/games/test_log_file_export.py, test/test_files/log_files/fusion/all_hidden_with_random.rdvgame, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/all_hidden_with_random/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/fusion/starting_items/world_1.json, test/test_files/patcher_data/fusion/shiny_pickups_dict_from_starter_preset.json, uv.lock
Updates the mars-patcher package to add base accessibility patches, item jingles, and MessageIDs for infant metroids.
Message IDs are referenced as decimal in RDV, but Hex in asm. [Their values can be found here](https://github.com/MetroidAdvRandomizerSystem/mars-fusion-asm/blob/main/inc/enums.inc#L130)
~~Will depend on a patcher release which hasn't been published yet.~~
=> fusion: add item jingles and infant metroid automessage

CHANGELOG.md, randovania/games/dread/logic_database/Cataris.json, randovania/games/dread/logic_database/Cataris.txt, randovania/games/dread/logic_database/header.json
The logic is meant to break the missile door, then set up the ledge warp, then roll into the room by opening the door with a bomb. However, it's important that the bomb is not placed on the diffusion beam pickup.
=> Dread: Fix oversight with ledge warping out of diffusion beam room

CHANGELOG.md, randovania/games/fusion/exporter/patch_data_factory.py, test/test_files/log_files/fusion/all_hidden_with_random.rdvgame, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/all_hidden_with_random/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/fusion/starting_items/world_1.json
Changed one rdvgame in order to hit the test case of "nothing was replaced with metroid data"
=> Fusion: Fix hide-with-random on nothings

CHANGELOG.md, randovania/games/fusion/gui/dialog/game_export_dialog.py
I have no clue how this can even happen considering we use is_file_validator right before. Couldn't find anything on the docs either, other than invalid path or no perms to open, neither of which I think are the case here
But apparently it does happen, so band-aid it is.
=> Fusion: Fix unable to export game in weird edge case

randovania/cli/commands/new_game.py, randovania/cli/commands/refresh_presets.py, randovania/game/data.py, randovania/games/am2r/game_data.py, randovania/games/blank/game_data.py, randovania/games/cave_story/game_data.py, randovania/games/dread/game_data.py, randovania/games/factorio/game_data.py, randovania/games/fusion/game_data.py, randovania/games/planets_zebeth/game_data.py, randovania/games/prime1/game_data.py, randovania/games/prime2/game_data.py, randovania/games/prime_hunters/game_data.py, randovania/games/samus_returns/game_data.py, randovania/interface_common/preset_manager.py, test/games/test_game.py
Having a hardcoded key in a dictionary kinda defeats the purpose of using the dictionary in the first place.
I feel like there may have been plans in the past to use something other than paths (including preset directly?) which was never used.
=> Make included presets a list of filenames, instead of a dict with hardcoded key

CHANGELOG.md, randovania/gui/game_details/game_details_window.py, randovania/gui/main_window.py, randovania/gui/multiplayer_session_window.py
Randomly stumbled upon this. Parameter indicates stretching.
Long text now:
=> Status Bar: Increase message length before wrapping

randovania/games/fusion/exporter/patch_data_factory.py, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/all_hidden_with_random/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/fusion/starting_items/world_1.json
The fusion credits wants to write one blank line. Previously this was done by writing an empty string as a new line.
However it is much more memory efficient for the game, to just tell the previous element to include one more newlines.
This doesn't *fully* make the "Credits exceeded length" dissapear, but it postpones it to where 99% of people won't encounter it.
Before this change, I was able to trigger it by only including a few duplicates, after this change in order to trigger it, I have to shuffle ~95 majors (out of 127 locations). 
Fixes https://randovania.sentry.io/issues/6916113458/
=> Fusion: optimize blank line in credits

CHANGELOG.md, randovania/games/am2r/game_data.py, randovania/games/fusion/game_data.py, randovania/games/prime1/game_data.py, randovania/games/prime2/game_data.py, randovania/games/samus_returns/game_data.py, randovania/gui/generated/preset_hints_ui.py, randovania/gui/preset_settings/hints_tab.py, randovania/gui/ui_files/preset_hints.ui, randovania/layout/preset_describer.py, test/games/am2r/layout/test_am2r_describer.py, test/games/prime1/layout/test_preset_describer.py, test/games/prime2/layout/test_echoes_preset_describer.py, test/games/samus_returns/layout/test_msr_describer.py, test/gui/preset_settings/test_hints_tab.py
Gets rid of the ugly nested groupbox
=> GUI: Clean up how Specific Pickup Hints are displayed

randovania/lib/obfuscator.py, tools/create_release.py
The file is already checked by mypy, but these errors only occur if it can import the secret and thus basically never happens for us.
Happened for me as I had an old generated secret for some debugging.
=> Some adjusted typing in obfuscator
