randovania/randovania

README.md, tools/start_debug_client.sh, tools/start_dev_server.sh
I was too lazy to type these all out every time for MW testing.
=> Add bash scripts for debug client/server for Unix

.github/workflows/daily-generate.yml
am2r is relatively quick to generate, so would that like on two days
bumped the time to be earlier to hopefully be less conflicting with other schedules (and also because it aligns better with my timezone)
=> Add AM2R to daily generate

randovania/games/am2r/generator/bootstrap.py
Forgot to add them apparently.
=> AM2R: Add missing logical patches

CHANGELOG.md, randovania/generator/filler/pickup_list.py
Ran 2k of am2r+prime+echoes, couldnt see any big regressions so far.
prime and dread probably would benefit the most from this
=> Generator: handle negative requirements a little better

CHANGELOG.md, randovania/games/prime2/json_data/Agon Wastes.json, randovania/games/prime2/json_data/Agon Wastes.txt, randovania/games/prime2/json_data/Sanctuary Fortress.json, randovania/games/prime2/json_data/Sanctuary Fortress.txt, randovania/games/prime2/json_data/Temple Grounds.json, randovania/games/prime2/json_data/Temple Grounds.txt, randovania/games/prime2/json_data/Torvus Bog.json, randovania/games/prime2/json_data/Torvus Bog.txt
- Added: 15 videos to the logic database. see the [Video Directory] (https://randovania.github.io/Metroid%20Prime%202%20Echoes/) for the full collection
- Added: Comments to some Beginner Bomb Jump tricks
- Added: Watch Staton: Bomb Space Jump (Advanced) to reach the Spidertrack (Standable Terrain (Advanced)) to reach the Bomb Slot with an Instant Morph (Advanced)
=> Echoes: Logic Updates and Video Upload

CHANGELOG.md, randovania/games/am2r/presets/starter_preset.rdvpreset, randovania/games/blank/presets/starter_preset.rdvpreset, randovania/games/cave_story/presets/classic.rdvpreset, randovania/games/cave_story/presets/starter_preset.rdvpreset, randovania/games/dread/presets/april_fools_2023.rdvpreset, randovania/games/dread/presets/starter_preset.rdvpreset, randovania/games/prime1/presets/april_fools_2022.rdvpreset, randovania/games/prime1/presets/moderate_challenge.rdvpreset, randovania/games/prime1/presets/starter_preset.rdvpreset, randovania/games/prime2/presets/darkszero_deluxe.rdvpreset, randovania/games/prime2/presets/fewest_changes.rdvpreset, randovania/games/prime2/presets/starter_preset.rdvpreset, randovania/games/prime3/presets/starter_preset.rdvpreset, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/games/super_metroid/presets/starter_preset.rdvpreset, randovania/layout/preset_migration.py, test/test_files/patcher_data/dread/crazy_settings.json, test/test_files/patcher_data/dread/custom_start.json, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json, test/test_files/patcher_data/dread/elevator_rando.json, test/test_files/patcher_data/dread/starter_preset.json
Also refresh all presets to latest
=> Power Bomb Limitations migrates to false

randovania/gui/ui_files/games_tab_dread_widget.ui
Changed: "seed" to "game"
To get started, use the Quick Generate button below to generate a  ̶s̶e̶e̶d̶ game using the default settings!
=> Update to Dread landing page.

CHANGELOG.md, randovania/gui/data_editor.py, randovania/gui/docks/connection_filtering_widget.py, randovania/gui/main_window.py, randovania/gui/ui_files/data_editor.ui, test/gui/docks/test_connection_layer_widget.py, test/gui/test_data_editor.py
=> Add checkbox to quickly toggle if trick filters are enabled

CHANGELOG.md, randovania/gui/data_editor.py
=> Add an alert for how many requirements were filtered

randovania/games/am2r/game_data.py, randovania/games/am2r/layout/preset_describer.py, randovania/games/am2r/pickup_database/item_data.json, randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/am2r/pickup_database/progressive_items.py, randovania/games/am2r/presets/starter_preset.rdvpreset, randovania/games/game.py, randovania/games/prime3/pickup_database/progressive_items.py, test/games/am2r/layout/test_am2r_describer.py
Adds progressive suit and jumps
None of them are enabled by default at the moment, as I'd like to only do that once I get non-placeholder sprites for them.
=> AM2R: Add progressives

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/Golden Temple.json, randovania/games/am2r/json_data/Golden Temple.txt, randovania/games/am2r/json_data/Hydro Station.json, randovania/games/am2r/json_data/Hydro Station.txt, randovania/games/am2r/json_data/Industrial Complex.json, randovania/games/am2r/json_data/Industrial Complex.txt, randovania/games/am2r/json_data/The Depths.json, randovania/games/am2r/json_data/The Depths.txt
The only nice-to-have logic changes on the list are now mandatory damage for some enemies, boss reworks, and hypermode bullshit
=> AM2R: Misc logic changes

CHANGELOG.md, randovania/gui/tracker_window.py, test/gui/test_tracker_window.py
The best description for this PR: 
"I tried to make it less broken."
=> Change tracker to use Nodes instead of Areas

randovania/games/super_metroid/json_data/Ceres Station.json, randovania/games/super_metroid/json_data/Ceres Station.txt, randovania/games/super_metroid/json_data/Crateria.json, randovania/games/super_metroid/json_data/Crateria.txt, randovania/games/super_metroid/json_data/header.json, randovania/games/super_metroid/json_data/header.txt, randovania/games/super_metroid/presets/starter_preset.rdvpreset
There are a bunch of TODOs in there. If you have some more knowledge on them, please fill me in and i'll fix them. If you don't, then I'll leave them as is.
@Logarhythmic (still cannot add you as a reviewer...)
=> SM: Revise Crateria Logic even more

randovania/games/super_metroid/json_data/Ceres Station.json, randovania/games/super_metroid/json_data/Ceres Station.txt
https://wiki.supermetroid.run/List_of_rooms#Ceres_Station
=> SM: Update Ceres room names to be according to wiki

randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/generator/pool_creator.py, randovania/games/samus_returns/gui/preset_settings/__init__.py, randovania/games/samus_returns/gui/preset_settings/msr_goal_tab.py, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_goal.ui, test/conftest.py, test/games/samus_returns/conftest.py, test/games/samus_returns/generator/test_msr_bootstrap.py, test/games/samus_returns/generator/test_msr_pool_creator.py, test/games/samus_returns/layout/test_msr_describer.py, test/test_files/log_files/samus_returns/starter_preset.rdvgame
Just for the record: I have a couple of commits and I'm going to split them.
(don't worry too much about the rdvgame because there will be a few changes in each commit)
=> MSR: Add Goal Tab+ Code for the DNA

randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/preset_settings/__init__.py, randovania/games/samus_returns/gui/preset_settings/msr_aeion_tab.py, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_aeion.ui, test/games/samus_returns/gui/test_msr_aeion_tab.py, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/patcher_data/samus_returns/starter_preset.json
=> MSR: Add Aeion tab

randovania/games/super_metroid/json_data/Crateria.json, randovania/games/super_metroid/json_data/Crateria.txt, randovania/games/super_metroid/json_data/header.json, randovania/games/super_metroid/json_data/header.txt
Added Crateria Door Wakup Type
=> SM: Add Crateria Wakeup Doortype

randovania/games/samus_returns/json_data/Surface - West.json, randovania/games/samus_returns/json_data/Surface - West.txt, randovania/games/samus_returns/json_data/header.json, randovania/games/samus_returns/json_data/header.txt
=> Samus Returns - Fix lingering connections bypassing DNA Check

CHANGELOG.md, randovania/games/dread/gui/preset_settings/dread_patches_tab.py, randovania/games/dread/layout/dread_configuration.py, randovania/games/dread/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_dread_patches.ui, test/games/dread/layout/test_dread_configuration.py
=> Mark PB limitation as unsupported feature.

tools/create_release.py
Consistently gets the same nintendont for a given commit, and probably fails less with rate limiting.
=> Download one specific nintendont version directly

randovania/games/am2r/json_data/Distribution Center.json, randovania/games/am2r/json_data/Distribution Center.txt, randovania/games/am2r/json_data/header.json, randovania/games/am2r/json_data/header.txt
Bumped ammo requirements for dual alphas and alpha squad, reworked alpha squad escape.
=> AM2R: multi alpha fight logic

randovania/games/samus_returns/pickup_database/pickup-database.json, test/test_files/patcher_data/samus_returns/starter_preset.json
I thought this was fixed 10 times already >_>
=> MSR - Actually use baby model for baby

randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/gui/preset_settings/msr_patches_tab.py, randovania/games/samus_returns/json_data/Area 8.json, randovania/games/samus_returns/json_data/Area 8.txt, randovania/games/samus_returns/json_data/header.json, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_patches.ui, test/games/samus_returns/layout/test_msr_describer.py, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/patcher_data/samus_returns/starter_preset.json
Also fix Optional Patches not persisting
=> MSR - Update A8 to support queen wall removal

randovania/games/super_metroid/json_data/Brinstar.json, randovania/games/super_metroid/json_data/Brinstar.txt, randovania/games/super_metroid/json_data/Crateria.json, randovania/games/super_metroid/json_data/Crateria.txt
Update on Rooms A2 through A10 on the spreadsheet.
https://docs.google.com/spreadsheets/d/1s04k5ZuvCV28-ZJtZbVghlfMCg0Szr6hh69tFAjXv3E/edit?usp=sharing
=> SM Logic: A2-A10 

CHANGELOG.md, randovania/games/dread/json_data/header.json, randovania/games/dread/json_data/header.txt
Not quite sure how to handle changelog
=> Dread: Change Charge Beam door weakness to use proper template

randovania/games/prime3/json_data/Pirate Homeworld - Research.json, randovania/games/prime3/json_data/Pirate Homeworld - Research.txt, randovania/games/prime3/json_data/header.json
This PR reorganizes the node connections within Scrapworks to make it solver-friendly to collect the items, as well as accounting for possible room rando with the additions of the three new events.
=> Corruption: Scrapworks Logic Refinement

.github/workflows/build-test-publish.yml
Helps when troubleshooting certain things / a build failed for a random reason / other things where we want to manually (re)run one
=> Allow manually running "Python" workflow

randovania/games/am2r/pickup_database/pickup-database.json
i blame jeff for not catching it in the first pr
=> Am3r fix wrong model names

randovania/games/am2r/pickup_database/item_data.json
Update descriptions for speed booster upgrades, flashlight, and blindfold.
=> AM2R: Update item descriptions

CHANGELOG.md, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt
Getting Item and leave was a bit to high. Should also help the solver.
=> Lowering Warrior's Walk health requirements

randovania/games/am2r/exporter/patch_data_factory.py, test/games/am2r/exporter/test_am2r_patch_data_factory.py, test/test_files/log_files/am2r/progressive_items.rdvgame, test/test_files/patcher_data/am2r/progressive_items.json
No clue how the other one failed cause i did test it.
=> AM2R: fix spoiler log in credits being broken

Dockerfile.server
Fixes https://randovania.sentry.io/issues/4570879949/?project=4504594037276672&referrer=github-pr-bot
=> Install exporters for servers, needed for Cave Story.

randovania/games/am2r/gui/dialog/game_export_dialog.py, test/games/am2r/gui/test_am2r_game_export_dialog.py
No idea if I should write tests for that function, and if yes how.
=> AM2R: Add better input validation

CHANGELOG.md, randovania/games/prime1/gui/dialog/prime_cosmetic_patches_dialog.py, randovania/games/prime2/gui/dialog/echoes_cosmetic_patches_dialog.py
=> Fix Prime 1 cosmetic patches dialog labels

CHANGELOG.md, README.md, randovania/games/am2r/game_data.py
The header in changelog should be changed to 7.0.0 at one point,but not sure if we're still waiting on a patch or two.
=> Add am2r to stable

randovania/games/super_metroid/logic_database/Crateria.json, randovania/games/super_metroid/logic_database/Crateria.txt, randovania/games/super_metroid/logic_database/header.json
Logic update for A83 to A95 on spreadsheet.
Added videos for several connections.
Spreadsheet: 
https://docs.google.com/spreadsheets/d/1s04k5ZuvCV28-ZJtZbVghlfMCg0Szr6hh69tFAjXv3E/edit?usp=sharing
=> SM Logic Update A83 to A95

randovania/gui/lib/flow_layout.py
Removed unnecessary declaration of `x`
Added test of visibility to layout creation
Added removal of excess padding
=> Fix Flowlayout to address game selection

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Surface - East.json, randovania/games/samus_returns/logic_database/Surface - East.txt
Not sure if i did this entirely right, Added a Generic Node, changed it to open passage dock to the teleporter in next room.
Then added the requirements for it in the connection from the start point to it, this IS a one way connection.
=> Add Ice/Melee Clip dock to get to teleporter room from teleporter Access in area 1

randovania/games/samus_returns/logic_database/header.json
Now includes checks for Bombs, Space Jump, and Spider so at least one of those won't be locked. Does not fully guarantee success but it increases the chances.
=> MSR - Support Minimal Logic

CHANGELOG.md, randovania/data/gui_assets/tracker/am2r-game-4x5.json, randovania/data/gui_assets/tracker/prime2-game-eight-lines.json, randovania/data/gui_assets/tracker/prime2-game-three-lines.json, randovania/data/gui_assets/tracker/prime2-game-two-lines.json, randovania/data/gui_assets/tracker/prime2-pixel-eight-lines.json, randovania/data/gui_assets/tracker/prime2-pixel-three-lines.json, randovania/data/gui_assets/tracker/prime2-pixel-two-lines.json
Set `disabled_image_path` for all trackers with progressive suits
=> Autotracker: Progressive Suit bug fix

CHANGELOG.md, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
- Health and dodging requirements separated
- Health scaled for multiple difficulties
- Dodging requirements expanded
=> AM2R: Zeta/Omega rebalances

randovania/lib/ftp_uploader.py
lot of red X here in the PR overview...oops!
=> Add return types for ftp_uploader.py

CHANGELOG.md, requirements.txt
Bumps the dependency and changes changelog accordingly.
=> Bump am2r_yams to 1.0.2

CHANGELOG.md, randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt
Mostly changes related to using Speed Booster, but also some fixes.
=> Dread: Various changes in Artaria EMMI Zone Hub

randovania/games/samus_returns/exporter/patch_data_factory.py, test/games/samus_returns/exporter/test_msr_patch_data_factory.py, test/test_files/log_files/samus_returns/start_inventory.rdvgame, test/test_files/patcher_data/samus_returns/start_inventory.json
EDIT: Oh wait. This could actually be covered by a test
=> Use export id for starting inventory

CHANGELOG.md, pyproject.toml, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/generator/bootstrap.py, randovania/games/prime1/layout/preset_describer.py, randovania/games/prime1/layout/prime_configuration.py, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt, randovania/games/prime1/logic_database/Frigate Orpheon.json, randovania/games/prime1/logic_database/Frigate Orpheon.txt, randovania/games/prime1/logic_database/Impact Crater.json, randovania/games/prime1/logic_database/Impact Crater.txt, randovania/games/prime1/logic_database/Magmoor Caverns.json, randovania/games/prime1/logic_database/Magmoor Caverns.txt, randovania/games/prime1/logic_database/Phazon Mines.json, randovania/games/prime1/logic_database/Phazon Mines.txt, randovania/games/prime1/logic_database/Phendrana Drifts.json, randovania/games/prime1/logic_database/Phendrana Drifts.txt, randovania/games/prime1/logic_database/header.json, randovania/gui/preset_settings/patcher_energy_tab.py, randovania/gui/ui_files/preset_patcher_energy.ui, randovania/gui/ui_files/preset_prime_qol.ui, randovania/layout/preset_migration.py, requirements.txt, test/test_files/log_files/prime1_crazy_seed_one_way_door.rdvgame, test/test_files/patcher_data/prime1/all_game_multi/world_2.json, test/test_files/patcher_data/prime1/all_game_multi/world_6.json, test/test_files/randomprime_expected_data.json, test/test_files/randomprime_expected_data_crazy.json, test/test_files/randomprime_expected_data_one_way_door.json
Mostly just Hard Mode bootstrapping that needs review, thanks!
=> Randomprime v1.20.1

CHANGELOG.md, pyproject.toml, randovania/cli/commands/export_db_videos.py, requirements-setuptools.txt, requirements.txt
[Before.zip](https://github.com/randovania/randovania/files/13537854/Before.zip)
[After.zip](https://github.com/randovania/randovania/files/13537855/After.zip)
=> Improve db video static site generator

randovania/games/dread/gui/dialog/game_export_dialog.py, randovania/games/samus_returns/exporter/game_exporter.py, randovania/games/samus_returns/exporter/options.py, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/game_data.py, randovania/games/samus_returns/gui/dialog/game_export_dialog.py, randovania/gui/ui_files/msr_game_export_dialog.ui, randovania/lib/windows_drives.py, test/games/samus_returns/exporter/test_msr_game_exporter.py, test/games/samus_returns/exporter/test_msr_options.py, test/games/samus_returns/gui/test_msr_game_export_dialog.py, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
Will be activated if we feel ready for beta test, have a released of the patcher etc.
=> Add (disabled) export functionality for MSR

randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
Unsure if I need to write a changelog entry for this. This does not change any logic, only door types, which currently are not referenced anywhere.
Area transitions have been currently removed. For the future, when we'll do area rando, we can determine the needed types by extra data.
=> AM2R: do some door type revision

randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
Docks for Main Caves updated to Horizontal Docks.
=> Update open passage to horizontal docks for Main Caves

randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
Excluded from this PR:
- one way paths (BG2 shinespark, Tower Interior)
- Tower exterior
=> Add vertical dock information

CHANGELOG.md, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
- 15 Videos
- IBJ to reach Inner Alpha Nest South Item
- Shinespark conservation to reach Hi-Jump Challenge Item
=> AM2R: Add videos to DB, minor trick additions

randovania/games/samus_returns/logic_database/Area 6.json, randovania/games/samus_returns/logic_database/Area 6.txt, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt
- Improves Trickless logic for Area 6
- Adds template for defeating enemies that can't be countered
=> MSR - Update A6 Trickless Logic

randovania/games/samus_returns/logic_database/Area 5 - Interior.json, randovania/games/samus_returns/logic_database/Area 5 - Interior.txt, randovania/games/samus_returns/logic_database/Area 7.json, randovania/games/samus_returns/logic_database/Area 7.txt, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt
- Updates all Metroid fight templates to have proper logic
- Adds new trick for fighting Metroids without Missiles or Supers (not super relevant right now until shuffled Missiles is possible)
=> MSR - Update all Metroid fight templates

randovania/games/samus_returns/game_data.py, randovania/games/samus_returns/gui/__init__.py, randovania/games/samus_returns/gui/hint_details_tab.py
Adds the Hint Tab to the generated game window. I don't know why there's so much padding for each hint
=> MSR - Add hint tab to generated game window

randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt
=> AM2R: Add extra data for transitions in GT

randovania/games/samus_returns/logic_database/Area 2 - Exterior.json, randovania/games/samus_returns/logic_database/Area 2 - Exterior.txt
- Adds Morph Ball to Space Jump path to collect outer item
- Adjusts Spiderspark requirements in exterior to require the trick at proper levels
=> MSR - Fix A2 Exterior item and climb requirements

randovania/games/samus_returns/exporter/game_exporter.py, randovania/games/samus_returns/exporter/patch_data_factory.py, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
=> MSR - Add OSRR version number to file select screen

randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt
i think we're halfway done now in terms of areas
=> AM2R: extra data to 4-high labs docks

CHANGELOG.md, randovania/games/prime1/logic_database/Tallon Overworld.json, randovania/games/prime1/logic_database/Tallon Overworld.txt
- Adds way to reach the landing site item without morph ball
=> MP1: Landing Site SR OoB

CHANGELOG.md, pyproject.toml, requirements.txt
Changes from Randomprime v1.21.0
=> Stable Prime1 Changes

randovania/games/am2r/exporter/patch_data_factory.py, test/games/am2r/exporter/test_am2r_patch_data_factory.py, test/test_files/log_files/am2r/starting_items.rdvgame, test/test_files/patcher_data/am2r/door_lock.json, test/test_files/patcher_data/am2r/progressive_items.json, test/test_files/patcher_data/am2r/starting_items.json
Fixes #5111 
Not sure if there's a nicer way to do something like:
```py
return {
...
if starting_memo:
"starting_memo": starting_memo
}
=> AM2R: Add starting items memo

CHANGELOG.md, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt
Added: more beam requirements
Added: dodging requirements
TODO: changelog and reword comments.
=> AM2R: Queen logic revisit

CHANGELOG.md, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt
- Added: more thorough health requirements for Arachnus
- Changed: Torizo fight reworked
=> AM2R: Update Arachnus and Tester reqs

randovania/games/samus_returns/exporter/patch_data_factory.py, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
https://github.com/randovania/open-samus-returns-rando/pull/231
=> Add Rando-ID for save game check

randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt
=> Am2R: extra data to A2 4 tile docks

randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt
=> AM2R: finish 4 tile extra data in A3

CHANGELOG.md, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
=> AM2R: add support for research site hatch

randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt
Part of the future "force lab doors to be blue" option. PRing this seperately, so that the future PR gets easier to review
=> AM2R: add extra data for blue lab doors

CHANGELOG.md
#5748 was missing a changelog entry. this adds it.
=> Add missing changelog for stream friendly autotrackers

requirements.txt
Changelog entry not needed here, as the featureset is the exact same as before. just fixing unexpected behaviour from #5791
=> Bump yams to 1.1.1

requirements.txt
Changelog entry not needed here, as the featureset is the exact same as before. just fixing unexpected behaviour from #5793
=> bump am2r yams to 1.1.2

randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/generator/pool_creator.py, randovania/games/samus_returns/gui/preset_settings/msr_goal_tab.py, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_goal.ui, test/games/samus_returns/generator/test_msr_bootstrap.py, test/games/samus_returns/generator/test_msr_pool_creator.py, test/games/samus_returns/gui/preset_settings/test_msr_goal_tab.py, test/games/samus_returns/layout/test_msr_describer.py, test/test_files/log_files/samus_returns/start_inventory.rdvgame, test/test_files/log_files/samus_returns/starter_preset.rdvgame
Preferred Placement
Free Placement
=> MSR - Support logical/offworld DNA anywhere

randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt, randovania/gui/ui_files/preset_msr_patches.ui, test/games/samus_returns/layout/test_msr_describer.py
- Renamed Nerf Supers for more clarity on what is actually happening (will change back if we figure out block stuff)
- Updated preset describer
=> MSR - Minor UI Updates

randovania/games/prime1/generator/pickup_pool/artifacts.py, randovania/games/prime1/pickup_database/pickup-database.json
AM2r now has unique models for prime.
=> Add am2r models for prime offworld

randovania/game_connection/builder/am2r_connector_builder.py, randovania/game_connection/builder/connector_builder_option.py, randovania/game_connection/connector/am2r_remote_connector.py, randovania/game_connection/connector/remote_connector.py, randovania/game_connection/connector_builder_choice.py, randovania/game_connection/executor/am2r_executor.py, randovania/game_connection/executor/dread_executor.py, randovania/games/am2r/game_data.py, randovania/games/am2r/gui/dialog/game_export_dialog.py, randovania/gui/widgets/game_connection_window.py, test/conftest.py, test/game_connection/builder/test_am2r_connector_builder.py, test/game_connection/connector/test_am2r_remote_connector.py, test/game_connection/executor/test_am2r_executor.py
Stuff still to fix:
~~- mypy errors (waiting for this PR)~~
~~- add tests (want to wait implementing them until after a basic review, so that I dont write tests for something thats still changing)~~
- some bugs on patcher side + new patcher version (will come after this PR)
=> Implement AM2R Multiworld

randovania/games/am2r/pickup_database/model_data.json
These were supposed to be updated with #5841
=> Add missing animation speeds for models

randovania/games/dread/pickup_database/pickup-database.json
Checked in YAMS that names are equal.
=> AM2R: Fix offworld item for Dread Epart

randovania/games/prime2/pickup_database/pickup-database.json
=> AM2R: Fix offworld item for Echoes Supers

randovania/gui/widgets/base_game_tab_widget.py, randovania/gui/widgets/generate_game_widget.py
Also added type annotations. Just need to wait for mypy if they are correct and I wasn't bothered to add a test😶
Before:
After:
Before:
After:
=> Disable "Quick Generate" and "Generate without retry" if preset is invalid

randovania/games/am2r/pickup_database/pickup-database.json
Fixes https://github.com/randovania/YAMS/issues/148
=> Clarify am2r speedbooster upgrades

CHANGELOG.md, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
- gravity required for trickless and beginner combat
- health required adjusted around above change
fixes https://github.com/randovania/YAMS/issues/155
=> AM2R: Dual Gammas require gravity for trickless

CHANGELOG.md, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
Main goal was to fix possibility of a trickless SJ-less fight with enough E-tanks.
Actual Health values still likely need adjusting.
=> AM2R: Tester rebalance

CHANGELOG.md
Missing changelog entry for #5848
=> Add missing changelog for qdesktopservices

randovania/games/samus_returns/logic_database/Area 2 - Interior.json, randovania/games/samus_returns/logic_database/Area 2 - Interior.txt
=> MSR - Fix wrong dock type in A2 Interior

CHANGELOG.md, randovania/games/am2r/pickup_database/model_data.json, randovania/games/prime1/generator/pickup_pool/artifacts.py, randovania/games/prime2/pickup_database/pickup-database.json, requirements.txt
Apparently the MW PR *and* the earlier dependency bump PR forgot to add a changelog entry. whoops.
=> Bump am2r-yams to 1.2.2

CHANGELOG.md, randovania/games/am2r/assets/migration_data.json, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/layout/description_migration.py, test/test_files/patcher_data/am2r/door_lock.json, test/test_files/patcher_data/am2r/progressive_items.json, test/test_files/patcher_data/am2r/starter_preset.json, test/test_files/patcher_data/am2r/starting_items.json
Fixes https://github.com/randovania/YAMS/issues/154
=> AM2R: rename area "spazer beam" -> "spazer beam chamber"

test/games/prime2/patcher/test_patch_data_generator.py, test/test_files/log_files/prime2_no_pbs.rdvgame, test/test_files/patcher_data/prime2/prime2_no_pbs_new_patcher.json, test/test_files/patcher_data/prime2/prime2_no_pbs_old_patcher.json, test/test_files/patcher_data/prime2/seed_a_new_patcher.json, test/test_files/patcher_data/prime2/seed_a_old_patcher.json
The thing I mentioned from here https://github.com/randovania/randovania/pull/5387#issuecomment-1746894851
=> Create more detailed tests for prime2

randovania/games/super_metroid/exporter/game_exporter.py
=> Delay SDM import

randovania/games/samus_returns/generator/bootstrap.py, randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Area 2 - Entrance.json, randovania/games/samus_returns/logic_database/Area 2 - Entrance.txt, randovania/games/samus_returns/logic_database/Area 4 - East.json, randovania/games/samus_returns/logic_database/Area 4 - East.txt, randovania/games/samus_returns/logic_database/header.json
Preparing for the future and this fixes a current logic issue in Area 2 Entrance, so win-win.
- Adds misc resource for Door Lock Rando
- Fixes node connections to account for resouces
- Fixes broken logic in Area 2 Entrance
=> MSR - Add misc resource for Door Lock Rando

CHANGELOG.md, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt
closes https://github.com/randovania/YAMS/issues/156
=> AM2R: Guardian quick kill and trick videos

CHANGELOG.md, randovania/games/dread/pickup_database/pickup-database.json
=> Dread: change SpeedBoster+FlashShift upgrades to be minor

randovania/games/dread/pickup_database/pickup-database.json, randovania/games/prime1/generator/pickup_pool/artifacts.py, requirements.txt
Changelog entry not needed, as this is still bugfixing from the MultiWorld feature.
=> Bump am2r_yams to 1.2.3

CHANGELOG.md, randovania/resolver/resolver.py, randovania/resolver/resolver_reach.py
Aimed at making certain hard seeds go from timing out to having a more definitive result.
=> Resolver: Avoid dangerous requirements turning trivial when rolling back

requirements.txt
No changelog entry needed, it's still trying to fix MW bugs.
=> Bump am2r_yams to 1.2.5

CHANGELOG.md, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt
Health required for decent bumped (50 -> 75).
=> AM2R: Bump Western Cave health req

CHANGELOG.md, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt
Bumps a few shinesparking tricks from beginner to intermediate that according to our internal list doesnt qualify as a beginner shinespark.
=> AM2R: bump a few shinesparking tricks to intermediate

randovania/gui/docks/resource_database_editor.py
Only affects when running from source, so not sure whether changelog entry is needed. Nor whether this approach is better.
This whole class also is not tested
Fixes #4342
=> Fix None templates wreaking havoc.

CHANGELOG.md, randovania/games/am2r/logic_database/header.json, randovania/games/prime1/logic_database/header.json, randovania/games/prime2/logic_database/header.json
CC @Samuel6710 (for some reason, you're not a triager yet)
=> Adjust minimal logic for prime1/echoes/am2r

CHANGELOG.md, randovania/games/dread/logic_database/Ferenia.json, randovania/games/dread/logic_database/Ferenia.txt
Using Ammo in dread requires the main item.
=> Dread: Fix slight PB logic in Ferenia

CHANGELOG.md, randovania/exporter/hints/joke_hints.py, test/test_files/patcher_data/dread/all_game_multi/world_4.json, test/test_files/patcher_data/dread/all_game_multi/world_8.json, test/test_files/patcher_data/prime2/all_game_multi/world_3.json, test/test_files/patcher_data/prime2/all_game_multi/world_7.json, test/test_files/patcher_data/prime2/prime2_no_pbs_new_patcher.json, test/test_files/patcher_data/prime2/prime2_no_pbs_old_patcher.json, test/test_files/patcher_data/prime2/seed_a_new_patcher.json, test/test_files/patcher_data/prime2/seed_a_old_patcher.json
unfortunately, the ^ and * characters don't get displayed well :(
=> echoes: remove badly displaying joke hint

requirements.txt
No changelog entry needed, as it's still an MW fix.
=> Bump am2r_yams to 1.2.12

CHANGELOG.md, randovania/games/am2r/game_data.py, randovania/gui/ui_files/games_tab_am2r_widget.ui
=> AM2R: Fix FAQ and add hint pages

randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/samus_returns/pickup_database/pickup-database.json
A bit too early probably but might as well.
=> Add offworld models for AM2R <-> MSR

randovania/games/samus_returns/exporter/patch_data_factory.py, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
=> MSR - Update intro text with custom tip text

randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/preset_settings/msr_patches_tab.py, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/gui/ui_files/preset_msr_patches.ui, test/games/samus_returns/layout/test_msr_describer.py, test/test_files/log_files/samus_returns/start_inventory.rdvgame, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/patcher_data/samus_returns/start_inventory.json, test/test_files/patcher_data/samus_returns/starter_preset.json
Merge after OSRR has been updated
=> MSR - Add option to nerf PBs against Blob Throwers and Steel Orbs

randovania/gui/ui_files/games_tab_samusreturns_widget.ui
=> MSR - Fix incorrect name in Hints tab for A1 DNA Seal

README.md
This doesnt change anything in-app, so dont think this needs a changelog entry.
Pretty much just winged it for MW stuff, feel free to correct me.
=> Readme: fix MW credits, simplify linux download

randovania/gui/ui_files/preset_am2r_hints.ui, randovania/gui/ui_files/preset_msr_reserves.ui, randovania/gui/ui_files/preset_prime_hints.ui, randovania/gui/ui_files/super_cosmetic_patches_dialog.ui
=> Fix duplicated names in UI files

CHANGELOG.md, randovania/gui/widgets/select_preset_widget.py
Fixes #4658
Before: Randovania would consistently freeze before 10 attempts
After: Randovania does not freeze anymore even after 40+ attempts
=> Delay freeing customize window to avoid double free

CHANGELOG.md, randovania/game_description/requirements/requirement_template.py, randovania/gui/data_editor.py, test/gui/test_data_editor.py
Use an entirely custom function for patching+simplify for Data Visualizer.
---
For a single Dread Starter Preset rdvgame, running the solver 10 times before and after went from 2.384s mean to 2.257s, about 5% faster.
=> Properly patch RequirementTemplate

randovania/game_description/data_writer.py, randovania/game_description/integrity_check.py, test/game_description/test_data_writer.py, test/game_description/test_integrity_check.py
Makes it easier to find the loops, though while one exists nothing really works.
=> Add integrity check for detecting loops in RequirementTemplate

tools/deploy_server.py, tools/server-docker/docker-compose.yml
I sure hope this works and doesn't blow up everything.
At least if it blows up it's going to be staging only
=> Support a second domain for the server

randovania/games/samus_returns/logic_database/Area 6.json, randovania/games/samus_returns/logic_database/Area 6.txt, randovania/games/samus_returns/logic_database/Area 7.json, randovania/games/samus_returns/logic_database/Area 7.txt
Reduces some damage requirements in Areas 6 and 7 where it wasn't necessary. This also helps with resolver issues with low health seeds.
=> MSR - Improve A6/A7 damage requirements

test/cli/test_init.py, test/test_randovania_init.py
Hopefully makes these tests less flaky
=> Improve get_configuration tests

randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/layout/dread_configuration.py, randovania/layout/preset_migration.py, test/test_files/patcher_data/dread/all_game_multi/world_4.json, test/test_files/patcher_data/dread/all_game_multi/world_8.json, test/test_files/patcher_data/dread/crazy_settings.json, test/test_files/patcher_data/dread/custom_start.json, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json, test/test_files/patcher_data/dread/elevator_rando.json, test/test_files/patcher_data/dread/starter_preset.json
Reverts randovania/randovania#6094
=> Revert "Add toggle for warp to start to Dread"

randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/layout/dread_configuration.py, randovania/layout/preset_migration.py, test/test_files/patcher_data/dread/all_game_multi/world_4.json, test/test_files/patcher_data/dread/all_game_multi/world_8.json, test/test_files/patcher_data/dread/crazy_settings.json, test/test_files/patcher_data/dread/custom_start.json, test/test_files/patcher_data/dread/dread_dread_multiworld_expected.json, test/test_files/patcher_data/dread/dread_prime1_multiworld_expected.json, test/test_files/patcher_data/dread/elevator_rando.json, test/test_files/patcher_data/dread/starter_preset.json
Reverts randovania/randovania#6100
Ooops
=> Re-Do Add toggle for warp to start to Dread

randovania/cli/commands/benchmark.py, randovania/cli/development.py, test/cli/commands/test_benchmark.py
It also stores results into a file so it's easier to compare.
=> Add command for quickly benchmarking

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
Kihunter hallway spacejump changed to combat level // Added todo to Blue security room // Ability to freeze evir updated // Combat requirements added to aquarium tank // TODO added to security shaft west // TODO note added for Nightmare Nook // Simplified combat requirements in Crow's Nest from charge or missiles to beam-resistant enemies template // TODO note added to Big Shell 1 room to exit. // Combat beginner added to menu hallway
=> Adding additional combat requirements for several rooms.

CHANGELOG.md, randovania/resolver/state.py
This line has been wrong for over 2 years. I don't know how things work.
=> Fix assign_pickups_resources not properly handling progressive pickups

randovania/games/samus_returns/logic_database/header.json
Includes Acid, Fleech Swarm, and Red Plants
=> MSR - Add trick to tank damage from hazards

randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt
Couldn't decide on whether to have Plasma or not. I didn't want to make this overkill, but I probably should include all things that essentially one shot it, so that would mean also adding Plasma and Screw Attack
=> MSR - Add template for defeating swarms

test/game_connection/connector/test_am2r_remote_connector.py, test/game_connection/connector/test_dread_remote_connector.py
That seems to be randomly fails tests. At least sometimes.
=> Change Dread/AM2R remote connector tests

randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
Per request in fusion-dev https://discord.com/channels/914291389293027329/1215675687936196608/1216489151256334387
Change long name of "High Jump" to "Hi-Jump"
=> Fusion: logic-db: change 'High Jump' to 'Hi-Jump' in item resources

randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt, randovania/games/fusion/pickup_database/pickup-database.json
-update doors with extra data needed for patcher
- fix the models in pickup db
=> Fusion: Fix data for Doors and Pickups

randovania/gui/main_window.py, randovania/gui/widgets/changelog_widget.py, test/gui/lib/test_data_editor_canvas.py, test/gui/widgets/test_changelog_widget.py
=> Change more tests that mock signals

randovania/games/fusion/exporter/hint_namer.py, randovania/games/fusion/game_data.py, randovania/games/fusion/generator/hint_distributor.py, randovania/games/fusion/gui/__init__.py, randovania/games/fusion/gui/hint_details_tab.py, randovania/games/fusion/gui/preset_settings/__init__.py, randovania/games/fusion/gui/preset_settings/fusion_hints_tab.py, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/layout/hint_configuration.py, randovania/games/fusion/layout/preset_describer.py, randovania/games/fusion/presets/starter_preset.rdvpreset, randovania/gui/ui_files/games_tab_fusion_widget.ui, randovania/gui/ui_files/preset_fusion_hints.ui, test/conftest.py, test/games/fusion/exporter/test_fusion_hint_namer.py, test/games/fusion/layout/test_fusion_describer.py
adds hint configuration for Metroids and Charge Beam
=> Fusion: Add hint configuration

randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt, randovania/games/dread/logic_database/Burenia.json, randovania/games/dread/logic_database/Burenia.txt, randovania/games/dread/logic_database/Cataris.json, randovania/games/dread/logic_database/Cataris.txt, randovania/games/dread/logic_database/Dairon.json, randovania/games/dread/logic_database/Dairon.txt, randovania/games/dread/logic_database/Elun.json, randovania/games/dread/logic_database/Elun.txt, randovania/games/dread/logic_database/Ferenia.json, randovania/games/dread/logic_database/Ferenia.txt, randovania/games/dread/logic_database/Ghavoran.json, randovania/games/dread/logic_database/Ghavoran.txt, randovania/games/dread/logic_database/Hanubia.json, randovania/games/dread/logic_database/Hanubia.txt, randovania/games/dread/logic_database/header.json, randovania/games/dread/logic_database/header.txt
- Adds `Lay Any Bomb` template
- Renames `Lay Bomb` to `Lay Small Bomb`
- Changes all instances of `Lay Small Bomb or Lay Power Bomb` to `Lay Any Bomb`
- A few miscellaneous changes
Resolves #2843.
=> Dread: Simplify/clarify bomb logic

randovania/games/samus_returns/logic_database/Area 2 - Dam Entryway.json, randovania/games/samus_returns/logic_database/Area 2 - Dam Entryway.txt
Should also fix the failed seed in the daily test generate
=> MSR - Fix logic error in A2

README.md
1. Spruces up & updates the description text (trying to make it a bit more fun than earlier drafts at the request of @duncathan )
2. removes game-specific jargon
3. adds the tag info
=> Update & refine README.md

CHANGELOG.md, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
Fixes a  bunch of things, including fixes https://github.com/randovania/YAMS/issues/174
=> AM2R: Fix a few DB errors

randovania/games/samus_returns/logic_database/Area 8.json, randovania/games/samus_returns/logic_database/Area 8.txt, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt
- Improves trickless logic
- Adds new trick logic
- Cleans up excessive/incorrect logic
- Cleans up nodes
- Updates `Defeat Larva Metroid` template
- Adds videos/comments where appropriate
=> MSR - Update Area 8 logic and add videos/comments

randovania/games/samus_returns/logic_database/Surface - West.json, randovania/games/samus_returns/logic_database/Surface - West.txt
- Adds the other beams as possible options with varying trick levels
- Adds more methods for dealing with the attacks
=> MSR - Improve Ridley Logic

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Area 2 - Dam Interior.json, randovania/games/samus_returns/logic_database/Area 2 - Dam Interior.txt, randovania/games/samus_returns/logic_database/Area 3 - Factory Exterior.json, randovania/games/samus_returns/logic_database/Area 3 - Factory Exterior.txt, randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.json, randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.txt, randovania/games/samus_returns/logic_database/Area 4 - Central Caves.json, randovania/games/samus_returns/logic_database/Area 4 - Central Caves.txt, randovania/games/samus_returns/logic_database/Area 5 - Tower Exterior.json, randovania/games/samus_returns/logic_database/Area 5 - Tower Exterior.txt, randovania/games/samus_returns/logic_database/Area 5 - Tower Interior.json, randovania/games/samus_returns/logic_database/Area 5 - Tower Interior.txt, randovania/games/samus_returns/logic_database/Area 5 - Tower Lobby.json, randovania/games/samus_returns/logic_database/Area 5 - Tower Lobby.txt, randovania/games/samus_returns/logic_database/Area 6.json, randovania/games/samus_returns/logic_database/Area 6.txt, randovania/games/samus_returns/logic_database/Area 7.json, randovania/games/samus_returns/logic_database/Area 7.txt, randovania/games/samus_returns/logic_database/Area 8.json, randovania/games/samus_returns/logic_database/Area 8.txt, randovania/games/samus_returns/logic_database/Surface - East.json, randovania/games/samus_returns/logic_database/Surface - East.txt, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt
This doesn't fix *all* of them, but fixes all that were complaining in my WIP tests
Also adds Ice Beam requirements to some Ice Beam clips that had it missing.
=> MSR: use templates over direct resources

randovania/games/samus_returns/logic_database/Surface - West.json, randovania/games/samus_returns/logic_database/Surface - West.txt
- Fighting without Spazer or Plasma now requires a significant trick boost due to low damage values
- Changed health as well to be more balanced
=> MSR - Rebalance Ridley to be better

randovania/game_connection/builder/dread_connector_builder.py, randovania/game_connection/connector/dread_remote_connector.py, randovania/game_connection/executor/dread_executor.py
=> Dread MW: fix mypy errors

CHANGELOG.md, randovania/games/cave_story/gui/preset_settings/cs_item_pool_tab.py
=> Cave Story: make explosive vanilla on bad ending

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/header.json
made the connection from bottom to top nicer and added trick video for the jump bomb jump method
=> MF: Zoro zig zag rework

randovania/games/super_metroid/pickup_database/pickup-database.json
Last time I checked, Pier mentioned this should work. Can't currently test tho.
=> SM: Allow negative ammo

randovania/games/samus_returns/logic_database/header.json
=> MSR - Update Minimum Logic

randovania/games/samus_returns/exporter/patch_data_factory.py
MSR currently doesn't support negative ammo, but the future proof is still nice.
=> MSR: fix full random models+text crashing, and future proof memo data

randovania/games/samus_returns/exporter/joke_hints.py, randovania/games/samus_returns/pickup_database/pickup-database.json, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
=> MSR - Support Negative Ammo

randovania/gui/dialog/scroll_label_dialog.py, randovania/gui/game_details/game_details_window.py, randovania/gui/tracker_window.py
=> ScrollLabelDialog: use parent as first argument

CHANGELOG.md, randovania/gui/lib/common_qt_lib.py
This doesn't fix #3610 but remedies it a little.
=> Better cases to show fallback when trying to open directory on Unix

CHANGELOG.md, randovania/server/discord/preset_lookup.py, test/server/discord/test_preset_lookup.py
=> Discord Bot: mention game when describing preset

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
ALL:
- `Entrance Hub` ->`Entrance Lobby`
- `Connection to [Sector]` -> `Glass Pipe to [Sector]`
SRX:
- `Zebesian Tower` and `Shaft South` -> `Zebesian Zig` and `Zebesian Zag` respectively
- `Shaft North` -> `Northwestern Intersection`
- `Short Shaft` -> `Checkpoint Intersection`
PYR:
- `Namihe's Abode` -> `Namihe's Lair`
- `Bob Room` -> `Bob's Abode`
AQA:
- `Owtch-Couch` -> `Owtch Atrium`
- `Owtch Cache` -> `C-Cache`
ARC:
- `Aerie` -> `Training Aerie`
- `Transformation Trial` -> `Transmutation Trial`
NOC: 
- `Menu Corridor` -> `Cavern Save Access`
- `Menu Save Room` -> `Cavern Save Room`
=> MF: More room renames

randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt, randovania/games/samus_returns/logic_database/Area 2 Dam Entryway.json, randovania/games/samus_returns/logic_database/Area 2 Dam Entryway.txt
- Update Inner Temple West Hall with more methods
- Lower Transport Access Hazard Runs difficulty
=> MSR - Minor TODOs for A1 and A2

CHANGELOG.md, README.md, randovania/games/samus_returns/game_data.py
=> Add MSR to stable 

.github/workflows/trick-documentation-report.yml, randovania/cli/commands/export_db_videos.py, randovania/cli/database.py, randovania/game_description/pretty_print.py, randovania/games/blank/logic_database/Intro.json, randovania/games/blank/logic_database/Intro.txt, randovania/gui/lib/connections_visualizer.py, randovania/server/discord/database_command.py, test/cli/commands/test_database_cli.py, test/game_description/test_pretty_print.py, tools/send_report_to_discord.py, tools/trick_documentation_report.py
=> Add automated report for how many tricks are documented

CHANGELOG.md, pyproject.toml, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/am2r/layout/preset_describer.py, randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/am2r/pickup_database/text_data.json, randovania/layout/description_migration.py, randovania/layout/preset_migration.py, requirements.txt, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/progressive_items/world_1.json, test/test_files/patcher_data/am2r/am2r/starter_preset/world_1.json, test/test_files/patcher_data/am2r/am2r/starting_items/world_1.json, test/test_files/patcher_data/am2r/shiny_pickups_dict_from_starter_preset.json
=> AM2R: rename expansions to tanks

CHANGELOG.md, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt
Talked about this with Toaster, its a not too bad R/L Jump and is a good one for beginners to learn.
=> Prime: Main Plaza adjustment

randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
Assumes Missile Data enables firing, regardless.
=> Require Missiles fireable for dmg templates

randovania/games/samus_returns/logic_database/Area 2 Dam Entryway.json, randovania/games/samus_returns/logic_database/Area 2 Dam Entryway.txt, randovania/games/samus_returns/logic_database/Area 8.json, randovania/games/samus_returns/logic_database/Area 8.txt
- A2 Dam Entryway
- A8 Transport to Surface
=> MSR - Even More DB TODOs

CHANGELOG.md, randovania/server/discord/database_command.py, randovania/server/discord/faq_command.py
=> Keep experimental games in the bot only to dev bots

randovania/gui/ui_files/msr_cosmetic_patches_dialog.ui
=> MSR: clarify cosmetic aim colors

randovania/games/samus_returns/logic_database/Area 5 Tower Interior.json, randovania/games/samus_returns/logic_database/Area 5 Tower Interior.txt
Intermediate cause a) punishment if you fail b) jump isn't "literally everyone can do this"-trivial.
=> MSR: Bump HJ jump in a5 interior save

CHANGELOG.md, randovania/games/prime1/logic_database/header.json, randovania/games/prime1/logic_database/header.txt
expose the power beam only doors to Randovania. People shuffle power beam, think this is a good addition.
=> Prime: Add power beam only doors to DLR

CHANGELOG.md, randovania/games/cave_story/logic_database/Sand Zone.json, randovania/games/cave_story/logic_database/Sand Zone.txt
Health numbers for convenience:
Curly:
14 -> 21
9 -> 14
Omega:
19 -> 29
10 -> 15
Toroko+
22 -> 33
15 -> 23
9 -> 14
=> Cave Story: Revise Sand Zone

randovania/games/prime3/gui/preset_settings/__init__.py, randovania/games/prime3/gui/preset_settings/corruption_starting_area_tab.py, randovania/games/prime3/logic_database/Norion.json, randovania/games/prime3/logic_database/Norion.txt
=> Prime3: Add Landing Site quick fill option

randovania/games/samus_returns/gui/dialog/game_export_dialog.py, randovania/gui/ui_files/msr_game_export_dialog.ui
Shows up when Citra is selected as the target
=> MSR: show reminder to enable game patching on 3ds

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
fixed a connection in `Sector 6 - Entrance Lobby` not hard requiring screw attack to get past the blocks
tweaked wall jump logic for climbing from the bottom sector connector in `Sector 4 - Powamp Shaft`
=> Sector Connection tweaks

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
this specifically changes the lower to mid connection. mid to upper has no logical change
=> add HJ to AQA security access

randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
=> MF: Remove logical redundancy in NOC entrance lobby

randovania/gui/ui_files/msr_game_export_dialog.ui
=> MSR - Improve text on export window and fix spacing

CHANGELOG.md, randovania/games/cave_story/logic_database/Sand Zone.json, randovania/games/cave_story/logic_database/Sand Zone.txt
Darn energy requirements strike again
=> CS: remove health reqs for omega and curly

randovania/gui/dialog/node_details_popup.py
=> Show proper layer for a node in details popup

randovania/gui/ui_files/am2r_cosmetic_patches_dialog.ui
=> am2r: rephrase music in cosmetic option

randovania/games/prime1/game_data.py
Rooms are now listed in order from Burning Trail to Workstation
consolidated Burning Trail and Lake Access into one point since they are adjacent rooms
changed phrasing on the end of magmoor section
=> reword magmoor nonheated rooms FAQ

CHANGELOG.md, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt
Fixes https://github.com/randovania/YAMS/issues/187
Fixes https://github.com/randovania/YAMS/issues/188
=> AM2R: Small intermediate adjustment

CHANGELOG.md, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt
Fixes https://github.com/randovania/YAMS/issues/152
=> AM2R: add waterfalls hypermode trick

randovania/games/prime3/exporter/game_exporter.py, randovania/games/prime3/exporter/options.py, randovania/games/prime3/exporter/patch_data_factory.py, randovania/games/prime3/game_data.py, randovania/games/prime3/gui/dialog/game_export_dialog.py, randovania/gui/game_details/game_details_window.py, randovania/gui/ui_files/corruption_game_export_dialog.ui, test/gui/test_game_details_window.py
Should keep the same behaviour as before. Maybe the window is a little bigger, but i dont really care about that.
=> Dont hardcode prime 3 export message

CHANGELOG.md, randovania/games/samus_returns/gui/dialog/game_export_dialog.py, randovania/gui/ui_files/msr_game_export_dialog.ui
=> MSR: small export window niceties

randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt
from fusion discord
~~transmutation trial~~ and nightmare playground
=> Add 1 shinespark tricks to ARC

pyproject.toml, requirements.txt
Fixed an issue with pyinstaller hook not working
=> Bump am2r_yams to 2.1.1

requirements.txt
=> Bump am2r_yams to 2.1.2

CHANGELOG.md, randovania/game_description/db/event_pickup.py
It's ignoring `context.current_resources.add_self_as_requirement_to_resources`
=> Fix EventPickupNode.requirement_to_leave

CHANGELOG.md, pyproject.toml, randovania/games/samus_returns/logic_database/Area 2 Dam Interior.json, randovania/games/samus_returns/logic_database/Area 2 Dam Interior.txt, randovania/games/samus_returns/logic_database/Area 4 Crystal Mines.json, randovania/games/samus_returns/logic_database/Area 4 Crystal Mines.txt, randovania/games/samus_returns/logic_database/Surface East.json, randovania/games/samus_returns/logic_database/Surface East.txt, randovania/games/samus_returns/logic_database/header.json, randovania/games/samus_returns/logic_database/header.txt, randovania/games/samus_returns/presets/starter_preset.rdvpreset, requirements.txt, test/test_files/log_files/samus_returns/door_lock.rdvgame, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json
=> MSR - Add Custom Door Locks

CHANGELOG.md, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
See https://github.com/randovania/randovania/issues/4781 for more info
=> AM2R: exclude permanently locked doors for tower

randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt, randovania/games/am2r/pickup_database/model_data.json, randovania/games/am2r/pickup_database/pickup-database.json, randovania/layout/preset_migration.py
Adds those as items, and adjusts the database accordingly.
Preperation for a nearing patcher update that adds these as items.
=> AM2R: Add IBJ, WJ and Long Beam as unavailable items

pyproject.toml, randovania/game_description/data_reader.py, randovania/game_description/data_writer.py, randovania/game_description/editor.py, randovania/game_description/pretty_print.py, randovania/game_description/requirements/node_requirement.py, randovania/games/binary_data.py, randovania/games/blank/logic_database/Intro.json, randovania/games/blank/logic_database/Intro.txt, randovania/games/blank/logic_database/header.json, randovania/gui/data_editor.py, randovania/gui/dialog/connections_editor.py, randovania/gui/dialog/node_details_popup.py, randovania/gui/docks/resource_database_editor.py, randovania/gui/lib/signal_handling.py, randovania/gui/widgets/node_selector_widget.py, test/game_description/test_editor.py, test/generator/filler/test_player_state.py, test/gui/dialog/test_connections_editor.py, test/gui/test_data_editor.py, test/gui/widgets/test_node_selector_widget.py
Adds the option for a requirement in the database to require collecting one specific node. The UI lets one select any node, but it only makes sense if the node is a resource node.
I intend to use this feature for things in the future :)
=> Add NodeRequirement

CHANGELOG.md, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/dialog/cosmetic_patches_dialog.py, randovania/games/samus_returns/layout/msr_cosmetic_patches.py, randovania/gui/ui_files/msr_cosmetic_patches_dialog.ui, randovania/interface_common/persisted_options.py, test/games/samus_returns/gui/dialog/test_msr_cosmetic_patches_dialog.py, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/cosmetic_1.json
Options were inverted and clunky
=> MSR - Fix Laser Aim Cosmetic Export Window

CHANGELOG.md, randovania/gui/ui_files/dread_game_export_dialog.ui
=> Dread: slightly improve export window

randovania/gui/data_editor.py
=> create lock nodes when adding new docks in the db editor

randovania/game_description/editor.py
=> update node identifiers when renaming areas

randovania/games/am2r/game_data.py, randovania/games/cave_story/game_data.py, randovania/games/prime1/game_data.py, randovania/games/prime2/game_data.py, randovania/games/samus_returns/game_data.py
=> Sllightly clarify web info for games

CHANGELOG.md, randovania/gui/game_details/game_details_window.py
=> Hide playthrough tab for minimal logic

CHANGELOG.md, pyproject.toml, randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt, randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/am2r/pickup_database/text_data.json, randovania/layout/preset_migration.py, requirements.txt
Breaks presets that were made between 9848a1abcd60fc1a9dbeef161dbd8234f90acf97 and this commit. But since its a relatively short timeframe and only within dev builds, I don't care about ensuring that these migrate properly.
=> Bump am2r_yams to 2.4.0

.vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, README.md
Here is a cleaned up version of my vscode folder.
Mainly consists of:
- 3 tasks scrips: Create venv, build ui and run tests
- 2 launch scripts: One for the client (using build ui as prelaunch taks) and one to refresh game description.
- Recommendations on which plugins should be used.  Unsure about mypy as plugin. There are a lot of files which are missing type annotations and so it marks whole files with a red line which is very distracting.
=> Added .vscode configs + how to use section in README

CHANGELOG.md, randovania/generator/dock_weakness_distributor.py
Fixes #4781 
Looking at it now, I'm not quite sure whether just setting the node of the state is enough. Thought about using `act_on_node` but that one only works with resource nodes. I think this one should be fine tho except for maybe a few health edge cases?
=> Locked door: check if you can escape back

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Great Temple.json, randovania/games/prime2/logic_database/Great Temple.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
Added the schema from the new patcher for the 'extra' field entry in item pickup locations.
=> Updated Echoes database for new patcher integration

README.md, randovania/cli/commands/new_game.py, randovania/games/fusion/game_data.py, randovania/games/game.py, randovania/games/prime3/game_data.py, randovania/games/super_metroid/game_data.py
This readds the `DEVELOPMENT` game status which is used for games which are not ready to be playtested/used in dev builds, but instead only in from source compiled builds. This could be due to a number of reasons, e.g. missing exporter, maintainer stepping away etc.
=> Readd games as DEVELOPMENT status

randovania/games/prime3/layout/preset_describer.py
fixes https://github.com/SchwartzGandhi/randovania/issues/1
=> MP3: fix duplicate progressive item message in preset describer

randovania/games/prime3/logic_database/SkyTown Elysia - Main.json, randovania/games/prime3/logic_database/SkyTown Elysia - Main.txt
Until theres actually any proof of this trick being possible (on all versions, not just primehack). It's better to just remove it.
=> MP3: remove spring ball trick for skytown aurora chamber

CHANGELOG.md, randovania/game_description/game_description.py, randovania/game_description/pretty_print.py, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.txt, randovania/games/prime2/logic_database/header.json, randovania/gui/data_editor.py, randovania/gui/dialog/trick_details_popup.py
=> Fix lock/open override being ignored when looking for uses

randovania/games/am2r/exporter/game_exporter.py, randovania/games/prime1/exporter/game_exporter.py, randovania/lib/ftp_uploader.py
As with last time, I dont think this needs a changelog entry as its mostly internal stuff
Would be nice to get in before june release
=> Add more monitoring

randovania/games/prime3/logic_database/GFS Valhalla.json, randovania/games/prime3/logic_database/GFS Valhalla.txt
Added the SSJ for crossing both ways.
=> MP3: hangar access a fix

randovania/monitoring/__init__.py
Let's skip this for 8.1.0: wanna if it doesn't break anything via few days in dev builds
=> Try event harder to avoid sending user paths

CHANGELOG.md, pyproject.toml, requirements.txt
Closes #6677
@henriquegemignani, @Miepee, this may warrant a hotfix. Not super urgent, but the behavior does technically affect logic
=> Randomprime v1.24.5

randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/dread/pickup_database/pickup-database.json
- AM2R now uses proper items for Progressive Suit/Jump
- Dread's Ice Missile can now show up in MSR with the custom Ice Missile model
=> Offworld Models updates for AM2R <-> MSR and Dread <-> MSR

CHANGELOG.md
=> MSR - Update changelog for 2.0.0 stuff

randovania/games/prime3/exporter/patch_data_factory.py
Convenient to keep for experimenting
=> Restore python 3.11 compat

randovania/cli/commands/permalink.py, test/cli/commands/test_generate_cli.py
Game is now part of the the preset name, via <game name>/<preset name> Add --preset-file to specify files directly
=> Change CLI to allow better creating crossgame permalinks

randovania/bitpacking/construct_pack.py, randovania/lib/construct_lib.py
Not sure I like hacking construct like that, but it's slightly faster
=> Compile structs in construct_pack.encode

randovania/games/prime1/pickup_database/pickup-database.json
=> Fix typo in Prime <-> MSR Gravity Offworld Model

randovania/exporter/patch_data_factory.py, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/factorio/exporter/patch_data_factory.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/super_metroid/exporter/patch_data_factory.py
Should make it much easier to follow and do it correctly for new games.
=> Refactor how PDFs call pickup_exporter.export_all_indices

requirements.txt
No relevant changes. Internal refactors and features that rdv doesnt use yet.
=> Bump am2r_yams to 2.6.0

CHANGELOG.md, randovania/layout/base/dock_rando_configuration.py, test/games/prime1/exporter/test_prime_dangerous_settings.py, test/test_files/log_files/prime1_crazy_seed.rdvgame
=> Warn about permanently locked doors and DLR Types

.github/workflows/build-test-publish.yml, pyproject.toml, randovania/__init__.py, randovania/__main__.py, randovania/cli/__init__.py, randovania/cli/cli_lib.py, randovania/cli/commands/batch_distribute.py, randovania/cli/commands/benchmark.py, randovania/cli/commands/decribe_layout.py, randovania/cli/commands/export_db_videos.py, randovania/cli/commands/export_game.py, randovania/cli/commands/generate.py, randovania/cli/commands/new_game.py, randovania/cli/commands/patcher_data.py, randovania/cli/commands/permalink.py, randovania/cli/commands/refresh_presets.py, randovania/cli/commands/render_regions.py, randovania/cli/commands/validate.py, randovania/cli/commands/website.py, randovania/cli/database.py, randovania/cli/development.py, randovania/cli/gui.py, randovania/cli/layout.py, randovania/cli/server.py, test/cli/commands/test_database_cli.py, test/cli/commands/test_generate_cli.py
Also fixes a crash with `rdv database list-resource-usage`
=> Add typing to cli

randovania/game_connection/executor/am2r_executor.py, randovania/game_connection/executor/dread_executor.py, randovania/game_connection/executor/executor_to_connector_signals.py, randovania/game_connection/executor/msr_executor.py, test/game_connection/builder/test_am2r_connector_builder.py, test/game_connection/builder/test_dread_connector_builder.py, test/game_connection/builder/test_msr_connector_builder.py, test/game_connection/connector/test_am2r_remote_connector.py, test/game_connection/connector/test_dread_remote_connector.py, test/game_connection/connector/test_msr_remote_connector.py
Had this refactor in my back pocket
=> Remove redundant definition of executor to connector signals

randovania/game_description/data_reader.py, randovania/game_description/data_writer.py, randovania/game_description/db/dock_lock_node.py, randovania/game_description/db/event_node.py, randovania/game_description/db/event_pickup.py, randovania/game_description/db/hint_node.py, randovania/game_description/db/pickup_node.py, randovania/game_description/db/resource_node.py, randovania/game_description/db/teleporter_network_node.py, randovania/games/cave_story/exporter/patch_data_factory.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/generator/filler/filler_library.py, randovania/generator/filler/retcon.py, randovania/generator/hint_distributor.py, randovania/generator/old_generator_reach.py, randovania/generator/reach_lib.py, randovania/gui/dialog/node_details_popup.py, randovania/gui/tracker_window.py, randovania/resolver/resolver_reach.py, randovania/resolver/state.py, test/game_description/test_node.py, test/games/prime/patcher_file_lib/test_item_hints.py, test/generator/filler/test_player_state.py, test/generator/filler/test_runner.py, test/resolver/test_resolver_reach.py
Might change slightly how translators are placed for Echoes, but I didn't test too much.
=> Add requirement_to_collect to ResourceNode

randovania/game_connection/connector/am2r_remote_connector.py, randovania/game_connection/connector/cs_remote_connector.py, randovania/game_connection/connector/debug_remote_connector.py, randovania/game_connection/connector/mercury_remote_connector.py, randovania/game_connection/connector/prime_remote_connector.py, randovania/game_connection/connector/remote_connector.py, test/game_connection/connector/test_am2r_remote_connector.py, test/game_connection/connector/test_cs_remote_connector.py, test/game_connection/connector/test_dread_remote_connector.py, test/game_connection/connector/test_msr_remote_connector.py
We only emit the signal but nothing is connected to it. So...remove it or leave it for future?
=> Remove unused signal

randovania/server/multiplayer/web_api.py, test/server/multiplayer/test_web_api.py
It took a few years to need some moderation tools. It was a good run.
=> Add delete session to admin ui

randovania/resolver/resolver_reach.py, test/resolver/test_resolver_reach.py
=> Remove ResolverReach.satisfiable_requirements as it's unused

.github/workflows/build-test-publish.yml
I wish there was a proper way to test this than "push onto main and hope it works"
=> Downgrade upload-artifact action to hopefully fix dev builds

.github/workflows/build-test-publish.yml
=> Update download dep to use pattern matching

CHANGELOG.md, randovania/games/dread/logic_database/Cataris.json, randovania/games/dread/logic_database/Cataris.txt
- Fixed: Moving Magnet Walls (Tall) now uses the correct lava button event for the magnet surfaces.
=> Dread: Fix Moving Magnet Walls (Tall) logic

CHANGELOG.md, randovania/games/dread/pickup_database/pickup-database.json
Don't care who reviews this lol
=> AM2R: Fix Dread widebeam showing up as spazer

requirements.txt
Changelog releavnt for future feature
=> Bump yams to 2.6.2

randovania/game_description/db/node_provider.py, randovania/game_description/integrity_check.py, randovania/games/cave_story/exporter/patch_data_factory.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/dread/gui/preset_settings/dread_teleporters_tab.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/gui/preset_settings/prime_teleporters_tab.py, randovania/games/prime2/exporter/hints.py, randovania/games/prime2/gui/preset_settings/echoes_teleporters_tab.py, randovania/games/prime2/gui/preset_settings/echoes_translators_tab.py, randovania/games/prime2/layout/translator_configuration.py, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/generator/filler/player_state.py, randovania/generator/hint_distributor.py, randovania/generator/teleporter_distributor.py, randovania/gui/dialog/node_details_popup.py, randovania/gui/tracker_window.py, randovania/layout/lib/teleporters.py, test/games/prime/patcher_file_lib/test_item_hints.py, test/generator/filler/test_runner.py
Once upon a time, the identifier was calculated.
That was years ago lmao
=> Remove identifier_for_node

CHANGELOG.md, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/am2r/gui/preset_settings/__init__.py, randovania/games/am2r/gui/preset_settings/am2r_chaos_tab.py, randovania/games/am2r/gui/ui_files/preset_am2r_chaos.ui, randovania/games/am2r/layout/am2r_configuration.py, randovania/layout/preset_migration.py, test/games/am2r/gui/preset_settings/test_am2r_chaos_tab.py, test/games/am2r/layout/test_am2r_configuration.py, test/games/test_log_file_export.py, test/test_files/log_files/am2r/chaos_options.rdvgame, test/test_files/patcher_data/am2r/am2r/chaos_options/world_1.json, test/test_files/patcher_data/am2r/am2r/custom_dna_required/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock_open/world_1.json, test/test_files/patcher_data/am2r/am2r/progressive_items/world_1.json, test/test_files/patcher_data/am2r/am2r/starter_preset/world_1.json, test/test_files/patcher_data/am2r/am2r/starting_items/world_1.json, test/test_files/patcher_data/am2r/am2r/transport_pipe_shuffle/world_1.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2+msr/world_6.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2/world_1.json
=> AM2R: add custom darkness/submerged chaos options

CHANGELOG.md, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/preset_settings/__init__.py, randovania/games/samus_returns/gui/preset_settings/msr_energy_tab.py, randovania/games/samus_returns/gui/ui_files/preset_msr_energy.ui, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/games/samus_returns/presets/multiworld-starter-preset.rdvpreset, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/layout/preset_migration.py, test/games/samus_returns/layout/test_msr_describer.py, test/test_files/log_files/multi-am2r+cs+dread+prime1+prime2+msr.rdvgame, test/test_files/log_files/samus_returns/door_lock.rdvgame, test/test_files/log_files/samus_returns/door_lock_access_open.rdvgame, test/test_files/log_files/samus_returns/start_inventory.rdvgame, test/test_files/log_files/samus_returns/starter_preset.rdvgame, test/test_files/patcher_data/samus_returns/multi-am2r+cs+dread+prime1+prime2+msr/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
Heat and Lava damage can now be configured to be constant instead of scaling
=> MSR - Support changing environmental damage

randovania/interface_common/generator_frontend.py
Inspired by the recent report about fewest changes.
=> Send to Sentry if we're genning with a bultin preset

.github/workflows/build-test-publish.yml
I tested parts of it in https://github.com/Miepee/randovania.github.io where it did work
=> Automatically update website when creating new release

randovania/games/am2r/exporter/patch_data_factory.py, test/test_files/patcher_data/am2r/am2r/chaos_options/world_1.json, test/test_files/patcher_data/am2r/am2r/custom_dna_required/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock_open/world_1.json, test/test_files/patcher_data/am2r/am2r/progressive_items/world_1.json, test/test_files/patcher_data/am2r/am2r/starter_preset/world_1.json, test/test_files/patcher_data/am2r/am2r/starting_items/world_1.json, test/test_files/patcher_data/am2r/am2r/transport_pipe_shuffle/world_1.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2+msr/world_6.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2/world_1.json
Might sound weird, but otherwise the game defaults are used which we do not want as they don't handle things properly.
=> AM2R: Override light and liquid info with default levels in export

requirements.txt
Reverts randovania/randovania#6778
=> Revert "Bump nod from 1.9.2 to 1.9.3"

pyproject.toml, randovania/gui/data_editor.py
=> Fix + Mypy for data_editor

randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/dread/pickup_database/pickup-database.json
- Power Grip (AM2R)
- Speed Booster (AM2R, Dread)
=> MSR <-> AM2R/Dread Offworld Updates

randovania/game_connection/connector_builder_choice.py
Tbh, if we add more and more it needs a new UI anyways.
Currently it is sorted like "when we added" something which is like the worst, so I decided to at least sort it by the pretty name.
=> Sort by pretty name

CHANGELOG.md, randovania/games/prime1/gui/ui_files/preset_prime_qol.ui
Y'all can read the diff, i'm not posting a screenshot for a 2 character change.
=> Fix typo, add previous commit changelog

randovania/games/prime3/logic_database/Bryyo - Fire.txt, randovania/games/prime3/logic_database/Bryyo - Reptilicus.txt, randovania/games/prime3/logic_database/GFS Valhalla.txt, randovania/games/prime3/logic_database/Norion.txt, randovania/games/prime3/logic_database/Phaaze.txt, randovania/games/prime3/logic_database/Pirate Homeworld - Command.txt, randovania/games/prime3/logic_database/Pirate Homeworld - Mines.txt, randovania/games/prime3/logic_database/Pirate Homeworld - Research.txt, randovania/games/prime3/logic_database/Pirate Homeworld - Seed.txt, randovania/games/prime3/logic_database/SkyTown Elysia - Main.txt, randovania/games/prime3/logic_database/SkyTown Elysia - Pod.txt, randovania/games/prime3/logic_database/header.json, randovania/games/prime3/logic_database/header.txt
Changed template names to be more concise and understandable.
=> Updated Template Names

randovania/gui/game_details/game_details_window.py, randovania/gui/lib/preset_tree_widget.py, randovania/gui/main_window.py, randovania/gui/widgets/generate_game_widget.py, randovania/gui/widgets/randovania_help_widget.py, randovania/gui/widgets/select_preset_widget.py, randovania/monitoring/__init__.py
I consider this internal stuff, so doesnt need a changelog
Just put some basic cherry-picked things for now, suggestions for more things welcome.
Since metrics are always helpful, I would like these in the next release.
=> Sentry: add metrics

requirements.txt
No changelog, fixes a thing that was found by abyss in dev builds
=> Bump am2r_yams to 2.7.1

requirements.txt
No changelog entry needed, fixes a bug where i accidentally made the game crash.
=> Bump am2r_yams to 2.7.2

.vscode/settings.json
Should stop the auto migration and also fix wrong auto imports
=> Remove old vscode setting

CHANGELOG.md, randovania/gui/dialog/racetime_browser_dialog.py
=> Add MSR to racetime.gg browser

requirements.txt
fixes one door looking in wrong direction in between dev build refactors
=> Bump am2r_yams to 2.7.4

randovania/games/prime3/logic_database/Pirate Homeworld - Command.json, randovania/games/prime3/logic_database/Pirate Homeworld - Command.txt
Fixed Command Courtyard Trick to Skip Voltage to correctly require standable terrain. I also truncated the video link.
=> MP3: Fix Command Courtyard Logic Bug

CHANGELOG.md, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/am2r/gui/dialog/cosmetic_patches_dialog.py, randovania/games/am2r/gui/ui_files/am2r_cosmetic_patches_dialog.ui, randovania/games/am2r/layout/am2r_cosmetic_patches.py, randovania/interface_common/persisted_options.py, test/games/am2r/gui/test_am2r_cosmetic_patches_dialog.py, test/test_files/patcher_data/am2r/am2r/chaos_options/world_1.json, test/test_files/patcher_data/am2r/am2r/custom_dna_required/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock_open/world_1.json, test/test_files/patcher_data/am2r/am2r/progressive_items/world_1.json, test/test_files/patcher_data/am2r/am2r/starter_preset/world_1.json, test/test_files/patcher_data/am2r/am2r/starting_items/world_1.json, test/test_files/patcher_data/am2r/am2r/transport_pipe_shuffle/world_1.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2+msr/world_6.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2/world_1.json
Only merge after yams bump please.
=> Am2r: Add tileset and background rotation

CHANGELOG.md, randovania/games/am2r/layout/am2r_configuration.py
=> AM2R: add chaos settings check for MW

requirements.txt
Fixes small issue when exporting
=> Bump am2r_yams to dev4

CHANGELOG.md, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, test/test_files/patcher_data/am2r/am2r/custom_dna_required/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock_open/world_1.json, test/test_files/patcher_data/am2r/am2r/progressive_items/world_1.json, test/test_files/patcher_data/am2r/am2r/starter_preset/world_1.json, test/test_files/patcher_data/am2r/am2r/starting_items/world_1.json, test/test_files/patcher_data/am2r/am2r/transport_pipe_shuffle/world_1.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2+msr/world_6.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2/world_1.json
Fixes https://github.com/randovania/YAMS/issues/228
=> Fix light level for Breeding Grounds Fly Stadium Access

CHANGELOG.md, randovania/games/am2r/gui/ui_files/games_tab_am2r_widget.ui, randovania/games/blank/gui/ui_files/games_tab_blank_widget.ui, randovania/games/cave_story/gui/ui_files/games_tab_cavestory_widget.ui, randovania/games/dread/gui/ui_files/games_tab_dread_widget.ui, randovania/games/factorio/gui/ui_files/games_tab_factorio_widget.ui, randovania/games/fusion/gui/ui_files/games_tab_fusion_widget.ui, randovania/games/planets_zebeth/gui/ui_files/games_tab_planets_zebeth_widget.ui, randovania/games/prime1/gui/ui_files/games_tab_prime_widget.ui, randovania/games/prime2/gui/ui_files/games_tab_echoes_widget.ui, randovania/games/prime3/gui/ui_files/games_tab_corruption_widget.ui, randovania/games/samus_returns/gui/ui_files/games_tab_samusreturns_widget.ui, randovania/games/super_metroid/gui/ui_files/games_tab_supermetroid_widget.ui, randovania/gui/ui_files/customize_preset_dialog.ui, randovania/gui/widgets/games_help_widget.py
I only tested this on Linux, I have no idea how this looks like on Windows or even macos.
| Before | After |
|--------|-------|
| ![grafik](https://github.com/user-attachments/assets/461cd2ad-4f95-43a7-a9ac-483627b35930) | ![grafik](https://github.com/user-attachments/assets/7152be8c-8138-4e13-9a23-878d7a3cab5d) |
|![grafik](https://github.com/user-attachments/assets/5a0f6cb8-0e01-4e59-acb2-0aa998a8f3e6) | ![grafik](https://github.com/user-attachments/assets/7355f677-b534-4b50-956a-31fe279e688d) |
| ![grafik](https://github.com/user-attachments/assets/6e8c9621-b24d-4cd3-b3f4-99c0eef90af2)      | ![grafik](https://github.com/user-attachments/assets/e1328021-ed78-49ca-b340-51bd33a2c159)  |
|  ![grafik](https://github.com/user-attachments/assets/c15aedaf-3914-4433-93af-fc059258336c) | …
=> Reduce visual noise in main window

randovania/games/am2r/exporter/patch_data_factory.py, randovania/gui/main_online_interaction.py, randovania/gui/main_window.py, randovania/gui/multiplayer_session_window.py, randovania/gui/qt.py, randovania/gui/widgets/base_game_tab_widget.py, randovania/gui/widgets/generate_game_widget.py, randovania/gui/widgets/multiplayer_session_users_widget.py, randovania/gui/widgets/select_preset_widget.py, randovania/interface_common/generator_frontend.py
See title.
No changelog cause internal stuff.
=> Add more sentry metrics

CHANGELOG.md, randovania/games/dread/exporter/patch_data_factory.py, test/games/test_log_file_export.py, test/test_files/log_files/dread/hide_all_with_nothing.rdvgame, test/test_files/patcher_data/dread/dread/dread_dread_multiworld/world_2.json, test/test_files/patcher_data/dread/dread/hide_all_with_nothing/world_1.json, test/test_files/patcher_data/dread/dread_prime1_multiworld/world_1.json, test/test_files/patcher_data/dread/multi-am2r+cs+dread+prime1+prime2/world_4.json, test/test_files/patcher_data/dread/multi-cs+dread+prime1+prime2/world_4.json
=> Dread: fix hide scans with nothing data

randovania/monitoring/__init__.py
This seems to automatically make a function span for each asyncio task. It'll make a bunch of stuff show there, but I'm more curious about transactions not leaking into unrelated issues. Hopefully this fixes that.
=> Enable sentry's asyncio support

randovania/exporter/game_exporter.py, randovania/monitoring/__init__.py
I noticed all the examples on sentry have it setup like this, so I'm just trying it and hope it works.
=> Try inlineing attach_patcher_data

CHANGELOG.md, randovania/games/am2r/exporter/patch_data_factory.py, randovania/games/am2r/gui/preset_settings/am2r_chaos_tab.py, randovania/games/am2r/gui/ui_files/preset_am2r_chaos.ui, randovania/games/am2r/layout/am2r_configuration.py, randovania/games/am2r/layout/preset_describer.py, randovania/layout/preset_migration.py, test/games/am2r/gui/preset_settings/test_am2r_chaos_tab.py, test/games/am2r/layout/test_am2r_configuration.py, test/test_files/patcher_data/am2r/am2r/chaos_options/world_1.json, test/test_files/patcher_data/am2r/am2r/custom_dna_required/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock/world_1.json, test/test_files/patcher_data/am2r/am2r/door_lock_open/world_1.json, test/test_files/patcher_data/am2r/am2r/progressive_items/world_1.json, test/test_files/patcher_data/am2r/am2r/starter_preset/world_1.json, test/test_files/patcher_data/am2r/am2r/starting_items/world_1.json, test/test_files/patcher_data/am2r/am2r/transport_pipe_shuffle/world_1.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2+msr/world_6.json, test/test_files/patcher_data/am2r/multi-am2r+cs+dread+prime1+prime2/world_1.json
=> AM2R: add options to flip gameplay

.idea/runConfigurations/Validate_Prime_Vanilla.xml, randovania/generator/filler/action.py
plus a fix for a pycharm run configuration
=> Generator log improvements

CHANGELOG.md, randovania/games/prime1/logic_database/Phazon Mines.json, randovania/games/prime1/logic_database/Phazon Mines.txt
=> Prime: re-add Mines Security Station barrier item reqs

pyproject.toml, requirements.txt
No changelog entry since it's just fixing new stuff
=> Bump OSRR to 2.4.1

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt
Forgot about the Morph Ball requirements 😬
=> MSR - Fix A1 Broken Logic in Inner Temple West Hall

CHANGELOG.md, randovania/gui/lib/generation_failure_handling.py
=> Fix MW tab selection

CHANGELOG.md, randovania/games/prime1/exporter/patch_data_factory.py, test/test_files/patcher_data/prime1/prime1_crazy_seed/world_1.json, test/test_files/patcher_data/prime1/prime1_crazy_seed_one_way_door/world_1.json
It's a largely unused chaos option but it's fun so I fix
Fixes #7004
(no changelog because experimental option)
=> Item Position Rando Fixes

requirements.txt
Reverts randovania/randovania#6860
=> Revert "Bump matplotlib from 3.9.0 to 3.9.1"

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 6.json, randovania/games/samus_returns/logic_database/Area 6.txt
Makes going for the DNA not dangerous
=> MSR - A6 Crumbling Stairwell Door Exclusion

randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
=> AM2R: DB changes for future region rando

CHANGELOG.md, randovania/games/dread/logic_database/Ferenia.json, randovania/games/dread/logic_database/Ferenia.txt
Remove possibility of using Speed Booster with Normal Bombs.
=> Dread: Revise connection to Missile Tank in Space Jump Room

randovania/games/am2r/gui/ui_files/preset_am2r_chaos.ui, randovania/games/am2r/gui/ui_files/preset_am2r_energy.ui, randovania/games/am2r/gui/ui_files/preset_am2r_goal.ui, randovania/games/am2r/gui/ui_files/preset_am2r_hints.ui, randovania/games/am2r/gui/ui_files/preset_am2r_patches.ui, randovania/games/am2r/gui/ui_files/preset_teleporters_am2r.ui
=> AM2R:  make spacing consistent

randovania/games/prime1/logic_database/header.json, randovania/games/prime2/logic_database/header.json
Prime: changed Bomb Jump and Knowledge to above beginner
Echoes: changed Bomb Jump to above beginner
=> Adjust documentation need for prime/echoes

randovania/games/cave_story/gui/preset_settings/__init__.py, randovania/games/dread/gui/preset_settings/__init__.py, randovania/games/prime1/gui/preset_settings/__init__.py, randovania/games/prime2/gui/preset_settings/__init__.py, randovania/games/prime3/gui/preset_settings/__init__.py
This has no visual changes, it just makes the list nicer to look at and slightly less confusing.
=> GUI: sort preset __init__ based on how they appear

CHANGELOG.md, randovania/games/am2r/generator/bootstrap.py
tested with 3x prog suit and also 3x varia 3x gravity and both gen correctly
=> AM2R: fix DR for more suits than vanilla

CHANGELOG.md, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/generator/pool_creator.py, randovania/games/samus_returns/gui/preset_settings/msr_goal_tab.py, randovania/games/samus_returns/gui/ui_files/preset_msr_goal.ui, randovania/games/samus_returns/layout/msr_configuration.py, randovania/games/samus_returns/layout/preset_describer.py, randovania/layout/preset_migration.py, test/games/samus_returns/generator/test_msr_bootstrap.py, test/games/samus_returns/generator/test_msr_pool_creator.py, test/games/samus_returns/gui/preset_settings/test_msr_goal_tab.py, test/games/samus_returns/layout/test_msr_configuration.py, test/games/samus_returns/layout/test_msr_describer.py, test/games/test_log_file_export.py, test/test_files/log_files/samus_returns/custom_required_dna.rdvgame, test/test_files/patcher_data/samus_returns/multi-am2r+cs+dread+prime1+prime2+msr/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/custom_required_dna/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
More DNA can be placed than required
Requires #7117 to be merged first.
=> MSR - Add option to have a custom amount of required DNA

CHANGELOG.md, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/games/samus_returns/gui/dialog/cosmetic_patches_dialog.py, randovania/games/samus_returns/gui/ui_files/msr_cosmetic_patches_dialog.ui, randovania/games/samus_returns/layout/msr_cosmetic_patches.py, randovania/interface_common/persisted_options.py, test/games/samus_returns/gui/dialog/test_msr_cosmetic_patches_dialog.py, test/test_files/patcher_data/samus_returns/multi-am2r+cs+dread+prime1+prime2+msr/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/custom_required_dna/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/door_lock_access_open/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/cosmetic_1.json, test/test_files/patcher_data/samus_returns/samus_returns/start_inventory/world_1.json, test/test_files/patcher_data/samus_returns/samus_returns/starter_preset/world_1.json
Requires #7117 to be merged first
=> MSR: Add cosmetic option to change volume of music and ambience

randovania/games/am2r/gui/preset_settings/__init__.py, randovania/games/am2r/gui/preset_settings/am2r_room_design_tab.py
=> AM2R: address preset feedback

randovania/games/samus_returns/gui/ui_files/msr_cosmetic_patches_dialog.ui
Music and Ambient Sound were swapped in the GUI, causing the wrong field to be changed.
=> MSR - Fix inverted sound sliders

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 1.json, randovania/games/samus_returns/logic_database/Area 1.txt
=> MSR - Fix Spider Ball Chamber spawn point

randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
Add new miscellaneous resources as per https://discord.com/channels/914291389293027329/1215675687936196608/1280273366812590131
Resource to indicate when softlock patches are enabled
Resource to indicate when Power Bombs without bombs is enabled
=> Fusion: Add Miscellaneous Resources

tools/server-docker/docker-compose.yml
Hopefully lets larger rdvgames upload.
=> Traefik: Change maximum body size to 25MB

randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/fusion/gui/dialog/cosmetic_patches_dialog.py, randovania/games/fusion/gui/ui_files/fusion_cosmetic_patches_dialog.ui, randovania/games/fusion/layout/fusion_cosmetic_patches.py, test/games/fusion/gui/test_fusion_cosmetic_patches_dialog.py, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
text might need some workshopping?
=> Fusion: add unexplored map option

randovania/__init__.py, randovania/__main__.py
Makes it clear that someone has an invalid dev environment sooner than later.
=> Nicer error message if someone forgot tags during setup

randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/fusion/generator/bootstrap.py, randovania/games/fusion/gui/preset_settings/fusion_patches_tab.py, randovania/games/fusion/gui/ui_files/preset_fusion_patches.ui, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/presets/starter_preset.rdvpreset, test/test_files/log_files/fusion/starter_preset.rdvgame, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
=> Fusion: add anti softlock and pb without bombs options

randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt
=> Fusion: fix door id in arctic containment

randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt
Draft until i figure out wtf to do with lava maze.
=> Fusion: more heat run data for most of s3

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
=> Rename `Can Climb High Jump Wall` to `Have Any Jump Upgrade`

randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
=> Fusion: adjust mega-x-related connection based on newly acquired information

randovania/games/fusion/exporter/game_exporter.py, randovania/games/fusion/exporter/options.py, randovania/games/fusion/gui/dialog/game_export_dialog.py, randovania/games/fusion/gui/ui_files/fusion_game_export_dialog.ui, test/games/fusion/gui/test_fusion_game_export_dialog.py
=> Fusion: Exporter GUI

requirements.txt, tools/create_release.py
Also deletes the specific OS+arch dependencies, so we dont end up shipping win+lin+macos+x64+arm for everyone.
=> Bump am2r_yams to 2.9.1-rc1

tools/create_release.py
Reverts randovania/randovania#7266
=> Revert "TEMP remove dotnet cleanup"

randovania/__main__.py, requirements.txt
cant figure out how to handle the new imagemagick lib in utmt right now, so we revert
=> Revert am2r_yams back to 2.8.0

randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/logic_database/header.json
Misc resource for tricks that require enabling/disabling an item mid-trick
=> Introduce Equipment Manipulation resource

CHANGELOG.md, randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/Genetics Laboratory.json, randovania/games/am2r/logic_database/Genetics Laboratory.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
Whoops, turns out we had quite a bit of these!
=> AM2R: fix instances of certain resources not being used together

tools/create_release.py
=> Fix possibility of obfuscator secrets being supplied incorrectly

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
Doesn't stop missile start anymore.
=> Fusion: arachnus health

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
180 x 1,5 = 270
90 x 1,5 = 135
=> Fusion: tweak zazabi health

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Went through a few generation logs and adjusted things based on what I was seeing.
=> Fusion: misc logic tweaks

randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/pickup_database/pickup-database.json
now with us pushing bosses more via e and missiles, the workarounds dont seem to be needed anymore from the quick tests i did.
=> Fusion: tweak more generator stuff

CHANGELOG.md, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt, randovania/games/prime1/logic_database/Phendrana Drifts.json, randovania/games/prime1/logic_database/Phendrana Drifts.txt
- also adds a video for Control tower OoB
=> Prime: add furnace bsj and spider standable documentation for PAL

randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt
* Geron's Crossing, break the left-side bomb block with Speed Booster.
* Nocturnal Shaft, navigate bottom to top with no upgrades.
* Mimic Access, Both directions with damage boost (up to 3 ice-x)
* XBOX Access, Bottom to Top
* With Speed Booster
* With Ice Weapons
* With Wall Jumps (no upgrades)
* XBOX Access, use Speed Booster from Spaceboost Alley to top right
* Neglected Shaft, Bottom to Top
* With Ice Weapons
* With Wall Jumps (no upgrades)
* Entrance Lobby, From Sector Connection
* With Speed Booster
* With JBJ
* With Power Bombs + High Jump
* Nocturnal Playground from Maintenance Annex
* With Springball
* With Single Wall Jumps
* Twin Caverns East, Top Right to Save room with Damage Boost (up to 3 Ice X)
* Twin Caverns East, Save room to Top Right
* With Wide + Plasma + Damage …
=> fusion: sector6: Document some tricks.

pytest.ini
=> Add asyncio_default_fixture_loop_scope

randovania/gui/lib/data_editor_canvas.py
=> Data visualizer: dont draw polygon in black

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
=> Fusion: fix door id in s2 central shaft

randovania/games/dread/gui/ui_files/games_tab_dread_widget.ui
=> Dread: make gui game page consistent

CHANGELOG.md, randovania/games/dread/gui/dialog/game_export_dialog.py, test/games/dread/gui/test_dread_game_export_dialog.py
Fixes https://randovania.sentry.io/issues/5492935863/ and its variations
=> Dread: be slightly stricter for input romfs

CHANGELOG.md, randovania/games/prime2/exporter/patch_data_factory.py, test/test_files/patcher_data/prime2/cs_echoes_multi_1/world_2.json, test/test_files/patcher_data/prime2/multi-am2r+cs+dread+prime1+prime2+msr/world_2.json, test/test_files/patcher_data/prime2/multi-cs+dread+prime1+prime2/world_3.json, test/test_files/patcher_data/prime2/multi-cs+dread+prime1+prime2/world_7.json, test/test_files/patcher_data/prime2/prime1_and_2_multi/world_2.json, test/test_files/patcher_data/prime2/prime2_no_pbs_new_patcher.json, test/test_files/patcher_data/prime2/prime2_no_pbs_old_patcher.json, test/test_files/patcher_data/prime2/seed_a_new_patcher.json, test/test_files/patcher_data/prime2/seed_a_old_patcher.json
=> Echoes: update tournament winners scan

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Eastern Shaft will later need one more pass, once we get a few things merged in patcher side.
=> Fusion: Sector 2 cleanup

CHANGELOG.md, pyproject.toml, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/generator/base_patches_factory.py, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt, requirements.txt, test/test_files/patcher_data/prime1/dread_prime1_multiworld/world_2.json, test/test_files/patcher_data/prime1/multi-am2r+cs+dread+prime1+prime2+msr/world_3.json, test/test_files/patcher_data/prime1/multi-cs+dread+prime1+prime2/world_2.json, test/test_files/patcher_data/prime1/multi-cs+dread+prime1+prime2/world_6.json, test/test_files/patcher_data/prime1/prime1_and_2_multi/world_1.json, test/test_files/patcher_data/prime1/prime1_crazy_seed/world_1.json, test/test_files/patcher_data/prime1/prime1_crazy_seed_one_way_door/world_1.json, test/test_files/patcher_data/prime1/prime1_refills/world_1.json
Technically out of spec with the JSON schema by omitting the new `startingItems`, but the defaults are fine and it'll be way more convenient to fix in the custom items PR
=> Randomprime v1.28.1

CHANGELOG.md, randovania/games/prime1/generator/pickup_pool/artifacts.py, randovania/games/prime1/pickup_database/pickup-database.json
Data: <https://docs.google.com/spreadsheets/d/1M3-d1ICg_FBMSZjYUSe8BBpKuJDbScUylH_eGzxX1YU/edit?usp=sharing>
=> Prime: weighting changes

CHANGELOG.md, pyproject.toml, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime1/generator/base_patches_factory.py, randovania/games/prime1/logic_database/Chozo Ruins.json, randovania/games/prime1/logic_database/Chozo Ruins.txt, requirements.txt, test/test_files/patcher_data/prime1/dread_prime1_multiworld/world_2.json, test/test_files/patcher_data/prime1/multi-am2r+cs+dread+prime1+prime2+msr/world_3.json, test/test_files/patcher_data/prime1/multi-cs+dread+prime1+prime2/world_2.json, test/test_files/patcher_data/prime1/multi-cs+dread+prime1+prime2/world_6.json, test/test_files/patcher_data/prime1/prime1_and_2_multi/world_1.json, test/test_files/patcher_data/prime1/prime1_crazy_seed/world_1.json, test/test_files/patcher_data/prime1/prime1_crazy_seed_one_way_door/world_1.json, test/test_files/patcher_data/prime1/prime1_refills/world_1.json
Reverts randovania/randovania#7443
Current randomprime has a regression where it has a decent chance of crashing when killing enemies.
=> Revert "Randomprime v1.28.1"

CHANGELOG.md
To ensure less conflicts with some of the PR waiting in to get into 8.7.0
=> Add changelog entries for future 8.7.0

randovania/games/fusion/exporter/patch_data_factory.py, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
=> Fusion: credits

CHANGELOG.md, randovania/gui/widgets/multiplayer_session_users_widget.py
Addresses https://github.com/randovania/randovania/issues/7010
Will edit change-log later after feature freeze/next release
=> Prompt for confirmation on multiworld world deletion

randovania/games/fusion/generator/bootstrap.py, randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/header.json
Heat and Electric water damage are based off of the number of suits and thus can't afaik be accurately modelled right now (other than just having different values in logic).
=> Fusion: Add damage reduction

requirements-lint.txt, requirements-setuptools.txt, tools/update_requirements.py
=> Cleanup paths in update_requirements.txt

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 2 Dam Exterior.json, randovania/games/samus_returns/logic_database/Area 2 Dam Exterior.txt
=> MSR - Fix Arachnus causing impossible seeds if FB

tools/prepare_virtual_env.sh
=> Make prepare-virtual-env check for existance of a .git folder

randovania/games/am2r/presets/starter_preset.rdvpreset, randovania/games/blank/presets/starter_preset.rdvpreset, randovania/games/cave_story/presets/classic.rdvpreset, randovania/games/cave_story/presets/multiworld-starter-preset.rdvpreset, randovania/games/cave_story/presets/starter_preset.rdvpreset, randovania/games/dread/presets/april_fools_2023.rdvpreset, randovania/games/dread/presets/starter_preset.rdvpreset, randovania/games/factorio/presets/starter_preset.rdvpreset, randovania/games/fusion/presets/starter_preset.rdvpreset, randovania/games/planets_zebeth/presets/starter_preset.rdvpreset, randovania/games/planets_zebeth/presets/starter_preset_shuffle_keys.rdvpreset, randovania/games/prime1/presets/april_fools_2022.rdvpreset, randovania/games/prime1/presets/moderate_challenge.rdvpreset, randovania/games/prime1/presets/starter_preset.rdvpreset, randovania/games/prime2/presets/darkszero_deluxe.rdvpreset, randovania/games/prime2/presets/starter_preset.rdvpreset, randovania/games/prime3/presets/starter_preset.rdvpreset, randovania/games/samus_returns/presets/multiworld-starter-preset.rdvpreset, randovania/games/samus_returns/presets/starter_preset.rdvpreset, randovania/games/super_metroid/presets/starter_preset.rdvpreset
Been quite a while since we've done this.
=> Modernize presets

CHANGELOG.md
Updated the Changelog for the Remove Bars Feature
=> Update changelog remove bars

randovania/server/discord/preset_lookup.py
Fixes #6645 
https://github.com/randovania/randovania/issues/6645
Formatted title as requested, removed permalink
=> Bot rdvgame clarifications #6645

randovania/games/prime3/logic_database/Bryyo - Fire.json, randovania/games/prime3/logic_database/Bryyo - Fire.txt, randovania/games/prime3/logic_database/Bryyo - Ice.json, randovania/games/prime3/logic_database/Bryyo - Ice.txt, randovania/games/prime3/logic_database/Bryyo - Reptilicus.json, randovania/games/prime3/logic_database/Bryyo - Reptilicus.txt, randovania/games/prime3/logic_database/Bryyo - Seed.json, randovania/games/prime3/logic_database/Bryyo - Seed.txt, randovania/games/prime3/logic_database/GFS Valhalla.json, randovania/games/prime3/logic_database/GFS Valhalla.txt, randovania/games/prime3/logic_database/Phaaze.json, randovania/games/prime3/logic_database/Phaaze.txt, randovania/games/prime3/logic_database/header.json, randovania/games/prime3/logic_database/header.txt
Featuring the use of many template that I'm surprised weren't made already
=> Fix future Data Validation for Bryyo, Valhalla, and Phaaze

CHANGELOG.md, randovania/cli/commands/hash_input.py, randovania/cli/development.py, randovania/exporter/game_exporter.py, randovania/games/common/prime_family/exporter/good_hashes.py, randovania/games/prime1/exporter/game_exporter.py, randovania/games/prime2/exporter/game_exporter.py, randovania/gui/dialog/game_export_dialog.py, randovania/gui/lib/async_dialog.py, randovania/gui/ui_files/game_details_window.ui, randovania/gui/ui_files/multiplayer_session.ui, test/cli/commands/test_hash_input.py, test/games/prime1/exporter/test_prime_game_exporter.py, test/games/prime2/exporter/test_echoes_game_exporter.py, test/games/prime2/gui/dialog/test_echoes_game_export_dialog.py
=> When exporting fails, check if input hash is good

randovania/gui/preset_settings/dock_rando_tab.py, randovania/gui/preset_settings/generation_tab.py, randovania/gui/ui_files/preset_dock_rando.ui, randovania/gui/ui_files/preset_generation.ui
=> Simplify wording for two_sided_door_search

randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt
missiles down from 2x to 1.5x
missile type down for Core-X
health down
=> Fusion: update Nightmare reqs

randovania/gui/multiplayer_session_window.py, test/gui/test_multiplayer_session_window.py
Hopefully this is the reason of the flaky tests??????
=> Don't make threads during tests

docs/Release Process.md
Safer to let everything get taken care of by CI
=> Clarify to not create releases manually

randovania/games/fusion/generator/base_patches_factory.py, randovania/games/fusion/gui/preset_settings/__init__.py, randovania/games/fusion/gui/preset_settings/fusion_dock_tab.py, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/presets/starter_preset.rdvpreset, test/test_files/log_files/fusion/starter_preset.rdvgame, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
=> Fusion: add option to force save rooms open

randovania/server/multiplayer/web_api.py
=> Web api: provide link for preset download

CHANGELOG.md, randovania/gui/preset_settings/split_ammo_widget.py
=> Echoes: Fixed div by 0 error with 0 beam expansions

CHANGELOG.md, randovania/games/prime1/pickup_database/pickup-database.json
=> Prime: remove refill ammo explanation text

randovania/game_connection/connector/am2r_remote_connector.py, test/game_connection/connector/test_am2r_remote_connector.py
=> AM2R MW: Strip last element if empty

CHANGELOG.md, randovania/gui/main_window.py, randovania/gui/tracker_window.py
=> Don't open the map tracker if opening it was cancelled

pyproject.toml, randovania/bitpacking/construct_pack.py, randovania/cli/commands/export_game.py, requirements.txt
=> Redo fixes needed for python 3.13

CHANGELOG.md
When Miepee doesn't wait for approval 😝
=> Add version to changelog

CHANGELOG.md, randovania/gui/ui_files/preset_dock_rando.ui, randovania/layout/base/dock_rando_configuration.py
=> GUI: Reword DLR stuff

CHANGELOG.md, randovania/games/am2r/gui/ui_files/am2r_cosmetic_patches_dialog.ui, randovania/games/blank/gui/ui_files/blank_cosmetic_patches_dialog.ui, randovania/games/cave_story/gui/ui_files/cs_cosmetic_patches_dialog.ui, randovania/games/dread/gui/ui_files/dread_cosmetic_patches_dialog.ui, randovania/games/fusion/gui/ui_files/fusion_cosmetic_patches_dialog.ui, randovania/games/planets_zebeth/gui/ui_files/planets_zebeth_cosmetic_patches_dialog.ui, randovania/games/prime1/gui/ui_files/prime_cosmetic_patches_dialog.ui, randovania/games/prime2/gui/ui_files/echoes_cosmetic_patches_dialog.ui, randovania/games/prime3/gui/ui_files/corruption_cosmetic_patches_dialog.ui, randovania/games/samus_returns/gui/ui_files/msr_cosmetic_patches_dialog.ui, randovania/games/super_metroid/gui/ui_files/super_cosmetic_patches_dialog.ui
The default button is what indicates the most important button and is also what gets triggered when pressing Enter.
Resetting to defaults is not the most important button, Accept is.
=> GUI: change default button in cosmetic dialogs

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 4 Central Caves.json, randovania/games/samus_returns/logic_database/Area 4 Central Caves.txt
Added OOB logic to enter Area 4 Crystal Mines
=> Added oob logic for Area 4 Central Caves

CHANGELOG.md, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt
Added spider method along the ceiling to both horizontal docks in mining facility gamma nest access making sure you can reach the ceiling as a ball first
Intermediate mid-air morph since the short height means you have to do the jump > morph > aim inputs in fairly quick succession
A single bomb jump inside the doorways lets you reach the ceiling
Plus disabled entrance rando since you can roll in from the adjacent rooms
=> Spider method of crossing mining facility gamma nest access

CHANGELOG.md, randovania/gui/ui_files/main_window.ui
=> GUI: remove outermost tab border / spacing around it

CHANGELOG.md, randovania/gui/ui_files/data_editor.ui
=> add word wrap to data visualizer node info

CHANGELOG.md, randovania/games/prime2/pickup_database/pickup-database.json
=> Echoes: change double dmg to beam category

randovania/games/fusion/generator/base_patches_factory.py, randovania/games/fusion/gui/preset_settings/fusion_dock_tab.py, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt, randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, randovania/games/fusion/presets/starter_preset.rdvpreset, test/test_files/log_files/fusion/starter_preset.rdvgame
also exclude ripper tower from DLR
=> Fusion: add recharge stations to force unlock option

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 3 PYR.json, randovania/games/fusion/logic_database/Sector 3 PYR.txt
Mostly addreses zarakavas comments
=> Fusion: fix more things

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
Health:
| db | 1.5x | 
|---|---|
|500 | 750 |
|300 |450 |
|200 |300 |
|100 |150 |
=> Fusion: Revise Omega Metroid

randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/fusion/gui/preset_settings/fusion_patches_tab.py, randovania/games/fusion/gui/ui_files/preset_fusion_patches.ui, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/presets/starter_preset.rdvpreset, test/games/test_log_file_export.py, test/test_files/log_files/fusion/short_intro.rdvgame, test/test_files/log_files/fusion/starter_preset.rdvgame, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json
=> Fusion: short intro text option

randovania/games/prime3/logic_database/GFS Olympus.json, randovania/games/prime3/logic_database/GFS Olympus.txt, randovania/games/prime3/logic_database/GFS Valhalla.json, randovania/games/prime3/logic_database/GFS Valhalla.txt, randovania/games/prime3/logic_database/Norion.json, randovania/games/prime3/logic_database/Norion.txt, randovania/games/prime3/logic_database/Phaaze.json, randovania/games/prime3/logic_database/Phaaze.txt, randovania/games/prime3/logic_database/SkyTown Elysia - Main.json, randovania/games/prime3/logic_database/SkyTown Elysia - Main.txt, randovania/games/prime3/logic_database/header.json, randovania/games/prime3/logic_database/header.txt
also properly marks some dock node as open passages
=> New Door Type for Prime 3

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
Mostly does an alphabetical cleanup from A-Pump Control Unit with a few rooms in between left for later
=> Fusion: Sector 4 Cleanup part 1

CHANGELOG.md, randovania/games/prime2/game_data.py
=> Add FAQ entry for energy controller transports

CHANGELOG.md, README.md, pyproject.toml, requirements.txt
- Fixes some bugs with split suits/beams (heat rooms in gravity not playing sound, plasma doors being too "strong", beam rebalancing)
- Updates `README.md` to include Athebyne
=> Bump OSRR to 3.1.1

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/header.json, randovania/games/fusion/logic_database/header.txt
gonna make a seperate pr for dealing with new logic in eastern shaft.
=> Add connection dessgeega dorm <-> shadow moses island

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
adds bomb slots and boost spinners
=> add more echoes features

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
adds phazon, cannons, luminoth, grapple points, underwater
=> more echoes features

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 5 Tower Exterior.json, randovania/games/samus_returns/logic_database/Area 5 Tower Exterior.txt
I seriously need to do a full database sweep of this game..........
=> MSR - Fix incorrect spawn in A5 Exterior Zeta Area Access

randovania/cli/database.py, test/cli/commands/test_database_cli.py
spits out 
1) num of features per pickup node
2) num of pickup nodes with certain amounts of pickups
3) all pickup nodes with 0 features
=> add CLI for features-per-node

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt
Adds 1 (one) video for Lava Lake in Sector 1.
=> fusion: sector 1 video documentation

randovania/gui/widgets/hint_feature_tab.py
=> display correct region name in LocationHintFeatureTab

randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt
remove boss from main research and elevator from hive gyro
=> small fixes to echoes features

randovania/generator/hint_distributor.py
this makes it significantly easier to balance pickup features
=> use sets for determining pickup feature precision

randovania/games/fusion/gui/ui_files/preset_fusion_goal.ui
No screenshot because i did this from phone
=> Reorder fusion goal bosses

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
Zarakava mentioned a while ago that this trick feels too hard for intermediate and I agree
=> Fusion: Bump habitation entrance NHJ trick

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Great Temple.json, randovania/games/prime2/logic_database/Great Temple.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt, randovania/games/prime2/logic_database/header.json
this follows the exact wording from echoes FAQ
=> add Light Beam Transport hint feature

randovania/games/prime2/pickup_database/pickup-database.json, test/games/prime2/generator/test_echoes_hint_distributor.py
also hides a couple pickup features that don't need to be used
=> fix a couple keybearer hints

randovania/generator/hint_distributor.py
=> fix a couple set iterations in the generator

.vscode/tasks.json, README.md
Cursed changes for spaces in path.
=> Fix for spaces in path on windows, fix for linux commands, add necessary step to readme

randovania/generator/filler/player_state.py, randovania/generator/hint_distributor.py, test/generator/filler/test_runner.py
=> A couple quick fixes to hint distribution

CHANGELOG.md, randovania/games/samus_returns/logic_database/Area 4 Central Caves.json, randovania/games/samus_returns/logic_database/Area 4 Central Caves.txt, randovania/games/samus_returns/logic_database/Area 5 Tower Exterior.json, randovania/games/samus_returns/logic_database/Area 5 Tower Exterior.txt
Did a sweep of the database and fixed two incorrect spawn points. The rest were correct. (I'm so over this lol)
=> MSR - Fix spawns in DB

randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt
Forgot this in the rpevious pr
=> Fusion: Fix mini fridge todo

randovania/games/fusion/logic_database/Main Deck.json, randovania/games/fusion/logic_database/Main Deck.txt
|1x|1.5x|
|---|---|
|500|750|
|400|600|
|350|525|
|200|300|
|100|150|
=> Fusion: Sa-x revamp

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Duncathan suggested this a while ago and I just forgot about it.
=> Fusion: revamp pump control

pyproject.toml, randovania/games/am2r/exporter/game_exporter.py, randovania/games/common/dotnet.py, randovania/games/planets_zebeth/exporter/game_exporter.py, randovania/games/planets_zebeth/gui/dialog/game_export_dialog.py, randovania/games/planets_zebeth/gui/ui_files/planets_zebeth_game_export_dialog.ui, requirements.txt, test/games/am2r/exporter/test_am2r_game_exporter.py, test/games/common/test_dotnet.py, test/games/planets_zebeth/exporter/test_planets_zebeth_game_exporter.py, test/games/planets_zebeth/gui/test_planets_game_export_dialog.py
Also has tests for exporting the game
Export dialog from randovania :
Export dialog from QT :
=> Planets (Zebeth): Implemented game exporter

randovania/games/prime1/hint_distributor.py
=> prime: make artifacts less interesting

CHANGELOG.md, randovania/resolver/energy_tank_damage_state.py
```
> python -m randovania layout validate '.\Dread Randomizer - Shinespark Charge Autclast.
Took 3.938 seconds. Game is possible.
> python -m randovania layout validate '.\Dread Randomizer - Shinespark Charge Autclast.rdvgame'
Took 3.084 seconds. Game is possible.
```
🙃
=> Don't use copy.copy in EnergyTankDamageState

randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt
=> Echoes - Remove Echo Lock Feature from CATW

randovania/game_description/integrity_check.py, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Great Temple.json, randovania/games/prime2/logic_database/Great Temple.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
fixes #7367 
upon saving database, now checks if any youtube links are to a playlist (which breaks embeds)
ex below, wording slightly modified:
=> Video Integrity Check

randovania/gui/docks/hint_feature_database_editor.py, randovania/gui/docks/resource_database_editor.py, randovania/gui/lib/editable_table_model.py, test/gui/lib/test_editable_table_model.py
- Move new element support into AppendableEditableTableModel
- Add FieldDefinition.read_only
- Add FieldDefinition.default_factory
- Add DateFieldDefinition
=> EditableTableModel improvements

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt, randovania/games/prime2/logic_database/header.json, test/games/prime/patcher_file_lib/test_item_hints.py
=> rename boost pipe to half pipe

randovania/games/am2r/game_data.py, randovania/games/am2r/generator/hint_distributor.py
=> make am2r dna less interesting to hint

CHANGELOG.md, randovania/games/dread/presets/starter_preset.rdvpreset
Inspired by other games. Fixes #7493
=> Update Dread Starter Preset Description

CHANGELOG.md, randovania/gui/multiplayer_session_window.py
unsure from a UX pov if i should remove the info popup or not.
=> Move Co-Op into stable

randovania/games/prime2/game_data.py, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Great Temple.json, randovania/games/prime2/logic_database/Great Temple.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt, randovania/games/prime2/logic_database/header.json
=> Change "Light Beam Transport" to "Light Energy Transport"

randovania/games/cave_story/game_data.py
=> Fix missing space after end of sentence

randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/header.json
=> Echoes: phazon location feature update

randovania/games/prime1/assets/migration_data.json
=> Fix prime hint migration

randovania/games/fusion/gui/preset_settings/__init__.py, randovania/games/fusion/gui/preset_settings/fusion_patches_tab.py, randovania/games/fusion/gui/ui_files/fusion_cosmetic_patches_dialog.ui, randovania/games/fusion/gui/ui_files/preset_fusion_patches.ui
=> Fusion: Merge Energy and Other into Gameplay tab

randovania/games/fusion/gui/ui_files/preset_fusion_goal.ui, randovania/games/fusion/gui/ui_files/preset_fusion_hints.ui
=> Fusion: fix more gui issues

.github/workflows/build-test-publish.yml
Hopefully it doesn't break things badly...
=> Better handle running main CI via workflow_dispatch

CHANGELOG.md, randovania/generator/filler/filler_library.py, randovania/generator/filler/filler_logging.py, randovania/generator/filler/player_state.py, randovania/generator/filler/retcon.py, randovania/generator/filler/weights.py
I could've made this an experimental change but like... is it even worth it?
also makes `ActionWeights` a bit more accurate/readable
=> change action weighting to take the max of events and pickups, not sum

randovania/games/fusion/logic_database/Sector 1 SRX.json, randovania/games/fusion/logic_database/Sector 1 SRX.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt, randovania/games/fusion/logic_database/Sector 6 NOC.json, randovania/games/fusion/logic_database/Sector 6 NOC.txt, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
HD II.8 Final Chapter Prologue Birth By Memories
=> Fusion: Room renames final part

CHANGELOG.md, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt
bump mining plaza, trial tunnel
lower temple assembly site (also change the video to use easier method)
=> Echoes: nsj sa logic adjustments

randovania/games/blank/exporter/hint_namer.py, randovania/games/blank/exporter/patch_data_factory.py, randovania/games/blank/game_data.py, randovania/games/blank/generator/__init__.py, randovania/games/blank/generator/hint_distributor.py, randovania/games/cave_story/generator/hint_distributor.py, randovania/games/prime2/generator/hint_distributor.py, randovania/generator/filler/filler_configuration.py, randovania/generator/filler/player_state.py, randovania/generator/filler/retcon.py, randovania/generator/filler/runner.py, randovania/generator/generator.py, randovania/generator/hint_distributor.py, randovania/generator/hint_state.py, test/generator/test_generator.py, test/interface_common/test_generator_frontend.py
=> refactors for hints

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Logic updated to include hi-jump from the bottom security access node to crumble city.
=> Sector 2 Security Room Logic update`

CHANGELOG.md, randovania/generator/hint_distributor.py, randovania/layout/base/base_configuration.py, randovania/layout/preset_migration.py, randovania/resolver/hint_state.py, randovania/resolver/logic.py, randovania/resolver/resolver.py, randovania/resolver/resolver_reach.py, randovania/resolver/state.py, test/layout/test_echoes_configuration.py, test/layout/test_generator_parameters.py
depends on #8036 and #8037 
also adds a hidden preset option to enable this in non-DLR seeds. i don't want to expose it in the GUI atm
=> in individual DLR, use the resolver for hint placement

pyproject.toml, randovania/games/factorio/exporter/game_exporter.py, randovania/games/factorio/exporter/patch_data_factory.py, randovania/games/factorio/game_data.py, randovania/games/factorio/layout/factorio_preset_describer.py, randovania/gui/preset_settings/location_pool_tab.py, requirements.txt, test/games/factorio/exporter/test_factorio_game_exporter.py, test/test_files/patcher_data/factorio/factorio/starter_preset/world_1.json
Uses latest exporter for mod-setting mode.
=> Polishing UI/UX for Factorio

randovania/gui/preset_settings/generation_tab.py
=> make check_if_beatable_after_base_patches persist

CHANGELOG.md, pyproject.toml, randovania/cli/commands/validate.py, randovania/gui/game_details/game_details_window.py, randovania/gui/ui_files/game_validator_widget.ui, randovania/gui/widgets/game_validator_widget.py, randovania/resolver/debug.py, randovania/resolver/logic.py, randovania/resolver/resolver.py, test/gui/widgets/test_game_validator_widget.py
this should be infinitely easier for users to actually read and follow along with, lmao
screenshots:
=> Give the playthrough tab a long-overdue makeover

randovania/games/fusion/pickup_database/pickup-database.json, randovania/games/fusion/presets/starter_preset.rdvpreset
=> put fusion's SA weight in the pickup database instead of the preset

CHANGELOG.md, randovania/gui/preset_settings/dock_rando_tab.py
=> sort DLR lists better in the preset tab

randovania/exporter/pickup_exporter.py, randovania/game_description/db/node_provider.py, randovania/game_description/db/region_list.py, randovania/game_description/game_description.py, randovania/game_description/node_search.py, randovania/games/cave_story/exporter/patch_data_factory.py, randovania/games/cave_story/generator/hint_distributor.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/prime1/exporter/patch_data_factory.py, randovania/games/prime2/exporter/hints.py, randovania/games/prime2/exporter/patch_data_factory.py, randovania/games/prime2/generator/bootstrap.py, randovania/games/prime2/generator/hint_distributor.py, randovania/games/prime2/gui/preset_settings/echoes_translators_tab.py, randovania/games/prime2/layout/translator_configuration.py, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/generator/filler/player_state.py, randovania/generator/hint_distributor.py, randovania/generator/hint_state.py, randovania/generator/pickup_pool/pool_creator.py, randovania/gui/dialog/node_details_popup.py, randovania/gui/tracker_window.py, randovania/layout/base/available_locations.py, randovania/resolver/hint_state.py, test/games/prime/patcher_file_lib/test_pickup_exporter.py, test/games/prime2/generator/test_echoes_hint_distributor.py, test/gui/dialog/test_connections_editor.py
this pattern comes up a bunch, might as well make it less verbose
=> add NodeProvider.iterate_nodes_of_type()

pyproject.toml, randovania/games/factorio/assets/recipes-raw.json, randovania/games/factorio/assets/techs-raw.json, randovania/games/factorio/exporter/patch_data_factory.py, randovania/games/factorio/generator/base_patches_factory.py, randovania/games/factorio/gui/preset_settings/factorio_patches_tab.py, randovania/games/factorio/gui/ui_files/games_tab_factorio_widget.ui, randovania/games/factorio/gui/ui_files/preset_factorio_patches.ui, randovania/games/factorio/importer_util.py, randovania/games/factorio/layout/factorio_configuration.py, randovania/games/factorio/layout/factorio_preset_describer.py, randovania/games/factorio/logic_database/header.json, randovania/games/factorio/pickup_database/pickup-database.json, randovania/games/factorio/presets/starter_preset.rdvpreset, requirements.txt, test/test_files/log_files/factorio/starter_preset.rdvgame, test/test_files/patcher_data/factorio/factorio/starter_preset/world_1.json, tools/factorio/create_nodes.py, tools/factorio/create_resources.py
DRAFT: make new release of patcher and depend on it
- Fix database importer
- Import database files
- Tweak Rocket Part recipe balancing
- Randomize Satellite recipe
- Make Satellite part of the win condition
- Add Differences tab
=> Factorio improvements

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
Reworked Stand on Frozen Enemies Advanced with the old method to the new methods
- Ice Missiles or Ice Beam and Stand on Frozen Enemies Intermediate
- Diffusion Missiles and Stand on Frozen Enemies Advanced
Generall concensous when I posted this on the Fusion Discord would be that Ice Missiles and Ice Beam would be consdiered intermediate and since Diffusion required more knowledge/timing it would be considered higher than the intermidate level.
=> Fusion Oasis Videos and Trick Updates

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Videos have been updated to be more in line with our standard of trick videos. Videos without an input display have been rerecorded and replaced to show the trick with input viewer.
=> Metroid Fusion - S4 - Powamp Playhouse videos updated

randovania/game_description/integrity_check.py, test/game_description/test_integrity_check.py
=> add integrity checks for hint stuff

randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
Gathering Hall has a spinner in interdimensional flux
=> Add boost spinner feature to Gathering Hall

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt
- Adds morph ball tunnel feature to Temple Assembly Site
- Adds morph ball tunnel feature to Great Bridge
- Adds luminoth corpse feature to Portal Access A
- Adds spider track feature to Bioenergy Production
=> Echoes: Add missing features

randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt
- Added trick video for beginner wall jump
- Added trick video for beginner shinespark
=> Fusion Zazabi Speedway Trick Videos

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Added Wall Jump Video
Added Stand on Frozen Enemies Video
Changed from Freeze with any Weapon to only Ice Beam or Ice Missiles. After 40 min of attempts I could not get the diffusion missile to time right due to the radius of diffusion freezing both Owtch. Either its impossible due to the enemey timings or much harder then beginner.
Edit: I have also found and added a new trick for the upper part of the room for review.
=> Fusion Updated Videos and Trick Logic for Reservoir Vault

randovania/network_common/error.py, randovania/server/user_session.py, test/gui/lib/test_multiplayer_session_api.py, test/server/test_user_session.py
Does server stuff need changelog entries? My assumption is no.
=> Show which user is unauthorized when trying to login

randovania/game_description/game_description.py, randovania/game_description/resources/resource_database.py, randovania/games/am2r/generator/pool_creator.py, randovania/games/blank/generator/pool_creator.py, randovania/games/dread/generator/pool_creator.py, randovania/games/fusion/generator/pool_creator.py, randovania/games/planets_zebeth/generator/pool_creator.py, randovania/games/prime1/generator/pickup_pool/artifacts.py, randovania/games/prime1/generator/pickup_pool/pool_creator.py, randovania/games/prime2/generator/pickup_pool/dark_temple_keys.py, randovania/games/prime2/generator/pickup_pool/pool_creator.py, randovania/games/prime2/generator/pickup_pool/sky_temple_keys.py, randovania/games/samus_returns/generator/pool_creator.py, randovania/generator/pickup_pool/pickup_creator.py, test/games/am2r/generator/test_am2r_pool_creator.py, test/games/dread/generator/test_dread_pool_creator.py, test/games/fusion/generator/test_fusion_pool_creator.py, test/games/planets_zebeth/generator/test_planets_zebeth_pool_creator.py, test/games/prime/patcher_file_lib/test_sky_temple_key_hint.py, test/games/prime2/generator/test_sky_temple_key.py, test/games/samus_returns/generator/test_msr_pool_creator.py
Bite sized refactors being pulled out from a monster PR. Enjoy :)
=> create_generated_pickup: get PickupDatabase as argument

randovania/games/fusion/gui/ui_files/fusion_cosmetic_patches_dialog.ui
pallete -> palette
fixes #8015
=> Fix a typo in Fusion cosmetic patches UI

randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt, randovania/games/prime2/logic_database/Sanctuary Fortress.json, randovania/games/prime2/logic_database/Sanctuary Fortress.txt, randovania/games/prime2/logic_database/Temple Grounds.json, randovania/games/prime2/logic_database/Temple Grounds.txt, randovania/games/prime2/logic_database/Torvus Bog.json, randovania/games/prime2/logic_database/Torvus Bog.txt, randovania/games/prime2/logic_database/header.json
useful for when keybearer hints are disabled but random hints are not
=> add Flying Ing Cache hint feature

docs/New Game.md
=> Fix pickup definition links in `New Game.md`

.github/workflows/daily-generate.yml, .github/workflows/trick-documentation-report.yml
`--with` is the poetry api >.>
=> Fix wrong uv sync command

randovania/network_common/error.py
=> Fix UserNotAuthorizedToUseServerError not declaring the detail

.gitignore, pyproject.toml, randovania/__init__.py, setup.py
For less hacks with the website
=> Ensure the README is added to the python package

randovania/gui/preset_settings/generation_tab.py
Imagine there's a screenshot here
=> Fix dangerous settings being considered experimental setting

CHANGELOG.md
=> Add changelog entry for #7947

randovania/gui/widgets/game_validator_widget.py
I don't want to touch these regexes.
Fixes #8169
=> Work around game validator widget crashing for impossible games

CHANGELOG.md, randovania/games/dread/logic_database/header.json, randovania/games/dread/logic_database/header.txt
=> Dread: Add Health requirements to Robot fights

.github/workflows/build-test-publish.yml
=> Fix server being deployed on `stable`

CHANGELOG.md, pyproject.toml, randovania/gui/dialog/login_prompt_dialog.py, randovania/gui/lib/qt_network_client.py, randovania/gui/ui_files/login_prompt_dialog.ui, test/gui/lib/test_qt_network_client.py, uv.lock
The url kinda contains a secret...
=> Allow Discord login to be completed in more ways

randovania/gui/dialog/login_prompt_dialog.py, randovania/gui/ui_files/login_prompt_dialog.ui
Center text, make clicking the link work, some feedback that you've pressed and is trying to talk to the server.
=> Better UX for the discord login button

randovania/exporter/hints/hint_namer.py, randovania/game_description/db/node.py, randovania/game_description/db/node_identifier.py, randovania/game_description/db/region_list.py, randovania/game_description/integrity_check.py, randovania/game_description/pretty_print.py, randovania/games/dread/exporter/patch_data_factory.py, randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/samus_returns/exporter/patch_data_factory.py, randovania/generator/filler/filler_logging.py, randovania/generator/filler/player_state.py, randovania/generator/filler/retcon.py, randovania/generator/hint_distributor.py, randovania/gui/game_details/hint_details_tab.py, randovania/gui/game_details/pickup_details_tab.py, randovania/gui/multiplayer_session_window.py, randovania/gui/tracker_window.py, randovania/layout/game_patches_serializer.py, randovania/resolver/logic.py, test/layout/test_game_patches_serializer.py
`RegionList.area_name` needs a bit more thinking, left for later
=> Remove most functions for naming nodes from RegionList

README.md, randovania/gui/main_window.py, randovania/gui/ui_files/main_window.ui
=> Remove the list of games from the README and intro UI page.

randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt
Added in missing trick videos for:
- Underwater Wall Jump
- SpeedBoost Movement
- ShineSpark
- Stand on Frozen Enemies
- Wall Jump
=> Fusion Cargo Hold Trick Videos

.github/workflows/build-test-publish.yml
Turns our GH is nice and dynamically update the workflow dispatch parameters based on the selected branch.
=> CI: Support server_environment for production

CHANGELOG.md, randovania/games/prime1/logic_database/Chozo Ruins.txt, randovania/games/prime1/logic_database/Magmoor Caverns.txt, randovania/games/prime1/logic_database/Phazon Mines.txt, randovania/games/prime1/logic_database/Phendrana Drifts.txt, randovania/games/prime1/logic_database/Tallon Overworld.txt, randovania/games/prime1/logic_database/header.json
=> Prime: Fix the Door Lock Rando misc resource being called Dock Rando

randovania/games/prime2/pickup_database/pickup-database.json, randovania/layout/description_migration.py, randovania/layout/game_patches_serializer.py, test/layout/test_game_patches_serializer.py
=> Rename ETM to nothing (HD Edition)

CHANGELOG.md, randovania/games/prime1/logic_database/Phendrana Drifts.json, randovania/games/prime1/logic_database/Phendrana Drifts.txt
Fixes https://github.com/JustinDMS/prime-map-tool/issues/25
I confirmed this in PAL rando, I will assume that it works in NTSC rando too.
=> Prime: Fix not always being able to trigger observatory

CHANGELOG.md, randovania/gui/ui_files/data_editor.ui
=> adjust width of data visualizer and area view

pyproject.toml, uv.lock
Update's Fusion Patcher to new version.
=> Update Fusion Patcher Version to 0.3.0

pyproject.toml, uv.lock
=> Update Fusion Patcher

CHANGELOG.md, randovania/bitpacking/bitpacking.py, randovania/lib/json_lib.py, randovania/network_common/pickup_serializer.py, test/bitpacking/test_bitpacking.py, test/layout/test_game_patches_serializer.py, test/server/multiplayer/test_world_api.py
Fixes cave story multiworld just straight up not working in 9.1.0
=> Encode/decode PickupEntry extra dict when bitpacking

randovania/game_connection/connector/am2r_remote_connector.py, randovania/game_connection/connector/debug_remote_connector.py, randovania/game_connection/connector/remote_connector.py, randovania/game_connection/executor/am2r_executor.py, randovania/game_connection/executor/executor_to_connector_signals.py, randovania/gui/lib/signal.py, randovania/lib/signal.py, test/game_connection/connector/test_am2r_remote_connector.py, test/game_connection/connector/test_dread_remote_connector.py, test/game_connection/connector/test_echoes_remote_connector.py, test/game_connection/connector/test_msr_remote_connector.py, test/game_connection/executor/test_am2r_executor.py
=> Alternative signal implementation

CHANGELOG.md, randovania/server/multiplayer/session_admin.py, test/server/multiplayer/test_session_admin.py
Also add "Everyone can claim worlds"?
=> Duplicate co-op setting

randovania/network_common/__init__.py
Because of changes in `BitPackPickupEntry`
=> Bump server API Version

randovania/resolver/bootstrap.py, test/games/am2r/generator/test_am2r_bootstrap.py, test/games/fusion/generator/test_fusion_bootstrap.py, test/games/prime_hunters/generator/test_prime_hunters_bootstrap.py, test/games/samus_returns/generator/test_msr_bootstrap.py
implementation of weighting up to individual games to decide
some sample data
=> Weighted Pre-Placement

randovania/games/fusion/exporter/patch_data_factory.py, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/shiny_pickups_dict_from_starter_preset.json
Add Kind to Fusion JSON for patcher enhancements
=> Add Kind to Fusion JSON

randovania/games/prime_hunters/gui/ui_files/games_tab_prime_hunters_widget.ui
`Explore the ruins of the Alimbic Cluster and recover the Octoliths, then actiavte the Alimbic Cannon to open the Oubliette and defeat Gorea.`
`To get started, use the Quick Generate button to generate a game using the default settings!`
This will get more stuff added to as ophr gets more features.
=> Hunters intro text

randovania/games/am2r/logic_database/Distribution Center.json, randovania/games/am2r/logic_database/Distribution Center.txt, randovania/games/am2r/logic_database/GFS Thoth.json, randovania/games/am2r/logic_database/GFS Thoth.txt, randovania/games/am2r/logic_database/Golden Temple.json, randovania/games/am2r/logic_database/Golden Temple.txt, randovania/games/am2r/logic_database/Hydro Station.json, randovania/games/am2r/logic_database/Hydro Station.txt, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/am2r/logic_database/Main Caves.json, randovania/games/am2r/logic_database/Main Caves.txt, randovania/games/am2r/logic_database/The Depths.json, randovania/games/am2r/logic_database/The Depths.txt, randovania/games/am2r/logic_database/The Tower.json, randovania/games/am2r/logic_database/The Tower.txt
type is dict[instance_id, enemy_name]
=> AM2R: Add enemy extra data

randovania/games/am2r/generator/bootstrap.py, randovania/games/cave_story/generator/bootstrap.py, randovania/games/dread/generator/bootstrap.py, randovania/games/fusion/generator/bootstrap.py, randovania/games/prime2/generator/bootstrap.py, randovania/games/prime_hunters/generator/bootstrap.py, randovania/games/samus_returns/generator/bootstrap.py, randovania/resolver/bootstrap.py
games now supply a list of `PickupEntry`s to be pre-placed, which allows more per-game implementations
=> change pre-placement to have games provide list of pickupentry

randovania/cli/cli_lib.py, randovania/generator/filler/filler_logging.py
This piece produces a lot of output to the debug, and it seems less interesting than most of everything else at debug level 3.
=> Generator: Increase debug level to print reach

randovania/games/prime_hunters/pickup_database/pickup-database.json
Launcher isn't really a thing so the option doesn't do anything.
=> Hunters - Hide requires main option for Missiles from GUI

randovania/games/am2r/logic_database/header.json, randovania/games/am2r/logic_database/header.txt, randovania/games/am2r/pickup_database/pickup-database.json, randovania/games/am2r/pickup_database/text_data.json, randovania/layout/preset_migration.py
This one's not blocked on a patcher release.
=> Add Metroid Lures

randovania/game_description/integrity_check.py, randovania/games/am2r/logic_database/Industrial Complex.json, randovania/games/am2r/logic_database/Industrial Complex.txt, randovania/games/prime1/logic_database/Tallon Overworld.json, randovania/games/prime1/logic_database/Tallon Overworld.txt
=> Add integrity check for discord links

randovania/games/fusion/generator/base_patches_factory.py, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 5 ARC.json, randovania/games/fusion/logic_database/Sector 5 ARC.txt
ripper tower was already marked to exclude, just fixed the description
=> Fusion: force ripper tower and road to open

randovania/games/prime_hunters/exporter/patch_data_factory.py, test/test_files/patcher_data/prime_hunters/prime_hunters/shuffled_force_fields/world_1.json, test/test_files/patcher_data/prime_hunters/prime_hunters/starter_preset/world_1.json, test/test_files/patcher_data/prime_hunters/prime_hunters/starting_items_with_nothings/world_1.json
Used by the patcher for RNG seeding
=> Hunters - Add configuration_id to PDF

CHANGELOG.md, randovania/interface_common/world_database.py
Related to https://discord.com/channels/914291389293027329/1370819005811790036
=> Wrap read in try catch

randovania/exporter/patch_data_factory.py, test/test_files/log_files/am2r/door_lock.rdvgame, test/test_files/log_files/am2r/starter_preset.rdvgame
No clue on how to test locally that this actually works.
No changelog, since we don't add entries for telemetry stuff.
=> Attach rdvgame to PDF sentry errors

pyproject.toml, uv.lock
mars patcher to 0.6.1
Patcher side update included
- Audio fix on messages/jingles
- Block Graphics
- patcher map change for s5
=> Fusion update mars patcher

CHANGELOG.md, randovania/games/prime2/logic_database/Agon Wastes.json, randovania/games/prime2/logic_database/Agon Wastes.txt
I've seen people call this a BSJ and I really really don't like that term here
=> Echoes: add instant morph to transport center

CHANGELOG.md, randovania/gui/multiplayer_session_window.py
=> MW Session: rename "generate without spoiler" to "for race"

randovania/games/fusion/exporter/patch_data_factory.py, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/all_hidden_with_random/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json
=> Fusion Fix Double Period on BSL starting text

randovania/games/fusion/presets/vanilla_start.rdvpreset
=> Fusion adjust vanilla preset description

randovania/games/fusion/presets/open_sector_hub.rdvpreset, randovania/games/fusion/presets/vanilla_start.rdvpreset
as directed by Dunc here https://discordapp.com/channels/914291389293027329/1215675687936196608/1397279857456447538
=> fusion: change hint settings

CHANGELOG.md, randovania/games/fusion/game_data.py
=> fusion: mark as stable

CHANGELOG.md, pyproject.toml, randovania/games/fusion/exporter/game_exporter.py, randovania/games/fusion/exporter/patch_data_factory.py, randovania/games/fusion/gui/generated/preset_fusion_patches_ui.py, randovania/games/fusion/gui/preset_settings/fusion_patches_tab.py, randovania/games/fusion/gui/ui_files/preset_fusion_patches.ui, randovania/games/fusion/layout/fusion_configuration.py, randovania/games/fusion/logic_database/Sector 2 TRO.json, randovania/games/fusion/logic_database/Sector 2 TRO.txt, randovania/games/fusion/logic_database/Sector 4 AQA.json, randovania/games/fusion/logic_database/Sector 4 AQA.txt, randovania/layout/preset_migration.py, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/all_hidden_with_random/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/fusion/starting_items/world_1.json, uv.lock
Reliant on new patcher version
Obsoletes / Closes #8470
=> Fusion: Bump to mars_patcher 0.7.0 (anti-softlock + title screen text)

CHANGELOG.md, randovania/games/fusion/exporter/game_exporter.py, randovania/games/fusion/exporter/patch_data_factory.py, test/test_files/patcher_data/fusion/fusion/all_hidden_with_nothing/world_1.json, test/test_files/patcher_data/fusion/fusion/all_hidden_with_random/world_1.json, test/test_files/patcher_data/fusion/fusion/short_intro/world_1.json, test/test_files/patcher_data/fusion/fusion/starter_preset/world_1.json, test/test_files/patcher_data/fusion/fusion/starting_items/world_1.json
=> Fusion: Show Seed Hash on title screen

CHANGELOG.md, randovania/games/dread/logic_database/Artaria.json, randovania/games/dread/logic_database/Artaria.txt, randovania/games/dread/logic_database/Cataris.json, randovania/games/dread/logic_database/Cataris.txt, randovania/games/dread/logic_database/Dairon.json, randovania/games/dread/logic_database/Dairon.txt, randovania/games/dread/logic_database/Ferenia.json, randovania/games/dread/logic_database/Ferenia.txt, randovania/games/dread/logic_database/Ghavoran.json, randovania/games/dread/logic_database/Ghavoran.txt, randovania/games/dread/logic_database/header.json, randovania/games/dread/logic_database/header.txt
Reworked combat logic for Central Units in Artaria, Cataris, Dairon, Ferenia, and Ghavoran reflecting the escalating difficulty in later areas.
resolves https://github.com/randovania/randovania/issues/7065
=> Reworked CU combat logic

randovania/games/samus_returns/logic_database/Surface West.json, randovania/games/samus_returns/logic_database/Surface West.txt
No changelog entry, as this doesnt change logic in anyway other than being nicer for the generator
=> MSR: Remove unnecessary before

randovania/gui/dialog/connections_editor.py
Super special cases for these two. Hopefully nothing blows up...
=> Add explicit categories for Trivial/Impossible in the ConnectionsEditor

.github/workflows/build-test-publish.yml, randovania/lib/obfuscator.py, test/lib/test_obfuscator.py, tools/deploy_server.py, tools/server-docker/docker-compose.yml
Will this actually work is a mystery we find out after merging.
=> Supply obfuscator secret via env var for the discord bot
